/**
 * [INPUT]: Product locale.
 * [OUTPUT]: Five-language preview actions, connecting/closing progress, draining/download/verification recovery, normalized native/remote failures and development origin repair drafts.
 * [POS]: Shared artifact copy for desktop, browser and mobile shell.
 */
const copy = {
 en: ["Enable remote preview", "Close remote preview", "Open on this device", "Ask Agent to restart", "This preview passes through trycloudflare.com. It is not end-to-end encrypted and availability is not guaranteed.", "Please confirm the component download on your computer.", "Preview & tunnels is turned off on the computer.", "The computer or service is unavailable. Reconnect or ask the Agent to restart it.", "Registering connector…", "Waiting for the edge…", "Remote preview is open", "Streaming output may arrive in batches. Share a built version for faster loading.", "This one-time link expires in 60 seconds.", "Prepare a new link", "Sign in and unlock the computer to open a remote preview.", "This platform is not supported yet.", "The computer needs an update.", "The computer is offline.", "Manage previews", "Restart this application's managed preview server using preview_server_start and return a new live application card.", "Remote preview is closed.", "No remote previews are open.", "Account closure takes effect at the next lease check. If the computer loses contact, access expires within five minutes.", "Cloudflare preview is unavailable. Try again."],
 "zh-CN": ["开启远程预览", "关闭远程预览", "在此设备打开", "让 Agent 重新启动", "此预览经 trycloudflare.com 中转，不使用端到端加密，也不保证可用性。", "请在电脑上确认下载预览组件。", "电脑上的「预览与隧道」已关闭。", "电脑或服务不可用，请重新连接或让 Agent 重新启动。", "正在注册连接器…", "等待边缘可达…", "远程预览已开启", "流式输出可能成批到达。分享构建版可以更快加载。", "一次性链接将在 60 秒后过期。", "生成新链接", "请先在电脑上登录并解锁，再开启远程预览。", "本平台暂不支持。", "请先更新电脑端。", "电脑已离线。", "管理预览", "请用 preview_server_start 重新启动这个应用的托管预览服务，并返回新的活应用卡片。", "远程预览已关闭。", "当前没有开启的远程预览。", "从账户关闭会在电脑下次检查租约时生效；电脑断网时，访问最迟五分钟后失效。", "Cloudflare 预览中转暂不可用，请重试。"],
 ja: ["リモートプレビューを有効にする", "リモートプレビューを閉じる", "この端末で開く", "Agent に再起動を依頼", "通信は trycloudflare.com を経由し、エンドツーエンド暗号化されません。可用性は保証されません。", "コンピューターでダウンロードを承認してください。", "コンピューターのプレビューとトンネルがオフです。", "コンピューターまたはサービスが利用できません。再接続するか再起動を依頼してください。", "コネクターを登録中…", "エッジを確認中…", "リモートプレビューは有効です", "ストリーム出力はまとめて届く場合があります。ビルド版の共有はより高速です。", "この一回限りのリンクは60秒で失効します。", "新しいリンク", "コンピューターでサインインしてロックを解除してください。", "このプラットフォームは未対応です。", "コンピューターの更新が必要です。", "コンピューターはオフラインです。", "プレビューを管理", "preview_server_start でこのアプリの管理対象プレビューを再起動し、新しいカードを返してください。", "リモートプレビューは閉じています。", "開いているリモートプレビューはありません。", "次のリース確認で閉じます。接続が失われた場合も5分以内に失効します。", "Cloudflare のプレビューが利用できません。再試行してください。"],
 es: ["Activar vista previa remota", "Cerrar vista previa remota", "Abrir aquí", "Pedir al Agent que reinicie", "La vista previa pasa por trycloudflare.com sin cifrado de extremo a extremo ni disponibilidad garantizada.", "Confirma la descarga en tu ordenador.", "Vista previa y túneles está desactivado.", "El ordenador o servicio no está disponible. Reconecta o pide un reinicio.", "Registrando conector…", "Esperando la conexión…", "Vista previa remota activa", "La salida en directo puede llegar en grupos. Comparte una versión compilada para cargar más rápido.", "Este enlace de un solo uso caduca en 60 segundos.", "Crear otro enlace", "Inicia sesión y desbloquea el ordenador.", "Esta plataforma aún no es compatible.", "Actualiza el ordenador.", "El ordenador está sin conexión.", "Administrar vistas previas", "Reinicia la vista previa administrada con preview_server_start y devuelve una nueva tarjeta.", "La vista previa remota está cerrada.", "No hay vistas previas remotas abiertas.", "El cierre se aplica en la siguiente comprobación. Sin conexión, el acceso caduca en cinco minutos.", "La vista previa de Cloudflare no está disponible. Inténtalo de nuevo."],
 fr: ["Activer l’aperçu distant", "Fermer l’aperçu distant", "Ouvrir ici", "Demander un redémarrage à l’Agent", "Cet aperçu passe par trycloudflare.com sans chiffrement de bout en bout ni disponibilité garantie.", "Confirmez le téléchargement sur l’ordinateur.", "Aperçus et tunnels est désactivé.", "L’ordinateur ou le service est indisponible. Reconnectez-vous ou demandez un redémarrage.", "Enregistrement du connecteur…", "Connexion à la périphérie…", "L’aperçu distant est ouvert", "La sortie en continu peut arriver par lots. Une version compilée se charge plus vite.", "Ce lien à usage unique expire dans 60 secondes.", "Créer un nouveau lien", "Connectez-vous et déverrouillez l’ordinateur.", "Cette plateforme n’est pas encore prise en charge.", "Mettez à jour l’ordinateur.", "L’ordinateur est hors ligne.", "Gérer les aperçus", "Redémarre l’aperçu géré avec preview_server_start et renvoie une nouvelle carte.", "L’aperçu distant est fermé.", "Aucun aperçu distant ouvert.", "La fermeture prend effet au prochain contrôle. Sans connexion, l’accès expire sous cinq minutes.", "L’aperçu Cloudflare est indisponible. Réessayez."],
} as const;
export const livePreviewCopy = (locale: string) => copy[locale as keyof typeof copy] ?? copy.en;
const recovery = {
  en: ["Keep running", "The turn's server has stopped. Restart it as a managed service to keep it available.", "Share a built version for faster loading", "Build this application for sharing, start its production preview using preview_server_start with mode build, and return the new live application card.", "Ask Agent to allow this preview", "Next.js may be blocking this preview’s development resources.", "Allow this preview’s exact host in the Next.js allowedDevOrigins setting, preserve existing allowed hosts, and restart the managed development server. Return a new live application card."],
  "zh-CN": ["保持运行", "本轮服务已停止。可按原启动方式重启为托管服务，让它继续运行。", "分享构建版更快", "请构建这个应用，用 preview_server_start 的 build 模式启动构建版预览，并返回新的活应用卡片。", "让 Agent 允许此预览", "Next.js 可能正在阻止此预览的开发资源。", "请将此预览的确切主机名加入 Next.js 的 allowedDevOrigins 配置，保留已有的允许列表，并重启托管开发服务。请返回新的活应用卡片。"],
  ja: ["実行を維持", "ターンのサーバーは停止しました。管理対象サービスとして再起動できます。", "ビルド版の共有はより高速です", "共有用にアプリをビルドし、preview_server_start の build モードで起動して新しいカードを返してください。", "Agent にこのプレビューの許可を依頼", "Next.js がこのプレビューの開発リソースをブロックしている可能性があります。", "このプレビューの正確なホスト名を Next.js の allowedDevOrigins に追加し、既存の許可リストを保持して管理対象の開発サーバーを再起動してください。新しいカードを返してください。"],
  es: ["Mantener en ejecución", "El servidor del turno se ha detenido. Reinícialo como servicio administrado.", "Comparte una versión compilada para cargar más rápido", "Compila la aplicación y abre la vista previa con preview_server_start en modo build. Devuelve la nueva tarjeta.", "Pedir al Agent que permita esta vista previa", "Next.js puede estar bloqueando los recursos de desarrollo de esta vista previa.", "Añade el host exacto de esta vista previa a allowedDevOrigins de Next.js, conserva los hosts permitidos y reinicia el servidor de desarrollo administrado. Devuelve una nueva tarjeta."],
  fr: ["Maintenir en cours", "Le serveur du tour est arrêté. Redémarrez-le comme service géré.", "Partager une version compilée charge plus vite", "Compile l’application, lance son aperçu avec preview_server_start en mode build et renvoie la nouvelle carte.", "Demander à l’Agent d’autoriser cet aperçu", "Next.js bloque peut-être les ressources de développement de cet aperçu.", "Ajoute l’hôte exact de cet aperçu à allowedDevOrigins dans Next.js, conserve les hôtes autorisés et redémarre le serveur de développement géré. Renvoie une nouvelle carte."],
} as const;
export const livePreviewRecovery = (locale: string) => recovery[locale as keyof typeof recovery] ?? recovery.en;
const lifecycle = {
  en: { connecting: "Opening remote preview…", closing: "Closing remote preview…", draining: "The service changed. Closing remote preview…", reopen: "Reopen remote preview", download: "The preview component could not be downloaded. Try again.", verification: "The downloaded preview component could not be verified. Try again." },
  "zh-CN": { connecting: "正在开启远程预览…", closing: "正在关闭远程预览…", draining: "服务已变化，正在关闭远程预览…", reopen: "重新开启远程预览", download: "预览组件下载失败，请重试。", verification: "无法验证下载的预览组件，请重试。" },
  ja: { connecting: "リモートプレビューを開始中…", closing: "リモートプレビューを閉じています…", draining: "サービスが変わったため、リモートプレビューを閉じています…", reopen: "リモートプレビューを再開", download: "プレビュー用コンポーネントをダウンロードできませんでした。再試行してください。", verification: "ダウンロードしたプレビュー用コンポーネントを検証できませんでした。再試行してください。" },
  es: { connecting: "Abriendo la vista previa remota…", closing: "Cerrando la vista previa remota…", draining: "El servicio ha cambiado. Cerrando la vista previa remota…", reopen: "Volver a abrir la vista previa remota", download: "No se pudo descargar el componente de vista previa. Inténtalo de nuevo.", verification: "No se pudo verificar el componente de vista previa descargado. Inténtalo de nuevo." },
  fr: { connecting: "Ouverture de l’aperçu distant…", closing: "Fermeture de l’aperçu distant…", draining: "Le service a changé. Fermeture de l’aperçu distant…", reopen: "Rouvrir l’aperçu distant", download: "Le composant d’aperçu n’a pas pu être téléchargé. Réessayez.", verification: "Le composant d’aperçu téléchargé n’a pas pu être vérifié. Réessayez." },
} as const;
export const livePreviewLifecycle = (locale: string) => lifecycle[locale as keyof typeof lifecycle] ?? lifecycle.en;
export const previewErrorCode = (message: string) => message.split(": ").at(-1) ?? message;
export function previewFailure(message: string, locale: string) {
  const code = previewErrorCode(message);
  if (/^tunnel-(?:component|signature|archive)-/.test(code)) return livePreviewLifecycle(locale).verification;
  if (code.startsWith("tunnel-download-") && code !== "tunnel-download-consent-required") return livePreviewLifecycle(locale).download;
  const text = livePreviewCopy(locale);
  return text[({ "tunnel-download-consent-required": 5, "tunnel-plugin-disabled": 6, "preview-account-required": 14,
    "tunnel-platform-unsupported": 15, "protocol-mismatch": 16, "remote-offline": 17, "preview-tunnel-unavailable": 23 } as Record<string, number>)[code] ?? 7];
}
