/**
 * [INPUT]: Depends on Node fetch/fs/path, models.dev `/api.json` The price/directory converters are strictly
 * [OUTPUT]: Provides catalog provenance summary of pricing: update Atomic generation and pricing: check the pump; 0 is success, 1 is data/difference, 2 is network failure
 * [POS]: The only author of the desktop build term price seed; PricingStore never changes the source code when the product is running
 */

import { readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import {
  convertModelsDev,
  type PricingCatalog,
} from "../electron/main/usage/pricing/catalog";

const API_URL = process.env.MODELS_DEV_API_URL ?? "https://models.dev/api.json";
const desktop = join(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = join(
  desktop,
  "electron/main/usage/pricing/model-pricing.data.ts"
);
const delays = [250, 1_000] as const;

export class PricingNetworkError extends Error {}

export function pricingFailureExitCode(cause: unknown) {
  return cause instanceof PricingNetworkError ? 2 : 1;
}

function sleep(ms: number) {
  return new Promise<void>((resolve) => setTimeout(resolve, ms));
}

export async function fetchModelsDev(
  request: typeof fetch = fetch,
  pause: (ms: number) => Promise<void> = sleep
) {
  let lastCause: unknown;
  for (let attempt = 0; attempt < 3; attempt += 1) {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 10_000);
    try {
      const response = await request(API_URL, { signal: controller.signal });
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      return await response.json();
    } catch (cause) {
      lastCause = cause;
    } finally {
      clearTimeout(timeout);
    }
    if (attempt < delays.length) await pause(delays[attempt]);
  }
  throw new PricingNetworkError("models.dev 请求三次均失败", {
    cause: lastCause,
  });
}

export function renderSeed(catalog: PricingCatalog, digest: string) {
  return `/**
 * [INPUT]: Generated by scripts/update-model-pricing.ts from models.dev Current directory definitions
 * [OUTPUT]: Provides the seedCatalog and seedSourceDigest required to start the application offline
 * [POS]: The use/pricing read-only price snapshot; Updating only overlay when running, not directly rewriting the file
 */

import type { PricingCatalog } from "./catalog";

export const seedCatalog: PricingCatalog = ${JSON.stringify(catalog, null, 2)};

export const seedSourceDigest = ${JSON.stringify(digest)};
`;
}

type PricingUpdateOptions = {
  output?: string;
  request?: typeof fetch;
  pause?: (ms: number) => Promise<void>;
};

export async function runPricingUpdate(
  check: boolean,
  options: PricingUpdateOptions = {}
) {
  const target = options.output ?? outputPath;
  const raw = await fetchModelsDev(options.request, options.pause);
  const converted = convertModelsDev(raw, "seed");
  const expected = renderSeed(converted.catalog, converted.catalogDigest);
  const current = await readFile(target, "utf8").catch(() => "");
  if (current === expected) return 0;
  if (check) return 1;
  const temporary = `${target}.tmp-${process.pid}`;
  try {
    await writeFile(temporary, expected, { encoding: "utf8", mode: 0o600 });
    await rename(temporary, target);
  } catch (cause) {
    await unlink(temporary).catch(() => undefined);
    throw cause;
  }
  return 0;
}

async function main() {
  const check = process.argv.slice(2).includes("--check");
  try {
    process.exitCode = await runPricingUpdate(check);
  } catch (cause) {
    console.error(cause instanceof Error ? cause.message : cause);
    process.exitCode = pricingFailureExitCode(cause);
  }
}

const invoked = process.argv[1]
  ? fileURLToPath(import.meta.url) === resolve(process.argv[1])
  : false;
if (invoked) void main();
