/**
 * [INPUT]: Depends on the narrow Objective-C screen source and macOS Command Line Tools.
 * [OUTPUT]: Provides a universal arm64/x86_64 helper in the selected assembly's presence directory.
 * [POS]: Native build step; generated bytes stay outside source inputs.
 */

import process from "node:process";
import { mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { resolveOutputRoot } from "../assembly/output-root.mjs";
const outputRoot = resolveOutputRoot(process.argv.slice(2));
if (process.platform === "darwin") {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
  const output = resolve(root, outputRoot, "presence/bin/screen-bridge");
  mkdirSync(dirname(output), { recursive: true });
  const result = spawnSync("xcrun", ["clang", "-arch", "arm64", "-arch", "x86_64", "-fobjc-arc", "-O2", "-mmacosx-version-min=12.0", "-framework", "AppKit",
    "-framework", "CoreGraphics", resolve(root, "resources/presence/native/screen-bridge.m"), "-o", output], { stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
}
