/**
 * [INPUT]: Narrow Objective-C screen and process-capture sources, plus macOS Command Line Tools.
 * [OUTPUT]: Universal screen and preview-capture helpers in the selected assembly's resource directories.
 * [POS]: Native build step; generated bytes stay outside source inputs.
 */

import process from "node:process";
import { mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { resolveOutputRoot } from "../assembly/output-root.mjs";
const outputRoot = resolveOutputRoot(process.argv.slice(2));
if (process.platform === "darwin") {
  const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
  const output = resolve(root, outputRoot, "presence/bin/screen-bridge");
  mkdirSync(dirname(output), { recursive: true });
  const result = spawnSync("xcrun", ["clang", "-arch", "arm64", "-arch", "x86_64", "-fobjc-arc", "-O2", "-mmacosx-version-min=12.0", "-framework", "AppKit",
    "-framework", "CoreGraphics", resolve(root, "resources/presence/native/screen-bridge.m"), "-o", output], { stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
  const capture = resolve(root, outputRoot, "tunnel/bin/preview-capture");
  mkdirSync(dirname(capture), { recursive: true });
  const captured = spawnSync("xcrun", ["clang", "-arch", "arm64", "-arch", "x86_64", "-fobjc-arc", "-O2", "-mmacosx-version-min=12.0", "-framework", "Foundation",
    resolve(root, "resources/tunnel/preview-capture.m"), "-o", capture], { stdio: "inherit" });
  if (captured.status !== 0) process.exit(captured.status ?? 1);
}
