/**
 * [INPUT]: Depends on the interface locale.
 * [OUTPUT]: Provides explicit Project deletion conflict, cancellation and fresh-review copy.
 * [POS]: Retained Project recovery text; no storage or authentication details reach the product flow.
 */
const en = { title: "Project deletion", pending: "Waiting for deletion confirmation", conflicted: "The Project changed before deletion", kept: "Deletion canceled", deleted: "Deleted in the cloud; local changes retained",
  review: "Review current Project", retry: "Retry original request", keep: "Keep Project", remove: "Delete reviewed Project", close: "Close", loading: "Loading…", error: "Could not complete this action. Your local data is retained.",
  description: "Review the current Project before deciding. Deletion permanently removes the Project and its synced Chats and Bases from the cloud.",
  retained: "Other computers keep their local content. This decision does not restore Chats already deleted.", online: "Connect to review or retry deletion.", more: "Load more", revision: "Current version {revision}", working: "Saving…" };
type Copy = { [K in keyof typeof en]: string };
const copies: Record<string, Copy> = {
  en,
  zh: { title: "Project 删除", pending: "等待删除确认", conflicted: "Project 在删除前已被修改", kept: "已取消删除", deleted: "云端已删除，本机修改仍保留", review: "查看当前 Project", retry: "重试原请求", keep: "保留 Project", remove: "删除已审阅的 Project", close: "关闭", loading: "正在读取…", error: "未能完成此操作，本机数据仍保留。", description: "请查看当前 Project 后再决定。删除会永久移除云端 Project 及其中已同步的 Chat 和 Base。", retained: "其他电脑会保留本机内容。此操作不会恢复已删除的 Chat。", online: "请联网后审阅或重试删除。", more: "加载更多", revision: "当前版本 {revision}", working: "正在保存…" },
  ja: { title: "Project の削除", pending: "削除の確認待ち", conflicted: "削除前に Project が変更されました", kept: "削除をキャンセルしました", deleted: "クラウドでは削除済み。ローカルの変更は保存されています", review: "現在の Project を確認", retry: "元の要求を再試行", keep: "Project を保持", remove: "確認した Project を削除", close: "閉じる", loading: "読み込み中…", error: "操作を完了できませんでした。ローカルデータは保持されています。", description: "現在の Project を確認してください。削除すると、Project と同期した Chat、Base がクラウドから完全に削除されます。", retained: "他のパソコンではローカル内容を保持します。削除済みの Chat は復元されません。", online: "確認または再試行には接続が必要です。", more: "もっと表示", revision: "現在のバージョン {revision}", working: "保存中…" },
  es: { title: "Eliminación de Project", pending: "Esperando confirmación", conflicted: "El Project cambió antes de eliminarse", kept: "Eliminación cancelada", deleted: "Eliminado de la nube; cambios locales conservados", review: "Revisar Project actual", retry: "Reintentar solicitud original", keep: "Conservar Project", remove: "Eliminar Project revisado", close: "Cerrar", loading: "Cargando…", error: "No se pudo completar la acción. Tus datos locales se conservan.", description: "Revisa el Project actual. Eliminarlo borra permanentemente el Project y sus Chats y Bases sincronizados de la nube.", retained: "Los otros ordenadores conservan su contenido local. Esto no restaura Chats ya eliminados.", online: "Conéctate para revisar o reintentar.", more: "Cargar más", revision: "Versión actual {revision}", working: "Guardando…" },
  fr: { title: "Suppression du Project", pending: "Confirmation en attente", conflicted: "Le Project a changé avant la suppression", kept: "Suppression annulée", deleted: "Supprimé du cloud ; modifications locales conservées", review: "Examiner le Project actuel", retry: "Réessayer la demande initiale", keep: "Conserver le Project", remove: "Supprimer le Project examiné", close: "Fermer", loading: "Chargement…", error: "L’action n’a pas abouti. Vos données locales sont conservées.", description: "Examinez le Project actuel. La suppression efface définitivement le Project et ses Chats et Bases synchronisés du cloud.", retained: "Les autres ordinateurs conservent leur contenu local. Les Chats déjà supprimés ne sont pas restaurés.", online: "Connectez-vous pour examiner ou réessayer.", more: "Afficher plus", revision: "Version actuelle {revision}", working: "Enregistrement…" },
};
export const projectDeletionCopy = (locale: string) => copies[locale.toLowerCase().split("-")[0]!] ?? en;
