/**
 * [INPUT]: Generated by scripts/update-model-pricing.ts from models.dev Current directory definitions
 * [OUTPUT]: Provides the seedCatalog and seedSourceDigest required to start the application offline
 * [POS]: The use/pricing read-only price snapshot; Updating only overlay when running, not directly rewriting the file
 */

import type { PricingCatalog } from "./catalog";

export const seedCatalog: PricingCatalog = {
  "providers": {
    "anthropic": {
      "claude-fable-5": {
        "input": 10,
        "cacheRead": 1,
        "cacheWrite": 12.5,
        "output": 50
      },
      "claude-haiku-4-5": {
        "input": 1,
        "cacheRead": 0.1,
        "cacheWrite": 1.25,
        "output": 5
      },
      "claude-haiku-4-5-20251001": {
        "input": 1,
        "cacheRead": 0.1,
        "cacheWrite": 1.25,
        "output": 5
      },
      "claude-opus-4-1": {
        "input": 15,
        "cacheRead": 1.5,
        "cacheWrite": 18.75,
        "output": 75
      },
      "claude-opus-4-1-20250805": {
        "input": 15,
        "cacheRead": 1.5,
        "cacheWrite": 18.75,
        "output": 75
      },
      "claude-opus-4-5": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-opus-4-5-20251101": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-opus-4-6": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-opus-4-7": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-opus-4-8": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-opus-5": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 25
      },
      "claude-sonnet-4-5": {
        "input": 3,
        "cacheRead": 0.3,
        "cacheWrite": 3.75,
        "output": 15
      },
      "claude-sonnet-4-5-20250929": {
        "input": 3,
        "cacheRead": 0.3,
        "cacheWrite": 3.75,
        "output": 15
      },
      "claude-sonnet-4-6": {
        "input": 3,
        "cacheRead": 0.3,
        "cacheWrite": 3.75,
        "output": 15
      },
      "claude-sonnet-5": {
        "input": 2,
        "cacheRead": 0.2,
        "cacheWrite": 2.5,
        "output": 10
      }
    },
    "openai": {
      "chatgpt-image-latest": null,
      "gpt-3.5-turbo": {
        "input": 0.5,
        "cacheRead": 0,
        "cacheWrite": 0.5,
        "output": 1.5
      },
      "gpt-4": {
        "input": 30,
        "cacheRead": 30,
        "cacheWrite": 30,
        "output": 60
      },
      "gpt-4-turbo": {
        "input": 10,
        "cacheRead": 10,
        "cacheWrite": 10,
        "output": 30
      },
      "gpt-4.1": {
        "input": 2,
        "cacheRead": 0.5,
        "cacheWrite": 2,
        "output": 8
      },
      "gpt-4.1-mini": {
        "input": 0.4,
        "cacheRead": 0.1,
        "cacheWrite": 0.4,
        "output": 1.6
      },
      "gpt-4.1-nano": {
        "input": 0.1,
        "cacheRead": 0.025,
        "cacheWrite": 0.1,
        "output": 0.4
      },
      "gpt-4o": {
        "input": 2.5,
        "cacheRead": 1.25,
        "cacheWrite": 2.5,
        "output": 10
      },
      "gpt-4o-2024-05-13": {
        "input": 5,
        "cacheRead": 5,
        "cacheWrite": 5,
        "output": 15
      },
      "gpt-4o-2024-08-06": {
        "input": 2.5,
        "cacheRead": 1.25,
        "cacheWrite": 2.5,
        "output": 10
      },
      "gpt-4o-2024-11-20": {
        "input": 2.5,
        "cacheRead": 1.25,
        "cacheWrite": 2.5,
        "output": 10
      },
      "gpt-4o-mini": {
        "input": 0.15,
        "cacheRead": 0.075,
        "cacheWrite": 0.15,
        "output": 0.6
      },
      "gpt-5": {
        "input": 1.25,
        "cacheRead": 0.125,
        "cacheWrite": 1.25,
        "output": 10
      },
      "gpt-5-mini": {
        "input": 0.25,
        "cacheRead": 0.025,
        "cacheWrite": 0.25,
        "output": 2
      },
      "gpt-5-nano": {
        "input": 0.05,
        "cacheRead": 0.005,
        "cacheWrite": 0.05,
        "output": 0.4
      },
      "gpt-5-pro": {
        "input": 15,
        "cacheRead": 15,
        "cacheWrite": 15,
        "output": 120
      },
      "gpt-5.1": {
        "input": 1.25,
        "cacheRead": 0.125,
        "cacheWrite": 1.25,
        "output": 10
      },
      "gpt-5.2": {
        "input": 1.75,
        "cacheRead": 0.175,
        "cacheWrite": 1.75,
        "output": 14
      },
      "gpt-5.2-chat-latest": {
        "input": 1.75,
        "cacheRead": 0.175,
        "cacheWrite": 1.75,
        "output": 14
      },
      "gpt-5.2-pro": {
        "input": 21,
        "cacheRead": 21,
        "cacheWrite": 21,
        "output": 168
      },
      "gpt-5.3-chat-latest": {
        "input": 1.75,
        "cacheRead": 0.175,
        "cacheWrite": 1.75,
        "output": 14
      },
      "gpt-5.3-codex": {
        "input": 1.75,
        "cacheRead": 0.175,
        "cacheWrite": 1.75,
        "output": 14
      },
      "gpt-5.3-codex-spark": {
        "input": 1.75,
        "cacheRead": 0.175,
        "cacheWrite": 1.75,
        "output": 14
      },
      "gpt-5.4": {
        "input": 2.5,
        "cacheRead": 0.25,
        "cacheWrite": 2.5,
        "output": 15
      },
      "gpt-5.4-mini": {
        "input": 0.75,
        "cacheRead": 0.075,
        "cacheWrite": 0.75,
        "output": 4.5
      },
      "gpt-5.4-nano": {
        "input": 0.2,
        "cacheRead": 0.02,
        "cacheWrite": 0.2,
        "output": 1.25
      },
      "gpt-5.4-pro": {
        "input": 30,
        "cacheRead": 30,
        "cacheWrite": 30,
        "output": 180
      },
      "gpt-5.5": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 5,
        "output": 30
      },
      "gpt-5.5-pro": {
        "input": 30,
        "cacheRead": 30,
        "cacheWrite": 30,
        "output": 180
      },
      "gpt-5.6": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 30
      },
      "gpt-5.6-luna": {
        "input": 0.2,
        "cacheRead": 0.02,
        "cacheWrite": 0.25,
        "output": 1.2
      },
      "gpt-5.6-sol": {
        "input": 5,
        "cacheRead": 0.5,
        "cacheWrite": 6.25,
        "output": 30
      },
      "gpt-5.6-terra": {
        "input": 2,
        "cacheRead": 0.2,
        "cacheWrite": 2.5,
        "output": 12
      },
      "gpt-image-1": null,
      "gpt-image-1-mini": null,
      "gpt-image-1.5": null,
      "gpt-image-2": {
        "input": 5,
        "cacheRead": 1.25,
        "cacheWrite": 5,
        "output": 30
      },
      "gpt-realtime-2.1": {
        "input": 4,
        "cacheRead": 0.4,
        "cacheWrite": 4,
        "output": 24
      },
      "o1": {
        "input": 15,
        "cacheRead": 7.5,
        "cacheWrite": 15,
        "output": 60
      },
      "o1-pro": {
        "input": 150,
        "cacheRead": 150,
        "cacheWrite": 150,
        "output": 600
      },
      "o3": {
        "input": 2,
        "cacheRead": 0.5,
        "cacheWrite": 2,
        "output": 8
      },
      "o3-mini": {
        "input": 1.1,
        "cacheRead": 0.55,
        "cacheWrite": 1.1,
        "output": 4.4
      },
      "o3-pro": {
        "input": 20,
        "cacheRead": 20,
        "cacheWrite": 20,
        "output": 80
      },
      "o4-mini": {
        "input": 1.1,
        "cacheRead": 0.275,
        "cacheWrite": 1.1,
        "output": 4.4
      },
      "text-embedding-3-large": {
        "input": 0.13,
        "cacheRead": 0.13,
        "cacheWrite": 0.13,
        "output": 0
      },
      "text-embedding-3-small": {
        "input": 0.02,
        "cacheRead": 0.02,
        "cacheWrite": 0.02,
        "output": 0
      },
      "text-embedding-ada-002": {
        "input": 0.1,
        "cacheRead": 0.1,
        "cacheWrite": 0.1,
        "output": 0
      }
    },
    "moonshotai": {
      "kimi-k2-0711-preview": {
        "input": 0.6,
        "cacheRead": 0.15,
        "cacheWrite": 0.6,
        "output": 2.5
      },
      "kimi-k2-0905-preview": {
        "input": 0.6,
        "cacheRead": 0.15,
        "cacheWrite": 0.6,
        "output": 2.5
      },
      "kimi-k2-thinking": {
        "input": 0.6,
        "cacheRead": 0.15,
        "cacheWrite": 0.6,
        "output": 2.5
      },
      "kimi-k2-thinking-turbo": {
        "input": 1.15,
        "cacheRead": 0.15,
        "cacheWrite": 1.15,
        "output": 8
      },
      "kimi-k2-turbo-preview": {
        "input": 2.4,
        "cacheRead": 0.6,
        "cacheWrite": 2.4,
        "output": 10
      },
      "kimi-k2.5": {
        "input": 0.6,
        "cacheRead": 0.1,
        "cacheWrite": 0.6,
        "output": 3
      },
      "kimi-k2.6": {
        "input": 0.95,
        "cacheRead": 0.16,
        "cacheWrite": 0.95,
        "output": 4
      },
      "kimi-k2.7-code": {
        "input": 0.95,
        "cacheRead": 0.19,
        "cacheWrite": 0.95,
        "output": 4
      },
      "kimi-k2.7-code-highspeed": {
        "input": 1.9,
        "cacheRead": 0.38,
        "cacheWrite": 1.9,
        "output": 8
      },
      "kimi-k3": {
        "input": 3,
        "cacheRead": 0.3,
        "cacheWrite": 3,
        "output": 15
      }
    }
  },
  "kimiAliases": {
    "k3": "kimi-k3",
    "k3-256k": "kimi-k3",
    "kimi-for-coding": "kimi-k2.7-code",
    "kimi-for-coding-highspeed": "kimi-k2.7-code-highspeed"
  }
};

export const seedSourceDigest = "8f7d6d43d14895ee9bbc3525ec98583ad508bc2f9d1193295a660ae73fa005c4";
