/**
 * [INPUT]: Depends on the settingsExtensionsEn structural type
 * [OUTPUT]: Provides settingsExtensionsEs, the Spanish Settings › Extensions catalog
 * [POS]: Spanish leaf of shared/i18n/locales/settings/extensions; loaded on demand by the matching top-level locale
 */

import type { settingsExtensionsEn } from "./en";

export const settingsExtensionsEs: typeof settingsExtensionsEn = {
  page: {
    bridgeMissing: "La gestión de extensiones no está disponible en este entorno (falta el bridge IPC)", admissionClosed: "Una extensión está convergiendo a desactivada: se revocan proyecciones, se liberan artefactos, se reinician sesiones con snapshots antiguos y se invalidan cachés. No se inician Agents nuevos hasta terminar.", installedTitle: "Extensiones instaladas", installedDescription: "Instala extensiones desde GitHub. Sus Skills quedan disponibles de inmediato para todos los Agents.", installGithub: "Instalar desde GitHub", emptyTitle: "No hay extensiones instaladas", emptyHint: "Instala una extensión desde GitHub para empezar.", retainedTitle: "Desinstaladas con datos conservados", retainedDescription: "Eliminar el código del paquete nunca borra de forma implícita sus datos. El borrado permanente es una acción separada y reinstalar no recupera datos eliminados.", purgeData: "Eliminar datos permanentemente", retainedCustody: "Custody aún activa: {{custody}}", retainedEpochs: "Quedan {{count}} data epochs en este equipo.",
  },
  install: {
    stage: { source: { title: "Añadir extensión", description: "Pega la página principal del repositorio GitHub. El sistema fija un commit, admite un paquete Agent Plugins 1.0 si existe plugin.json o importa un repositorio puro skills/<nombre>/SKILL.md. La confirmación activa los Skills de inmediato.", commit: "Continuar", pending: "Resolviendo origen…" }, install: { title: "Confirmar instalación", commit: "Confirmar instalación", pending: "Instalando…" }, update: { title: "Confirmar actualización", commit: "Confirmar actualización", pending: "Actualizando…" } }, resolveFailed: "No se pudo resolver el origen", installFailed: "Falló la instalación", summary: "{{url}} @ {{commit}} ({{files}} archivos / {{kilobytes}} KB)", repository: "URL del repositorio", repositoryHint: "Las capacidades se muestran tras resolver un commit inmutable; no se escribe en el registro antes de confirmar. Un repositorio ya instalado se convierte en una generación nueva.", back: "Volver",
    disclosure: { format: "Formato detectado", pluginFormat: "Paquete Agent Plugins 1.0 (plugin.json en la raíz).", skillFormat: "Repositorio de Skills puro (sin plugin.json; solo skills/).", scripts: "Scripts ejecutables", none: "Ninguno", skill: "Skill {{name}}", allowedTools: "allowed-tools: {{tools}}", undeclared: "Sin declarar", mcp: "MCP {{serverId}} ({{transport}})", mcpUnavailable: "La entrega MCP aún no está disponible y se abrirá por niveles separados. {{target}}", staticHeaders: "; headers estáticos: {{headers}}", writeRoot: "Raíz de escritura persistente", writeRootRequired: "Incluye un servidor stdio y necesita una raíz install-owned. Cada generación usa su propio data epoch.", writeRootNone: "No necesaria", capabilityChange: "Cambios de capacidades", addedRemoved: "Añadidas: {{added}} | eliminadas: {{removed}}", noChange: "Sin cambios", report: "Nota del analizador", postUpdate: "Estado tras actualizar", postInstall: "Estado tras instalar", reauthorize: "Las capacidades aumentaron: la generación nueva empieza desactivada y cada componente debe volver a activarse. La generación anterior sigue atendiendo a las Apps vinculadas.", retainAuthorization: "Las capacidades no aumentaron: se mantienen los ajustes actuales y la generación anterior sigue atendiendo a las Apps vinculadas.", defaultEnabled: "La confirmación activa los Skills de inmediato.", migrateAria: "Migrar {{appId}} a la generación nueva", migrateDescription: "Actualmente vinculada a {{generation}}. Migrar crea una generación pendiente de autorización; sin migrar, la App sigue usando la anterior.", migrateLabel: "Migrar App {{appId}}" },
  },
  package: {
    enabledCount: "{{enabled}}/{{total}} Skills activados", mcpUnavailable: "La entrega MCP aún no está disponible", manageSkills: "Gestionar Skills",
    description: "{{admission}} · {{administration}} · catálogo {{catalog}} · permisos de App independientes · commit {{commit}}", admission: { valid: "Admitida", misconfigured: "Configuración incorrecta" }, administration: { active: "Administración activa", "disable-pending": "Desactivación administrativa convergiendo", denied: "Administración denegada" }, catalog: { on: "activado", off: "desactivado" }, checkUpdate: "Buscar actualizaciones", disable: "Desactivar", cancelUninstall: "Cancelar desinstalación", uninstall: "Desinstalar", eligibilityEntry: "{{backend}}: {{status}}", componentDescription: "{{kind}} · {{transport}}", kind: { skill: "Skill", "mcp-server": "Servidor MCP" }, generation: "Generación anterior {{generation}}", generationBlocked: "Sigue vinculada exactamente por {{count}} propietarios; se conserva inmutable y direccionable.", generationFree: "Sin referencias; se puede retirar con una desinstalación separada.", done: "Completado", pending: "Pendiente", convergenceBlocked: "Convergencia bloqueada", foreignCopy: "Copia externa {{projectionId}}", foreignCopyDetail: "{{componentInstanceIdentity}} no fue escrito por el producto. Solo puede marcarse como {{strength}} y debe resolverse manualmente.", uninstallBlocked: "Desinstalación bloqueada", otherOwners: "Otros propietarios", runtimeReferences: "Referencias runtime", runtimeReferencesDetail: "Quedan {{leases}} leases de proyección; {{artifacts}} artefactos compartidos siguen referenciados y no se eliminarán.", custody: "Custody de proceso / transport", migrate: "Migrar a generación nueva", migrateDescription: "Sigue vinculada exactamente a {{generation}}. La migración vuelve a fijar con la referencia cerrada: required pasa a blocked, optional a degraded y requiere autorización. Si no, cancela la desinstalación.", retryUninstall: "Reintentar desinstalación",
    convergenceStep: { "projection-binding-revoked": "Revocar proyecciones gestionadas", "shared-artifacts-released": "Liberar artefactos por refcount", "product-sessions-drained": "Reiniciar sesiones con snapshots antiguos", "discovery-cache-invalidated": "Invalidar cachés de descubrimiento" }, uninstallStep: { "durable-references-resolved": "Resolver referencias duraderas", "runtime-custody-drained": "Vaciar leases y custody de runtime", "package-generations-removed": "Eliminar todas las generaciones del paquete", "package-bytes-collected": "Recoger bytes sin referencias salvo datos install-owned" }, strength: { "per-tool-enforced": "forzado por herramienta", "per-turn-enforced": "forzado por turno", "server-inclusion-only": "servidor completo", "workspace-requested": "workspace solicitado", "backend-delegated": "delegado al backend", "unsupported-by-policy": "bloqueado por política", unknown: "desconocido" }, exclusion: { "package-disabled": "paquete desactivado", "package-disable-pending": "desactivación de paquete pendiente", "package-generation-removal-pending": "eliminación de generación pendiente", "component-disabled": "componente desactivado", "backend-capability-mismatch": "capacidad del backend incompatible", "delivery-channel-unsupported": "canal de entrega incompatible", "transport-unsupported": "transport incompatible", "projection-unavailable": "proyección no disponible", "runtime-health-failed": "falló el estado del runtime", "turn-policy-ineligible": "turno no elegible", "snapshot-materialization-failed": "falló la materialización del snapshot" },
  },
};
