/**
 * [INPUT]: Depends on the settingsExtensionsEn structural type
 * [OUTPUT]: Provides settingsExtensionsFr, the French Settings › Extensions catalog
 * [POS]: French leaf of shared/i18n/locales/settings/extensions; loaded on demand by the matching top-level locale
 */

import type { settingsExtensionsEn } from "./en";

export const settingsExtensionsFr: typeof settingsExtensionsEn = {
  page: {
    bridgeMissing: "La gestion des extensions est indisponible dans cet environnement (bridge IPC absent)", admissionClosed: "Une extension converge vers l’état désactivé : révocation des projections, libération des artefacts, redémarrage des sessions avec un ancien snapshot et invalidation des caches. Aucun nouvel Agent ne démarre avant la fin.", installedTitle: "Extensions installées", installedDescription: "Installez des extensions depuis GitHub. Leurs Skills sont immédiatement disponibles pour tous les Agents.", installGithub: "Installer depuis GitHub", emptyTitle: "Aucune extension installée", emptyHint: "Installez une extension depuis GitHub pour commencer.", retainedTitle: "Désinstallées avec données conservées", retainedDescription: "Supprimer le code du package ne supprime jamais implicitement ses données. La suppression définitive est séparée et une réinstallation ne peut pas récupérer les données supprimées.", purgeData: "Supprimer définitivement les données", retainedCustody: "Custody encore active : {{custody}}", retainedEpochs: "{{count}} data epochs restent sur cet ordinateur.",
  },
  install: {
    stage: { source: { title: "Ajouter une extension", description: "Collez l’URL d’accueil du dépôt GitHub. Le système fige un commit, admet un package Agent Plugins 1.0 si plugin.json existe, sinon importe un dépôt pur skills/<nom>/SKILL.md. La confirmation active immédiatement les Skills.", commit: "Continuer", pending: "Résolution de la source…" }, install: { title: "Confirmer l’installation", commit: "Confirmer l’installation", pending: "Installation…" }, update: { title: "Confirmer la mise à jour", commit: "Confirmer la mise à jour", pending: "Mise à jour…" } }, resolveFailed: "Échec de résolution de la source", installFailed: "Échec de l’installation", summary: "{{url}} @ {{commit}} ({{files}} fichiers / {{kilobytes}} Ko)", repository: "URL du dépôt", repositoryHint: "Les capacités apparaissent après résolution d’un commit immuable ; rien n’est écrit dans le registre avant confirmation. Un dépôt déjà installé devient une nouvelle génération.", back: "Retour",
    disclosure: { format: "Format détecté", pluginFormat: "Package Agent Plugins 1.0 (plugin.json à la racine).", skillFormat: "Dépôt de Skills pur (sans plugin.json ; sous-arbre skills/ uniquement).", scripts: "Scripts exécutables", none: "Aucun", skill: "Skill {{name}}", allowedTools: "allowed-tools : {{tools}}", undeclared: "Non déclaré", mcp: "MCP {{serverId}} ({{transport}})", mcpUnavailable: "La livraison MCP n’est pas encore disponible et sera ouverte par paliers séparés. {{target}}", staticHeaders: " ; headers statiques : {{headers}}", writeRoot: "Racine d’écriture persistante", writeRootRequired: "Contient un serveur stdio et nécessite une racine install-owned. Chaque génération utilise son propre data epoch.", writeRootNone: "Non requise", capabilityChange: "Évolution des capacités", addedRemoved: "Ajout : {{added}} | retrait : {{removed}}", noChange: "Aucun changement", report: "Note d’analyse", postUpdate: "État après mise à jour", postInstall: "État après installation", reauthorize: "Les capacités augmentent : la nouvelle génération est désactivée et chaque composant doit être réactivé. L’ancienne génération immuable continue de servir les Apps liées.", retainAuthorization: "Les capacités n’augmentent pas : les réglages actuels sont conservés et l’ancienne génération continue de servir les Apps liées.", defaultEnabled: "La confirmation active immédiatement les Skills.", migrateAria: "Migrer {{appId}} vers la nouvelle génération", migrateDescription: "Actuellement lié à {{generation}}. La migration crée une génération en attente d’autorisation ; sans migration, l’App garde l’ancienne.", migrateLabel: "Migrer l’App {{appId}}" },
  },
  package: {
    enabledCount: "{{enabled}}/{{total}} Skills activés", mcpUnavailable: "La livraison MCP n’est pas encore disponible", manageSkills: "Gérer les Skills",
    description: "{{admission}} · {{administration}} · catalogue {{catalog}} · autorisations App indépendantes · commit {{commit}}", admission: { valid: "Admise", misconfigured: "Configuration incorrecte" }, administration: { active: "Administration active", "disable-pending": "Désactivation administrative en convergence", denied: "Administration refusée" }, catalog: { on: "activé", off: "désactivé" }, checkUpdate: "Rechercher une mise à jour", disable: "Désactiver", cancelUninstall: "Annuler la désinstallation", uninstall: "Désinstaller", eligibilityEntry: "{{backend}} : {{status}}", componentDescription: "{{kind}} · {{transport}}", kind: { skill: "Skill", "mcp-server": "Serveur MCP" }, generation: "Génération précédente {{generation}}", generationBlocked: "Toujours liée précisément par {{count}} propriétaires ; conservée immuable et adressable.", generationFree: "Non référencée, récupérable par une désinstallation séparée.", done: "Terminé", pending: "En attente", convergenceBlocked: "Convergence bloquée", foreignCopy: "Copie externe {{projectionId}}", foreignCopyDetail: "{{componentInstanceIdentity}} n’a pas été écrit par le produit. Il peut seulement être marqué {{strength}} et doit être traité manuellement.", uninstallBlocked: "Désinstallation bloquée", otherOwners: "Autres propriétaires", runtimeReferences: "Références runtime", runtimeReferencesDetail: "{{leases}} leases de projection restent actives ; {{artifacts}} artefacts partagés sont encore référencés et ne seront pas supprimés.", custody: "Custody processus / transport", migrate: "Migrer vers la nouvelle génération", migrateDescription: "Toujours lié précisément à {{generation}}. La migration regèle la référence fermée : required devient blocked, optional devient degraded, avec nouvelle autorisation. Sinon annulez la désinstallation.", retryUninstall: "Réessayer la désinstallation",
    convergenceStep: { "projection-binding-revoked": "Révoquer les projections gérées", "shared-artifacts-released": "Libérer les artefacts par refcount", "product-sessions-drained": "Redémarrer les sessions avec anciens snapshots", "discovery-cache-invalidated": "Invalider les caches de découverte" }, uninstallStep: { "durable-references-resolved": "Résoudre les références durables", "runtime-custody-drained": "Vider les leases et custody runtime", "package-generations-removed": "Supprimer toutes les générations du package", "package-bytes-collected": "Récupérer les octets non référencés hors données install-owned" }, strength: { "per-tool-enforced": "imposé par outil", "per-turn-enforced": "imposé par tour", "server-inclusion-only": "serveur entier uniquement", "workspace-requested": "workspace demandé", "backend-delegated": "délégué au backend", "unsupported-by-policy": "bloqué par la politique", unknown: "inconnu" }, exclusion: { "package-disabled": "package désactivé", "package-disable-pending": "désactivation du package en attente", "package-generation-removal-pending": "suppression de génération en attente", "component-disabled": "composant désactivé", "backend-capability-mismatch": "capacité backend incompatible", "delivery-channel-unsupported": "canal de livraison incompatible", "transport-unsupported": "transport incompatible", "projection-unavailable": "projection indisponible", "runtime-health-failed": "échec de santé runtime", "turn-policy-ineligible": "tour non éligible", "snapshot-materialization-failed": "échec de matérialisation du snapshot" },
  },
};
