/**
 * [INPUT]: Depends on the settingsExtensionsEn structural type
 * [OUTPUT]: Provides settingsExtensionsJa, the Japanese Settings › Extensions catalog
 * [POS]: Japanese leaf of shared/i18n/locales/settings/extensions; loaded on demand by the matching top-level locale
 */

import type { settingsExtensionsEn } from "./en";

export const settingsExtensionsJa: typeof settingsExtensionsEn = {
  page: {
    bridgeMissing: "この環境では拡張を管理できません（IPC bridge なし）", admissionClosed: "拡張を無効化する収束処理中です。投影の解除、共有成果物の解放、古い discovery snapshot を持つセッションの再起動、キャッシュ無効化が完了するまで新しい Agent セッションは開始しません。", installedTitle: "インストール済み拡張", installedDescription: "GitHub から拡張をインストールすると、Skills がすべての Agent ですぐに使えます。", installGithub: "GitHub からインストール", emptyTitle: "拡張はまだありません", emptyHint: "GitHub から拡張をインストールして始めましょう。", retainedTitle: "アンインストール済み・データ保持中", retainedDescription: "package コードの削除は install-owned データを暗黙に消しません。完全削除は独立した操作で、削除後に同じリポジトリを再インストールしても復元できません。", purgeData: "データを完全に削除", retainedCustody: "custody が残っています：{{custody}}", retainedEpochs: "{{count}} 個の data epoch がこのコンピューターに残っています。",
  },
  install: {
    stage: { source: { title: "拡張を追加", description: "GitHub リポジトリのホーム URL を貼り付けます。システムは commit を固定し、plugin.json があれば Agent Plugins 1.0 package、それ以外は純粋な skills/<名前>/SKILL.md repository として扱います。確認すると Skills がすぐに有効になります。", commit: "続行", pending: "ソースを解決中…" }, install: { title: "インストールの確認", commit: "インストールを確認", pending: "インストール中…" }, update: { title: "更新の確認", commit: "更新を確認", pending: "更新中…" } }, resolveFailed: "ソースの解決に失敗しました", installFailed: "インストールに失敗しました", summary: "{{url}} @ {{commit}}（{{files}} ファイル / {{kilobytes}} KB）", repository: "リポジトリ URL", repositoryHint: "不変 commit の解決後に機能を表示し、確認までは registry に書きません。インストール済みの同じリポジトリは新しい generation になります。", back: "戻る",
    disclosure: { format: "検出形式", pluginFormat: "Agent Plugins 1.0 package（ルートに plugin.json）。", skillFormat: "純粋な Skill repository（plugin.json なし、skills/ のみ）。", scripts: "実行可能スクリプト", none: "なし", skill: "Skill {{name}}", allowedTools: "allowed-tools：{{tools}}", undeclared: "未宣言", mcp: "MCP {{serverId}}（{{transport}}）", mcpUnavailable: "MCP component の配信は現在利用できず、別ポリシーで段階的に開放されます。{{target}}", staticHeaders: "；静的 header：{{headers}}", writeRoot: "永続データ書き込みルート", writeRootRequired: "stdio server を含むため install-owned 書き込みルートが必要です。新 generation は独立した data epoch を使います。", writeRootNone: "不要", capabilityChange: "前 generation からの機能変更", addedRemoved: "追加：{{added}}｜削除：{{removed}}", noChange: "変更なし", report: "解析メモ", postUpdate: "更新後の状態", postInstall: "インストール後の状態", reauthorize: "機能が拡大しました。新 generation は無効で始まり、component ごとに再有効化が必要です。旧 generation は不変のまま既存 App に提供されます。", retainAuthorization: "機能は拡大していません。現在の component 設定を引き継ぎ、旧 generation は既存 App に提供されます。", defaultEnabled: "確認すると Skills がすぐに有効になります。", migrateAria: "{{appId}} を新 generation に移行", migrateDescription: "現在 {{generation}} に紐づいています。移行すると承認待ちの新 generation を作成し、移行しなければ旧 generation を使い続けます。", migrateLabel: "App {{appId}} を移行" },
  },
  package: {
    enabledCount: "Skills {{enabled}}/{{total}} 件が有効", mcpUnavailable: "MCP 配信はまだ利用できません", manageSkills: "Skills を管理",
    description: "{{admission}}・{{administration}}・カタログ {{catalog}}・App 権限は独立・commit {{commit}}", admission: { valid: "承認済み", misconfigured: "設定エラー" }, administration: { active: "管理状態は正常", "disable-pending": "管理無効化の収束中", denied: "管理状態は拒否" }, catalog: { on: "オン", off: "オフ" }, checkUpdate: "更新を確認", disable: "無効化", cancelUninstall: "アンインストールを中止", uninstall: "アンインストール", eligibilityEntry: "{{backend}}：{{status}}", componentDescription: "{{kind}}・{{transport}}", kind: { skill: "Skill", "mcp-server": "MCP server" }, generation: "前 generation {{generation}}", generationBlocked: "{{count}} 所有者が正確に参照中のため、不変・参照可能なまま保持します。", generationFree: "参照がなく、独立したアンインストール操作で回収できます。", done: "完了", pending: "保留", convergenceBlocked: "収束がブロック", foreignCopy: "外部コピー {{projectionId}}", foreignCopyDetail: "{{componentInstanceIdentity}} は製品が書いたコピーではありません。{{strength}} とだけ表示し、手動で処理してください。製品は解除済みとは主張しません。", uninstallBlocked: "アンインストールがブロック", otherOwners: "他の所有者", runtimeReferences: "実行時参照", runtimeReferencesDetail: "未返却の projection lease が {{leases}} 件、参照中で削除しない共有成果物が {{artifacts}} 件あります。", custody: "プロセス / transport custody", migrate: "新 generation に移行", migrateDescription: "{{generation}} に正確に紐づいています。移行するとこの参照を閉じた snapshot で再固定し、required は blocked、optional は degraded となり再承認が必要です。移行しない場合はアンインストールを中止します。", retryUninstall: "アンインストールを再試行",
    convergenceStep: { "projection-binding-revoked": "製品管理の投影バインドを解除", "shared-artifacts-released": "refcount で共有成果物を解放", "product-sessions-drained": "古い discovery snapshot のセッションを再起動", "discovery-cache-invalidated": "discovery cache を無効化" }, uninstallStep: { "durable-references-resolved": "durable 参照を解決（reservation、App generation、他所有者）", "runtime-custody-drained": "plan lease、projection lease、process custody を解消", "package-generations-removed": "すべての package generation を削除", "package-bytes-collected": "install-owned データを除く未参照 package byte を回収" }, strength: { "per-tool-enforced": "ツール単位で強制", "per-turn-enforced": "ターン単位で強制", "server-inclusion-only": "server 全体のみ", "workspace-requested": "workspace 要求", "backend-delegated": "backend に委任", "unsupported-by-policy": "ポリシーで非対応", unknown: "不明" }, exclusion: { "package-disabled": "package 無効", "package-disable-pending": "package 無効化待ち", "package-generation-removal-pending": "generation 削除待ち", "component-disabled": "component 無効", "backend-capability-mismatch": "backend 機能不一致", "delivery-channel-unsupported": "配信チャネル非対応", "transport-unsupported": "transport 非対応", "projection-unavailable": "投影利用不可", "runtime-health-failed": "runtime 状態エラー", "turn-policy-ineligible": "ターンポリシー対象外", "snapshot-materialization-failed": "snapshot 生成失敗" },
  },
};
