/**
 * [INPUT]: Depends on the host-selected locale.
 * [OUTPUT]: Provides five-language Chat reading and file labels plus compact interaction-completion copy independent of remote composer catalogs.
 * [POS]: Shared presentation copy; transport and execution errors stay structured in client adapters.
 */
const en = { outline: "Conversation outline", showMore: "Show more", showLess: "Show less", partial: "Some imported history is incomplete. The available messages are preserved.", latest: "Latest messages", previous: "Previous", next: "Next", assistant: "Assistant", fullMessage: "Read full message", loading: "Loading conversation…", pending: "This conversation is still syncing.", unavailable: "Content is unavailable. Try again when connected.",
  retry: "Try again", earlier: "Show earlier messages", empty: "No messages yet", readOnly: "Read-only conversation", appReadOnly: "Read-only App conversation. Saved messages and files remain available here.",
  running: "Responding", unknown: "The computer has not confirmed whether this reply is still running.", sealing: "Saving the available reply…", settling: "Loading the saved reply…",
  interrupted: "This reply was interrupted. The available content has been preserved.", complete: "Reply saved", attachment: "Open attachment", download: "Download", failedFile: "Could not load the file.",
  copy: "Copy", copied: "Copied", process: "Activity", subagent: "Subagent", unavailableDetail: "Details are unavailable.", plan: "Plan", imported: "Imported history", close: "Close",
  omittedTools: "{count} tool outputs were not synced", user: "You", switchedDevice: "Continued on {device}", switchedAgent: "Continued with {agent}", archived: "Archived", interactions: "Respond to this request on the computer running this conversation." };
export type ChatCopy = { [K in keyof typeof en]: string };
const copies: Record<string, ChatCopy> = {
  en,
  zh: { outline: "会话大纲", showMore: "显示更多", showLess: "收起", partial: "部分导入历史不完整，已有消息已保留。", latest: "回到最新消息", previous: "上一页", next: "下一页", assistant: "助手", fullMessage: "阅读完整消息", loading: "正在加载对话…", pending: "这段对话仍在同步。", unavailable: "内容暂不可用，请联网后重试。", retry: "重试", earlier: "显示更早的消息", empty: "还没有消息", readOnly: "只读对话",
    appReadOnly: "此 App 专用对话仅供阅读，已保存的消息与文件可在此查看。", running: "正在回复", unknown: "尚未确认执行电脑是否仍在回复。", sealing: "正在保存已有回复…", settling: "正在读取已保存的回复…",
    interrupted: "此回复已中断，已有内容已保留。", complete: "回复已保存", attachment: "打开附件", download: "下载", failedFile: "文件加载失败。", copy: "复制", copied: "已复制", process: "执行过程",
    subagent: "子 Agent", unavailableDetail: "详情暂不可用。", plan: "计划", imported: "导入的历史记录", close: "关闭", omittedTools: "{count} 条工具输出未同步", user: "你", switchedDevice: "从此处开始在 {device} 上运行", switchedAgent: "从此处开始使用 {agent}", archived: "已归档", interactions: "请在执行此对话的电脑上回应此请求。" },
  ja: { outline: "会話のアウトライン", showMore: "もっと見る", showLess: "折りたたむ", partial: "インポート履歴の一部が不完全です。利用可能な内容は保存されています。", latest: "最新のメッセージ", previous: "前へ", next: "次へ", assistant: "アシスタント", fullMessage: "全文を読む", loading: "会話を読み込み中…", pending: "この会話は同期中です。", unavailable: "内容を取得できません。接続後に再試行してください。", retry: "再試行", earlier: "以前のメッセージ", empty: "メッセージはまだありません", readOnly: "読み取り専用の会話",
    appReadOnly: "この App の会話は読み取り専用です。保存済みのメッセージとファイルを閲覧できます。", running: "応答中", unknown: "パソコンがまだ応答中か確認できません。", sealing: "利用可能な応答を保存中…", settling: "保存済みの応答を読み込み中…",
    interrupted: "応答が中断されました。利用可能な内容は保存されています。", complete: "応答を保存しました", attachment: "添付ファイルを開く", download: "ダウンロード", failedFile: "ファイルを読み込めませんでした。", copy: "コピー", copied: "コピーしました", process: "アクティビティ",
    subagent: "サブエージェント", unavailableDetail: "詳細を取得できません。", plan: "プラン", imported: "インポートした履歴", close: "閉じる", omittedTools: "{count} 件のツール出力は同期されていません", user: "あなた", switchedDevice: "{device} で続行", switchedAgent: "{agent} で続行", archived: "アーカイブ済み", interactions: "この会話を実行しているパソコンで応答してください。" },
  fr: { outline: "Plan de la conversation", showMore: "Afficher plus", showLess: "Afficher moins", partial: "Une partie de l’historique importé est incomplète. Les messages disponibles sont conservés.", latest: "Derniers messages", previous: "Précédent", next: "Suivant", assistant: "Assistant", fullMessage: "Lire le message complet", loading: "Chargement de la conversation…", pending: "Cette conversation est en cours de synchronisation.", unavailable: "Contenu indisponible. Réessayez une fois connecté.", retry: "Réessayer", earlier: "Messages précédents", empty: "Aucun message", readOnly: "Conversation en lecture seule",
    appReadOnly: "Conversation App en lecture seule. Les messages et fichiers enregistrés restent consultables ici.", running: "Réponse en cours", unknown: "L’ordinateur n’a pas confirmé si la réponse est toujours en cours.", sealing: "Enregistrement de la réponse disponible…", settling: "Chargement de la réponse enregistrée…",
    interrupted: "Cette réponse a été interrompue. Le contenu disponible a été conservé.", complete: "Réponse enregistrée", attachment: "Ouvrir la pièce jointe", download: "Télécharger", failedFile: "Impossible de charger le fichier.", copy: "Copier", copied: "Copié", process: "Activité",
    subagent: "Sous-agent", unavailableDetail: "Détails indisponibles.", plan: "Plan", imported: "Historique importé", close: "Fermer", omittedTools: "{count} sorties d’outil n’ont pas été synchronisées", user: "Vous", switchedDevice: "Suite sur {device}", switchedAgent: "Suite avec {agent}", archived: "Archivée", interactions: "Répondez à cette demande sur l’ordinateur qui exécute cette conversation." },
  es: { outline: "Esquema de la conversación", showMore: "Mostrar más", showLess: "Mostrar menos", partial: "Parte del historial importado está incompleta. Los mensajes disponibles se han conservado.", latest: "Mensajes recientes", previous: "Anterior", next: "Siguiente", assistant: "Asistente", fullMessage: "Leer mensaje completo", loading: "Cargando conversación…", pending: "Esta conversación se está sincronizando.", unavailable: "El contenido no está disponible. Inténtalo de nuevo al conectarte.", retry: "Reintentar", earlier: "Mensajes anteriores", empty: "Aún no hay mensajes", readOnly: "Conversación de solo lectura",
    appReadOnly: "Conversación de App de solo lectura. Los mensajes y archivos guardados siguen disponibles aquí.", running: "Respondiendo", unknown: "El ordenador no ha confirmado si la respuesta sigue en curso.", sealing: "Guardando la respuesta disponible…", settling: "Cargando la respuesta guardada…",
    interrupted: "Esta respuesta se interrumpió. Se ha conservado el contenido disponible.", complete: "Respuesta guardada", attachment: "Abrir adjunto", download: "Descargar", failedFile: "No se pudo cargar el archivo.", copy: "Copiar", copied: "Copiado", process: "Actividad",
    subagent: "Subagente", unavailableDetail: "Los detalles no están disponibles.", plan: "Plan", imported: "Historial importado", close: "Cerrar", omittedTools: "{count} salidas de herramienta no se sincronizaron", user: "Tú", switchedDevice: "Continuado en {device}", switchedAgent: "Continuado con {agent}", archived: "Archivada", interactions: "Responde a esta solicitud en el ordenador que ejecuta esta conversación." },
};
export function chatCopy(locale: string): ChatCopy { return copies[locale.toLowerCase().split("-")[0]!] ?? en; }

const interactionLabels: Record<string, string> = { en: "Handled on {name}", zh: "已在 {name} 处理", ja: "{name} で処理済み", fr: "Traité sur {name}", es: "Gestionado en {name}" };
export function interactionCopy(locale: string) { return { handledOn: interactionLabels[locale.toLowerCase().split("-")[0]!] ?? interactionLabels.en! }; }
