/**
 * [INPUT]: Depends on the host-selected language.
 * [OUTPUT]: Provides Chat navigation, title/archive/position decisions and durable-receipt feedback in five languages.
 * [POS]: Shared navigation copy; no transport diagnostics or local execution capabilities appear here.
 */
const en = { openNavigation: "Open navigation", closeNavigation: "Close navigation", completed: "New reply", executionFailed: "Reply failed", running: "Replying", waiting: "Waiting for input", unknown: "Waiting for recovery", savingReply: "Saving reply", pending: "Saved on this computer. Waiting to sync.", localOffline: "Offline. Changes are saved on this computer and will sync when connected.", draft: "Unsaved changes", leave: "Leave this page?", leaveDetail: "Unsaved input stays only on this page. Leaving does not cancel a change already sent.", stay: "Keep editing", leaveNow: "Leave page", chats: "Chats", active: "Active", archived: "Archived", empty: "No conversations here", title: "Conversation title", rename: "Rename", archive: "Archive", restore: "Restore",
  save: "Save", cancel: "Cancel", saving: "Saving…", saved: "Saved", failed: "This change is not confirmed. Your input is preserved. Retry to check the original attempt.",
  retry: "Try again", conflict: "This conversation changed on another device. Your change is preserved below.", current: "Current value", mine: "My change", useMine: "Use my change", keepCurrent: "Keep current value", position: "Sidebar position", positionMoved: "Moved by hand", positionCreated: "Creation order",
  deleted: "This conversation was deleted. Your input is preserved here.", offline: "Connection lost. Reconnect to save your change.", first: "First page", more: "Next page", refresh: "Refresh list", changed: "The list changed. Refresh to continue." };
export type ChatNavigationCopy = { [K in keyof typeof en]: string };
const copy: Record<string, ChatNavigationCopy> = {
  en,
  zh: { openNavigation: "打开导航", closeNavigation: "关闭导航", completed: "新回复", executionFailed: "回复失败", running: "正在回复", waiting: "等待处理", unknown: "等待恢复", savingReply: "正在保存回复", pending: "已保存在这台电脑，等待同步。", localOffline: "当前离线。修改保存在这台电脑，联网后同步。", draft: "\u6709\u672a\u4fdd\u5b58\u4fee\u6539", leave: "\u79bb\u5f00\u6b64\u9875\u9762\uff1f", leaveDetail: "\u672a\u4fdd\u5b58\u7684\u8f93\u5165\u4ec5\u4fdd\u7559\u5728\u5f53\u524d\u9875\u9762\u3002\u79bb\u5f00\u4e0d\u4f1a\u64a4\u56de\u5df2\u53d1\u51fa\u7684\u4fee\u6539\u3002", stay: "\u7ee7\u7eed\u7f16\u8f91", leaveNow: "\u79bb\u5f00\u9875\u9762", chats: "对话", active: "未归档", archived: "已归档", empty: "这里还没有对话", title: "对话名称", rename: "重命名", archive: "归档", restore: "取消归档",
    save: "保存", cancel: "取消", saving: "正在保存…", saved: "已保存", failed: "此修改尚未确认，输入已保留。重试会核对原操作。", retry: "重试",
    conflict: "这段对话已在其他设备修改，你的修改保留在下方。", current: "当前值", mine: "我的修改", useMine: "使用我的修改", keepCurrent: "保留当前值", position: "侧栏位置", positionMoved: "手动排序", positionCreated: "按创建顺序",
    deleted: "这段对话已删除，你的输入仍保留在此。", offline: "连接已断开，请联网后保存修改。", first: "第一页", more: "下一页", refresh: "刷新列表", changed: "列表已更新，请刷新后继续。" },
  ja: { openNavigation: "ナビゲーションを開く", closeNavigation: "ナビゲーションを閉じる", completed: "新しい返信", executionFailed: "返信に失敗", running: "返信中", waiting: "入力待ち", unknown: "復旧待ち", savingReply: "返信を保存中", pending: "このパソコンに保存済み。同期待ちです。", localOffline: "オフラインです。変更はこのパソコンに保存され、接続後に同期されます。", draft: "\u672a\u4fdd\u5b58\u306e\u5909\u66f4", leave: "\u3053\u306e\u30da\u30fc\u30b8\u3092\u96e2\u308c\u307e\u3059\u304b\uff1f", leaveDetail: "\u672a\u4fdd\u5b58\u306e\u5165\u529b\u306f\u3053\u306e\u30da\u30fc\u30b8\u306b\u3060\u3051\u4fdd\u6301\u3055\u308c\u307e\u3059\u3002\u96e2\u308c\u3066\u3082\u9001\u4fe1\u6e08\u307f\u306e\u5909\u66f4\u306f\u53d6\u308a\u6d88\u3055\u308c\u307e\u305b\u3093\u3002", stay: "\u7de8\u96c6\u3092\u7d9a\u3051\u308b", leaveNow: "\u30da\u30fc\u30b8\u3092\u96e2\u308c\u308b", chats: "会話", active: "アクティブ", archived: "アーカイブ済み", empty: "会話はありません", title: "会話の名前", rename: "名前を変更", archive: "アーカイブ", restore: "アーカイブ解除",
    save: "保存", cancel: "キャンセル", saving: "保存中…", saved: "保存しました", failed: "変更はまだ確認できません。入力は保持されています。再試行で元の操作を確認します。", retry: "再試行",
    conflict: "この会話は別の端末で変更されました。あなたの変更は下に保持されています。", current: "現在の値", mine: "自分の変更", useMine: "自分の変更を使用", keepCurrent: "現在の値を保持", position: "サイドバーの位置", positionMoved: "手動で並べ替え", positionCreated: "作成順",
    deleted: "この会話は削除されました。入力はここに保持されています。", offline: "接続が切れました。再接続して変更を保存してください。", first: "最初のページ", more: "次のページ", refresh: "一覧を更新", changed: "一覧が変更されました。更新して続行してください。" },
  fr: { openNavigation: "Ouvrir la navigation", closeNavigation: "Fermer la navigation", completed: "Nouvelle réponse", executionFailed: "Échec de la réponse", running: "Réponse en cours", waiting: "En attente de saisie", unknown: "En attente de récupération", savingReply: "Enregistrement de la réponse", pending: "Enregistré sur cet ordinateur. En attente de synchronisation.", localOffline: "Hors ligne. Les modifications sont enregistrées sur cet ordinateur et seront synchronisées à la reconnexion.", draft: "Modifications non enregistr\u00e9es", leave: "Quitter cette page ?", leaveDetail: "La saisie non enregistr\u00e9e reste uniquement sur cette page. Quitter n\u2019annule pas une modification d\u00e9j\u00e0 envoy\u00e9e.", stay: "Continuer \u00e0 modifier", leaveNow: "Quitter la page", chats: "Conversations", active: "Actives", archived: "Archivées", empty: "Aucune conversation ici", title: "Titre de la conversation", rename: "Renommer", archive: "Archiver", restore: "Désarchiver",
    save: "Enregistrer", cancel: "Annuler", saving: "Enregistrement…", saved: "Enregistré", failed: "Cette modification n’est pas confirmée. Votre saisie est conservée. Réessayez pour vérifier l’opération initiale.", retry: "Réessayer",
    conflict: "Cette conversation a été modifiée sur un autre appareil. Votre modification est conservée ci-dessous.", current: "Valeur actuelle", mine: "Ma modification", useMine: "Utiliser ma modification", keepCurrent: "Conserver la valeur actuelle", position: "Position dans la barre latérale", positionMoved: "Déplacée à la main", positionCreated: "Ordre de création",
    deleted: "Cette conversation a été supprimée. Votre saisie reste disponible ici.", offline: "Connexion perdue. Reconnectez-vous pour enregistrer.", first: "Première page", more: "Page suivante", refresh: "Actualiser la liste", changed: "La liste a changé. Actualisez pour continuer." },
  es: { openNavigation: "Abrir navegación", closeNavigation: "Cerrar navegación", completed: "Nueva respuesta", executionFailed: "La respuesta falló", running: "Respondiendo", waiting: "Esperando respuesta", unknown: "Esperando recuperación", savingReply: "Guardando respuesta", pending: "Guardado en este ordenador. Pendiente de sincronización.", localOffline: "Sin conexión. Los cambios se guardan en este ordenador y se sincronizarán al volver a conectar.", draft: "Cambios sin guardar", leave: "\u00bfSalir de esta p\u00e1gina?", leaveDetail: "La entrada sin guardar solo permanece en esta p\u00e1gina. Salir no cancela un cambio ya enviado.", stay: "Seguir editando", leaveNow: "Salir de la p\u00e1gina", chats: "Conversaciones", active: "Activas", archived: "Archivadas", empty: "No hay conversaciones aquí", title: "Título de la conversación", rename: "Renombrar", archive: "Archivar", restore: "Desarchivar",
    save: "Guardar", cancel: "Cancelar", saving: "Guardando…", saved: "Guardado", failed: "Este cambio no está confirmado. Tu entrada se conserva. Reintenta para comprobar la operación original.", retry: "Reintentar",
    conflict: "Esta conversación cambió en otro dispositivo. Tu cambio se conserva abajo.", current: "Valor actual", mine: "Mi cambio", useMine: "Usar mi cambio", keepCurrent: "Conservar valor actual", position: "Posición en la barra lateral", positionMoved: "Movida a mano", positionCreated: "Orden de creación",
    deleted: "Esta conversación se eliminó. Tu entrada se conserva aquí.", offline: "Conexión perdida. Vuelve a conectarte para guardar.", first: "Primera página", more: "Página siguiente", refresh: "Actualizar lista", changed: "La lista cambió. Actualiza para continuar." },
};
export function chatNavigationCopy(locale: string): ChatNavigationCopy { return copy[locale.toLowerCase().split("-")[0]!] ?? en; }
