/**
 * [INPUT]: No runtime dependencies; en workspace presentation vocabulary.
 * [OUTPUT]: Provides workspaceCopy for shared Chat actions, Project settings and Archive.
 * [POS]: Language leaf imported directly by desktop and selected by Web.
 */
export const workspaceCopy = {
  "chat": {
    "renameChatTitle": "Rename chat",
    "renameChatDescription": "Enter a new name for this chat.",
    "archiveConfetti": "Archive confetti",
    "archiveConfettiDescription": "Show confetti after archiving chats or projects with the mouse or keyboard. Turn off to restore the sidebar quick action’s archive icon.",
    "archiveConfettiReducedMotion": "Confetti is paused by your system’s reduced motion setting.",
    "archiveConfettiTooltip": "Archive Chat",
    "more": "More actions",
    "archiveChat": "Archive Chat",
    "archived": "Archived chat",
    "view": "View",
    "undo": "Undo"
  },
  "chatCommon": {
    "renameChatTitle": "Rename chat",
    "renameChatDescription": "Enter a new name for this chat."
  },
  "chatSettings": {
    "archiveConfetti": "Archive confetti",
    "archiveConfettiDescription": "Show confetti after archiving chats or projects with the mouse or keyboard. Turn off to restore the sidebar quick action’s archive icon.",
    "archiveConfettiReducedMotion": "Confetti is paused by your system’s reduced motion setting.",
    "archiveConfettiTooltip": "Archive Chat"
  },
  "project": {
    "more": "{{name}} more actions",
    "rename": "Rename",
    "renameTitle": "Rename Project",
    "renameDescription": "Only the in-app display name changes; the folder on disk is untouched.",
    "sortLabel": "Sort Projects",
    "recent": "Last updated",
    "manual": "Manual order",
    "settings": "Project settings",
    "settingsTitle": "{{name}} settings",
    "general": "General",
    "basics": "Basics",
    "identity": "Name and appearance",
    "appearanceLabel": "Change Project appearance",
    "appearance": {
      "trigger": "{{name}} appearance",
      "colorGroup": "Project color",
      "iconGroup": "Project icon",
      "done": "Done",
      "color": {
        "default": "Default",
        "red": "Red",
        "orange": "Orange",
        "amber": "Amber",
        "green": "Green",
        "blue": "Blue",
        "violet": "Violet",
        "pink": "Pink"
      },
      "icon": {
        "folder": "Folder",
        "money": "Money",
        "book": "Book",
        "study": "Study",
        "pencil": "Pencil",
        "pen": "Pen",
        "code": "Code",
        "terminal": "Terminal",
        "music": "Music",
        "movie": "Film",
        "craft": "Craft",
        "art": "Art",
        "health": "Health",
        "spark": "Spark",
        "flower": "Flower",
        "work": "Work",
        "chart": "Chart",
        "gem": "Gem",
        "fitness": "Fitness",
        "notes": "Notes",
        "legal": "Legal",
        "globe": "Globe",
        "travel": "Travel",
        "world": "World",
        "tools": "Tools",
        "pet": "Pet",
        "science": "Science",
        "brain": "Thinking",
        "heart": "Favorite",
        "plant": "Plant"
      }
    },
    "archive": "Archive",
    "archiveTitle": "Archive Project?",
    "archiveHint": "Archive this Project and its members.",
    "danger": "Danger zone",
    "baseTitle": "Base",
    "baseSummary": "Project Base",
    "baseEmpty": "This Project does not have a Base yet",
    "baseCreate": "Create Base",
    "baseOpen": "Open",
    "conflict": "This Project changed on another device. Your change is preserved below.",
    "deleted": "This Project has been deleted.",
    "archived": "Archived Project"
  },
  "archive": {
    "sectionTitle": "Chats and Projects",
    "chatCount": "{{count}} chats",
    "projectKind": "Project · {{count}} chats",
    "chatKind": "Chat",
    "purgeIrreversible": "Local chat records will be permanently deleted. This cannot be undone.",
    "purgeFolders": "The following working folders, including every file in them, are removed with them:",
    "basesDeletedLabel": "Bases deleted with them",
    "retainedLabel": "Bases retained (external or App-bound)",
    "memoryRetainedTitle": "Extracted Memory is kept",
    "memoryRetainedDetail": "Other Chats allowed by the current sharing scope may still recall it; a later rebuild or uninstall cleans only that provider instance.",
    "rebuildTitle": "Also rebuild Memory",
    "rebuildDetail": "Re-extracts all surviving authorized content, not only these Chats. About {{chats}} Chats / {{turns}} turns, and it incurs charges.",
    "rebuildScopeLabel": "Scope",
    "rebuildScope": "All surviving authorized content, not only these Chats",
    "rebuildSizeLabel": "Size",
    "rebuildSize": "{{chats}} Chats · {{turns}} turns",
    "rebuildTargetLabel": "Target",
    "rebuildImpactLabel": "Impact",
    "rebuildImpact": "Incurs charges and takes a while; Memory is unavailable during the rebuild",
    "rebuildNote": "Your enabled / paused setting is preserved.",
    "rebuildUnavailable": "The current Memory target cannot rebuild.",
    "description": "Archived Chats, Projects and imported history stay here and return to their original location when restored. Deletion permanently removes product-owned local records and working folders; imported history remains read-only, and extracted Memory is handled separately in the confirmation.",
    "selected": "{{count}} selected",
    "clearSelection": "Clear selection",
    "restoreSelected": "Restore selected",
    "deleteSelected": "Delete local Chats and files",
    "emptyTitle": "Archive is empty",
    "emptyDetail": "Chats, Projects or imported history archived from the Sidebar will appear here.",
    "deselectAll": "Deselect all",
    "selectAll": "Select all",
    "confirmTitleChats": "Permanently delete {{count}} Chats?",
    "confirmTitleProjects": "Permanently delete {{count}} Projects?",
    "confirmTitleMixed": "Permanently delete {{chats}} Chats and {{projects}} Projects?",
    "confirmRebuild": "Delete and rebuild",
    "confirmLocal": "Delete permanently",
    "selectEntity": "Select {{title}}",
    "restoreEntity": "Restore {{title}}",
    "deleteEntity": "Delete {{title}}",
    "importedDeleteUnavailable": "Imported history is read-only and cannot be permanently deleted in Bottega.",
    "toast": {
      "archivedChat": "Archived chat",
      "archivedProject": "Archived project",
      "view": "View",
      "undo": "Undo",
      "undoFailed": "Could not undo archive: {{message}}"
    }
  },
  "browserArchive": {
    "sectionTitle": "Chats and Projects",
    "description": "Archived Chats, Projects and imported history stay here. Open an item to view its contents.",
    "emptyTitle": "Archive is empty",
    "emptyDetail": "Chats, Projects or imported history archived from the Sidebar will appear here.",
    "pageEmpty": "No archived items on these pages."
  }
};
