/**
 * [INPUT]: No runtime dependencies; es workspace presentation vocabulary.
 * [OUTPUT]: Provides workspaceCopy for shared Chat actions, Project settings and Archive.
 * [POS]: Language leaf imported directly by desktop and selected by Web.
 */
export const workspaceCopy = {
  "chat": {
    "renameChatTitle": "Cambiar el nombre del chat",
    "renameChatDescription": "Introduce un nombre nuevo para este chat.",
    "archiveConfetti": "Confeti al archivar",
    "archiveConfettiDescription": "Muestra confeti al archivar chats o proyectos con el ratón o el teclado. Desactívalo para restaurar el icono de archivo de la acción rápida de la barra lateral.",
    "archiveConfettiReducedMotion": "El confeti está en pausa por el ajuste de movimiento reducido del sistema.",
    "archiveConfettiTooltip": "Mueve este chat a los elementos archivados. Puedes deshacer esta acción.",
    "more": "Más acciones",
    "archiveChat": "Archivar chat",
    "archived": "Chat archivado",
    "view": "Ver",
    "undo": "Deshacer"
  },
  "chatCommon": {
    "renameChatTitle": "Cambiar el nombre del chat",
    "renameChatDescription": "Introduce un nombre nuevo para este chat."
  },
  "chatSettings": {
    "archiveConfetti": "Confeti al archivar",
    "archiveConfettiDescription": "Muestra confeti al archivar chats o proyectos con el ratón o el teclado. Desactívalo para restaurar el icono de archivo de la acción rápida de la barra lateral.",
    "archiveConfettiReducedMotion": "El confeti está en pausa por el ajuste de movimiento reducido del sistema.",
    "archiveConfettiTooltip": "Mueve este chat a los elementos archivados. Puedes deshacer esta acción."
  },
  "project": {
    "more": "Más acciones de {{name}}",
    "rename": "Cambiar nombre",
    "renameTitle": "Cambiar el nombre del Project",
    "renameDescription": "Solo cambia el nombre mostrado en la aplicación; la carpeta del disco no se toca.",
    "sortLabel": "Ordenar Projects",
    "recent": "Última actualización",
    "manual": "Orden manual",
    "settings": "Ajustes del Project",
    "settingsTitle": "Ajustes de {{name}}",
    "general": "General",
    "basics": "Información básica",
    "identity": "Nombre y apariencia",
    "appearanceLabel": "Cambiar apariencia del Project",
    "appearance": {
      "trigger": "Apariencia de {{name}}",
      "colorGroup": "Color del Project",
      "iconGroup": "Icono del Project",
      "done": "Listo",
      "color": {
        "default": "Predeterminado",
        "red": "Rojo",
        "orange": "Naranja",
        "amber": "Ámbar",
        "green": "Verde",
        "blue": "Azul",
        "violet": "Violeta",
        "pink": "Rosa"
      },
      "icon": {
        "folder": "Carpeta",
        "money": "Finanzas",
        "book": "Libro",
        "study": "Estudio",
        "pencil": "Lápiz",
        "pen": "Pluma",
        "code": "Código",
        "terminal": "Terminal",
        "music": "Música",
        "movie": "Cine",
        "craft": "Manualidades",
        "art": "Arte",
        "health": "Salud",
        "spark": "Idea",
        "flower": "Flor",
        "work": "Trabajo",
        "chart": "Gráfico",
        "gem": "Gema",
        "fitness": "Fitness",
        "notes": "Notas",
        "legal": "Legal",
        "globe": "Globo terráqueo",
        "travel": "Viaje",
        "world": "Mundo",
        "tools": "Herramientas",
        "pet": "Mascota",
        "science": "Ciencia",
        "brain": "Pensamiento",
        "heart": "Favorito",
        "plant": "Planta"
      }
    },
    "archive": "Archivar",
    "archiveTitle": "¿Archivar el Project?",
    "archiveHint": "Archiva este Project y sus miembros.",
    "danger": "Zona de peligro",
    "baseTitle": "Base",
    "baseSummary": "Project Base",
    "baseEmpty": "Este Project aún no tiene Base",
    "baseCreate": "Crear Base",
    "baseOpen": "Abrir",
    "conflict": "Este proyecto cambió en otro dispositivo. Tu cambio se conserva abajo.",
    "deleted": "Este proyecto se ha eliminado.",
    "archived": "Proyecto archivado"
  },
  "archive": {
    "sectionTitle": "Chats y Projects",
    "chatCount": "{{count}} Chats",
    "projectKind": "Project · {{count}} Chats",
    "chatKind": "Chat",
    "purgeIrreversible": "Los chats locales se eliminarán permanentemente. Esta acción no se puede deshacer.",
    "purgeFolders": "Las siguientes carpetas de trabajo, con todos sus archivos, se eliminan también:",
    "basesDeletedLabel": "Bases que se eliminarán",
    "retainedLabel": "Bases conservadas (externas o vinculadas a una App)",
    "memoryRetainedTitle": "La Memory extraída se conserva",
    "memoryRetainedDetail": "Otros Chats permitidos por el ámbito compartido actual todavía pueden recuperarla; una reconstrucción o desinstalación posterior solo limpia esa instancia del proveedor.",
    "rebuildTitle": "Reconstruir también Memory",
    "rebuildDetail": "Vuelve a extraer todo el contenido autorizado que aún exista, no solo estos Chats. Unos {{chats}} Chats / {{turns}} turnos, con cargos asociados.",
    "rebuildScopeLabel": "Alcance",
    "rebuildScope": "Todo el contenido autorizado que aún exista, no solo estos Chats",
    "rebuildSizeLabel": "Tamaño",
    "rebuildSize": "{{chats}} Chats · {{turns}} turnos",
    "rebuildTargetLabel": "Destino",
    "rebuildImpactLabel": "Impacto",
    "rebuildImpact": "Genera cargos y tarda; Memory no está disponible durante la reconstrucción",
    "rebuildNote": "Se conserva el ajuste activado / en pausa.",
    "rebuildUnavailable": "El destino actual de Memory no permite reconstruir.",
    "description": "Los Chats, Projects y historiales importados archivados permanecen aquí y vuelven a su lugar al restaurarlos. Solo se pueden eliminar los datos locales propiedad del producto; el historial importado permanece en modo de solo lectura.",
    "selected": "{{count}} seleccionados",
    "clearSelection": "Borrar selección",
    "restoreSelected": "Restaurar selección",
    "deleteSelected": "Eliminar Chats y archivos locales",
    "emptyTitle": "El archivo está vacío",
    "emptyDetail": "Los Chats, Projects e historiales importados archivados desde la Sidebar aparecerán aquí.",
    "deselectAll": "Deseleccionar todo",
    "selectAll": "Seleccionar todo",
    "confirmTitleChats": "¿Eliminar permanentemente {{count}} Chats?",
    "confirmTitleProjects": "¿Eliminar permanentemente {{count}} Projects?",
    "confirmTitleMixed": "¿Eliminar permanentemente {{chats}} Chats y {{projects}} Projects?",
    "confirmRebuild": "Eliminar y reconstruir",
    "confirmLocal": "Eliminar permanentemente",
    "selectEntity": "Seleccionar {{title}}",
    "restoreEntity": "Restaurar {{title}}",
    "deleteEntity": "Eliminar {{title}}",
    "importedDeleteUnavailable": "El historial importado es de solo lectura y no se puede eliminar permanentemente en Bottega.",
    "toast": {
      "archivedChat": "Chat archivado",
      "archivedProject": "Project archivado",
      "view": "Ver",
      "undo": "Deshacer",
      "undoFailed": "No se pudo deshacer el archivado: {{message}}"
    }
  },
  "browserArchive": {
    "sectionTitle": "Chats y Projects",
    "description": "Los Chats, Projects e historiales importados archivados permanecen aquí. Abre un elemento para consultar su contenido.",
    "emptyTitle": "El archivo está vacío",
    "emptyDetail": "Los Chats, Projects e historiales importados archivados desde la Sidebar aparecerán aquí.",
    "pageEmpty": "No hay elementos archivados en estas páginas."
  }
};
