/**
 * [INPUT]: No runtime dependencies; fr workspace presentation vocabulary.
 * [OUTPUT]: Provides workspaceCopy for shared Chat actions, Project settings and Archive.
 * [POS]: Language leaf imported directly by desktop and selected by Web.
 */
export const workspaceCopy = {
  "chat": {
    "renameChatTitle": "Renommer le chat",
    "renameChatDescription": "Saisissez un nouveau nom pour ce chat.",
    "archiveConfetti": "Confettis à l’archivage",
    "archiveConfettiDescription": "Affiche des confettis après l’archivage de chats ou de projets avec la souris ou le clavier. Désactivez cette option pour rétablir l’icône d’archivage du raccourci latéral.",
    "archiveConfettiReducedMotion": "Les confettis sont suspendus par le réglage de réduction des animations du système.",
    "archiveConfettiTooltip": "Déplace ce chat vers les éléments archivés. Vous pouvez annuler cette action.",
    "more": "Plus d’actions",
    "archiveChat": "Archiver le chat",
    "archived": "Chat archivé",
    "view": "Afficher",
    "undo": "Annuler"
  },
  "chatCommon": {
    "renameChatTitle": "Renommer le chat",
    "renameChatDescription": "Saisissez un nouveau nom pour ce chat."
  },
  "chatSettings": {
    "archiveConfetti": "Confettis à l’archivage",
    "archiveConfettiDescription": "Affiche des confettis après l’archivage de chats ou de projets avec la souris ou le clavier. Désactivez cette option pour rétablir l’icône d’archivage du raccourci latéral.",
    "archiveConfettiReducedMotion": "Les confettis sont suspendus par le réglage de réduction des animations du système.",
    "archiveConfettiTooltip": "Déplace ce chat vers les éléments archivés. Vous pouvez annuler cette action."
  },
  "project": {
    "more": "Autres actions pour {{name}}",
    "rename": "Renommer",
    "renameTitle": "Renommer le Project",
    "renameDescription": "Seul le nom affiché dans l’application change ; le dossier sur le disque reste intact.",
    "sortLabel": "Trier les Projects",
    "recent": "Dernière mise à jour",
    "manual": "Ordre manuel",
    "settings": "Paramètres du Project",
    "settingsTitle": "Paramètres de {{name}}",
    "general": "Général",
    "basics": "Informations",
    "identity": "Nom et apparence",
    "appearanceLabel": "Modifier l’apparence du Project",
    "appearance": {
      "trigger": "Apparence de {{name}}",
      "colorGroup": "Couleur du Project",
      "iconGroup": "Icône du Project",
      "done": "Terminé",
      "color": {
        "default": "Par défaut",
        "red": "Rouge",
        "orange": "Orange",
        "amber": "Ambre",
        "green": "Vert",
        "blue": "Bleu",
        "violet": "Violet",
        "pink": "Rose"
      },
      "icon": {
        "folder": "Dossier",
        "money": "Finances",
        "book": "Livre",
        "study": "Études",
        "pencil": "Crayon",
        "pen": "Stylo",
        "code": "Code",
        "terminal": "Terminal",
        "music": "Musique",
        "movie": "Cinéma",
        "craft": "Loisirs créatifs",
        "art": "Art",
        "health": "Santé",
        "spark": "Idée",
        "flower": "Fleur",
        "work": "Travail",
        "chart": "Graphique",
        "gem": "Gemme",
        "fitness": "Fitness",
        "notes": "Notes",
        "legal": "Juridique",
        "globe": "Globe",
        "travel": "Voyage",
        "world": "Monde",
        "tools": "Outils",
        "pet": "Animal",
        "science": "Science",
        "brain": "Réflexion",
        "heart": "Favori",
        "plant": "Plante"
      }
    },
    "archive": "Archiver",
    "archiveTitle": "Archiver le Project ?",
    "archiveHint": "Archiver ce Project et ses membres.",
    "danger": "Zone dangereuse",
    "baseTitle": "Base",
    "baseSummary": "Project Base",
    "baseEmpty": "Ce Project n’a pas encore de Base",
    "baseCreate": "Créer une Base",
    "baseOpen": "Ouvrir",
    "conflict": "Ce projet a été modifié sur un autre appareil. Votre modification est conservée ci-dessous.",
    "deleted": "Ce projet a été supprimé.",
    "archived": "Projet archivé"
  },
  "archive": {
    "sectionTitle": "Chats et Projects",
    "chatCount": "{{count}} Chats",
    "projectKind": "Project · {{count}} Chats",
    "chatKind": "Chat",
    "purgeIrreversible": "Les conversations locales seront supprimées définitivement. Cette action est irréversible.",
    "purgeFolders": "Les dossiers de travail suivants, avec tous leurs fichiers, sont supprimés également :",
    "basesDeletedLabel": "Bases supprimées avec eux",
    "retainedLabel": "Bases conservées (externes ou liées à une App)",
    "memoryRetainedTitle": "La Memory extraite est conservée",
    "memoryRetainedDetail": "D’autres Chats autorisés par la portée de partage actuelle peuvent encore la rappeler ; une reconstruction ou désinstallation ultérieure ne nettoie que cette instance du fournisseur.",
    "rebuildTitle": "Reconstruire aussi Memory",
    "rebuildDetail": "Réextrait tout le contenu autorisé encore présent, pas seulement ces Chats. Environ {{chats}} Chats / {{turns}} tours, avec des frais à la clé.",
    "rebuildScopeLabel": "Portée",
    "rebuildScope": "Tout le contenu autorisé encore présent, pas seulement ces Chats",
    "rebuildSizeLabel": "Volume",
    "rebuildSize": "{{chats}} Chats · {{turns}} tours",
    "rebuildTargetLabel": "Cible",
    "rebuildImpactLabel": "Impact",
    "rebuildImpact": "Entraîne des frais et prend du temps ; Memory est indisponible pendant la reconstruction",
    "rebuildNote": "Le réglage activé / en pause est conservé.",
    "rebuildUnavailable": "La cible Memory actuelle ne permet pas la reconstruction.",
    "description": "Les Chats, Projects et historiques importés archivés restent ici et retrouvent leur emplacement après restauration. Seules les données locales appartenant au produit peuvent être supprimées ; l’historique importé reste en lecture seule.",
    "selected": "{{count}} sélectionnés",
    "clearSelection": "Effacer la sélection",
    "restoreSelected": "Restaurer la sélection",
    "deleteSelected": "Supprimer les Chats et fichiers locaux",
    "emptyTitle": "Archive vide",
    "emptyDetail": "Les Chats, Projects et historiques importés archivés depuis la Sidebar apparaîtront ici.",
    "deselectAll": "Tout désélectionner",
    "selectAll": "Tout sélectionner",
    "confirmTitleChats": "Supprimer définitivement {{count}} Chats ?",
    "confirmTitleProjects": "Supprimer définitivement {{count}} Projects ?",
    "confirmTitleMixed": "Supprimer définitivement {{chats}} Chats et {{projects}} Projects ?",
    "confirmRebuild": "Supprimer et reconstruire",
    "confirmLocal": "Supprimer définitivement",
    "selectEntity": "Sélectionner {{title}}",
    "restoreEntity": "Restaurer {{title}}",
    "deleteEntity": "Supprimer {{title}}",
    "importedDeleteUnavailable": "L’historique importé est en lecture seule et ne peut pas être supprimé définitivement dans Bottega.",
    "toast": {
      "archivedChat": "Chat archivé",
      "archivedProject": "Project archivé",
      "view": "Afficher",
      "undo": "Annuler",
      "undoFailed": "Impossible d’annuler l’archivage : {{message}}"
    }
  },
  "browserArchive": {
    "sectionTitle": "Chats et Projects",
    "description": "Les Chats, Projects et historiques importés archivés restent ici. Ouvrez un élément pour consulter son contenu.",
    "emptyTitle": "Archive vide",
    "emptyDetail": "Les Chats, Projects et historiques importés archivés depuis la Sidebar apparaîtront ici.",
    "pageEmpty": "Aucun élément archivé sur ces pages."
  }
};
