/**
 * [INPUT]: No runtime dependencies; ja workspace presentation vocabulary.
 * [OUTPUT]: Provides workspaceCopy for shared Chat actions, Project settings and Archive.
 * [POS]: Language leaf imported directly by desktop and selected by Web.
 */
export const workspaceCopy = {
  "chat": {
    "renameChatTitle": "チャットの名前を変更",
    "renameChatDescription": "このチャットの新しい名前を入力してください。",
    "archiveConfetti": "アーカイブ時の紙吹雪",
    "archiveConfettiDescription": "マウスやキーボードでチャットやプロジェクトをアーカイブすると紙吹雪を表示します。オフにすると、サイドバーのクイック操作がアーカイブアイコンに戻ります。",
    "archiveConfettiReducedMotion": "システムの視差効果を減らす設定に従い、紙吹雪を停止しています。",
    "archiveConfettiTooltip": "このチャットをアーカイブ済みの項目に移動します。元に戻せます。",
    "more": "その他の操作",
    "archiveChat": "チャットをアーカイブ",
    "archived": "Chat をアーカイブしました",
    "view": "表示",
    "undo": "元に戻す"
  },
  "chatCommon": {
    "renameChatTitle": "チャットの名前を変更",
    "renameChatDescription": "このチャットの新しい名前を入力してください。"
  },
  "chatSettings": {
    "archiveConfetti": "アーカイブ時の紙吹雪",
    "archiveConfettiDescription": "マウスやキーボードでチャットやプロジェクトをアーカイブすると紙吹雪を表示します。オフにすると、サイドバーのクイック操作がアーカイブアイコンに戻ります。",
    "archiveConfettiReducedMotion": "システムの視差効果を減らす設定に従い、紙吹雪を停止しています。",
    "archiveConfettiTooltip": "このチャットをアーカイブ済みの項目に移動します。元に戻せます。"
  },
  "project": {
    "more": "{{name}} のその他の操作",
    "rename": "名前を変更",
    "renameTitle": "Project の名前を変更",
    "renameDescription": "アプリ内の表示名だけを変更します。ディスク上のフォルダーは変更されません。",
    "sortLabel": "Project の並び替え",
    "recent": "最終更新順",
    "manual": "手動の並び順",
    "settings": "Project 設定",
    "settingsTitle": "{{name}} の設定",
    "general": "一般",
    "basics": "基本情報",
    "identity": "名前と外観",
    "appearanceLabel": "Project の外観を変更",
    "appearance": {
      "trigger": "{{name}} の外観",
      "colorGroup": "Project の色",
      "iconGroup": "Project のアイコン",
      "done": "完了",
      "color": {
        "default": "既定",
        "red": "赤",
        "orange": "オレンジ",
        "amber": "黄",
        "green": "緑",
        "blue": "青",
        "violet": "紫",
        "pink": "ピンク"
      },
      "icon": {
        "folder": "フォルダー",
        "money": "資金",
        "book": "本",
        "study": "学習",
        "pencil": "鉛筆",
        "pen": "万年筆",
        "code": "コード",
        "terminal": "ターミナル",
        "music": "音楽",
        "movie": "映像",
        "craft": "手作り",
        "art": "アート",
        "health": "健康",
        "spark": "ひらめき",
        "flower": "花",
        "work": "仕事",
        "chart": "グラフ",
        "gem": "宝石",
        "fitness": "フィットネス",
        "notes": "ノート",
        "legal": "法務",
        "globe": "地球儀",
        "travel": "旅行",
        "world": "世界",
        "tools": "ツール",
        "pet": "ペット",
        "science": "科学",
        "brain": "思考",
        "heart": "お気に入り",
        "plant": "植物"
      }
    },
    "archive": "アーカイブ",
    "archiveTitle": "Project をアーカイブしますか？",
    "archiveHint": "この Project とメンバーをアーカイブします。",
    "danger": "危険な操作",
    "baseTitle": "Base",
    "baseSummary": "Project Base",
    "baseEmpty": "この Project にはまだ Base がありません",
    "baseCreate": "Base を作成",
    "baseOpen": "開く",
    "conflict": "このプロジェクトは別の端末で変更されました。あなたの変更は下に保持されています。",
    "deleted": "このプロジェクトは削除されました。",
    "archived": "プロジェクトをアーカイブしました"
  },
  "archive": {
    "sectionTitle": "Chat と Project",
    "chatCount": "{{count}} Chats",
    "projectKind": "Project・{{count}} Chats",
    "chatKind": "Chat",
    "purgeIrreversible": "ローカルのチャット記録を完全に削除します。取り消せません。",
    "purgeFolders": "次の作業フォルダー（内部の全ファイルを含む）も併せて削除します：",
    "basesDeletedLabel": "一緒に削除される Base",
    "retainedLabel": "保持される Base（外部・App 紐付け）",
    "memoryRetainedTitle": "抽出済み Memory は保持されます",
    "memoryRetainedDetail": "現在の共有範囲で許可された他の Chat から想起される場合があります。後の再構築やアンインストールは対象 provider instance だけを消去します。",
    "rebuildTitle": "同時に Memory を再構築",
    "rebuildDetail": "対象 Chat だけでなく、残存する承認済み内容をすべて再抽出します。約 {{chats}} Chats / {{turns}} ターン、料金が発生します。",
    "rebuildScopeLabel": "範囲",
    "rebuildScope": "対象 Chat だけでなく、残存する承認済み内容すべて",
    "rebuildSizeLabel": "規模",
    "rebuildSize": "{{chats}} Chats・{{turns}} ターン",
    "rebuildTargetLabel": "送信先",
    "rebuildImpactLabel": "影響",
    "rebuildImpact": "料金と時間が発生し、再構築中は Memory を利用できません",
    "rebuildNote": "完了後も有効・一時停止の設定は変わりません。",
    "rebuildUnavailable": "現在の Memory 送信先では再構築できません。",
    "description": "アーカイブした Chat、Project、インポート履歴がここに残り、復元すると元の場所へ戻ります。削除できるのは製品が所有するローカルデータだけで、インポート履歴は常に読み取り専用です。",
    "selected": "{{count}} 件を選択",
    "clearSelection": "選択を解除",
    "restoreSelected": "選択項目を復元",
    "deleteSelected": "ローカルの Chat とファイルを削除",
    "emptyTitle": "アーカイブは空です",
    "emptyDetail": "Sidebar でアーカイブした Chat、Project、インポート履歴がここに表示されます。",
    "deselectAll": "すべて解除",
    "selectAll": "すべて選択",
    "confirmTitleChats": "{{count}} 件の Chat を完全に削除しますか？",
    "confirmTitleProjects": "{{count}} 件の Project を完全に削除しますか？",
    "confirmTitleMixed": "{{chats}} 件の Chat と {{projects}} 件の Project を完全に削除しますか？",
    "confirmRebuild": "削除して再構築",
    "confirmLocal": "完全に削除",
    "selectEntity": "{{title}} を選択",
    "restoreEntity": "{{title}} を復元",
    "deleteEntity": "{{title}} を削除",
    "importedDeleteUnavailable": "インポート履歴は読み取り専用のため、Bottega で完全に削除できません。",
    "toast": {
      "archivedChat": "Chat をアーカイブしました",
      "archivedProject": "Project をアーカイブしました",
      "view": "表示",
      "undo": "元に戻す",
      "undoFailed": "アーカイブを元に戻せませんでした：{{message}}"
    }
  },
  "browserArchive": {
    "sectionTitle": "Chat と Project",
    "description": "アーカイブした Chat、Project、インポート履歴がここに残ります。項目を開くと内容を確認できます。",
    "emptyTitle": "アーカイブは空です",
    "emptyDetail": "Sidebar でアーカイブした Chat、Project、インポート履歴がここに表示されます。",
    "pageEmpty": "現在のページにアーカイブ項目はありません。"
  }
};
