/**
 * [INPUT]: No runtime dependencies; zh-CN workspace presentation vocabulary.
 * [OUTPUT]: Provides workspaceCopy for shared Chat actions, Project settings and Archive.
 * [POS]: Language leaf imported directly by desktop and selected by Web.
 */
export const workspaceCopy = {
  "chat": {
    "renameChatTitle": "重命名聊天",
    "renameChatDescription": "输入聊天的新名称。",
    "archiveConfetti": "归档撒花",
    "archiveConfettiDescription": "归档会话或项目后显示撒花动效，支持鼠标和键盘操作。关闭后，侧栏快捷按钮恢复归档图标。",
    "archiveConfettiReducedMotion": "已按系统“减少动态效果”设置暂停撒花。",
    "archiveConfettiTooltip": "会话会移入已归档，可撤销。",
    "more": "更多操作",
    "archiveChat": "归档聊天",
    "archived": "已归档聊天",
    "view": "查看",
    "undo": "撤销"
  },
  "chatCommon": {
    "renameChatTitle": "重命名聊天",
    "renameChatDescription": "输入聊天的新名称。"
  },
  "chatSettings": {
    "archiveConfetti": "归档撒花",
    "archiveConfettiDescription": "归档会话或项目后显示撒花动效，支持鼠标和键盘操作。关闭后，侧栏快捷按钮恢复归档图标。",
    "archiveConfettiReducedMotion": "已按系统“减少动态效果”设置暂停撒花。",
    "archiveConfettiTooltip": "会话会移入已归档，可撤销。"
  },
  "project": {
    "more": "{{name}} 更多操作",
    "rename": "重命名",
    "renameTitle": "重命名 Project",
    "renameDescription": "只修改应用内显示名称，不改动磁盘文件夹。",
    "sortLabel": "Project 排序",
    "recent": "最近更新",
    "manual": "手动排序",
    "settings": "Project 设置",
    "settingsTitle": "{{name}} 设置",
    "general": "通用",
    "basics": "基本信息",
    "identity": "名称与外观",
    "appearanceLabel": "更改 Project 外观",
    "appearance": {
      "trigger": "{{name}} 外观",
      "colorGroup": "Project 颜色",
      "iconGroup": "Project 图标",
      "done": "完成",
      "color": {
        "default": "默认",
        "red": "红",
        "orange": "橙",
        "amber": "黄",
        "green": "绿",
        "blue": "蓝",
        "violet": "紫",
        "pink": "粉"
      },
      "icon": {
        "folder": "文件夹",
        "money": "资金",
        "book": "书",
        "study": "学习",
        "pencil": "铅笔",
        "pen": "钢笔",
        "code": "代码",
        "terminal": "终端",
        "music": "音乐",
        "movie": "影视",
        "craft": "手作",
        "art": "美术",
        "health": "健康",
        "spark": "灵感",
        "flower": "花",
        "work": "工作",
        "chart": "图表",
        "gem": "宝石",
        "fitness": "健身",
        "notes": "笔记",
        "legal": "法务",
        "globe": "地球仪",
        "travel": "旅行",
        "world": "世界",
        "tools": "工具",
        "pet": "宠物",
        "science": "科学",
        "brain": "思考",
        "heart": "喜爱",
        "plant": "植物"
      }
    },
    "archive": "归档",
    "archiveTitle": "归档 Project？",
    "archiveHint": "归档此 Project 及其成员。",
    "danger": "危险区",
    "baseTitle": "Base",
    "baseSummary": "Project Base",
    "baseEmpty": "此 Project 还没有 Base",
    "baseCreate": "创建 Base",
    "baseOpen": "打开",
    "conflict": "此 Project 已在其他设备修改，你的修改保留在下方。",
    "deleted": "此 Project 已被删除。",
    "archived": "已归档 Project"
  },
  "archive": {
    "sectionTitle": "Chat 与 Project",
    "chatCount": "{{count}} 个聊天",
    "projectKind": "Project · {{count}} 个聊天",
    "chatKind": "Chat",
    "purgeIrreversible": "本机聊天记录会被永久删除，无法撤销。",
    "purgeFolders": "下列工作文件夹（含其中全部文件）一并移除：",
    "basesDeletedLabel": "随之删除的 Base",
    "retainedLabel": "保留的 Base（外部 / App 绑定）",
    "memoryRetainedTitle": "已提取的 Memory 会保留",
    "memoryRetainedDetail": "其它 Chat 仍可能在当前共享范围内召回它；今后重建或卸载时只清对应 provider instance。",
    "rebuildTitle": "同时重建 Memory",
    "rebuildDetail": "重新提取全部存续且获授权的内容，而不止当前 Chat。约 {{chats}} 个 Chat / {{turns}} 个 turn，会产生费用。",
    "rebuildScopeLabel": "范围",
    "rebuildScope": "全部存续且获授权的内容，不止当前 Chat",
    "rebuildSizeLabel": "规模",
    "rebuildSize": "{{chats}} 个 Chat · {{turns}} 个 turn",
    "rebuildTargetLabel": "目标",
    "rebuildImpactLabel": "影响",
    "rebuildImpact": "会产生费用并耗时较长；重建期间长期记忆不可用",
    "rebuildNote": "完成后不改变「开启 / 暂停」设置。",
    "rebuildUnavailable": "当前 Memory 目标不可重建。",
    "description": "归档的 Chat、Project 与导入历史保留在这里，恢复后回到原位。删除会永久移除产品拥有的本机记录和工作文件夹；导入历史始终只读，已提取记忆按确认页单独处理。",
    "selected": "已选 {{count}} 项",
    "clearSelection": "取消选择",
    "restoreSelected": "恢复所选",
    "deleteSelected": "删除本机 Chat 与文件",
    "emptyTitle": "归档为空",
    "emptyDetail": "从 Sidebar 归档的 Chat、Project 或导入历史会出现在这里。",
    "deselectAll": "取消全选",
    "selectAll": "全选",
    "confirmTitleChats": "永久删除 {{count}} 个 Chat？",
    "confirmTitleProjects": "永久删除 {{count}} 个 Project？",
    "confirmTitleMixed": "永久删除 {{chats}} 个 Chat 与 {{projects}} 个 Project？",
    "confirmRebuild": "删除并重建",
    "confirmLocal": "永久删除",
    "selectEntity": "选择 {{title}}",
    "restoreEntity": "恢复 {{title}}",
    "deleteEntity": "删除 {{title}}",
    "importedDeleteUnavailable": "导入历史是只读内容，无法在 Bottega 内永久删除。",
    "toast": {
      "archivedChat": "已归档聊天",
      "archivedProject": "已归档 Project",
      "view": "查看",
      "undo": "撤销",
      "undoFailed": "无法撤销归档：{{message}}"
    }
  },
  "browserArchive": {
    "sectionTitle": "Chat 与 Project",
    "description": "归档的 Chat、Project 与导入历史保留在这里。打开一项即可查看内容。",
    "emptyTitle": "归档为空",
    "emptyDetail": "从 Sidebar 归档的 Chat、Project 或导入历史会出现在这里。",
    "pageEmpty": "当前页没有归档项目。"
  }
};
