/**
 * [INPUT]: Depends on nothing.
 * [OUTPUT]: Provides the App and Artifact channel names. Routes App impact and enablement commands through main.
 * [POS]: Zod-free IPC channel names (OPT-34): preload imports these so no schema module enters its bundle; the owning contract modules re-export them unchanged.
 */
export const APPS_CHANNEL = {
  disableImpact: "apps:disable-impact",
  setEnabled: "apps:set-enabled",
  add: "apps:add",
  remove: "apps:remove",
  list: "apps:list",
  open: "apps:open",
  originWithoutStart: "apps:origin-without-start",
  stop: "apps:stop",
  grant: "apps:grant",
  setGrantState: "apps:grant:state",
  setDefaultGrant: "apps:grant:default",
  listGrantSources: "apps:grant:sources",
  listGrantCandidates: "apps:grant:candidates",
  listAvailable: "apps:available",
  acquireSurface: "apps:surface:acquire",
  releaseSurface: "apps:surface:release",
  event: "apps:event",
  reveal: "apps:reveal",
  cancelInstall: "apps:cancel-install",
  readLog: "apps:read-log",
  retry: "apps:retry",
  repair: "apps:repair",
  setAgent: "apps:set-agent",
  saveAsApp: "apps:save-as-app",
  rename: "apps:rename",
  ensureChatSlot: "apps:ensure-chat-slot",
  listUseHistory: "apps:use-history:list",
  openUseChat: "apps:use-chat:open",
  newUseChat: "apps:use-chat:new",
  openEditor: "apps:editor:open",
  openEditorChat: "apps:editor-chat:open",
  hideEditor: "apps:editor:hide",
  retrySkill: "apps:retry-skill",
  authorizeStudioAccess: "apps:studio-access:authorize",
  declineStudioAccess: "apps:studio-access:decline",
  revokeStudioAccess: "apps:studio-access:revoke",
  extensionStatus: "apps:extension-status",
  revokeExtensionGrant: "apps:extension-grant:revoke",
  rebuildExtensionGeneration: "apps:extension-generation:rebuild",
  capabilities: "apps:capabilities",
  checkAgentTools: "apps:check-agent-tools",
  guiInfo: "apps:gui-info",
  guiReady: "apps:gui-ready",
  releaseGuiSurface: "apps:gui-surface:release",
  fileExportBegin: "apps:file-export:begin",
  fileExportWrite: "apps:file-export:write",
  fileExportFinalize: "apps:file-export:finalize",
  fileExportCancel: "apps:file-export:cancel",
  setPinned: "apps:set-pinned",
  importDesignCanvas: "apps:design:import",
  listDesignImportCandidates: "apps:design:import-candidates",
  listDesignFiles: "apps:design:files",
  listDesignVersions: "apps:design:versions",
  restoreDesignVersion: "apps:design:restore",
  setDesignAutoOpen: "apps:design:auto-open:set",
  designDataStatus: "apps:design:data:status",
  deleteDesignData: "apps:design:data:delete",
  setDesignEnabled: "apps:design:enabled:set",
  readReadme: "apps:read-readme",
  probeRepo: "apps:probe-repo",
  compatibilityRequests: "apps:compatibility-requests",
  compatibilityChanged: "apps:compatibility-changed",
  resumeCompatibility: "apps:resume-compatibility",
  applyCompatibility: "apps:compatibility:apply",
  forgetCompatibility: "apps:forget-compatibility",
  discardProbe: "apps:discard-probe",
  listPresets: "apps:list-presets",
  probePreset: "apps:probe-preset",
  discardPresetProbe: "apps:discard-preset-probe",
  installPreset: "apps:install-preset",
  ghStatus: "apps:gh-status",
  readConfig: "apps:read-config",
  writeConfig: "apps:write-config",
  sharePreview: "apps:share-preview",
  sharePublish: "apps:share-publish",
  shareDiscard: "apps:share-discard",
} as const;

export const ARTIFACT_IPC = { preview: "artifact:preview", lease: "artifact:lease", release: "artifact:release", action: "artifact:action", workbook: "artifact:workbook", importBase: "artifact:import-base" } as const;
