/**
 * [INPUT]: Depends on the resolved application locale.
 * [OUTPUT]: Provides five-language recovery actions with a precise data-loss boundary, the userData socket-budget headline and its count-aware body (socketBudgetMessage), the settings-reset notice and the deferred-recovery failure line (settingsResetNotice, deferredRecoveryFailedNotice; a held profile has none, its turns wait at the dispatch gate).
 * [POS]: Startup recovery copy, available before any renderer or account session exists.
 */
const en = { socketTitle: "Bottega can't start on this Mac account", socketMessage: "This account's home folder path is {over} bytes too long for the local connections Bottega's helper processes use (macOS allows at most 103 bytes). This can't be changed from Bottega. Please report it so we can support accounts like this one.", socketMessageOne: "This account's home folder path is {over} byte too long for the local connections Bottega's helper processes use (macOS allows at most 103 bytes). This can't be changed from Bottega. Please report it so we can support accounts like this one.", title: "Bottega could not open your data", message: "Your files have been kept. Copy the technical details or report the problem to get help.",
  open: "Open data folder", copy: "Copy technical details", report: "Report on GitHub", rebuild: "Rebuild from Bottega folder", close: "Close Bottega", cancel: "Cancel",
  confirm: "Rebuild the local database?", disclosure: "The previous database will be preserved. Conversations will be restored from your Bottega folder; unfinished replies may be missing. Search indexes and cloud synchronization state will be recreated. Your keys and settings will remain on this computer." };
type Copy = typeof en;
const locales: Record<string, Copy> = {
  en,
  "zh-CN": { socketTitle: "Bottega 无法在这个 Mac 账户上启动", socketMessage: "这个账户的个人文件夹路径太长，比 Bottega 辅助进程使用的本地连接所允许的长度多出 {over} 字节（macOS 最多允许 103 字节）。这无法在 Bottega 里更改。请反馈这个问题，以便我们支持这类账户。", socketMessageOne: "这个账户的个人文件夹路径太长，比 Bottega 辅助进程使用的本地连接所允许的长度多出 {over} 字节（macOS 最多允许 103 字节）。这无法在 Bottega 里更改。请反馈这个问题，以便我们支持这类账户。", title: "Bottega 暂时无法打开数据", message: "文件已保留。你可以复制技术详情或反馈问题获取帮助。", open: "打开数据目录", copy: "复制技术详情", report: "在 GitHub 反馈", rebuild: "从 Bottega 文件夹重建", close: "关闭 Bottega", cancel: "取消", confirm: "重建本机数据库？", disclosure: "旧数据库会保留。对话将从 Bottega 文件夹恢复，尚未完成的回复可能缺失。搜索索引与云端同步状态将重新建立，密钥和设置仍保留在本机。" },
  ja: { socketTitle: "この Mac アカウントでは Bottega を起動できません", socketMessage: "このアカウントのホームフォルダーのパスが、Bottega の補助プロセスが使うローカル接続の上限より {over} バイト長すぎます（macOS で使えるのは最大 103 バイトです）。これは Bottega からは変更できません。このようなアカウントに対応できるよう、報告してください。", socketMessageOne: "このアカウントのホームフォルダーのパスが、Bottega の補助プロセスが使うローカル接続の上限より {over} バイト長すぎます（macOS で使えるのは最大 103 バイトです）。これは Bottega からは変更できません。このようなアカウントに対応できるよう、報告してください。", title: "Bottega がデータを開けませんでした", message: "ファイルは保持されています。技術情報をコピーするか、問題を報告してください。", open: "データフォルダーを開く", copy: "技術情報をコピー", report: "GitHub で報告", rebuild: "Bottega フォルダーから再構築", close: "Bottega を閉じる", cancel: "キャンセル", confirm: "ローカルデータベースを再構築しますか？", disclosure: "以前のデータベースは保持されます。会話は Bottega フォルダーから復元されますが、未完了の返信が欠ける場合があります。検索索引とクラウド同期状態を再作成します。鍵と設定はこのコンピューターに残ります。" },
  fr: { socketTitle: "Bottega ne peut pas démarrer sur ce compte Mac", socketMessage: "Le chemin du dossier de départ de ce compte dépasse de {over} octets la limite des connexions locales utilisées par les processus auxiliaires de Bottega (macOS autorise au plus 103 octets). Cela ne peut pas être modifié depuis Bottega. Signalez-le pour que nous puissions prendre en charge ce type de compte.", socketMessageOne: "Le chemin du dossier de départ de ce compte dépasse de {over} octet la limite des connexions locales utilisées par les processus auxiliaires de Bottega (macOS autorise au plus 103 octets). Cela ne peut pas être modifié depuis Bottega. Signalez-le pour que nous puissions prendre en charge ce type de compte.", title: "Bottega n’a pas pu ouvrir vos données", message: "Vos fichiers sont conservés. Copiez les détails techniques ou signalez le problème pour obtenir de l’aide.", open: "Ouvrir le dossier de données", copy: "Copier les détails techniques", report: "Signaler sur GitHub", rebuild: "Reconstruire depuis le dossier Bottega", close: "Fermer Bottega", cancel: "Annuler", confirm: "Reconstruire la base locale ?", disclosure: "La base précédente sera conservée. Les conversations seront restaurées depuis le dossier Bottega ; des réponses inachevées peuvent manquer. Les index de recherche et l’état de synchronisation seront recréés. Les clés et réglages restent sur cet ordinateur." },
  es: { socketTitle: "Bottega no puede iniciarse en esta cuenta de Mac", socketMessage: "La ruta de la carpeta de inicio de esta cuenta supera en {over} bytes el límite de las conexiones locales que usan los procesos auxiliares de Bottega (macOS permite como máximo 103 bytes). Esto no se puede cambiar desde Bottega. Infórmalo para que podamos admitir cuentas como esta.", socketMessageOne: "La ruta de la carpeta de inicio de esta cuenta supera en {over} byte el límite de las conexiones locales que usan los procesos auxiliares de Bottega (macOS permite como máximo 103 bytes). Esto no se puede cambiar desde Bottega. Infórmalo para que podamos admitir cuentas como esta.", title: "Bottega no pudo abrir tus datos", message: "Tus archivos se han conservado. Copia los detalles técnicos o informa del problema para pedir ayuda.", open: "Abrir carpeta de datos", copy: "Copiar detalles técnicos", report: "Informar en GitHub", rebuild: "Reconstruir desde la carpeta Bottega", close: "Cerrar Bottega", cancel: "Cancelar", confirm: "¿Reconstruir la base de datos local?", disclosure: "Se conservará la base anterior. Las conversaciones se restaurarán desde la carpeta Bottega; pueden faltar respuestas sin terminar. Se recrearán los índices de búsqueda y el estado de sincronización. Las claves y los ajustes seguirán en este equipo." },
};
export const recoveryCopy = (locale: string) => locales[locale] ?? locales[locale.split("-")[0]!] ?? en;
/** The socket-budget body with its count: English, French and Spanish have a singular for one byte. */
export const socketBudgetMessage = (locale: string, over: number) =>
  (over === 1 ? recoveryCopy(locale).socketMessageOne : recoveryCopy(locale).socketMessage).replace("{over}", String(over));

const notices = {
  en: { deferredFailed: "Bottega couldn’t finish one of its startup checks. If something doesn’t work as expected, restarting Bottega usually fixes it.", settings: "Some settings could not be read and were reset. The original settings file has been preserved." },
  "zh-CN": { deferredFailed: "Bottega 有一项启动检查没能完成。如果有功能不正常，重新打开 Bottega 通常就能恢复。", settings: "部分设置无法读取，已恢复默认值。原设置文件已保留。" },
  ja: { deferredFailed: "Bottega の起動時チェックの一部を完了できませんでした。うまく動かない機能があれば、Bottega を再起動するとたいてい直ります。", settings: "一部の設定を読み込めず、初期値に戻しました。元の設定ファイルは保持されています。" },
  fr: { deferredFailed: "Bottega n’a pas pu terminer l’une de ses vérifications de démarrage. Si quelque chose ne fonctionne pas comme prévu, redémarrer Bottega règle généralement le problème.", settings: "Certains réglages étaient illisibles et ont été réinitialisés. Le fichier original est conservé." },
  es: { deferredFailed: "Bottega no pudo terminar una de sus comprobaciones de inicio. Si algo no funciona como esperas, reiniciar Bottega suele solucionarlo.", settings: "Algunos ajustes no se pudieron leer y se restablecieron. Se conservó el archivo original." },
};
const noticesFor = (locale: string) => notices[locale as keyof typeof notices] ?? notices[locale.split("-")[0] as keyof typeof notices] ?? notices.en;
export const settingsResetNotice = (locale: string) => noticesFor(locale).settings;
/** A deferred startup-recovery task failed: one plain line for the person; its name and cause go to the log only. */
export const deferredRecoveryFailedNotice = (locale: string) => noticesFor(locale).deferredFailed;

/* The folder branch is a different conversation from a database failure: nothing is
   broken, a folder is simply not where it was, so every action names what it does to
   the user's own files rather than to Bottega's internals. */
