/**
 * [INPUT]: Depends on zod; Receive the Base Line Differential Audit Entries generated by the main commit point
 * [OUTPUT]: Provides BaseHistoryLedger/Entry types, the strict schema, and the entry/byte/query/row/cell budgets
 * [POS]: Shared Base semantic kernel; shared/bases contracts with a history of duration; Only record a lost summary, no commitments to rollback or time travel
 */

import { z } from "zod";

export const BASE_HISTORY_ENTRY_LIMIT = 1_000;
export const BASE_HISTORY_LEDGER_BYTE_LIMIT = 2 * 1024 * 1024;
export const BASE_ROW_HISTORY_QUERY_LIMIT = 50;
export const BASE_HISTORY_ENTRY_ROW_LIMIT = 500;
export const BASE_HISTORY_ENTRY_CELL_COLUMN_LIMIT = 64;

const baseHistoryActorSchema = z.enum([
  "renderer",
  "agent",
  "system",
  "app-gui",
]);

export const baseHistoryEntrySchema = z
  .object({
    at: z.number().int().nonnegative(),
    actor: baseHistoryActorSchema,
    operation: z.string().min(1).max(64),
    rowIds: z.array(z.string().min(1).max(128)).max(BASE_HISTORY_ENTRY_ROW_LIMIT),
    cells: z
      .array(
        z
          .object({
            rowId: z.string().min(1).max(128),
            columnIds: z.array(z.string().min(1).max(128)).max(BASE_HISTORY_ENTRY_CELL_COLUMN_LIMIT),
          })
          .strict()
      )
      .max(BASE_HISTORY_ENTRY_ROW_LIMIT)
      .optional(),
  })
  .strict();

export const baseHistoryLedgerSchema = z
  .object({
    schemaVersion: z.literal(1),
    entries: z.array(baseHistoryEntrySchema).max(BASE_HISTORY_ENTRY_LIMIT),
  })
  .strict();

export type BaseHistoryActor = z.infer<typeof baseHistoryActorSchema>;
export type BaseHistoryEntry = z.infer<typeof baseHistoryEntrySchema>;
export type BaseHistoryLedger = z.infer<typeof baseHistoryLedgerSchema>;
