/**
 * [INPUT]: Product locale.
 * [OUTPUT]: Five-language consent, privacy and plugin health text, including installed supply verification labels.
 * [POS]: Main-process preview copy; user-facing surfaces share the same disclosure.
 */
const rows = {
 en: ["Preview & tunnels", "Open a managed application on another device.", "Download the preview component?", "Bottega will download a verified Cloudflare component. Remote preview traffic passes through trycloudflare.com and is not end-to-end encrypted. Availability is not guaranteed.", "Download", "Cancel", "This platform is not supported yet.", "Download permission needed", "Verified", "Not downloaded", "Active previews", "Server grants", "Pinned version", "Integrity and signature", "Connectors", "Last edge check", "Platform", "Installed version", "Verified SHA-256", "Developer ID"],
 "zh-CN": ["预览与隧道", "在其他设备打开托管应用。", "下载预览组件？", "Bottega 将下载经过校验的 Cloudflare 组件。远程预览经 trycloudflare.com 中转，不使用端到端加密，也不保证可用性。", "下载", "取消", "本平台暂不支持。", "等待下载许可", "已校验", "尚未下载", "进行中的预览", "Server 授权", "锁定版本", "摘要与签名", "连接器", "上次边缘检查", "平台", "已安装版本", "已校验 SHA-256", "开发者 ID"],
 ja: ["プレビューとトンネル", "管理されたアプリを別の端末で開きます。", "プレビュー用コンポーネントをダウンロードしますか？", "検証済みの Cloudflare コンポーネントをダウンロードします。プレビューの通信は trycloudflare.com を経由し、エンドツーエンド暗号化されません。可用性は保証されません。", "ダウンロード", "キャンセル", "このプラットフォームは未対応です。", "ダウンロードの許可が必要", "検証済み", "未ダウンロード", "実行中のプレビュー", "Server 許可", "固定バージョン", "整合性と署名", "コネクター", "エッジ最終確認", "プラットフォーム", "インストール済みバージョン", "検証済み SHA-256", "開発者 ID"],
 es: ["Vista previa y túneles", "Abre una aplicación administrada en otro dispositivo.", "¿Descargar el componente de vista previa?", "Bottega descargará un componente verificado de Cloudflare. El tráfico pasa por trycloudflare.com sin cifrado de extremo a extremo. La disponibilidad no está garantizada.", "Descargar", "Cancelar", "Esta plataforma aún no es compatible.", "Se necesita permiso de descarga", "Verificado", "Sin descargar", "Vistas previas activas", "Permisos de servidor", "Versión fijada", "Integridad y firma", "Conectores", "Última comprobación", "Plataforma", "Versión instalada", "SHA-256 verificado", "ID del desarrollador"],
 fr: ["Aperçus et tunnels", "Ouvrir une application gérée sur un autre appareil.", "Télécharger le composant d’aperçu ?", "Bottega téléchargera un composant Cloudflare vérifié. Le trafic passe par trycloudflare.com sans chiffrement de bout en bout. La disponibilité n’est pas garantie.", "Télécharger", "Annuler", "Cette plateforme n’est pas encore prise en charge.", "Autorisation de téléchargement requise", "Vérifié", "Non téléchargé", "Aperçus actifs", "Autorisations serveur", "Version fixée", "Intégrité et signature", "Connecteurs", "Dernière vérification", "Plateforme", "Version installée", "SHA-256 vérifié", "Identifiant développeur"],
} as const;
export const previewNativeCopy = (locale: string) => rows[locale as keyof typeof rows] ?? rows.en;
