/**
 * [INPUT]: Host locale.
 * [OUTPUT]: Five-language attachment status (processing, unsupported format, too large, reselect after reload, expired upload), limit, draft restoration and session confirmation copy.
 * [POS]: Remote composer feedback, separate from shared native control labels.
 */
import { resolveAppLocale } from "@ai-chat/ui/lib/locale";
const en = { loadingReferences: "Loading references…", noFiles: "No matching files", nextMessage: "For next message", currentTurn: "For current turn", referenceChanged: "The computer changed. Remove or reselect file references.", restoreDraft: "Restore draft", remove: "Remove {name}", retry: "Retry upload", uploading: "Uploading", failed: "Upload failed. Your file is retained.", expired: "Upload expired. Retry to upload it again.",
  limits: "Up to 8 files, 8 MiB each; photos up to 50 MB are resized before sending.", processing: "Preparing image…", unsupportedFormat: "This image format can’t be opened here. Save it as JPEG or PNG and add it again.", imageTooLarge: "This image is too large to send, even after resizing.", imageDimensions: "This image has too many pixels to prepare.", reselect: "This file wasn’t kept when the page reloaded. Choose it again.",
  scope: "For this chat on {computer}", preview: "Preview {name}", previewFile: "Preview file", download: "Download", guide: "Guide this turn", attach: "Files" };
const values: Record<string, typeof en> = {
  en,
  "zh-CN": { loadingReferences: "正在读取引用…", noFiles: "没有匹配的文件", nextMessage: "用于下一条消息", currentTurn: "用于当前轮插话", referenceChanged: "电脑已改变，请移除或重新选择文件引用。", restoreDraft: "恢复草稿", remove: "移除 {name}", retry: "重试上传", uploading: "上传中", failed: "上传失败，文件已保留。", expired: "上传已过期，点击重试重新上传。", limits: "每条最多 8 个文件，单个不超过 8 MiB；50 MB 以内的照片会在发送前自动缩小。", processing: "正在处理图片…", unsupportedFormat: "此图片格式无法在这里打开，请另存为 JPEG 或 PNG 后重新添加。", imageTooLarge: "图片缩小后仍超出发送上限。", imageDimensions: "图片像素过多，无法处理。", reselect: "页面重新加载后未保留此文件，请重新选择。", scope: "仅用于「{computer}」上的当前会话", preview: "预览 {name}", previewFile: "预览文件", download: "下载", guide: "引导当前轮", attach: "文件" },
  ja: { loadingReferences: "参照を読み込み中…", noFiles: "一致するファイルはありません", nextMessage: "次のメッセージ用", currentTurn: "現在のターン用", referenceChanged: "パソコンが変わりました。ファイル参照を削除するか選び直してください。", restoreDraft: "下書きを復元", remove: "{name} を削除", retry: "アップロードを再試行", uploading: "アップロード中", failed: "アップロードできませんでした。ファイルは保持されています。", expired: "アップロードの有効期限が切れました。再試行して再アップロードしてください。", limits: "最大 8 ファイル、各 8 MiB まで。50 MB までの写真は送信前に縮小されます。", processing: "画像を準備中…", unsupportedFormat: "この画像形式はここでは開けません。JPEG か PNG で保存して追加し直してください。", imageTooLarge: "縮小しても送信できるサイズを超えています。", imageDimensions: "画像のピクセル数が多すぎて処理できません。", reselect: "ページの再読み込みでこのファイルは保持されませんでした。もう一度選んでください。", scope: "{computer} のこのチャットのみ", preview: "{name} をプレビュー", previewFile: "ファイルをプレビュー", download: "ダウンロード", guide: "このターンを指示", attach: "ファイル" },
  fr: { loadingReferences: "Chargement des références…", noFiles: "Aucun fichier correspondant", nextMessage: "Pour le prochain message", currentTurn: "Pour le tour actuel", referenceChanged: "L’ordinateur a changé. Supprimez ou sélectionnez à nouveau les références.", restoreDraft: "Restaurer le brouillon", remove: "Retirer {name}", retry: "Réessayer l’envoi", uploading: "Envoi", failed: "Échec de l’envoi. Votre fichier est conservé.", expired: "L’envoi a expiré. Réessayez pour l’envoyer à nouveau.", limits: "8 fichiers maximum, 8 Mio chacun ; les photos jusqu’à 50 Mo sont réduites avant l’envoi.", processing: "Préparation de l’image…", unsupportedFormat: "Ce format d’image ne peut pas être ouvert ici. Enregistrez-la en JPEG ou PNG puis ajoutez-la à nouveau.", imageTooLarge: "Cette image reste trop lourde à envoyer, même réduite.", imageDimensions: "Cette image compte trop de pixels pour être préparée.", reselect: "Ce fichier n’a pas été conservé au rechargement de la page. Choisissez-le à nouveau.", scope: "Pour cette conversation sur {computer}", preview: "Aperçu de {name}", previewFile: "Aperçu du fichier", download: "Télécharger", guide: "Guider ce tour", attach: "Fichiers" },
  es: { loadingReferences: "Cargando referencias…", noFiles: "No hay archivos coincidentes", nextMessage: "Para el próximo mensaje", currentTurn: "Para el turno actual", referenceChanged: "El ordenador cambió. Quita o vuelve a seleccionar las referencias.", restoreDraft: "Restaurar borrador", remove: "Quitar {name}", retry: "Reintentar carga", uploading: "Subiendo", failed: "Error al subir. El archivo se conserva.", expired: "La carga caducó. Reintenta para volver a subirla.", limits: "Hasta 8 archivos, de 8 MiB cada uno; las fotos de hasta 50 MB se reducen antes de enviarse.", processing: "Preparando imagen…", unsupportedFormat: "Este formato de imagen no se puede abrir aquí. Guárdala como JPEG o PNG y vuelve a añadirla.", imageTooLarge: "La imagen sigue siendo demasiado grande para enviarla, incluso reducida.", imageDimensions: "La imagen tiene demasiados píxeles para prepararla.", reselect: "Este archivo no se conservó al recargar la página. Vuelve a elegirlo.", scope: "Para este chat en {computer}", preview: "Vista previa de {name}", previewFile: "Vista previa del archivo", download: "Descargar", guide: "Guiar este turno", attach: "Archivos" },
};
export const remoteInputCopy = (locale: string) => values[resolveAppLocale(locale)] ?? en;
