/**
 * [INPUT]: dependence when not in operation; The first is the installation of five local directories
 * [OUTPUT]: Provides five languages of syntax Archive/Purge product text
 * [POS]: Archive feature catalog of shared/i18n/locales
 */

export const archiveEn = {
  sectionTitle: "Chats and Projects", chatCount: "{{count}} chats", projectKind: "Project · {{count}} chats", chatKind: "Chat", purgeIrreversible: "This cannot be undone. Local chat records and the listed working folders, including every file in them, will be permanently deleted.", pinnedBasesLabel: "Pinned Bases deleted with them", retainedLabel: "Retained (external or App-bound)", deleteFoldersLabel: "Working folders to delete", none: "None", memoryMode: "Choose how to clean Memory:", localOnlyTitle: "Delete local Chats and files only", localOnlyDetail: "Extracted Memory is retained and may still be recalled by other Chats allowed by the current sharing scope. A later rebuild or uninstall cleans only that provider instance.", rebuildTitle: "Delete Chats and rebuild Memory", rebuildDetail: "Re-extract all surviving authorized content, not only these Chats. Estimated {{chats}} Chats / {{turns}} turns; destination {{hostname}} · {{model}}. This may take time or incur third-party charges; Memory is unavailable during rebuild and your enabled/paused setting is preserved.", rebuildUnavailable: "The current Memory target cannot rebuild; local data can still be deleted.", description: "Archived Chats and Projects stay here and return to their original location when restored. Deletion permanently removes local records and owned working folders; extracted memory is handled separately in the confirmation.", selected: "{{count}} selected", clearSelection: "Clear selection", restoreSelected: "Restore selected", deleteSelected: "Delete local Chats and files", emptyTitle: "Archive is empty", emptyDetail: "Chats or Projects archived from the Sidebar will appear here.", deselectAll: "Deselect all", selectAll: "Select all", confirmRebuildTitle: "Delete selected archive and rebuild Memory?", confirmTitle: "Delete selected archive?", confirmRebuild: "Delete and rebuild Memory", confirmLocal: "Delete local data only", selectEntity: "Select {{title}}", restoreEntity: "Restore {{title}}", deleteEntity: "Delete {{title}}",
};
type ArchiveCatalog = typeof archiveEn;
export const archiveZhCN: ArchiveCatalog = {
  sectionTitle: "Chat 与 Project", chatCount: "{{count}} 个聊天", projectKind: "Project · {{count}} 个聊天", chatKind: "Chat", purgeIrreversible: "此操作无法撤销。本机聊天记录与下列工作文件夹（含其中全部文件）会被永久删除。", pinnedBasesLabel: "一并删除的 pinned Base", retainedLabel: "保留（外部或 App 绑定）", deleteFoldersLabel: "将删除的工作文件夹", none: "无", memoryMode: "选择 Memory 清理方式：", localOnlyTitle: "仅删除本机 Chat 与文件", localOnlyDetail: "已提取 Memory 不会自动删除，仍可能被当前共享范围允许的其它 Chat 召回；以后重建或卸载只清对应 provider instance。", rebuildTitle: "删除 Chat 并重建 Memory", rebuildDetail: "将重新提取全部存续且获授权内容，而非仅当前 Chat。预计 {{chats}} 个 Chat / {{turns}} 个 turn；目标 {{hostname}} · {{model}}。可能产生费用并耗费较长时间；重建期间长期记忆不可用，完成不改变开启或暂停设置。", rebuildUnavailable: "当前 Memory 目标不可重建；你仍可仅删除本机数据。", description: "归档的 Chat 与 Project 保留在这里，恢复后回到原位。删除会永久移除本机记录及归属本应用的工作文件夹；已提取的记忆按确认页单独处理。", selected: "已选 {{count}} 项", clearSelection: "取消选择", restoreSelected: "恢复所选", deleteSelected: "删除本机 Chat 与文件", emptyTitle: "归档为空", emptyDetail: "在 Sidebar 里归档 Chat 或 Project 后，它们会出现在这里。", deselectAll: "取消全选", selectAll: "全选", confirmRebuildTitle: "删除所选归档并重建 Memory？", confirmTitle: "删除所选归档？", confirmRebuild: "删除并重建 Memory", confirmLocal: "仅删除本机数据", selectEntity: "选择 {{title}}", restoreEntity: "恢复 {{title}}", deleteEntity: "删除 {{title}}",
};
export const archiveJa: ArchiveCatalog = {
  sectionTitle: "Chat と Project", chatCount: "{{count}} Chats", projectKind: "Project・{{count}} Chats", chatKind: "Chat", purgeIrreversible: "この操作は取り消せません。ローカルのチャット記録と、一覧の作業フォルダー内にある全ファイルを完全に削除します。", pinnedBasesLabel: "一緒に削除される固定 Base", retainedLabel: "保持（外部または App 紐付け）", deleteFoldersLabel: "削除する作業フォルダー", none: "なし", memoryMode: "Memory の削除方法を選択：", localOnlyTitle: "ローカルの Chat とファイルだけを削除", localOnlyDetail: "抽出済み Memory は残り、現在の共有範囲で許可された他の Chat から引き続き想起される場合があります。後の再構築やアンインストールは対象 provider instance だけを消去します。", rebuildTitle: "Chat を削除して Memory を再構築", rebuildDetail: "対象 Chat だけでなく、残存する承認済み内容をすべて再抽出します。推定 {{chats}} Chats / {{turns}} ターン、送信先 {{hostname}}・{{model}}。時間や料金が発生する場合があり、再構築中は Memory を利用できませんが有効・一時停止設定は保たれます。", rebuildUnavailable: "現在の Memory 送信先では再構築できません。ローカルデータだけは削除できます。", description: "Sidebar からアーカイブした Chat と Project がここに残り、復元すると元の場所へ戻ります。削除はローカル記録と所有する作業フォルダーを完全に消去し、抽出済み Memory は確認画面の選択に従います。", selected: "{{count}} 件を選択", clearSelection: "選択を解除", restoreSelected: "選択項目を復元", deleteSelected: "ローカルの Chat とファイルを削除", emptyTitle: "アーカイブは空です", emptyDetail: "Sidebar でアーカイブした Chat と Project がここに表示されます。", deselectAll: "すべて解除", selectAll: "すべて選択", confirmRebuildTitle: "選択項目を削除して Memory を再構築しますか？", confirmTitle: "選択項目を削除しますか？", confirmRebuild: "削除して再構築", confirmLocal: "ローカルデータだけを削除", selectEntity: "{{title}} を選択", restoreEntity: "{{title}} を復元", deleteEntity: "{{title}} を削除",
};
export const archiveFr: ArchiveCatalog = {
  sectionTitle: "Chats et Projects", chatCount: "{{count}} Chats", projectKind: "Project · {{count}} Chats", chatKind: "Chat", purgeIrreversible: "Cette opération est irréversible. Les conversations locales et tous les fichiers des dossiers indiqués seront supprimés définitivement.", pinnedBasesLabel: "Bases épinglées supprimées avec eux", retainedLabel: "Conservés (externes ou liés à une App)", deleteFoldersLabel: "Dossiers de travail à supprimer", none: "Aucun", memoryMode: "Choisir le nettoyage de Memory :", localOnlyTitle: "Supprimer uniquement les Chats et fichiers locaux", localOnlyDetail: "La Memory extraite est conservée et peut encore être rappelée par les autres Chats autorisés par la portée de partage actuelle. Une reconstruction ou désinstallation ultérieure ne nettoie que cette instance du fournisseur.", rebuildTitle: "Supprimer les Chats et reconstruire Memory", rebuildDetail: "Réextraire tout le contenu autorisé encore présent, pas seulement ces Chats. Estimation : {{chats}} Chats / {{turns}} tours ; destination {{hostname}} · {{model}}. Cela peut prendre du temps ou entraîner des frais ; Memory est indisponible pendant la reconstruction et le réglage activé/en pause est conservé.", rebuildUnavailable: "La cible Memory actuelle ne permet pas la reconstruction ; les données locales peuvent tout de même être supprimées.", description: "Les Chats et Projects archivés restent ici et retrouvent leur emplacement après restauration. La suppression efface définitivement les données locales et les dossiers de travail appartenant à l’application ; la Memory extraite est traitée séparément dans la confirmation.", selected: "{{count}} sélectionnés", clearSelection: "Effacer la sélection", restoreSelected: "Restaurer la sélection", deleteSelected: "Supprimer les Chats et fichiers locaux", emptyTitle: "Archive vide", emptyDetail: "Les Chats et Projects archivés depuis la Sidebar apparaîtront ici.", deselectAll: "Tout désélectionner", selectAll: "Tout sélectionner", confirmRebuildTitle: "Supprimer la sélection et reconstruire Memory ?", confirmTitle: "Supprimer la sélection ?", confirmRebuild: "Supprimer et reconstruire", confirmLocal: "Supprimer les données locales", selectEntity: "Sélectionner {{title}}", restoreEntity: "Restaurer {{title}}", deleteEntity: "Supprimer {{title}}",
};
export const archiveEs: ArchiveCatalog = {
  sectionTitle: "Chats y Projects", chatCount: "{{count}} Chats", projectKind: "Project · {{count}} Chats", chatKind: "Chat", purgeIrreversible: "Esta acción no se puede deshacer. Se eliminarán permanentemente los chats locales y todos los archivos de las carpetas indicadas.", pinnedBasesLabel: "Bases fijadas que se eliminarán", retainedLabel: "Conservadas (externas o vinculadas a una App)", deleteFoldersLabel: "Carpetas de trabajo que se eliminarán", none: "Ninguna", memoryMode: "Elige cómo limpiar Memory:", localOnlyTitle: "Eliminar solo Chats y archivos locales", localOnlyDetail: "La Memory extraída se conserva y todavía puede recuperarse desde otros Chats permitidos por el ámbito compartido actual. Una reconstrucción o desinstalación posterior solo limpia esa instancia del proveedor.", rebuildTitle: "Eliminar Chats y reconstruir Memory", rebuildDetail: "Volver a extraer todo el contenido autorizado que aún exista, no solo estos Chats. Estimación: {{chats}} Chats / {{turns}} turnos; destino {{hostname}} · {{model}}. Puede tardar o generar cargos; Memory no está disponible durante la reconstrucción y se conserva el ajuste activado/en pausa.", rebuildUnavailable: "El destino actual de Memory no permite reconstruir; los datos locales aún se pueden eliminar.", description: "Los Chats y Projects archivados permanecen aquí y vuelven a su lugar al restaurarlos. Eliminar borra para siempre los registros locales y las carpetas de trabajo propiedad de la app; la Memory extraída se trata por separado en la confirmación.", selected: "{{count}} seleccionados", clearSelection: "Borrar selección", restoreSelected: "Restaurar selección", deleteSelected: "Eliminar Chats y archivos locales", emptyTitle: "El archivo está vacío", emptyDetail: "Los Chats y Projects archivados desde la Sidebar aparecerán aquí.", deselectAll: "Deseleccionar todo", selectAll: "Seleccionar todo", confirmRebuildTitle: "¿Eliminar la selección y reconstruir Memory?", confirmTitle: "¿Eliminar la selección?", confirmRebuild: "Eliminar y reconstruir", confirmLocal: "Eliminar solo datos locales", selectEntity: "Seleccionar {{title}}", restoreEntity: "Restaurar {{title}}", deleteEntity: "Eliminar {{title}}",
};
