/**
 * [INPUT]: Depends on the five supported UI locales and the account erasure product contract.
 * [OUTPUT]: Provides precise Google authorization, permanent deletion, local retention and phone-to-browser continuation copy.
 * [POS]: Shared account-deletion copy without platform or authentication dependencies.
 */
const copies = {
  "en": {
    "title": "Delete cloud account",
    "action": "Delete account",
    "description": "Delete this account’s synced conversations, Bases, Apps and files from the cloud. Every device and browser session will lose access.",
    "local": "Content created or taken over on a computer stays there with its local files. Cloud-only mirrors are removed when devices reconnect. This cannot be undone.",
    "deleted": "Account deletion confirmed",
    "reauthenticate": "Continue with Google",
    "reauthDetails": "Choose the same Google account again. Google may reuse its existing session; Bottega requires a new successful Google authorization for this deletion request.",
    "confirmTitle": "Permanently delete this cloud account?",
    "confirm": "Delete cloud account permanently",
    "cancel": "Cancel",
    "pending": "Google confirmation is required.",
    "accepted": "Account deletion confirmed. Cloud access is closed and cleanup will continue automatically. Your local content is kept.",
    "unavailable": "This deletion request is unavailable or expired. Start again to review the current account.",
    "wrongAccount": "This is a different account from the one selected on your computer. Switch to that account before continuing.",
    "back": "Back to account",
    "failed": "The request could not be completed. Check the original request before starting again.",
    "browser": "Review the account and confirm with Google in your browser.",
    "retry": "Check original request",
    "startAgain": "Start a new review",
    "loading": "Checking account…",
    "browserPending": "Finish in your browser: continue with the same Google account and confirm there. This page updates when you come back.",
    "continuation": "You started deleting this account in the Bottega app. Continue with the same Google account to confirm it here.",
    "continuationWrongAccount": "This Google account is not the account being deleted. Continue with Google and choose the account you started from.",
    "cancelled": "Google sign-in was cancelled. Continue with Google to try again.",
    "returnToApp": "Account deletion confirmed. You can return to the Bottega app."
  },
  "zh-cn": {
    "title": "删除云端账号",
    "action": "删除账号",
    "description": "从云端删除此账号已同步的对话、Base、App 和文件。所有设备和浏览器会话都将失去访问权限。",
    "local": "本机创建或已接管到此电脑的内容及其本地文件会保留。其他设备重新联网后将移除纯云端镜像。此操作无法撤销。",
    "deleted": "账号删除已确认",
    "reauthenticate": "使用 Google 继续",
    "reauthDetails": "请再次选择同一 Google 账号。Google 可能复用已有登录状态；Bottega 要求为本次删除完成一次新的 Google 授权。",
    "confirmTitle": "永久删除此云端账号？",
    "confirm": "永久删除云端账号",
    "cancel": "取消",
    "pending": "需要通过 Google 确认。",
    "accepted": "账号删除已确认。云端访问已关闭，清理将自动继续。本机内容已保留。",
    "unavailable": "此删除请求不可用或已过期。请重新查看当前账号。",
    "wrongAccount": "此账号与电脑上选择的账号不同。请切换到该账号后继续。",
    "back": "返回账号",
    "failed": "未能完成请求。请先查询原请求，再开始新的操作。",
    "browser": "请在浏览器中查看账号，并通过 Google 确认。",
    "retry": "查询原请求",
    "startAgain": "重新查看账号",
    "loading": "正在检查账号…",
    "browserPending": "请在浏览器中完成：使用同一 Google 账号继续并在那里确认。回到此页面后会自动更新。",
    "continuation": "你在 Bottega App 中发起了删除此账号。请使用同一 Google 账号继续，并在这里确认。",
    "continuationWrongAccount": "此 Google 账号不是要删除的账号。请使用 Google 继续，并选择发起删除的账号。",
    "cancelled": "Google 登录已取消。请使用 Google 继续以重试。",
    "returnToApp": "账号删除已确认。你可以返回 Bottega App。"
  },
  "ja": {
    "title": "クラウドアカウントを削除",
    "action": "アカウントを削除",
    "description": "このアカウントの同期済みの会話、Base、App、ファイルをクラウドから削除します。すべての端末とブラウザのセッションがアクセスできなくなります。",
    "local": "このコンピュータで作成または引き継いだ内容とローカルファイルは残ります。クラウドのみのミラーは端末の再接続時に削除されます。この操作は取り消せません。",
    "deleted": "アカウントの削除を確認済み",
    "reauthenticate": "Google で続行",
    "reauthDetails": "同じ Google アカウントを再度選択してください。Google は既存のセッションを使う場合がありますが、この削除には新しい Google 認証の成功が必要です。",
    "confirmTitle": "このクラウドアカウントを完全に削除しますか？",
    "confirm": "クラウドアカウントを完全に削除",
    "cancel": "キャンセル",
    "pending": "Google での確認が必要です。",
    "accepted": "アカウントの削除が確認されました。クラウドへのアクセスを停止し、削除処理を自動で続けます。ローカルの内容は残ります。",
    "unavailable": "この削除リクエストは利用できないか、期限切れです。現在のアカウントを再度確認してください。",
    "wrongAccount": "コンピュータで選択したアカウントとは異なります。そのアカウントに切り替えてから続行してください。",
    "back": "アカウントに戻る",
    "failed": "リクエストを完了できませんでした。新しく開始する前に元のリクエストを確認してください。",
    "browser": "ブラウザでアカウントを確認し、Google で認証してください。",
    "retry": "元のリクエストを確認",
    "startAgain": "新しく確認を開始",
    "loading": "アカウントを確認中…",
    "browserPending": "ブラウザで完了してください：同じ Google アカウントで続行し、そこで確認します。戻るとこのページは更新されます。",
    "continuation": "Bottega アプリでこのアカウントの削除を開始しました。同じ Google アカウントで続行し、ここで確認してください。",
    "continuationWrongAccount": "この Google アカウントは削除対象のアカウントではありません。Google で続行し、削除を開始したアカウントを選択してください。",
    "cancelled": "Google へのログインがキャンセルされました。Google で続行して再試行してください。",
    "returnToApp": "アカウントの削除を確認しました。Bottega アプリに戻れます。"
  },
  "fr": {
    "title": "Supprimer le compte cloud",
    "action": "Supprimer le compte",
    "description": "Supprimez du cloud les conversations, Bases, Apps et fichiers synchronisés de ce compte. Tous les appareils et sessions de navigateur perdront l’accès.",
    "local": "Le contenu créé ou repris sur cet ordinateur et ses fichiers locaux sont conservés. Les simples copies cloud sont supprimées à la reconnexion. Cette action est irréversible.",
    "deleted": "Suppression du compte confirmée",
    "reauthenticate": "Continuer avec Google",
    "reauthDetails": "Sélectionnez à nouveau le même compte Google. Google peut réutiliser sa session existante ; Bottega exige une nouvelle autorisation Google réussie pour cette demande.",
    "confirmTitle": "Supprimer définitivement ce compte cloud ?",
    "confirm": "Supprimer définitivement le compte cloud",
    "cancel": "Annuler",
    "pending": "Une confirmation avec Google est nécessaire.",
    "accepted": "Suppression du compte confirmée. L’accès cloud est fermé et le nettoyage continuera automatiquement. Votre contenu local est conservé.",
    "unavailable": "Cette demande est indisponible ou expirée. Vérifiez à nouveau le compte actuel.",
    "wrongAccount": "Ce compte diffère de celui sélectionné sur votre ordinateur. Connectez-vous à ce dernier pour continuer.",
    "back": "Retour au compte",
    "failed": "La demande n’a pas abouti. Vérifiez la demande initiale avant d’en créer une autre.",
    "browser": "Vérifiez le compte et confirmez avec Google dans votre navigateur.",
    "retry": "Vérifier la demande initiale",
    "startAgain": "Recommencer la vérification",
    "loading": "Vérification du compte…",
    "browserPending": "Terminez dans votre navigateur : continuez avec le même compte Google et confirmez-y. Cette page se met à jour à votre retour.",
    "continuation": "Vous avez commencé à supprimer ce compte dans l’app Bottega. Continuez avec le même compte Google pour confirmer ici.",
    "continuationWrongAccount": "Ce compte Google n’est pas celui que vous supprimez. Continuez avec Google et choisissez le compte de départ.",
    "cancelled": "La connexion Google a été annulée. Continuez avec Google pour réessayer.",
    "returnToApp": "Suppression du compte confirmée. Vous pouvez revenir à l’app Bottega."
  },
  "es": {
    "title": "Eliminar cuenta en la nube",
    "action": "Eliminar cuenta",
    "description": "Elimina de la nube las conversaciones, Bases, Apps y archivos sincronizados de esta cuenta. Todos los dispositivos y sesiones de navegador perderán el acceso.",
    "local": "El contenido creado o retomado en este ordenador y sus archivos locales se conservan. Las copias que solo reflejan la nube se eliminan al reconectar. No se puede deshacer.",
    "deleted": "Eliminación de cuenta confirmada",
    "reauthenticate": "Continuar con Google",
    "reauthDetails": "Selecciona de nuevo la misma cuenta de Google. Google puede reutilizar su sesión existente; Bottega requiere una nueva autorización de Google correcta para esta solicitud.",
    "confirmTitle": "¿Eliminar permanentemente esta cuenta en la nube?",
    "confirm": "Eliminar cuenta en la nube permanentemente",
    "cancel": "Cancelar",
    "pending": "Es necesario confirmar con Google.",
    "accepted": "Eliminación de cuenta confirmada. Se ha cerrado el acceso a la nube y la limpieza continuará automáticamente. Tu contenido local se conserva.",
    "unavailable": "Esta solicitud no está disponible o ha caducado. Vuelve a revisar la cuenta actual.",
    "wrongAccount": "Esta cuenta es diferente de la seleccionada en tu ordenador. Cambia a esa cuenta para continuar.",
    "back": "Volver a la cuenta",
    "failed": "No se pudo completar la solicitud. Comprueba la solicitud original antes de crear otra.",
    "browser": "Revisa la cuenta y confirma con Google en tu navegador.",
    "retry": "Comprobar la solicitud original",
    "startAgain": "Empezar una nueva revisión",
    "loading": "Comprobando cuenta…",
    "browserPending": "Termina en tu navegador: continúa con la misma cuenta de Google y confirma allí. Esta página se actualiza al volver.",
    "continuation": "Empezaste a eliminar esta cuenta en la app de Bottega. Continúa con la misma cuenta de Google para confirmarlo aquí.",
    "continuationWrongAccount": "Esta cuenta de Google no es la que se está eliminando. Continúa con Google y elige la cuenta desde la que empezaste.",
    "cancelled": "Se canceló el inicio de sesión con Google. Continúa con Google para volver a intentarlo.",
    "returnToApp": "Eliminación de cuenta confirmada. Puedes volver a la app de Bottega."
  }
};
export function accountDeletionCopy(locale: string) {
  const language = locale.toLowerCase().split("-")[0];
  return copies[language === "zh" ? "zh-cn" : language === "ja" || language === "fr" || language === "es" ? language : "en"];
}
