/**
 * [INPUT]: Desktop setup and browser unlock product language.
 * [OUTPUT]: Reference encrypted-sync copy with immediate eight-character unlock validation, the twelve-character creation checklist, the review-expired and connection sentences, the browser gate's checking/unavailable/unsupported/lock-failed headings, and a closed five-language key type.
 * [POS]: Shared password, local storage and recovery messages; no platform dependencies.
 */
export const en = {
  setupInProgress: "Enabling sync…", setupConnectionFailed: "Connection failed. Check your network and try again.",
  title: "Unlock synced workspace",
  description: "Enter the sync password you set on your desktop.",
  password: "Sync password",
  confirmation: "Confirm sync password",
  setPassword: "Set a sync password",
  setupDescription: "Choose a password only you know. Keep it safe; Bottega cannot recover it.",
  risk: "I understand that losing this password may make cloud data unrecoverable.",
  inProgress: "Securing sync…",
  unlock: "Unlock",
  unlocking: "Unlocking…",
  checking: "Checking encrypted sync…",
  remember: "Keep this browser unlocked",
  rememberDescription: "Save an encrypted unlock key on this browser. You can lock it at any time.",
  remembered: "This browser will remember the unlock key.",
  thisPageOnly: "Unlocked for this page only.",
  saving: "Saving the unlock key…",
  saveFailed: "Unlocked for now, but the unlock key could not be saved. You may need your sync password next time.",
  saveRetry: "Retry saving unlock key",
  cachedStorageUnavailable: "Secure local storage is unavailable. You may need your sync password when you reopen the app.",
  cacheUnreadable: "The saved unlock key could not be read. Enter your sync password to continue.",
  cacheClearFailed: "The saved unlock key could not be removed. Retry to lock remembered access on this browser.",
  lock: "Lock this browser",
  locked: "Synced workspace is locked",
  offlineTitle: "Connect to unlock your workspace",
  offlineDescription: "Your browser must verify the account before it can unlock saved content. Your encrypted cache is kept.",
  unavailable: "Encrypted sync could not be checked. Please retry.",
  reviewExpired: "This review has expired. Scan again before confirming.", connectionFailed: "Your connection is unavailable. Encrypted sync will continue once you are back online.",
  retry: "Retry",
  cancel: "Cancel",
  account: "Account and devices",
  showPassword: "Show password", hidePassword: "Hide password", passwordMismatch: "The passwords do not match.", independentPassword: "This password is separate from your Google password and only unlocks synced content.",
  unrecoverableCloud: "Keep your sync password safe. Recovering your Google account cannot recover this password. If you lose it and no device can decrypt your old data, content stored only in the cloud cannot be recovered.",
  secureSaveFailedDesktop: "The unlock key could not be saved securely on this computer. Sync remains off. Retry saving before enabling sync.",
  legacyUnsupported: "This account still contains data from the previous sync format. Encrypted sync cannot start until that data has been handled.",
  passwordTooShort: "Use at least 8 characters.",
  passwordTooLong: "Use no more than 1,024 UTF-8 bytes. Some characters use more than one byte.",
  passwordRules: "Password requirements", ruleMet: "met", ruleUnmet: "not met",
  ruleLength: "At least 12 characters", ruleLetter: "At least one letter", ruleDigit: "At least one number",
  ruleSimple: "Avoid repeated or sequential characters", ruleEmail: "Don’t include your email name", ruleCommon: "Avoid common passwords and “Bottega”",
  "sync-password-invalid": "Use at least 8 characters and no more than 1,024 UTF-8 bytes. Some characters use more than one byte.",
  "sync-password-weak": "Choose a stronger password that meets every requirement.",
  "sync-unlock-failed": "The sync password could not unlock this workspace. Check it and try again.",
  "sync-integrity-failed": "This encrypted content could not be verified. Reload the latest copy before trying again.",
  "sync-encryption-unsupported": "This browser or device cannot run the required encryption. Use an updated Chrome browser or Bottega desktop.",
  "sync-space-changed": "The encrypted workspace or its key has changed. Access is paused; check the account and restore information before continuing.",
  "sync-operation-cancelled": "Unlocking was cancelled.",
  "sync-operation-busy": "Another encryption operation is running. Wait for it to finish or cancel it.",
  "sync-locked": "Unlock the synced workspace to continue.",
  checkingDescription: "Looking up this account’s encrypted space.",
  unavailableTitle: "Encrypted sync could not be checked", unavailableDescription: "Retry to check again. Your sign-in is kept.",
  unsupportedTitle: "This browser can’t run encrypted sync", lockFailedTitle: "Lock did not finish",
  cancelledDescription: "Unlocking was cancelled. Enter your sync password to try again.",
  lockedDescription: "This browser is locked. Enter your sync password to continue.",
  missingUnlock: "This browser has no saved unlock information. Enter your sync password again.",
};
export type CloudEncryptionCopy = Record<keyof typeof en, string>;
