/**
 * [INPUT]: Shared composer and Sketch presentation keys.
 * [OUTPUT]: Es locale catalog for common input controls.
 * [POS]: Browser-safe presentation authority shared with native controls.
 */
export const copy = {
  chatRevision: {
  notIdle: "El chat está ocupado o tiene mensajes en cola. Espera a que se estabilice y vuelve a enviar la revisión.",
  stale: "La conversación avanzó y este mensaje ya no es el último. Edita el mensaje más reciente.",
  edit: "Editar mensaje",
  cancel: "Cancelar",
  send: "Enviar revisión",
  editing: "Editar el último mensaje",
  unavailable: {
    busy: "Espera a que termine el turno activo antes de editar.",
    queued: "Completa o elimina los mensajes en cola antes de editar.",
    "imported-prefix": "Los mensajes importados no se pueden editar.",
  },
},
    newTask: "Nueva tarea",
    fork: {
      action: "Bifurcar desde aquí",
      title: "Bifurcar el chat desde aquí",
      description: "Crea una continuación independiente de {{title}} desde esta respuesta.",
      sameWorkspace: "Bifurcar en este espacio",
      sameWorkspaceDetail: "Bifurca desde este mensaje en el espacio de trabajo actual.",
      newWorktree: "Bifurcar en un worktree nuevo",
      newWorktreeDetail: "Bifurca desde este mensaje en un worktree nuevo.",
      dirtyWarning: "Los cambios locales del origen no se copian.",
      unsupported: "Los worktrees gestionados solo están disponibles en proyectos Git aptos en macOS.",
      unavailable: "Esta respuesta no se puede bifurcar",
      continuedFrom: "⑂ Continuado desde el chat",
      openSource: "Abrir chat de origen {{title}}",
      originalUnavailable: "El chat original no está disponible",
      inheritedReadOnly: "Los mensajes heredados no se pueden editar",
      recoveryTruncated: "El Agent recibió la parte más reciente del historial heredado porque el prefijo completo excedía el presupuesto de contexto.",
      worktreePermission: "Full Access no está disponible en un worktree administrado",
      errors: {
        pointInvalid: "Esta respuesta ya no se puede bifurcar. Actualiza el chat e inténtalo de nuevo.",
        sourceStale: "El chat cambió después de cargar esta vista. Actualiza e inténtalo de nuevo.",
        sourceUnsupported: "Este chat no se puede bifurcar.",
        prefixTooLarge: "El historial hasta esta respuesta es demasiado grande para bifurcar. Elige una respuesta anterior.",
        projectUnavailable: "El Project no está disponible, se está revinculando o se está eliminando.",
        requestConflict: "Otra solicitud de bifurcación ya usó esta identidad. Cierra el diálogo e inténtalo de nuevo.",
        recoveryRequired: "Esta bifurcación necesita recuperación antes de continuar.",
        notRepository: "La carpeta del Project no es un repositorio Git.",
        notGitRoot: "La carpeta del Project no es la raíz de su repositorio Git.",
        noHead: "El repositorio aún no tiene ningún commit. Crea uno primero.",
        bareRepository: "Los repositorios bare no pueden alojar un worktree gestionado.",
        operationInProgress: "Termina o cancela primero la operación Git en curso (merge, rebase, cherry-pick, revert o bisect).",
        submodule: "Los repositorios con submódulos aún no son compatibles.",
        treeTooLarge: "El árbol del repositorio es demasiado grande para verificarlo para un worktree gestionado.",
        configUnsafe: "La configuración Git del repositorio ejecuta programas externos (filters, fsmonitor o alternate refs). Desactívalos primero.",
        branchConflict: "La rama de la bifurcación ya existe. Se requiere recuperación.",
        pathConflict: "La ruta o el registro del worktree ya existen. Se requiere recuperación.",
        identityDrift: "La identidad del repositorio cambió durante la bifurcación. Inténtalo de nuevo.",
      },
    } ,
  resumeFailure: {
      title: "{{backend}} no puede abrir la sesión guardada de este chat",
      description: "Tu mensaje y sus adjuntos están guardados y todavía no se han enviado.",
      retriedTitle: "El reintento de la sesión original falló",
      retriedDescription: "{{backend}} sigue sin poder abrir la sesión guardada. Tu mensaje y sus adjuntos siguen guardados y no se han enviado.",
      recommended: "Recomendado",
      sameSession: "Reintentar la sesión original",
      sameSessionDetail: "Volver a conectar con la sesión original. Si funciona, el agente conserva todo lo que sabe de este chat.",
      sameSessionRetry: "Reintentar otra vez",
      sameSessionRetryDetail: "Intentar la misma reconexión una vez más. Ya falló una vez.",
      freshSession: "Iniciar una sesión nueva",
      freshSessionDetail: "Inicia una sesión nueva con el mismo Agent a partir de la conversación guardada en este Chat. Se incluye el historial reciente; si el acceso al historial del Chat está activado, el Agent puede consultar mensajes anteriores.",
      freshSessionBlocked: "No se puede iniciar una sesión nueva en este momento.",
      abandon: "Descartar este turno",
      abandonDetail: "No se envía nada; este turno termina aquí. Tu mensaje permanece en este chat.",
      actionFailed: "No se pudo completar: {{message}}",
      pendingTitle: "Este turno está pendiente de recuperación",
      pendingDetail: "Recupera o abandona este turno antes de enviar otro mensaje. Puedes seguir consultando tus Chats.",
      review: "Opciones de recuperación",
      later: "Resolver más tarde",
    },
  userInput: {
    countdown: "{{count}} s",
    skip: "Omitir",
    progress: "{{current}} de {{total}}",
    skipQuestion: "Omitir pregunta",
    pendingList: "Preguntas simultáneas pendientes",
    pending: "Pendiente",
    pendingCount: "{{count}} pendientes",
    mainAgent: "Agent principal",
    waiting: "Esperando una respuesta",
    other: "Ninguna; indicar otro enfoque al Agent",
    confirm: "Confirmar selección",
    decisionPlaceholder: "Indica tu decisión al Agent…",
    send: "Enviar",
  },
  approval: {
    requestChanges: "Solicitar cambios",
    decline: "Rechazar",
    allowSession: "Permitir en esta sesión",
    approvePlan: "Aprobar el Plan",
    allowOnce: "Permitir una vez",
    planTitle: "¿Continuar con este Plan?",
    commandTitle: "¿Permitir este comando?",
    fileChangeTitle: "¿Permitir estos cambios de archivos?",
    permissionTitle: "¿Permitir acceso adicional?",
    location: "Ubicación",
    network: "Red",
    plan: "Plan",
    details: "Detalles",
  },
  "permission": {
    "trigger": "Permiso de acción actual: {{mode}}",
    "heading": "¿Cómo se deben aprobar las acciones de {{backend}}?",
    "learnMore": "Más información",
    "selected": "Seleccionado",
    "mode": {
      "ask-for-approval": {
        "label": "Pedir aprobación",
        "description": "Preguntar antes de las acciones que requieran tu aprobación"
      },
      "approve-for-me": {
        "label": "Aprobar por mí",
        "description": "Aprobar las acciones seguras; las solicitudes sensibles siguen preguntando"
      },
      "full-access": {
        "label": "Acceso total",
        "description": "Acceso sin restricciones a internet y a cualquier archivo de este equipo"
      }
    },
    "fullAccess": {
      "title": "¿Activar el acceso total?",
      "description": "El Agent podrá ejecutar comandos, usar internet y crear o editar archivos fuera de este chat sin tu permiso. Los datos de control de AI Chat siguen protegidos, pero tus demás archivos no. Esto incluye, entre otros:",
      "files": {
        "title": "Archivos y carpetas",
        "description": "Leer, crear, modificar, subir o eliminar archivos en cualquier lugar de este equipo"
      },
      "terminal": {
        "title": "Comandos de terminal",
        "description": "Ejecutar comandos, instalar software y cambiar la configuración del sistema"
      },
      "internet": {
        "title": "Internet y apps conectadas",
        "description": "Acceder a sitios web, enviar datos y usar los plugins activados"
      },
      "risk": "Esto conlleva riesgos como la pérdida o exposición de datos sensibles y la inyección de prompts. Puedes desactivarlo cuando quieras.",
      "confirm": "Confirmar",
      "confirming": "Confirmando…",
      "failed": "No se pudo activar el acceso total: {{reason}}"
    }
  },
  "common": {
    "cancel": "Cancelar",
    "close": "Cerrar"
  },
  "sketch": {
    "title": "Boceto",
    "description": "Dibuja una imagen para tu mensaje.",
    "done": "Listo",
    "processing": "Procesando el boceto",
    "discardTitle": "¿Descartar los cambios?",
    "discardDescription": "Tus cambios no se guardarán.",
    "continueEditing": "Seguir editando",
    "discardChanges": "Descartar cambios",
    "edit": "Haz clic para editar el boceto",
    "select": "Seleccionar",
    "pen": "Lápiz",
    "text": "Texto",
    "shapeTool": "Formas",
    "eraser": "Borrador",
    "undo": "Deshacer",
    "redo": "Rehacer",
    "canvas": "Lienzo del boceto",
    "canvasHelp": "Dibuja o selecciona. Las flechas mueven, Supr elimina y Comando o Control Z deshace.",
    "penWidth": "Grosor del lápiz",
    "eraserWidth": "Diámetro del borrador",
    "color": "Color {{value}}",
    "customColor": "Color personalizado",
    "sampleColor": "Tomar color del lienzo",
    "red": "Rojo",
    "green": "Verde",
    "blue": "Azul",
    "textInput": "Texto del boceto",
    "busyErasing": "Terminando de borrar…",
    "historyTrimmed": "Se eliminaron los pasos de deshacer más antiguos.",
    "error": "No se pudo completar esta acción. Inténtalo de nuevo.",
    "empty": "Primero añade contenido al boceto.",
    "sourceMissing": "La fuente editable no está disponible. Se ha conservado el boceto.",
    "ownerExpired": "Este chat ya no está disponible.",
    "readOnly": "Este chat no se puede editar ahora.",
    "versionChanged": "Este adjunto cambió. Cierra el editor y abre la última versión.",
    "migrationActive": "Espera a que termine el traslado de ventana e inténtalo de nuevo.",
    "editorActive": "Primero termina o cierra el boceto.",
    "attachmentLimit": "Un mensaje admite hasta 8 adjuntos directos.",
    "imageTooLarge": "El PNG supera 8 MiB. Reduce el contenido e inténtalo de nuevo.",
    "budget": "Esta acción supera el límite de edición. Tu trabajo se ha conservado.",
    "resizeBudget": "Esta ampliación supera el límite de edición. Prueba un tamaño menor.",
    "eraseBudget": "El borrado supera el límite de procesamiento. Se ha conservado el contenido anterior. Reduce la forma o el contenido e inténtalo de nuevo.",
    "exportFailed": "No se pudo crear el PNG. Tu boceto sigue aquí; inténtalo de nuevo.",
    "workerFailed": "No se pudo borrar. Tu boceto no ha cambiado; inténtalo de nuevo.",
    "textOverflow": "El texto sale del lienzo. Acórtalo o cancela esta edición para moverlo o reducirlo.",
    "handle": "Cambiar tamaño {{direction}}",
    "shape": {
      "line": "Línea",
      "arrow": "Flecha",
      "rectangle": "Rectángulo",
      "circle": "Círculo",
      "triangle": "Triángulo",
      "diamond": "Rombo",
      "star": "Estrella",
      "heart": "Corazón"
    }
  },
  "chat": {
    "composer": {
  queue: {
    pickedUp: "Mensaje en cola seleccionado. Usa las flechas Arriba y Abajo para moverlo.",
    reorderCancelled: "Reordenación cancelada",
    moved: "Movido a la posición {{position}}",
    unchanged: "La posición no cambió",
    paused: "Cola en pausa",
    resume: "Reanudar envío",
    dismissError: "Cerrar error de la cola",
    drag: "Mover elemento {{position}} de {{count}}",
    resend: "Reenviar este mensaje",
    deleteAmbiguous: "Eliminar este mensaje ambiguo",
    steer: "Enviar a continuación en la tarea activa",
    delete: "Eliminar este mensaje en cola",
    edit: "Editar este mensaje en cola",
  },

      "surface": {
        "plan": "Plan"
      },
      "plan": {
        "closeChip": "Desactivar el Plan",
        "decisionTitle": "¿Implementar este Plan?",
        "closeDecision": "Cerrar la decisión del Plan",
        "implement": "Sí, implementar este Plan",
        "reviseLabel": "Indicar al Agent cómo revisar el Plan",
        "revisePlaceholder": "No. Indica al Agent qué debe hacer de otra forma",
        "send": "Enviar",
        "skip": "Omitir"
      },
      "add": "Añadir",
      "files": "Archivos",
      "disablePlan": "Desactivar Plan",
      "modelSelector": {
        currentModel: "Modelo actual {{model}}, esfuerzo {{effort}}",
        selector: "Selector de modelo del chat",
        advanced: "Avanzado",
        model: "Modelo",
        effort: "Esfuerzo",
        speed: "Velocidad",
        disableFast: "Desactivar velocidad Fast",
        enableFast: "Activar velocidad Fast",
        quickTier: "Nivel rápido del modelo",
        loadingModels: "Cargando catálogo de modelos…",
        retryModels: "Reintentar catálogo de modelos",
        resetDefault: "Restablecer valores predeterminados",
        onlyOneModel: "Solo hay un modelo disponible",
        effortUnavailable: "El modelo actual no permite cambiar el esfuerzo",
        noModels: "No se encontraron modelos disponibles",
        backendDefaultModel: "Modelo predeterminado del backend",
        speedDescription:
          "Aproximadamente 2,5 veces más rápido en modelos Opus 5/4.8 compatibles. Consume más créditos de uso, pero no el límite de velocidad de la suscripción.",
        speedReason: {
          modelUnsupported: "El modelo actual no ofrece Fast",
          backendOff: "El backend desactivó Fast en esta sesión",
          backendOn: "El backend activó Fast en esta sesión",
        },
      }
    }
  }
};
