/**
 * [INPUT]: Shared composer and Sketch presentation keys.
 * [OUTPUT]: Fr locale catalog for common input controls.
 * [POS]: Browser-safe presentation authority shared with native controls.
 */
export const copy = {
  chatRevision: {
  notIdle: "La conversation est occupée ou des messages sont en file. Attendez qu’elle se stabilise puis renvoyez la révision.",
  stale: "La conversation a avancé et ce message n’est plus le dernier. Modifiez plutôt le message le plus récent.",
  edit: "Modifier le message",
  cancel: "Annuler",
  send: "Envoyer la révision",
  editing: "Modifier le dernier message",
  unavailable: {
    busy: "Attendez la fin du tour actif avant de modifier.",
    queued: "Terminez ou retirez les messages en file avant de modifier.",
    "imported-prefix": "Les messages importés ne peuvent pas être modifiés.",
  },
},
    newTask: "Nouvelle tâche",
    fork: {
      action: "Créer une branche ici",
      title: "Créer une branche du chat ici",
      description: "Créez une continuation indépendante de {{title}} à partir de cette réponse.",
      sameWorkspace: "Dans cet espace de travail",
      sameWorkspaceDetail: "Reprenez depuis ce message dans l’espace de travail actuel.",
      newWorktree: "Dans un nouveau worktree",
      newWorktreeDetail: "Reprenez depuis ce message dans un nouveau worktree.",
      dirtyWarning: "Les modifications locales de la source ne sont pas copiées.",
      unsupported: "Les worktrees gérés sont réservés aux projets Git compatibles sous macOS.",
      unavailable: "Cette réponse ne peut pas être bifurquée",
      continuedFrom: "⑂ Suite du chat",
      openSource: "Ouvrir le chat source {{title}}",
      originalUnavailable: "Le chat d’origine est indisponible",
      inheritedReadOnly: "Les messages hérités ne peuvent pas être modifiés",
      recoveryTruncated: "L’Agent a reçu la partie la plus récente de l’historique hérité, le préfixe complet dépassant le budget de contexte.",
      worktreePermission: "Full Access est indisponible dans un worktree géré",
      errors: {
        pointInvalid: "Cette réponse ne peut plus servir de point de branche. Actualisez le chat et réessayez.",
        sourceStale: "Le chat a changé après le chargement de cette vue. Actualisez et réessayez.",
        sourceUnsupported: "Ce chat ne peut pas être bifurqué.",
        prefixTooLarge: "L’historique jusqu’à cette réponse est trop volumineux pour une branche. Choisissez une réponse antérieure.",
        projectUnavailable: "Le Project est indisponible, en cours de réassociation ou de suppression.",
        requestConflict: "Une autre demande de branche a déjà utilisé cette identité. Fermez la fenêtre et réessayez.",
        recoveryRequired: "Cette branche nécessite une récupération avant de continuer.",
        notRepository: "Le dossier du Project n’est pas un dépôt Git.",
        notGitRoot: "Le dossier du Project n’est pas la racine de son dépôt Git.",
        noHead: "Le dépôt n’a encore aucun commit. Créez d’abord un commit.",
        bareRepository: "Les dépôts bare ne peuvent pas héberger de worktree géré.",
        operationInProgress: "Terminez ou annulez d’abord l’opération Git en cours (merge, rebase, cherry-pick, revert ou bisect).",
        submodule: "Les dépôts avec sous-modules ne sont pas encore pris en charge.",
        treeTooLarge: "L’arborescence du dépôt est trop volumineuse pour être vérifiée pour un worktree géré.",
        configUnsafe: "La configuration Git du dépôt exécute des programmes externes (filters, fsmonitor ou alternate refs). Désactivez-les d’abord.",
        branchConflict: "La branche de la bifurcation existe déjà. Une récupération est nécessaire.",
        pathConflict: "Le chemin ou l’enregistrement du worktree existe déjà. Une récupération est nécessaire.",
        identityDrift: "L’identité du dépôt a changé pendant la bifurcation. Réessayez.",
      },
    } ,
  resumeFailure: {
      title: "{{backend}} ne parvient pas à ouvrir la session enregistrée de ce chat",
      description: "Votre message et ses pièces jointes sont enregistrés et n'ont pas encore été envoyés.",
      retriedTitle: "La reprise de la session d'origine a échoué",
      retriedDescription: "{{backend}} ne parvient toujours pas à ouvrir la session enregistrée. Votre message et ses pièces jointes restent enregistrés et n’ont pas été envoyés.",
      recommended: "Recommandé",
      sameSession: "Réessayer la session d'origine",
      sameSessionDetail: "Se reconnecter à la session d'origine. Si cela fonctionne, l'agent conserve tout ce qu'il sait de ce chat.",
      sameSessionRetry: "Réessayer la session d'origine",
      sameSessionRetryDetail: "Tenter la même reconnexion une fois de plus. Elle a déjà échoué une fois.",
      freshSession: "Démarrer une nouvelle session",
      freshSessionDetail: "Démarrez une nouvelle session avec le même Agent à partir de la conversation enregistrée dans ce Chat. L’historique récent est inclus ; si l’accès à l’historique du Chat est activé, l’Agent peut consulter les messages précédents.",
      freshSessionBlocked: "Le démarrage d’une nouvelle session est indisponible pour le moment.",
      abandon: "Abandonner ce tour",
      abandonDetail: "Rien n'est envoyé, ce tour s'arrête ici. Votre message reste dans ce chat.",
      actionFailed: "Échec de l'opération : {{message}}",
      pendingTitle: "Ce tour attend une récupération",
      pendingDetail: "Récupérez ou abandonnez ce tour avant d’envoyer un autre message. Vous pouvez continuer à consulter vos Chats.",
      review: "Options de récupération",
      later: "Traiter plus tard",
    },
  userInput: {
    countdown: "{{count}} s",
    skip: "Ignorer",
    progress: "{{current}} sur {{total}}",
    skipQuestion: "Ignorer la question",
    pendingList: "Questions simultanées en attente",
    pending: "En attente",
    pendingCount: "{{count}} en attente",
    mainAgent: "Agent principal",
    waiting: "En attente d’une réponse",
    other: "Aucune de ces réponses ; proposer une autre approche à l’Agent",
    confirm: "Confirmer la sélection",
    decisionPlaceholder: "Indiquez votre décision à l’Agent…",
    send: "Envoyer",
  },
  approval: {
    requestChanges: "Demander des modifications",
    decline: "Refuser",
    allowSession: "Autoriser pour cette session",
    approvePlan: "Approuver le Plan",
    allowOnce: "Autoriser une fois",
    planTitle: "Continuer avec ce Plan ?",
    commandTitle: "Autoriser cette commande ?",
    fileChangeTitle: "Autoriser ces modifications de fichiers ?",
    permissionTitle: "Autoriser un accès supplémentaire ?",
    location: "Emplacement",
    network: "Réseau",
    plan: "Plan",
    details: "Détails",
  },
  "permission": {
    "trigger": "Permission d’action actuelle : {{mode}}",
    "heading": "Comment approuver les actions de {{backend}} ?",
    "learnMore": "En savoir plus",
    "selected": "Sélectionné",
    "mode": {
      "ask-for-approval": {
        "label": "Demander l’approbation",
        "description": "Demander avant les actions qui nécessitent votre approbation"
      },
      "approve-for-me": {
        "label": "Approuver pour moi",
        "description": "Approuver les actions sûres ; les demandes sensibles restent soumises à approbation"
      },
      "full-access": {
        "label": "Accès complet",
        "description": "Accès illimité à Internet et à tous les fichiers de cet ordinateur"
      }
    },
    "fullAccess": {
      "title": "Activer l’accès complet ?",
      "description": "L’Agent pourra exécuter des commandes, utiliser Internet, créer et modifier des fichiers hors de ce chat sans votre permission. Les données de contrôle d’AI Chat restent protégées, mais pas vos autres fichiers. Cela comprend notamment :",
      "files": {
        "title": "Fichiers et dossiers",
        "description": "Lire, créer, modifier, téléverser ou supprimer des fichiers partout sur cet ordinateur"
      },
      "terminal": {
        "title": "Commandes du terminal",
        "description": "Exécuter des commandes, installer des logiciels et modifier les réglages système"
      },
      "internet": {
        "title": "Internet et applications connectées",
        "description": "Accéder aux sites web, envoyer des données et utiliser les plugins activés"
      },
      "risk": "Cela comporte des risques : perte ou exposition de données sensibles et injection de prompt. Vous pouvez le désactiver à tout moment.",
      "confirm": "Confirmer",
      "confirming": "Confirmation…",
      "failed": "Impossible d’activer l’accès complet : {{reason}}"
    }
  },
  "common": {
    "cancel": "Annuler",
    "close": "Fermer"
  },
  "sketch": {
    "title": "Croquis",
    "description": "Dessinez une image pour votre message.",
    "done": "Terminer",
    "processing": "Traitement du croquis",
    "discardTitle": "Abandonner les modifications ?",
    "discardDescription": "Vos modifications ne seront pas enregistrées.",
    "continueEditing": "Continuer à modifier",
    "discardChanges": "Abandonner",
    "edit": "Cliquer pour modifier le croquis",
    "select": "Sélection",
    "pen": "Crayon",
    "text": "Texte",
    "shapeTool": "Formes",
    "eraser": "Gomme",
    "undo": "Annuler",
    "redo": "Rétablir",
    "canvas": "Canevas du croquis",
    "canvasHelp": "Dessinez ou sélectionnez. Les flèches déplacent, Suppr supprime, Commande ou Contrôle Z annule.",
    "penWidth": "Épaisseur du crayon",
    "eraserWidth": "Diamètre de la gomme",
    "color": "Couleur {{value}}",
    "customColor": "Couleur personnalisée",
    "sampleColor": "Prélever sur le canevas",
    "red": "Rouge",
    "green": "Vert",
    "blue": "Bleu",
    "textInput": "Texte du croquis",
    "busyErasing": "Finalisation de l’effacement…",
    "historyTrimmed": "Les anciennes étapes d’annulation ont été effacées.",
    "error": "Impossible de terminer cette action. Réessayez.",
    "empty": "Ajoutez d’abord du contenu au croquis.",
    "sourceMissing": "La source modifiable est indisponible. Le croquis est conservé.",
    "ownerExpired": "Ce chat n’est plus disponible.",
    "readOnly": "Ce chat ne peut pas être modifié pour le moment.",
    "versionChanged": "Cette pièce jointe a changé. Fermez puis ouvrez sa dernière version.",
    "migrationActive": "Attendez la fin du déplacement de fenêtre, puis réessayez.",
    "editorActive": "Terminez ou fermez d’abord le croquis.",
    "attachmentLimit": "Un message accepte jusqu’à 8 pièces jointes directes.",
    "imageTooLarge": "Le PNG dépasse 8 Mio. Réduisez le contenu et réessayez.",
    "budget": "Cette action dépasse la limite d’édition. Votre travail est conservé.",
    "resizeBudget": "Cet agrandissement dépasse la limite d’édition. Réduisez la taille.",
    "eraseBudget": "Cet effacement dépasse la limite de traitement. Le contenu précédent est conservé. Réduisez la forme ou le contenu et réessayez.",
    "exportFailed": "Impossible de créer le PNG. Votre croquis est conservé ; réessayez.",
    "workerFailed": "Impossible d’effacer. Le croquis est inchangé ; réessayez.",
    "textOverflow": "Le texte dépasse du canevas. Raccourcissez-le ou annulez cette édition pour le déplacer ou le réduire.",
    "handle": "Redimensionner {{direction}}",
    "shape": {
      "line": "Ligne",
      "arrow": "Flèche",
      "rectangle": "Rectangle",
      "circle": "Cercle",
      "triangle": "Triangle",
      "diamond": "Losange",
      "star": "Étoile",
      "heart": "Cœur"
    }
  },
  "chat": {
    "composer": {
  queue: {
    pickedUp: "Message en file sélectionné. Utilisez les flèches Haut et Bas pour le déplacer.",
    reorderCancelled: "Réorganisation annulée",
    moved: "Déplacé à la position {{position}}",
    unchanged: "Position inchangée",
    paused: "File en pause",
    resume: "Reprendre l’envoi",
    dismissError: "Fermer l’erreur de la file",
    drag: "Déplacer l’élément {{position}} sur {{count}}",
    resend: "Renvoyer ce message",
    deleteAmbiguous: "Supprimer ce message ambigu",
    steer: "Envoyer ensuite dans la tâche en cours",
    delete: "Supprimer ce message en file",
    edit: "Modifier ce message en file",
  },

      "surface": {
        "plan": "Plan"
      },
      "plan": {
        "closeChip": "Désactiver le Plan",
        "decisionTitle": "Implémenter ce Plan ?",
        "closeDecision": "Fermer la décision du Plan",
        "implement": "Oui, implémenter ce Plan",
        "reviseLabel": "Indiquer à l’Agent comment réviser le Plan",
        "revisePlaceholder": "Non. Indiquez à l’Agent ce qu’il doit modifier",
        "send": "Envoyer",
        "skip": "Ignorer"
      },
      "add": "Ajouter",
      "files": "Fichiers",
      "disablePlan": "Désactiver Plan",
      "modelSelector": {
        currentModel: "Modèle actuel {{model}}, effort {{effort}}",
        selector: "Sélecteur de modèle de chat",
        advanced: "Avancé",
        model: "Modèle",
        effort: "Effort",
        speed: "Vitesse",
        disableFast: "Désactiver la vitesse Fast",
        enableFast: "Activer la vitesse Fast",
        quickTier: "Niveau rapide du modèle",
        loadingModels: "Chargement du catalogue de modèles…",
        retryModels: "Réessayer le catalogue de modèles",
        resetDefault: "Rétablir les valeurs par défaut",
        onlyOneModel: "Un seul modèle est disponible",
        effortUnavailable: "Le modèle actuel ne permet pas de modifier l’effort",
        noModels: "Aucun modèle disponible",
        backendDefaultModel: "Modèle par défaut du backend",
        speedDescription:
          "Environ 2,5 fois plus rapide sur les modèles Opus 5/4.8 compatibles. Utilise davantage de crédits d’usage, mais pas le quota de limitation de débit de l’abonnement.",
        speedReason: {
          modelUnsupported: "Le modèle actuel ne propose pas Fast",
          backendOff: "Le backend a désactivé Fast pour cette session",
          backendOn: "Le backend a activé Fast pour cette session",
        },
      }
    }
  }
};
