/**
 * [INPUT]: Shared composer and Sketch presentation keys.
 * [OUTPUT]: Ja locale catalog for common input controls.
 * [POS]: Browser-safe presentation authority shared with native controls.
 */
export const copy = {
  chatRevision: {
  notIdle: "チャットが実行中か、キューにメッセージがあります。落ち着いてから修正版を送信してください。",
  stale: "会話が進み、このメッセージは最後ではなくなりました。最新のメッセージを編集し直してください。",
  edit: "メッセージを編集",
  cancel: "キャンセル",
  send: "修正版を送信",
  editing: "最後のメッセージを編集",
  unavailable: {
    busy: "実行中のターンが終了してから編集してください。",
    queued: "キューのメッセージを完了または削除してから編集してください。",
    "imported-prefix": "取り込んだ履歴メッセージは編集できません。",
  },
},
    newTask: "新しいタスク",
    fork: {
      action: "ここから Fork",
      title: "ここからチャットを Fork",
      description: "この応答から「{{title}}」の独立した続きを作成します。",
      sameWorkspace: "このワークスペースで Fork",
      sameWorkspaceDetail: "このメッセージから現在のワークスペースで Fork します。",
      newWorktree: "新しい worktree で Fork",
      newWorktreeDetail: "このメッセージから新しい worktree で Fork します。",
      dirtyWarning: "コピー元のローカル変更はコピーされません。",
      unsupported: "管理 worktree は macOS 上の対象 Git Project のみ利用できます。",
      unavailable: "この応答から Fork できません",
      continuedFrom: "⑂ 元のチャットから継続",
      openSource: "元のチャット {{title}} を開く",
      originalUnavailable: "元のチャットは利用できません",
      inheritedReadOnly: "継承されたメッセージは編集できません",
      recoveryTruncated: "継承履歴全体がコンテキスト予算を超えたため、Agent には最新部分のみ送信されました。",
      worktreePermission: "管理対象 worktree では Full Access を使用できません",
      errors: {
        pointInvalid: "この応答はもう Fork の起点にできません。チャットを更新して再試行してください。",
        sourceStale: "このビューの読み込み後にチャットが変更されました。更新して再試行してください。",
        sourceUnsupported: "このチャットは Fork できません。",
        prefixTooLarge: "この応答までの履歴が大きすぎて Fork できません。より前の応答を選んでください。",
        projectUnavailable: "Project が利用できないか、再バインドまたは削除の途中です。",
        requestConflict: "別の Fork リクエストがこの ID をすでに使用しています。ダイアログを閉じて再試行してください。",
        recoveryRequired: "この Fork は続行する前に復旧が必要です。",
        notRepository: "Project フォルダーは Git リポジトリではありません。",
        notGitRoot: "Project フォルダーは Git リポジトリのルートではありません。",
        noHead: "リポジトリにまだコミットがありません。先にコミットを作成してください。",
        bareRepository: "bare リポジトリでは管理 worktree を作成できません。",
        operationInProgress: "進行中の Git 操作（merge、rebase、cherry-pick、revert、bisect）を先に完了または中止してください。",
        submodule: "サブモジュールを含むリポジトリはまだサポートされていません。",
        treeTooLarge: "リポジトリのツリーが大きすぎて、管理 worktree 用の検証ができません。",
        configUnsafe: "リポジトリの Git 設定が外部プログラム（filter、fsmonitor、alternate refs）を実行します。先に無効化してください。",
        branchConflict: "Fork ブランチがすでに存在します。復旧が必要です。",
        pathConflict: "worktree のパスまたは登録がすでに存在します。復旧が必要です。",
        identityDrift: "Fork 中にリポジトリの ID が変わりました。再試行してください。",
      },
    } ,
  resumeFailure: {
      title: "{{backend}} がこのチャットの保存済みセッションを開けません",
      description: "メッセージと添付ファイルは保存済みで、まだ送信されていません。",
      retriedTitle: "元のセッションでの再試行に失敗しました",
      retriedDescription: "{{backend}} は保存されたセッションをまだ開けません。メッセージと添付ファイルは保存されており、まだ送信されていません。",
      recommended: "推奨",
      sameSession: "元のセッションで再試行",
      sameSessionDetail: "元のセッションにもう一度つなぎます。成功すればエージェントはこのチャットの文脈をすべて保ったままです。",
      sameSessionRetry: "もう一度再試行",
      sameSessionRetryDetail: "同じ接続をもう一度試します。すでに一度失敗しています。",
      freshSession: "新しいセッションを開始",
      freshSessionDetail: "同じ Agent で新しいセッションを開始し、この Chat に保存された会話を引き継ぎます。最近の履歴が含まれ、Chat 履歴へのアクセスが有効なら、以前のメッセージも参照できます。",
      freshSessionBlocked: "現在、新しいセッションを開始できません。",
      abandon: "このターンを破棄",
      abandonDetail: "送信せずにこのターンを終了します。メッセージはこのチャットに残ります。",
      actionFailed: "実行できませんでした: {{message}}",
      pendingTitle: "このターンは復旧待ちです",
      pendingDetail: "次のメッセージを送る前に、このターンを復旧するか中止してください。閲覧は続けられます。",
      review: "復旧方法を確認",
      later: "後で対応",
    },
  userInput: {
    countdown: "残り {{count}} 秒",
    skip: "スキップ",
    progress: "{{total}} 件中 {{current}} 件目",
    skipQuestion: "質問をスキップ",
    pendingList: "待機中の同時質問",
    pending: "待機中",
    pendingCount: "{{count}} 件待機中",
    mainAgent: "メイン Agent",
    waiting: "入力待ち",
    other: "該当なし。別の方法を Agent に伝える",
    confirm: "選択を確定",
    decisionPlaceholder: "判断を Agent に伝える…",
    send: "送信",
  },
  approval: {
    requestChanges: "変更を依頼",
    decline: "拒否",
    allowSession: "このセッションで許可",
    approvePlan: "Plan を承認",
    allowOnce: "今回のみ許可",
    planTitle: "この Plan で続行しますか？",
    commandTitle: "このコマンドを許可しますか？",
    fileChangeTitle: "このファイル変更を許可しますか？",
    permissionTitle: "追加アクセスを許可しますか？",
    location: "場所",
    network: "ネットワーク",
    plan: "Plan",
    details: "詳細",
  },
  "permission": {
    "trigger": "現在の操作権限：{{mode}}",
    "heading": "{{backend}} の操作をどう承認しますか？",
    "learnMore": "詳細",
    "selected": "選択中",
    "mode": {
      "ask-for-approval": {
        "label": "毎回確認する",
        "description": "承認が必要な操作は実行前に確認します"
      },
      "approve-for-me": {
        "label": "任せて承認",
        "description": "安全な操作は自動承認し、機微な要求は確認します"
      },
      "full-access": {
        "label": "フルアクセス",
        "description": "インターネットとこのコンピューター上のあらゆるファイルへ無制限にアクセス"
      }
    },
    "fullAccess": {
      "title": "フルアクセスを有効にしますか？",
      "description": "Agent はあなたの許可なしにコマンドを実行し、インターネットを利用し、このチャットの外でファイルを作成・編集できるようになります。AI Chat の制御データは保護されますが、その他のファイルは保護されません。これには次が含まれます（これらに限りません）：",
      "files": {
        "title": "ファイルとフォルダー",
        "description": "このコンピューター上のどこにあるファイルでも読み取り・作成・変更・アップロード・削除"
      },
      "terminal": {
        "title": "ターミナルコマンド",
        "description": "コマンドの実行、ソフトウェアのインストール、システム設定の変更"
      },
      "internet": {
        "title": "インターネットと連携アプリ",
        "description": "ウェブサイトへのアクセス、データ送信、有効なプラグインの利用"
      },
      "risk": "機微なデータの流出や消失、プロンプトインジェクションなどのリスクがあります。いつでもオフにできます。",
      "confirm": "確認",
      "confirming": "確認中…",
      "failed": "フルアクセスを有効にできませんでした：{{reason}}"
    }
  },
  "common": {
    "cancel": "キャンセル",
    "close": "閉じる"
  },
  "sketch": {
    "title": "スケッチ",
    "description": "メッセージに添える画像を描きます。",
    "done": "完了",
    "processing": "スケッチを処理中",
    "discardTitle": "変更を破棄しますか？",
    "discardDescription": "変更は保存されません。",
    "continueEditing": "編集を続ける",
    "discardChanges": "変更を破棄",
    "edit": "クリックしてスケッチを編集",
    "select": "選択",
    "pen": "ペン",
    "text": "テキスト",
    "shapeTool": "図形",
    "eraser": "消しゴム",
    "undo": "元に戻す",
    "redo": "やり直す",
    "canvas": "スケッチキャンバス",
    "canvasHelp": "描画または選択。矢印で移動、Deleteで削除、CommandまたはControl Zで元に戻します。",
    "penWidth": "ペンの太さ",
    "eraserWidth": "消しゴムの直径",
    "color": "色 {{value}}",
    "customColor": "カスタムカラー",
    "sampleColor": "キャンバスから色を選択",
    "red": "赤",
    "green": "緑",
    "blue": "青",
    "textInput": "スケッチのテキスト",
    "busyErasing": "消去を完了しています…",
    "historyTrimmed": "古い取り消し履歴を削除しました。",
    "error": "操作を完了できませんでした。再試行してください。",
    "empty": "先に内容を追加してください。",
    "sourceMissing": "編集用データがありません。元のスケッチを保持しています。",
    "ownerExpired": "このチャットは利用できません。",
    "readOnly": "このチャットは現在編集できません。",
    "versionChanged": "添付が変更されました。閉じて最新の版を開いてください。",
    "migrationActive": "ウィンドウの移動後に再試行してください。",
    "editorActive": "先にスケッチを完了するか閉じてください。",
    "attachmentLimit": "直接添付できるファイルは8個までです。",
    "imageTooLarge": "PNGが8 MiBを超えています。内容を減らしてください。",
    "budget": "編集の上限を超えました。作品は保持されています。",
    "resizeBudget": "拡大が編集の上限を超えています。サイズを小さくしてください。",
    "eraseBudget": "消去の処理上限を超えました。消去前の内容を保持しました。図形や内容を減らしてください。",
    "exportFailed": "PNGを作成できませんでした。スケッチは保持されています。再試行してください。",
    "workerFailed": "消去できませんでした。スケッチは変更されていません。再試行してください。",
    "textOverflow": "文字がキャンバス外です。短くするか、編集をキャンセルして移動・縮小してください。",
    "handle": "{{direction}}をサイズ変更",
    "shape": {
      "line": "直線",
      "arrow": "矢印",
      "rectangle": "長方形",
      "circle": "円",
      "triangle": "三角形",
      "diamond": "ひし形",
      "star": "星",
      "heart": "ハート"
    }
  },
  "chat": {
    "composer": {
  queue: {
    pickedUp: "キューのメッセージを選択しました。上下矢印キーで移動できます。",
    reorderCancelled: "並べ替えをキャンセルしました",
    moved: "{{position}} 番目に移動しました",
    unchanged: "位置は変わりませんでした",
    paused: "キューは一時停止中です",
    resume: "送信を再開",
    dismissError: "キューのエラーを閉じる",
    drag: "{{count}} 件中 {{position}} 件目を移動",
    resend: "このメッセージを再送信",
    deleteAmbiguous: "この不確定なメッセージを削除",
    steer: "実行中のタスクで次に送信",
    delete: "このキュー済みメッセージを削除",
    edit: "このキュー済みメッセージを編集",
  },

      "surface": {
        "plan": "Plan"
      },
      "plan": {
        "closeChip": "Plan をオフにする",
        "decisionTitle": "この Plan を実行しますか？",
        "closeDecision": "Plan の判断を閉じる",
        "implement": "はい、この Plan を実行する",
        "reviseLabel": "Plan の修正方法を Agent に伝える",
        "revisePlaceholder": "実行せず、Agent に修正内容を伝える",
        "send": "送信",
        "skip": "スキップ"
      },
      "add": "追加",
      "files": "ファイル",
      "disablePlan": "Plan をオフ",
      "modelSelector": {
        currentModel: "現在のモデル {{model}}、Effort {{effort}}",
        selector: "チャットモデルセレクター",
        advanced: "詳細",
        model: "モデル",
        effort: "Effort",
        speed: "速度",
        disableFast: "Fast 速度を無効にする",
        enableFast: "Fast 速度を有効にする",
        quickTier: "クイックモデル段階",
        loadingModels: "モデルカタログを読み込み中…",
        retryModels: "モデルカタログを再試行",
        resetDefault: "既定値に戻す",
        onlyOneModel: "利用可能なモデルは 1 つだけです",
        effortUnavailable: "現在のモデルでは Effort を変更できません",
        noModels: "利用可能なモデルが見つかりません",
        backendDefaultModel: "バックエンドの既定モデル",
        speedDescription:
          "対応する Opus 5/4.8 モデルでは約 2.5 倍高速です。usage credits の消費は増えますが、サブスクリプションのレート制限枠は消費しません。",
        speedReason: {
          modelUnsupported: "現在のモデルは Fast を提供していません",
          backendOff: "バックエンドがこのセッションで Fast を無効にしました",
          backendOn: "バックエンドがこのセッションで Fast を有効にしました",
        },
      }
    }
  }
};
