/**
 * [INPUT]: Shared composer and Sketch presentation keys.
 * [OUTPUT]: ZhCN locale catalog for common input controls.
 * [POS]: Browser-safe presentation authority shared with native controls.
 */
export const copy = {
  chatRevision: {
  notIdle: "聊天正在进行或还有排队消息，等它安静下来再发送修订。",
  stale: "会话已前进，这条消息不再是最后一条；请对最新一条消息重新发起编辑。",
  edit: "编辑消息",
  cancel: "取消",
  send: "发送修订",
  editing: "编辑最后一条消息",
  unavailable: {
    busy: "当前轮次结束后才能编辑。",
    queued: "请先处理完排队消息再编辑。",
    "imported-prefix": "导入的历史消息不能编辑。",
  },
},
    newTask: "新任务",
    fork: {
      action: "从这里 Fork",
      title: "从这里 Fork Chat",
      description: "从这条回复开始，为《{{title}}》创建独立续篇。",
      sameWorkspace: "在当前工作区 Fork",
      sameWorkspaceDetail: "从这条消息开始，在当前工作区 Fork。",
      newWorktree: "在新 worktree 中 Fork",
      newWorktreeDetail: "从这条消息开始，在新 worktree 中 Fork。",
      dirtyWarning: "源工作区的 staged、unstaged、untracked 与 ignored 改动不会被复制。",
      unsupported: "受管 worktree 仅支持 macOS 上符合条件的 Git Project。",
      unavailable: "无法从这条回复 Fork",
      continuedFrom: "⑂ 续自上游 Chat",
      openSource: "打开来源 Chat {{title}}",
      originalUnavailable: "原 Chat 不可用",
      inheritedReadOnly: "继承消息不可编辑",
      recoveryTruncated: "继承历史超过上下文预算，Agent 本轮只收到最新的一段。",
      worktreePermission: "受管 worktree 不提供 Full Access",
      errors: {
        pointInvalid: "这条回复已不能作为 Fork 点。请刷新 Chat 后重试。",
        sourceStale: "Chat 在本视图加载后发生了变化。请刷新后重试。",
        sourceUnsupported: "这条 Chat 不支持 Fork。",
        prefixTooLarge: "截至这条回复的历史过大，无法 Fork。请选择更早的回复。",
        projectUnavailable: "Project 不可用、正在改绑或正在删除。",
        requestConflict: "另一个 Fork 请求已占用此身份。请关闭弹窗后重试。",
        recoveryRequired: "此 Fork 需要先完成恢复才能继续。",
        notRepository: "Project 文件夹不是 Git 仓库。",
        notGitRoot: "Project 文件夹不是其 Git 仓库的根目录。",
        noHead: "仓库尚无任何 commit。请先创建一个 commit。",
        bareRepository: "bare 仓库无法承载受管 worktree。",
        operationInProgress: "请先完成或终止进行中的 Git 操作（merge、rebase、cherry-pick、revert 或 bisect）。",
        submodule: "暂不支持含 submodule 的仓库。",
        treeTooLarge: "仓库文件树过大，无法为受管 worktree 完成校验。",
        configUnsafe: "仓库的 Git 配置会执行外部程序（filter、fsmonitor 或 alternate refs）。请先停用它们。",
        branchConflict: "Fork 分支已存在，需要先恢复。",
        pathConflict: "worktree 路径或注册已存在，需要先恢复。",
        identityDrift: "Fork 过程中仓库身份发生了变化。请重试。",
      },
    } ,
  resumeFailure: {
      title: "{{backend}} 打不开这个 Chat 保存的会话",
      description: "你的消息和附件都已保存，也还没有发送出去。",
      retriedTitle: "重试原来的会话失败了",
      retriedDescription: "{{backend}} 仍然无法打开已保存的会话。你的消息和附件仍已保存，尚未发送。",
      recommended: "推荐",
      sameSession: "重试原来的会话",
      sameSessionDetail: "再连一次原来的会话。成功后 Agent 保留这个 Chat 的全部上下文。",
      sameSessionRetry: "再重试一次",
      sameSessionRetryDetail: "再试着连一次原来的会话。刚才已经失败过一次。",
      freshSession: "开启新会话",
      freshSessionDetail: "用同一个 Agent 开启新会话，并接续这个 Chat 已保存的对话。会带上近期历史；启用 Chat 历史访问后，Agent 还可以查阅更早的消息。",
      freshSessionBlocked: "当前暂时无法开启新会话。",
      abandon: "放弃这一轮",
      abandonDetail: "这次不发送，本轮到此结束。消息仍留在这个 Chat 里。",
      actionFailed: "操作没有成功：{{message}}",
      pendingTitle: "这一轮等待恢复",
      pendingDetail: "恢复或放弃这一轮后，才能发送新消息。你可以继续浏览。",
      review: "查看恢复选项",
      later: "稍后处理",
    },
  userInput: {
    countdown: "{{count}} 秒",
    skip: "跳过",
    progress: "第 {{current}} 个，共 {{total}} 个",
    skipQuestion: "跳过问题",
    pendingList: "等待中的并发提问",
    pending: "等待中",
    pendingCount: "{{count}} 个待回答",
    mainAgent: "主 Agent",
    waiting: "等待输入",
    other: "都不合适，告诉 Agent 其它做法",
    confirm: "确认选择",
    decisionPlaceholder: "告诉 Agent 你的决定…",
    send: "发送",
  },
  approval: {
    requestChanges: "要求修改",
    decline: "拒绝",
    allowSession: "本会话允许",
    approvePlan: "批准 Plan",
    allowOnce: "允许一次",
    planTitle: "按这份 Plan 继续吗？",
    commandTitle: "允许运行这条命令吗？",
    fileChangeTitle: "允许这些文件修改吗？",
    permissionTitle: "允许额外访问权限吗？",
    location: "位置",
    network: "网络",
    plan: "Plan",
    details: "详情",
  },
  "permission": {
    "trigger": "当前操作权限：{{mode}}",
    "heading": "{{backend}} 的操作如何批准？",
    "learnMore": "了解更多",
    "selected": "已选择",
    "mode": {
      "ask-for-approval": {
        "label": "逐项询问",
        "description": "需要你批准的操作，执行前先询问"
      },
      "approve-for-me": {
        "label": "代我批准",
        "description": "安全操作自动批准；敏感请求仍会询问"
      },
      "full-access": {
        "label": "完全访问",
        "description": "不受限制地访问互联网与这台电脑上的任何文件"
      }
    },
    "fullAccess": {
      "title": "开启完全访问？",
      "description": "Agent 将无需你的许可即可执行命令、访问互联网，并在本次聊天之外创建和修改文件。AI Chat 的控制数据仍受保护，你的其他文件不受保护。这包括但不限于：",
      "files": {
        "title": "文件与文件夹",
        "description": "读取、创建、修改、上传或删除这台电脑上任意位置的文件"
      },
      "terminal": {
        "title": "终端命令",
        "description": "执行命令、安装软件并更改系统设置"
      },
      "internet": {
        "title": "互联网与已连接的应用",
        "description": "访问网站、发送数据并使用已启用的插件"
      },
      "risk": "这会带来敏感数据泄露或丢失、提示注入等风险。你可以随时关闭它。",
      "confirm": "确认",
      "confirming": "确认中…",
      "failed": "无法开启完全访问：{{reason}}"
    }
  },
  "common": {
    "cancel": "取消",
    "close": "关闭"
  },
  "sketch": {
    "title": "草图",
    "description": "为消息绘制一张图片。",
    "done": "完成草图",
    "processing": "正在处理草图",
    "discardTitle": "放弃更改？",
    "discardDescription": "你的更改将不会保存。",
    "continueEditing": "继续编辑",
    "discardChanges": "放弃更改",
    "edit": "点击编辑草图",
    "select": "选择",
    "pen": "画笔",
    "text": "文本",
    "shapeTool": "图形",
    "eraser": "橡皮擦",
    "undo": "撤销",
    "redo": "重做",
    "canvas": "草图画布",
    "canvasHelp": "绘制或选择元素。方向键移动，Delete 删除，Command 或 Control Z 撤销。",
    "penWidth": "画笔粗细",
    "eraserWidth": "橡皮擦直径",
    "color": "颜色 {{value}}",
    "customColor": "自定义颜色",
    "sampleColor": "从画布取色",
    "red": "红色",
    "green": "绿色",
    "blue": "蓝色",
    "textInput": "草图文本",
    "busyErasing": "正在完成擦除…",
    "historyTrimmed": "较早的撤销记录已清理。",
    "error": "未能完成操作，请重试。",
    "empty": "请先在草图中添加内容。",
    "sourceMissing": "找不到可编辑源数据，已保留原草图。",
    "ownerExpired": "这个聊天已不可用。",
    "readOnly": "这个聊天目前无法编辑。",
    "versionChanged": "附件已发生变化，请关闭编辑器并打开最新版本。",
    "migrationActive": "请等待窗口迁移完成后重试。",
    "editorActive": "先完成或关闭草图。",
    "attachmentLimit": "每条消息最多添加 8 个直接附件。",
    "imageTooLarge": "PNG 超过 8 MiB，请减少草图内容后重试。",
    "budget": "这次操作超过可编辑预算，已保留原作品。",
    "resizeBudget": "这次放大超过可编辑预算，请减小尺寸后重试。",
    "eraseBudget": "本次擦除超出处理上限，已保留擦除前内容。请缩小图形或减少画布内容后重试。",
    "exportFailed": "未能生成 PNG，草图内容已保留，请重试。",
    "workerFailed": "未能完成擦除，已保留原草图，请重试。",
    "textOverflow": "文字超出画布，请缩短内容，或取消本次编辑后移动、缩小文字。",
    "handle": "调整{{direction}}",
    "shape": {
      "line": "直线",
      "arrow": "箭头",
      "rectangle": "矩形",
      "circle": "圆形",
      "triangle": "三角形",
      "diamond": "菱形",
      "star": "五角星",
      "heart": "心形"
    }
  },
  "chat": {
    "composer": {
  queue: {
    pickedUp: "已拾起排队消息；使用上下方向键调整位置。",
    reorderCancelled: "已取消重排",
    moved: "已移动到第 {{position}} 条",
    unchanged: "位置未改变",
    paused: "队列已暂停",
    resume: "继续发送",
    dismissError: "关闭队列错误",
    drag: "拖动第 {{position}} 条，共 {{count}} 条",
    resend: "重发这条消息",
    deleteAmbiguous: "删除这条歧义消息",
    steer: "立即插入当前运行任务",
    delete: "删除这条排队消息",
    edit: "编辑这条排队消息",
  },

      "surface": {
        "plan": "Plan"
      },
      "plan": {
        "closeChip": "关闭 Plan",
        "decisionTitle": "要执行这份 Plan 吗？",
        "closeDecision": "关闭 Plan 决策",
        "implement": "是，执行这份 Plan",
        "reviseLabel": "告诉 Agent 如何调整 Plan",
        "revisePlaceholder": "不执行，并告诉 Agent 应如何调整",
        "send": "发送",
        "skip": "跳过"
      },
      "add": "添加",
      "files": "文件",
      "disablePlan": "关闭 Plan",
      "modelSelector": {
        currentModel: "当前模型 {{model}}，Effort {{effort}}",
        selector: "聊天模型选择器",
        advanced: "高级",
        model: "模型",
        effort: "Effort",
        speed: "速度",
        disableFast: "关闭 Fast 速度",
        enableFast: "开启 Fast 速度",
        quickTier: "快速模型档位",
        loadingModels: "正在读取模型目录…",
        retryModels: "重试模型目录",
        resetDefault: "恢复默认设置",
        onlyOneModel: "当前只有一个可用模型",
        effortUnavailable: "当前模型不支持调整 Effort",
        noModels: "未发现可用模型",
        backendDefaultModel: "后端默认模型",
        speedDescription:
          "在支持的 Opus 5/4.8 模型上约快 2.5 倍。会消耗更多 usage credits，但不计入订阅速率限制池。",
        speedReason: {
          modelUnsupported: "当前模型不提供 Fast",
          backendOff: "后端在本会话中关闭了 Fast",
          backendOn: "后端在本会话中开启了 Fast",
        },
      }
    }
  }
};
