/**
 * [INPUT]: Depends on the shared cloud account and approval copy structure.
 * [OUTPUT]: Provides localized account, Sync settings navigation, sync, installation/removal/deletion consent, retained-file and credential recovery, browser-first sign-in, manual-link fallback, approval, footer language copy, the Web gate's verifying/revoked/restricted next steps and its slow-open loading sentence.
 * [POS]: Shared UI copy consumed by desktop and Cloud Web without platform dependencies.
 */
export const cloudCopy = {
  "appDeletion": {
    "expired": "This review expired before a deletion request was saved. Review the current App before confirming again.",
    "sourceDeleted": "The source App has been deleted. This conversation is retained for reading.",
    "action": "Delete from all devices",
    "title": "Delete {{name}} everywhere?",
    "details": "This removes the App from your cloud account and every synced device. Saved conversations remain read-only. This cannot be undone.",
    "dataChoice": "App data",
    "keepData": "Keep Base data",
    "keepDetails": "Keep the Base as a separate, editable data source.",
    "deleteData": "Delete Base data too",
    "deleteDetails": "Permanently delete the Base records, images and related cloud files.",
    "localFiles": "Unpublished source and other local files stay on their original computer.",
    "offline": "Connect and resume sync to review or send this request.",
    "reviewing": "Checking the current App…",
    "unknown": "The result is not confirmed. Retry to check the original request; your data choice stays the same.",
    "conflicted": "The App changed after your review. Review its current version before deciding again.",
    "blocked": "This request could not delete the App. Review its current state before deciding again.",
    "failed": "The App could not be reviewed. Try again when connected.",
    "confirmed": "Deletion confirmed. Synced devices will finish applying it when they reconnect.",
    "close": "Close",
    "review": "Review current App",
    "retry": "Check original request",
    "deleting": "Deleting…",
    "confirm": "Delete from all devices",
    "pending": "Deletion needs confirmation",
    "keep": "Keep App",
    "retainedBase": "Open retained Base"
  },
  "appRemoval": {
    "manage": "Manage cloud App",
    "title": "Remove {{name}} from this computer?",
    "details": "The cloud App and its Base stay available. Conversations are retained without execution access. Unpublished source, local files and configuration stay on this computer; Agent access to configuration is cleared.",
    "confirm": "Remove installation",
    "remove": "Remove from this computer",
    "removing": "Removing installation…",
    "failed": "Removal could not finish. Retry the same request, or continue it from the App list.",
    "pending": "Local removal needs attention",
    "resume": "Continue removal",
    "retained": "Open retained files"
  },
  "appInstall": {
    "title": "Your cloud Apps",
    "installTitle": "Install {{name}}",
    "updateTitle": "Update {{name}}",
    "consent": "Review this version and approve its access on this computer. Configuration and permissions stay on this computer.",
    "preparing": "Downloading and checking this version…",
    "failed": "The request could not finish. Refresh to review its current state; an admitted installation can be resumed from the list.",
    "refresh": "Refresh",
    "source": "Your cloud account",
    "configuration": "Configuration on this computer",
    "agent": "Maintenance Agent",
    "noAgent": "Set up a compatible Agent before installing.",
    "confirmInstall": "Approve and install",
    "confirmUpdate": "Approve and update",
    "installing": "Installing…",
    "loading": "Loading cloud Apps…",
    "online": "Resume online sync to install or update. Downloaded Base data remains available.",
    "version": "Version {{version}}",
    "notInstalled": "Not installed here",
    "installed": "Installed here",
    "updateAvailable": "Update available",
    "interrupted": "Installation needs attention",
    "deleted": "Deleted",
    "resume": "Continue installation",
    "install": "Install",
    "update": "Update",
    "basePending": "Waiting for the complete Base data before installation."
  },
  "syncReview": {
    "switchAccount": "Confirm account switch",
    "switchTitle": "Switch accounts on this computer",
    "switchBody": "Your cloud data stays with the previous account. After switching, enable sync again for this account.",
    "pause": "Pause",
    "resume": "Resume",
    "disable": "Disable",
    "disableTitle": "Disable sync on this computer?",
    "disableBody": "Cloud copies that only exist as mirrors here will be removed. Everything created or continued on this computer stays, with its files. You’ll need your sync password to enable sync again.",
    "disableRemove": "Remove {{mirrors}} chat mirrors, {{mirroredBases}} Base mirrors, {{mirroredProjects}} Project mirrors and {{mirroredApps}} App mirrors.",
    "disableKeep": "Keep {{retainedChats}} chats, {{retainedHomes}} Home folders, {{retainedBases}} Bases, {{retainedProjects}} Projects and {{retainedApps}} Apps.",
    "disableConfirm": "Disable sync",
    "pendingDiscard": "{{count}} pending changes will be kept locally and disconnected from this account.",
    "progress": "{{completed}} of {{total}} items",
    "pending": "{{count}} changes waiting",
    "conflicts": "{{count}} conflicts need attention"
  },
  "syncStatus": {
    "partial": "Base data is up to date; some App packages need attention",
    "not-connected": "Sync has not been enabled.",
    "scanning": "Scanning local content…",
    "initializing": "Preparing your first sync…",
    "syncing": "Syncing…",
    "synced": "Up to date",
    "paused": "Sync is paused",
    "offline": "Waiting for your connection",
    "error": "Sync needs attention",
    "closing": "Disconnecting this account…"
  },
  "syncError": {
    "scan-failed": "Local content could not be inspected. Retry after any active import finishes.",
    "review-expired": "This review has expired. Scan again before confirming.",
    "upload-failed": "Some content has not synced. Your local copy is kept; retry to continue.",
    "cleanup-failed": "Disconnecting this account could not finish. Local content is kept; retry to continue."
  },
  "syncAppBlocked": {
    "migration-blocked": "This version needs an unsupported data migration. The previous cloud version is kept.",
    "version-conflict": "A different App version was published. Review the versions before retrying.",
    "not-published": "No published version",
    "package-too-large": "Package exceeds the 50 MB limit",
    "source-unavailable": "Published source could not be verified",
    "generation-changed": "Published version changed during review",
    "association-unavailable": "App data association needs recovery"
  },
  "setup": {
    "signIn": "Sign in",
    "enable": "Enable sync",
    "signInTitle": "Sign in to sync this computer",
    "browserApproval": "You’ll approve the sign-in in your browser.",
    "signedInAs": "You are signed in as {{email}}.",
    "checkCode": "Check that it matches the code in your browser before you allow sign-in.",
    "enterPassword": "Enter your sync password",
    "enterPasswordDescription": "This computer joins the encrypted workspace you set up on another device. Bottega cannot recover the password.",
    "unlockedDescription": "This computer is already unlocked. Enable sync to start uploading its content."
  },
  "syncBadge": {
    "synced": "Up to date",
    "syncing": "Syncing",
    "paused": "Paused",
    "offline": "Waiting for connection",
    "attention": "Needs attention",
    "locked": "Locked",
    "checking": "Checking",
    "closing": "Disconnecting",
    "unavailable": "Unavailable"
  },
  "syncRow": {
    "synced": "All local changes are in your cloud account, end-to-end encrypted with your sync password.",
    "locked": "Enter your sync password to resume sync on this computer."
  },
  "syncPhase": {
    "projects": "Uploading Projects",
    "apps": "Uploading Apps",
    "chats": "Uploading chats",
    "bases": "Uploading Bases",
    "files": "Uploading files",
    "homes": "Uploading Chat Home"
  },
  "appPackages": {
    "title": "App packages",
    "description": "Base data for these Apps is synced. Their packages need attention before the App can be restored on another computer.",
    "open": "Open App"
  },
  "platform": {
    "macos": "macOS",
    "windows": "Windows",
    "linux": "Linux",
    "browser": "Browser"
  },
  "apps": {
    "title": "Apps",
    "capabilities": "App GUI · Memory · Tools",
    "description": "Read and edit synced App records. Custom App interfaces run on your computer.",
    "empty": "No synced Apps on this page.",
    "version": "Version",
    "packageReady": "Source package ready",
    "packagePending": "Waiting for the source computer to upload this version.",
    "partial": "Some data is only available on the original computer.",
    "baseOnly": "Base records are included in sync.",
    "structure": "App structure is maintained by version updates. Records and view settings can be edited here.",
    "unavailable": "This App was deleted or is unavailable.",
    "back": "Back to Apps",
    "backToApp": "Back to App"
  },
  "catalog": {
    "titleColumn": "Title",
    "tableView": "Table",
    "noProjects": "No Projects on this page.",
    "projects": "Projects",
    "bases": "Bases",
    "noBases": "No synced Bases on this page.",


    "openBase": "Open Base",
    "loading": "Loading workspace…",
    "readLimit": "This Base exceeds the browser's read budget. The last complete view is kept; editing is paused.",
    "historyUnavailable": "Cloud record history is not available yet.",
    "original": "Original value",
    "source": "Source device",
    "readUpdating": "This Base is changing. Waiting for a complete update…",
    "readError": "Records could not be loaded. Your draft is kept."
  },
  "recovery": {
    "retrying": "Some content couldn’t load. Retrying in {{seconds}} s…",
    "stalled": "Still can’t reach Bottega Cloud.",
    "retryNow": "Retry now",
    "reload": "Reload page",
    "unavailable": "This item is not available."
  },
  "base": {
    "verification": "Base verification",
    "verificationDescription": "This page checks sync transactions. The full Base workspace is still being developed.",
    "empty": "No records are available.",
    "draft": "Draft",
    "saved": "Saved",
    "partial": "Some changes need attention",
    "outcomeUnknown": "Checking the save result…",
    "updating": "Updating confirmed data…",
    "offline": "Changes waiting for your connection",
    "conflicts": "Conflicts",
    "noConflicts": "No unresolved conflicts.",
    "current": "Current value",
    "candidate": "Your candidate",
    "reviewCurrent": "Review latest values",
    "reviewChanged": "Values changed again. Review the comparison before applying your candidate.",
    "apply": "Apply candidate",
    "discard": "Discard candidate",
    "more": "Load more",

    "unavailable": "The Base is unavailable or has been deleted.",
    "notInitialized": "The verification Base has not been initialized."
  },
  "workspace": "Workspace",
  "navigation": "Main navigation",
  "notFound": "Page not found",
  "cloudDevLogin": "Sign in to Bottega Cloud Dev",
  "cloudLogin": "Sign in to Bottega",
  "verificationCodeNote": "The code identifies the request; it is not a login credential.",
  "deletingDescription": "Cloud access is paused while your account is being removed.",
  "verifyingDescription": "Verifying your sign-in.",
  "revokedDescription": "Sign out and sign in again to continue.",
  "restrictedCloudDescription": "Cloud access for this account is restricted.",
  "title": "Account",
  "syncUnavailable": "Sync is temporarily unavailable. You can keep working locally.",
  "syncSettings": "Sync settings",
  "google": "Continue with Google",
  "signOut": "Sign out",
  "cancel": "Cancel",
  "retry": "Retry",
  "retrying": "Retrying…",
  "save": "Save",
  "saving": "Saving…",
  "rename": "Rename",
  "deviceName": "Device name",
  "revoke": "Revoke",
  "revoking": "Revoking…",
  "revokeTitle": "Revoke this session?",
  "revokeDescription": "This device will lose access to your cloud account. Content already downloaded stays on the device.",
  "localDescription": "Use Bottega locally for free. Signing in does not upload content until you confirm your first sync.",
  "sync": "Sync",
  "syncNotConnected": "Sync has not been enabled.",


  "devices": "Devices",
  "lastSeen": "Last seen {{when}}",
  "webSession": "Web session",
  "appVersion": "Bottega {{version}}",
  "noDevices": "No sessions on this page.",
  "current": "This device",
  "online": "Online",
  "offline": "Offline",
  "revoked": "Revoked",
  "nextPage": "Next sessions",
  "firstPage": "First page",
  "refresh": "Refresh",
  "showPastSessions": "Show past sessions",
  "loadFailed": "Could not load sessions. Please retry.",
  "actionFailed": "The change could not be saved. Check your connection and try again.",
  "secureStorageDescription": "macOS may request Keychain access to protect your sign-in on this computer.",
  "secureStorageRestart": "Restart Bottega, then sign in again.",
  "retrySecureSave": "Retry secure save",
  "discardSavedLogin": "Discard saved sign-in…",
  "discardSavedLoginTitle": "Discard the sign-in saved on this device?",
  "discardSavedLoginDescription": "This deletes the sign-in saved on this device. You will need to sign in again. Local content is kept. Cloud sessions may remain valid until they expire or are revoked, and device records may remain. If sign-in is blocked, revoke this device’s old session in your web account.",
  "discardSavedLoginConfirm": "Discard sign-in",
  "discardSavedLoginFailed": "Could not confirm that the saved sign-in was removed. Try again before starting a new sign-in.",
  "discardSavedLoginExpired": "This confirmation expired or the saved sign-in changed. Review the details again before confirming.",
  "retryCredentialStorage": "Retry secure storage access",
  "openCloudAccount": "Open web account",
  "cancelUnconfirmed": "Cancellation is not confirmed. Bottega will retry when connected. Keep Bottega running for now.",
  "abandonLogin": "Abandon sign-in and start over",
  "abandonLoginNote": "The pending request may stay valid on the server until it expires or you revoke it in your web account.",
  "openBrowser": "Reopen browser",
  "loginLinkLabel": "Sign-in link",
  "loginLinkDescription": "Browser didn’t open? Copy this link and paste it into your browser.",
  "copyLoginLink": "Copy sign-in link",
  "loginLinkCopied": "Link copied",
  "loginLinkCopyFailed": "Couldn’t copy the link. Select it and copy it manually.",
  "verificationCode": "Verification code",
  "expires": "This request expires after five minutes.",
  "loginTitle": "Welcome to Bottega",
  "loginDescription": "Sign in to access your synced workspace.",
  "account": "Account",
  "back": "Back to workspace",
  "moreActions": "More actions",
  "close": "Close",
  "download": "Download Bottega",
  "footer": {
    "copyright": "Bottega © 2026. All rights reserved.",
    "language": "Language",
    "languageError": "Could not change the language. Please try again.",
    "navigation": "Footer navigation",
    "changelog": "Changelog",
    "docs": "Docs",
    "github": "GitHub",
    "issues": "Issues",
    "download": "Download"
  },
  "allow": "I checked the desktop app. Allow sign-in",
  "reject": "I did not request this",
  "openDesktop": "Open Bottega",
  "approvedTitle": "Request approved",
  "approvedPollingOnly": "Return to the Bottega development window to finish signing in.",
  "loginVersionUnsupported": "This cloud service does not support this sign-in version. Update the service and try again.",
  "approved": "Return to Bottega to finish signing in.",
  "rejected": "This request has been cancelled",
  "expired": "This sign-in request has expired",
  "invalidRequest": "This sign-in request is unavailable",
  "startAgain": "Start again in Bottega.",
  "approvalDescription": "Only allow this request if you started it in Bottega on this computer. Check that the verification code matches the desktop window.",
  "approvalFailed": "The request could not be updated. Please retry.",
  "loading": {
    "slow": "Still opening your workspace. Slow connections can take a moment."
  },
  "status": {
    "deleted": "Your cloud account has been deleted",
    "account-switch-required": "Confirm the account switch to continue",
    "local-only": "Local only",
    "signed-out": "Signed out",
    "signing-in": "Signing in…",
    "signing-out": "Finishing sign-out…",
    "connecting": "Connecting…",
    "ready": "Signed in",
    "temporarily-offline": "Temporarily offline",
    "revoked": "This session was revoked",
    "suspended": "Your account is restricted",
    "deleting": "Your account is being deleted",
    "environment-mismatch": "The cloud environment does not match this app",
    "client-outdated": "Update Bottega to continue",
    "error": "Action needed"
  },
  "error": {
    "installation-already-active": "This device still has an active session. Revoke its old session in your web account so Bottega can finish this sign-in.",
    "session-already-bound": "This browser is already signed in with a different device record. Sign out and sign in again to continue.",
    "device-name-unavailable": "Too many browser sessions are registered for this account. Remove old web sessions in your account page, then sign in again.",
    "credentials-environment-mismatch": "Saved sign-in data belongs to another cloud environment. Use the matching environment or discard it and sign in again.",
    "credentials-unreadable": "Saved sign-in data could not be unlocked. The file is kept. Restore secure storage and try again, or discard the saved sign-in.",
    "secure-save-failed": "Could not securely save your sign-in. Retry secure save or cancel sign-in.",
    "browser-open-failed": "Could not open your browser. Copy the sign-in link below or try reopening it.",
    "encryption-unavailable": "Secure storage is unavailable. Check your system keychain and restart Bottega before trying again. You can keep using Bottega locally.",
    "credentials-invalid": "The saved sign-in format is invalid. Continue with Google to reset this sign-in file. Local content will be kept.",
    "connection-failed": "Your connection is unavailable. Your sign-in information is kept while Bottega reconnects.",
    "login-expired": "This sign-in request expired. Please start again.",
    "login-rejected": "This sign-in request was cancelled. Please start again if it was yours.",
    "rate-limited": "Too many sign-in attempts right now. Wait a minute and try again.",
    "sign-out-required": "Finish signing out of the previous session before starting a new sign-in.",
    "server-outdated": "The cloud service needs an update to work with this version of Bottega. Please try again after the service is updated.",
    "request-failed": "The request could not be completed. Please try again.",
    "environment-mismatch": "This build cannot connect to this cloud environment.",
    "client-outdated": "Install a newer Bottega version to connect."
  },
  "pending": {
    "preparing": "Preparing sign-in…",
    "opening": "Opening your browser…",
    "securing": "Securely saving your sign-in…",
    "waiting": "Waiting for your approval in the browser…",
    "exchanging": "Completing sign-in…",
    "confirming": "Confirming secure sign-in…",
    "registering": "Registering this computer…",
    "cancelling": "Cancelling the request…",
    "connection-failed": "Waiting for your connection…"
  }
};
export type CloudCopy = { [K in keyof typeof cloudCopy]: typeof cloudCopy[K] extends string ? string : { [P in keyof typeof cloudCopy[K]]: string } };
