/**
 * [INPUT]: Depends on the shared cloud account and approval copy structure.
 * [OUTPUT]: Provides localized account, Sync settings navigation, sync, installation/removal/deletion consent, retained-file and credential recovery, browser-first sign-in, manual-link fallback, approval, footer language copy and the Web gate's slow-open loading sentence.
 * [POS]: Shared UI copy consumed by desktop and Cloud Web without platform dependencies.
 */
import type { CloudCopy } from "./en";
export const cloudCopy = {
  "appDeletion": {
    "expired": "Esta revisión caducó antes de guardar la solicitud de eliminación. Revisa la App actual antes de confirmar de nuevo.",
    "sourceDeleted": "La App de origen se ha eliminado. Esta conversación se conserva para su lectura.",
    "action": "Eliminar de todos los dispositivos",
    "title": "¿Eliminar {{name}} en todos los dispositivos?",
    "details": "Esta acción elimina la App de tu cuenta en la nube y de todos los dispositivos sincronizados. Las conversaciones guardadas quedan en modo de solo lectura. No se puede deshacer.",
    "dataChoice": "Datos de la App",
    "keepData": "Conservar los datos de Base",
    "keepDetails": "Conserva la Base como una fuente de datos independiente y editable.",
    "deleteData": "Eliminar también los datos de Base",
    "deleteDetails": "Elimina permanentemente los registros, imágenes y archivos en la nube relacionados con la Base.",
    "localFiles": "El código sin publicar y otros archivos locales permanecen en su ordenador original.",
    "offline": "Conéctate y reanuda la sincronización para revisar o enviar esta solicitud.",
    "reviewing": "Comprobando la App actual…",
    "unknown": "El resultado no está confirmado. Reintenta para comprobar la solicitud original; tu elección sobre los datos no cambia.",
    "conflicted": "La App cambió después de revisarla. Revisa su versión actual antes de volver a decidir.",
    "blocked": "Esta solicitud no pudo eliminar la App. Revisa su estado actual antes de volver a decidir.",
    "failed": "No se pudo revisar la App. Vuelve a intentarlo cuando tengas conexión.",
    "confirmed": "Eliminación confirmada. Los dispositivos sincronizados terminarán de aplicarla cuando se reconecten.",
    "close": "Cerrar",
    "review": "Revisar la App actual",
    "retry": "Comprobar la solicitud original",
    "deleting": "Eliminando…",
    "confirm": "Eliminar de todos los dispositivos",
    "pending": "Resultado de eliminación por confirmar",
    "keep": "Conservar App",
    "retainedBase": "Abrir la Base conservada"
  },
  "appRemoval": {
    "manage": "Gestionar App en la nube",
    "title": "¿Quitar {{name}} de este ordenador?",
    "details": "La App en la nube y su Base siguen disponibles. Las conversaciones se conservan sin permiso de ejecución. El código no publicado, los archivos y la configuración permanecen en este equipo; se revoca el acceso del Agent a la configuración.",
    "confirm": "Quitar instalación",
    "remove": "Quitar de este ordenador",
    "removing": "Quitando instalación…",
    "failed": "No se pudo completar la eliminación. Reintenta la misma solicitud o continúala desde la lista de Apps.",
    "pending": "La eliminación local requiere atención",
    "resume": "Continuar eliminación",
    "retained": "Abrir archivos conservados"
  },
  "appInstall": {
    "title": "Tus Apps en la nube",
    "installTitle": "Instalar {{name}}",
    "updateTitle": "Actualizar {{name}}",
    "consent": "Revisa esta versión y autoriza su acceso en este ordenador. La configuración y los permisos se guardan en este ordenador.",
    "preparing": "Descargando y comprobando esta versión…",
    "failed": "No se pudo completar la solicitud. Actualiza la vista para consultar su estado; una instalación iniciada puede continuar desde la lista.",
    "refresh": "Actualizar vista",
    "source": "Tu cuenta en la nube",
    "configuration": "Configuración de este ordenador",
    "agent": "Agent de mantenimiento",
    "noAgent": "Configura un Agent compatible antes de instalar.",
    "confirmInstall": "Autorizar e instalar",
    "confirmUpdate": "Autorizar y actualizar",
    "installing": "Instalando…",
    "loading": "Cargando Apps de la nube…",
    "online": "Reanuda la sincronización en línea para instalar o actualizar. Los datos Base descargados siguen disponibles.",
    "version": "Versión {{version}}",
    "notInstalled": "No instalada aquí",
    "installed": "Instalada aquí",
    "updateAvailable": "Actualización disponible",
    "interrupted": "La instalación requiere atención",
    "deleted": "Eliminada",
    "resume": "Continuar instalación",
    "install": "Instalar",
    "update": "Actualizar",
    "basePending": "Esperando los datos Base completos antes de instalar."
  },
  "syncReview": {
    "switchAccount": "Confirmar cambio de cuenta",
    "switchTitle": "Cambiar de cuenta en este equipo",
    "switchBody": "Los datos de la nube siguen en la cuenta anterior. Tras cambiar, vuelve a activar la sincronización para esta cuenta.",
    "disable": "Desactivar",
    "cloudData": "Datos en la nube",
    "cloudDataDescription": "Desconecta este ordenador y elimina las copias de la nube guardadas aquí. Cerrar sesión no hace ninguna de las dos cosas.",
    "disableTitle": "¿Desactivar la sincronización en este ordenador?",
    "disableBody": "Se eliminarán las copias que solo existen aquí como espejos de la nube. Todo lo creado o continuado en este ordenador se conserva, con sus archivos. Necesitarás tu contraseña de sincronización para volver a activar la sincronización.",
    "disableRemove": "Eliminar {{mirrors}} espejos de chats, {{mirroredBases}} espejos de Bases, {{mirroredProjects}} espejos de Projects y {{mirroredApps}} espejos de Apps.",
    "disableKeep": "Conservar {{retainedChats}} chats, {{retainedHomes}} carpetas Home, {{retainedBases}} Bases, {{retainedProjects}} Projects y {{retainedApps}} Apps.",
    "disableConfirm": "Desactivar sincronización",
    "pendingDiscard": "{{count}} cambios pendientes se conservarán localmente y se desvincularán de esta cuenta.",
    "progress": "{{completed}} de {{total}} elementos",
    "pending": "{{count}} cambios pendientes",
    "conflicts": "{{count}} conflictos requieren atención"
  },
  "syncStatus": {
    "partial": "Los datos de Base están al día; algunos paquetes de Apps necesitan atención",
    "not-connected": "Este ordenador aún no se sincroniza.",
    "scanning": "Analizando contenido local…",
    "initializing": "Preparando la primera sincronización…",
    "syncing": "Sincronizando…",
    "synced": "Todo actualizado",
    "paused": "Sincronización en pausa",
    "offline": "Esperando conexión",
    "error": "La sincronización requiere atención",
    "closing": "Desconectando la cuenta…"
  },
  "syncError": {
    "scan-failed": "No se pudo analizar el contenido local. Reinténtalo cuando termine la importación.",
    "review-expired": "Esta revisión ha caducado. Vuelve a analizar el contenido.",
    "upload-failed": "Parte del contenido no se ha sincronizado. La copia local se conserva; reinténtalo.",
    "cleanup-failed": "No se pudo completar la desconexión de esta cuenta. El contenido local se conserva; reinténtalo para continuar.",
    "library-owned-elsewhere": "Esta carpeta de Bottega pertenece a {{host}}. Esta versión no puede abrirla en otro ordenador: crea una carpeta nueva o úsala en ese ordenador."
  },
  "syncAppBlocked": {
    "migration-blocked": "Esta versión requiere una migración no compatible. Se conserva la versión anterior en la nube.",
    "version-conflict": "Se publicó otra versión de la App. Revisa las versiones antes de reintentar.",
    "not-published": "No hay versión publicada",
    "package-too-large": "El paquete supera 50 MB",
    "source-unavailable": "No se pudo verificar el código publicado",
    "generation-changed": "La versión cambió durante la revisión",
    "association-unavailable": "La asociación de datos App requiere recuperación"
  },
  "setup": {
    "signIn": "Iniciar sesión",
    "enable": "Finalizar el inicio de sesión",
    "signInTitle": "Inicia sesión para sincronizar este ordenador",
    "browserApproval": "Aprobarás el inicio de sesión en tu navegador.",
    "signedInAs": "Has iniciado sesión como {{email}}.",
    "checkCode": "Comprueba que coincide con el código de tu navegador antes de permitir el acceso.",
    "enterPassword": "Introduce tu contraseña de sincronización",
    "enterPasswordDescription": "Este ordenador se une al espacio cifrado que configuraste en otro dispositivo. Bottega no puede recuperar la contraseña.",
    "unlockedDescription": "Este ordenador ya está desbloqueado. Finaliza para empezar a sincronizar."
  },
  "syncBadge": {
    "synced": "Al día",
    "syncing": "Sincronizando",
    "paused": "En pausa",
    "offline": "Esperando conexión",
    "attention": "Requiere atención",
    "locked": "Bloqueada",
    "checking": "Comprobando",
    "closing": "Desconectando",
    "unavailable": "No disponible"
  },
  "syncRow": {
    "synced": "Todos los cambios locales están en tu cuenta en la nube, cifrados de extremo a extremo con tu contraseña de sincronización.",
    "locked": "Introduce tu contraseña de sincronización para reanudar la sincronización en este ordenador."
  },
  "syncPhase": {
    "preparing": "Preparando chats",
    "projects": "Subiendo Projects",
    "apps": "Subiendo Apps",
    "chats": "Subiendo chats",
    "bases": "Subiendo Bases",
    "files": "Subiendo archivos",
    "homes": "Subiendo Chat Home"
  },
  "appPackages": {
    "title": "Paquetes de Apps",
    "description": "Los datos Base de estas Apps están sincronizados. Sus paquetes requieren atención antes de poder restaurar la App en otro ordenador.",
    "open": "Abrir App"
  },
  "platform": {
    "macos": "macOS",
    "windows": "Windows",
    "linux": "Linux",
    "browser": "Navegador"
  },
  "apps": {
    "title": "Apps",
    "capabilities": "Interfaz de la App · Memoria · Herramientas",
    "description": "Consulta y edita los registros sincronizados. Las interfaces propias de las Apps se ejecutan en tu ordenador.",
    "empty": "No hay Apps sincronizadas en esta página.",
    "version": "Versión",
    "packageReady": "Código fuente disponible",
    "packagePending": "Esperando a que el ordenador de origen suba esta versión.",
    "partial": "Algunos datos solo están en el ordenador de origen.",
    "baseOnly": "Los registros de Base se incluyen en la sincronización.",
    "structure": "Las actualizaciones mantienen la estructura. Aquí puedes editar registros y ajustes de vistas.",
    "unavailable": "Esta App se ha eliminado o no está disponible.",
    "back": "Volver a Apps",
    "backToApp": "Volver a la App"
  },
  "catalog": {
    "titleColumn": "Título",
    "tableView": "Tabla",
    "noProjects": "No hay Projects en esta página.",
    "projects": "Proyectos",
    "bases": "Bases",
    "noBases": "No hay Bases sincronizadas en esta página.",


    "openBase": "Abrir Base",
    "loading": "Cargando el espacio de trabajo…",
    "readLimit": "Esta Base supera la capacidad de lectura del navegador. Se conserva la última vista completa y se pausa la edición.",
    "historyUnavailable": "El historial de registros en la nube aún no está disponible.",
    "original": "Valor original",
    "source": "Dispositivo de origen",
    "readUpdating": "Esta Base está cambiando. Esperando una actualización completa…",
    "readError": "No se pudieron cargar los registros. Se conserva tu borrador."
  },
  "recovery": {
    "retrying": "Parte del contenido no se pudo cargar. Reintentando en {{seconds}} s…",
    "stalled": "Todavía no se puede conectar con Bottega Cloud.",
    "retryNow": "Reintentar ahora",
    "reload": "Recargar la página",
    "unavailable": "Este elemento no está disponible."
  },
  "base": {
    "verification": "Verificación de Base",
    "verificationDescription": "Esta página verifica las transacciones de sincronización. El espacio Base completo está en desarrollo.",
    "empty": "No hay registros.",
    "draft": "Borrador",
    "saved": "Guardado",
    "partial": "Algunos cambios requieren atención",
    "outcomeUnknown": "Comprobando el resultado…",
    "updating": "Actualizando los datos confirmados…",
    "offline": "Esperando la conexión",
    "conflicts": "Conflictos",
    "noConflicts": "No hay conflictos pendientes.",
    "current": "Valor actual",
    "candidate": "Tu propuesta",
    "reviewCurrent": "Revisar valores actuales",
    "reviewChanged": "Los valores volvieron a cambiar. Revisa la comparación antes de aplicar tu propuesta.",
    "apply": "Aplicar propuesta",
    "discard": "Descartar propuesta",
    "more": "Cargar más",

    "unavailable": "Esta Base no está disponible o se ha eliminado.",
    "notInitialized": "La Base de verificación aún no se ha inicializado."
  },
  "workspace": "Espacio de trabajo",
  "navigation": "Navegación principal",
  "notFound": "Página no encontrada",
  "cloudDevLogin": "Iniciar sesión en Bottega Cloud Dev",
  "cloudLogin": "Iniciar sesión en Bottega",
  "verificationCodeNote": "El código identifica la solicitud; no es una credencial de acceso.",
  "deletingDescription": "El acceso a la nube está pausado mientras se elimina tu cuenta.",
  "verifyingDescription": "Verificando tu inicio de sesión.",
  "revokedDescription": "Cierra sesión y vuelve a iniciarla para continuar.",
  "restrictedCloudDescription": "El acceso a la nube está restringido para esta cuenta.",
  "title": "Cuenta",
  "syncUnavailable": "La sincronización no está disponible temporalmente. Puedes seguir trabajando de forma local.",
  "syncSettings": "Ajustes de sincronización",
  "google": "Continuar con Google",
  "signOut": "Cerrar sesión",
  "cancel": "Cancelar",
  "retry": "Reintentar",
  "retrying": "Reintentando…",
  "save": "Guardar",
  "saving": "Guardando…",
  "rename": "Cambiar nombre",
  "deviceName": "Nombre del dispositivo",
  "revoke": "Revocar",
  "revoking": "Revocando…",
  "revokeTitle": "¿Revocar esta sesión?",
  "revokeDescription": "Este dispositivo perderá el acceso a tu cuenta en la nube. El contenido descargado permanecerá en el dispositivo.",
  "localDescription": "Usa Bottega gratis de forma local. Iniciar sesión no sube contenido hasta que confirmes la primera sincronización.",
  "sync": "Sincronización",
  "syncNotConnected": "La sincronización aún no está activada.",


  "computers": {
    "label": "Ordenadores",
    "offlineSince": "Sin conexión · {{when}}",
    "none": "Inicia sesión en Bottega en un ordenador y su barra lateral aparecerá aquí.",
    "thisComputer": "Este ordenador",
    "name": "Nombre del ordenador",
    "nameTaken": "Otro ordenador ya tiene ese nombre.",
    "notFound": "Este ordenador no ha iniciado sesión en la cuenta.",
    "nameInvalid": "Escribe un nombre.",
    "suffixHint": "Otro ordenador ya tenía este nombre. Cámbiale el nombre a este aquí."
  },
  "devices": "Dispositivos",
  "lastSeen": "Visto {{when}}",
  "webSession": "Sesión web",
  "appVersion": "Bottega {{version}}",
  "noDevices": "No hay sesiones en esta página.",
  "current": "Este dispositivo",
  "online": "En línea",
  "offline": "Sin conexión",
  "revoked": "Revocada",
  "nextPage": "Siguientes sesiones",
  "firstPage": "Primera página",
  "refresh": "Actualizar",
  "showPastSessions": "Mostrar sesiones anteriores",
  "loadFailed": "No se pudieron cargar las sesiones. Inténtalo de nuevo.",
  "actionFailed": "No se pudo guardar el cambio. Comprueba tu conexión e inténtalo de nuevo.",
  "secureStorageDescription": "macOS puede solicitar acceso al llavero para proteger tu inicio de sesión en este ordenador.",
  "secureStorageRestart": "Reinicia Bottega y vuelve a iniciar sesión.",
  "retrySecureSave": "Reintentar guardado seguro",
  "discardSavedLogin": "Descartar el inicio de sesión guardado…",
  "discardSavedLoginTitle": "¿Descartar el inicio de sesión guardado en este dispositivo?",
  "discardSavedLoginDescription": "Esto elimina el inicio de sesión guardado en este dispositivo. Tendrás que volver a iniciar sesión. El contenido local se conserva. Las sesiones en la nube pueden seguir siendo válidas hasta que caduquen o se revoquen, y los registros del dispositivo pueden permanecer. Si no puedes iniciar sesión, revoca la sesión anterior de este dispositivo desde tu cuenta web.",
  "discardSavedLoginConfirm": "Descartar inicio de sesión",
  "discardSavedLoginFailed": "No se pudo confirmar la eliminación del inicio de sesión guardado. Reinténtalo antes de iniciar una nueva sesión.",
  "discardSavedLoginExpired": "Esta confirmación ha caducado o el inicio de sesión guardado ha cambiado. Revisa los detalles antes de confirmar de nuevo.",
  "retryCredentialStorage": "Reintentar acceso al almacenamiento seguro",
  "openCloudAccount": "Abrir cuenta web",
  "cancelUnconfirmed": "La cancelación no está confirmada. Bottega lo reintentará cuando vuelva la conexión. Mantén Bottega abierto por ahora.",
  "abandonLogin": "Abandonar este inicio de sesión y empezar de nuevo",
  "abandonLoginNote": "La solicitud pendiente puede seguir siendo válida en el servidor hasta que caduque o la revoques en tu cuenta web.",
  "openBrowser": "Volver a abrir el navegador",
  "loginLinkLabel": "Enlace de inicio de sesión",
  "loginLinkDescription": "¿No se abrió el navegador? Copia este enlace y pégalo en tu navegador.",
  "copyLoginLink": "Copiar enlace de inicio de sesión",
  "loginLinkCopied": "Enlace copiado",
  "loginLinkCopyFailed": "No se pudo copiar el enlace. Selecciónalo y cópialo manualmente.",
  "verificationCode": "Código de verificación",
  "expires": "Esta solicitud caduca en cinco minutos.",
  "loginTitle": "Te damos la bienvenida a Bottega",
  "loginDescription": "Inicia sesión para acceder a tu espacio sincronizado.",
  "account": "Cuenta",
  "back": "Volver al espacio de trabajo",
  "moreActions": "Más acciones",
  "close": "Cerrar",
  "download": "Descargar Bottega",
  "footer": {
    "copyright": "Bottega © 2026. Todos los derechos reservados.",
    "language": "Idioma",
    "languageError": "No se pudo cambiar el idioma. Inténtalo de nuevo.",
    "navigation": "Navegación del pie de página",
    "changelog": "Novedades",
    "docs": "Documentación",
    "github": "GitHub",
    "issues": "Issues",
    "download": "Descargar"
  },
  "allow": "He comprobado la aplicación. Permitir el acceso",
  "reject": "No he solicitado este acceso",
  "openDesktop": "Abrir Bottega",
  "approvedTitle": "Solicitud aprobada",
  "approvedPollingOnly": "Vuelve a la ventana de desarrollo de Bottega para terminar de iniciar sesión.",
  "loginVersionUnsupported": "Este servicio en la nube no admite esta versión de inicio de sesión. Actualiza el servicio e inténtalo de nuevo.",
  "approved": "Vuelve a Bottega para terminar de iniciar sesión.",
  "rejected": "Esta solicitud se ha cancelado",
  "expired": "Esta solicitud ha caducado",
  "invalidRequest": "Esta solicitud no está disponible",
  "startAgain": "Empieza de nuevo en Bottega.",
  "approvalDescription": "Permite esta solicitud solo si la has iniciado en Bottega en este ordenador. Comprueba que el código de verificación coincide con la ventana de la aplicación.",
  "approvalFailed": "No se pudo actualizar la solicitud. Inténtalo de nuevo.",
  "loading": {
    "slow": "Seguimos abriendo tu espacio de trabajo. Con una conexión lenta puede tardar un momento."
  },
  "status": {
    "deleted": "Tu cuenta en la nube se ha eliminado",
    "account-switch-required": "Confirma el cambio de cuenta para continuar",
    "local-only": "Solo local",
    "signed-out": "Sesión cerrada",
    "signing-in": "Iniciando sesión…",
    "signing-out": "Cerrando sesión…",
    "connecting": "Conectando…",
    "ready": "Sesión iniciada",
    "temporarily-offline": "Temporalmente sin conexión",
    "revoked": "Esta sesión se ha revocado",
    "suspended": "Tu cuenta está restringida",
    "deleting": "Tu cuenta se está eliminando",
    "environment-mismatch": "El entorno de la nube no coincide con esta aplicación",
    "client-outdated": "Actualiza Bottega para continuar",
    "error": "Se requiere atención"
  },
  "error": {
    "installation-already-active": "Este dispositivo aún tiene una sesión activa. Revoca su sesión anterior en tu cuenta web para que Bottega termine este inicio de sesión.",
    "session-already-bound": "Este navegador ya inició sesión con otro registro de dispositivo. Cierra sesión y vuelve a iniciarla para continuar.",
    "device-name-unavailable": "Hay demasiadas sesiones de navegador registradas en esta cuenta. Elimina sesiones web antiguas en tu página de cuenta y vuelve a iniciar sesión.",
    "credentials-environment-mismatch": "Los datos de inicio de sesión pertenecen a otro entorno de nube. Usa el entorno correspondiente o descártalos y vuelve a iniciar sesión.",
    "credentials-unreadable": "No se pudieron desbloquear los datos de inicio de sesión. El archivo se conserva. Restaura el almacenamiento seguro y reinténtalo, o descarta el inicio de sesión guardado.",
    "secure-save-failed": "No se pudo guardar tu inicio de sesión de forma segura. Reintenta el guardado o cancela el inicio de sesión.",
    "browser-open-failed": "No se pudo abrir el navegador. Copia el enlace de inicio de sesión de abajo o intenta abrirlo de nuevo.",
    "encryption-unavailable": "El almacenamiento seguro no está disponible. Revisa el llavero del sistema y reinicia Bottega antes de reintentarlo. Puedes seguir usando Bottega localmente.",
    "credentials-invalid": "El formato del inicio de sesión guardado no es válido. Continúa con Google para restablecer este archivo. El contenido local se conservará.",
    "connection-failed": "Tu conexión no está disponible. Bottega conserva tus datos de acceso mientras se reconecta.",
    "login-expired": "Esta solicitud ha caducado. Empieza de nuevo.",
    "login-rejected": "Esta solicitud se ha cancelado. Empieza de nuevo si la has iniciado tú.",
    "rate-limited": "Demasiados intentos de inicio de sesión ahora mismo. Espera un minuto e inténtalo de nuevo.",
    "sign-out-required": "Termina de cerrar la sesión anterior antes de iniciar una nueva sesión.",
    "server-outdated": "El servicio en la nube necesita una actualización para funcionar con esta versión de Bottega. Vuelve a intentarlo cuando se haya actualizado.",
    "request-failed": "No se pudo completar la solicitud. Inténtalo de nuevo.",
    "environment-mismatch": "Esta compilación no puede conectarse a este entorno de la nube.",
    "client-outdated": "Instala una versión más reciente de Bottega para conectarte."
  },
  "pending": {
    "preparing": "Preparando el inicio de sesión…",
    "opening": "Abriendo el navegador…",
    "securing": "Guardando tu inicio de sesión de forma segura…",
    "waiting": "Esperando tu aprobación en el navegador…",
    "exchanging": "Completando el inicio de sesión…",
    "confirming": "Confirmando el acceso seguro…",
    "registering": "Registrando este ordenador…",
    "cancelling": "Cancelando la solicitud…",
    "connection-failed": "Esperando tu conexión…"
  }
} satisfies CloudCopy;
