/**
 * [INPUT]: Depends on the shared cloud account and approval copy structure.
 * [OUTPUT]: Provides localized account, Sync settings navigation, sync, installation/removal/deletion consent, retained-file and credential recovery, browser-first sign-in, manual-link fallback, approval, footer language copy and the Web gate's slow-open loading sentence.
 * [POS]: Shared UI copy consumed by desktop and Cloud Web without platform dependencies.
 */
import type { CloudCopy } from "./en";
export const cloudCopy = {
  "appDeletion": {
    "expired": "Cette vérification a expiré avant l’enregistrement de la demande de suppression. Vérifiez l’App actuelle avant de confirmer à nouveau.",
    "sourceDeleted": "L’App d’origine a été supprimée. Cette conversation reste disponible en lecture seule.",
    "action": "Supprimer de tous les appareils",
    "title": "Supprimer {{name}} partout ?",
    "details": "Cette action supprime l’App du compte cloud et de tous les appareils synchronisés. Les conversations enregistrées restent en lecture seule. Cette action est irréversible.",
    "dataChoice": "Données de l’App",
    "keepData": "Conserver les données Base",
    "keepDetails": "Conserver la Base comme source de données indépendante et modifiable.",
    "deleteData": "Supprimer aussi les données Base",
    "deleteDetails": "Supprimer définitivement les enregistrements, images et fichiers cloud associés à la Base.",
    "localFiles": "Les sources non publiées et les autres fichiers locaux restent sur leur ordinateur d’origine.",
    "offline": "Connectez-vous et reprenez la synchronisation pour vérifier ou envoyer cette demande.",
    "reviewing": "Vérification de l’App actuelle…",
    "unknown": "Le résultat n’est pas confirmé. Réessayez pour vérifier la demande initiale ; votre choix concernant les données reste inchangé.",
    "conflicted": "L’App a changé depuis votre vérification. Consultez la version actuelle avant de décider à nouveau.",
    "blocked": "Cette demande n’a pas pu supprimer l’App. Vérifiez son état actuel avant de décider à nouveau.",
    "failed": "Impossible de vérifier l’App. Réessayez une fois connecté.",
    "confirmed": "Suppression confirmée. Les appareils synchronisés termineront l’opération à leur prochaine connexion.",
    "close": "Fermer",
    "review": "Vérifier l’App actuelle",
    "retry": "Vérifier la demande initiale",
    "deleting": "Suppression…",
    "confirm": "Supprimer de tous les appareils",
    "pending": "Résultat de suppression à confirmer",
    "keep": "Conserver l’App",
    "retainedBase": "Ouvrir la Base conservée"
  },
  "appRemoval": {
    "manage": "Gérer l’App cloud",
    "title": "Retirer {{name}} de cet ordinateur ?",
    "details": "L’App cloud et sa Base restent disponibles. Les conversations sont conservées sans droit d’exécution. Les sources non publiées, fichiers et paramètres restent sur cet ordinateur ; l’accès de l’Agent aux paramètres est révoqué.",
    "confirm": "Retirer l’installation",
    "remove": "Retirer de cet ordinateur",
    "removing": "Suppression de l’installation…",
    "failed": "La suppression n’a pas abouti. Réessayez cette demande ou reprenez-la depuis la liste des Apps.",
    "pending": "La suppression locale nécessite votre attention",
    "resume": "Reprendre la suppression",
    "retained": "Ouvrir les fichiers conservés"
  },
  "appInstall": {
    "title": "Vos Apps dans le cloud",
    "installTitle": "Installer {{name}}",
    "updateTitle": "Mettre à jour {{name}}",
    "consent": "Vérifiez cette version et autorisez son accès sur cet ordinateur. La configuration et les autorisations restent sur cet ordinateur.",
    "preparing": "Téléchargement et vérification de cette version…",
    "failed": "La demande n’a pas abouti. Actualisez pour consulter son état ; une installation déjà commencée peut reprendre depuis la liste.",
    "refresh": "Actualiser",
    "source": "Votre compte cloud",
    "configuration": "Configuration sur cet ordinateur",
    "agent": "Agent de maintenance",
    "noAgent": "Configurez un Agent compatible avant l’installation.",
    "confirmInstall": "Autoriser et installer",
    "confirmUpdate": "Autoriser et mettre à jour",
    "installing": "Installation…",
    "loading": "Chargement des Apps du cloud…",
    "online": "Reprenez la synchronisation en ligne pour installer ou mettre à jour. Les données Base téléchargées restent accessibles.",
    "version": "Version {{version}}",
    "notInstalled": "Non installée ici",
    "installed": "Installée ici",
    "updateAvailable": "Mise à jour disponible",
    "interrupted": "L’installation nécessite votre attention",
    "deleted": "Supprimée",
    "resume": "Reprendre l’installation",
    "install": "Installer",
    "update": "Mettre à jour",
    "basePending": "En attente des données Base complètes avant l’installation."
  },
  "syncReview": {
    "switchAccount": "Confirmer le changement de compte",
    "switchTitle": "Changer de compte sur cet ordinateur",
    "switchBody": "Les données cloud restent associées au compte précédent. Après le changement, réactivez la synchronisation pour ce compte.",
    "disable": "Désactiver",
    "cloudData": "Données cloud",
    "cloudDataDescription": "Déconnecter cet ordinateur et supprimer les copies cloud conservées ici. La déconnexion du compte ne fait ni l’un ni l’autre.",
    "disableTitle": "Désactiver la synchronisation sur cet ordinateur ?",
    "disableBody": "Les copies présentes ici uniquement comme miroirs cloud seront supprimées. Tout ce qui a été créé ou repris sur cet ordinateur reste, avec ses fichiers. Votre mot de passe de synchronisation sera nécessaire pour réactiver la synchronisation.",
    "disableRemove": "Supprimer {{mirrors}} miroirs de chats, {{mirroredBases}} miroirs de Bases, {{mirroredProjects}} miroirs de Projects et {{mirroredApps}} miroirs d’Apps.",
    "disableKeep": "Conserver {{retainedChats}} chats, {{retainedHomes}} dossiers Home, {{retainedBases}} Bases, {{retainedProjects}} Projects et {{retainedApps}} Apps.",
    "disableConfirm": "Désactiver la synchronisation",
    "pendingDiscard": "{{count}} modifications en attente seront conservées localement et dissociées de ce compte.",
    "progress": "{{completed}} éléments sur {{total}}",
    "pending": "{{count}} modifications en attente",
    "conflicts": "{{count}} conflits à résoudre"
  },
  "syncStatus": {
    "partial": "Les données Base sont à jour ; certains paquets App demandent votre attention",
    "not-connected": "Cet ordinateur ne se synchronise pas encore.",
    "scanning": "Analyse du contenu local…",
    "initializing": "Préparation de la première synchronisation…",
    "syncing": "Synchronisation…",
    "synced": "À jour",
    "paused": "Synchronisation en pause",
    "offline": "En attente de connexion",
    "error": "La synchronisation nécessite une intervention",
    "closing": "Déconnexion du compte…"
  },
  "syncError": {
    "scan-failed": "Le contenu local n’a pas pu être analysé. Réessayez après la fin de l’importation.",
    "review-expired": "Cette vérification a expiré. Relancez l’analyse.",
    "upload-failed": "Une partie du contenu n’est pas synchronisée. La copie locale est conservée ; réessayez.",
    "cleanup-failed": "La déconnexion de ce compte n’a pas pu se terminer. Votre contenu local est conservé ; réessayez pour continuer.",
    "library-owned-elsewhere": "Ce dossier Bottega appartient à {{host}}. Cette version ne peut pas l’ouvrir sur un autre ordinateur : créez un nouveau dossier, ou utilisez-le sur cet ordinateur-là."
  },
  "syncAppBlocked": {
    "migration-blocked": "Cette version nécessite une migration non prise en charge. La version précédente est conservée dans le cloud.",
    "version-conflict": "Une autre version de l’App a été publiée. Vérifiez les versions avant de réessayer.",
    "not-published": "Aucune version publiée",
    "package-too-large": "Le paquet dépasse 50 MB",
    "source-unavailable": "Source publiée non vérifiable",
    "generation-changed": "Version modifiée pendant la vérification",
    "association-unavailable": "Association des données App à restaurer"
  },
  "setup": {
    "signIn": "Connexion",
    "enable": "Terminer la connexion",
    "signInTitle": "Connectez-vous pour synchroniser cet ordinateur",
    "browserApproval": "Vous approuverez la connexion dans votre navigateur.",
    "signedInAs": "Vous êtes connecté avec {{email}}.",
    "checkCode": "Vérifiez qu’il correspond au code affiché dans votre navigateur avant d’autoriser la connexion.",
    "enterPassword": "Saisissez votre mot de passe de synchronisation",
    "enterPasswordDescription": "Cet ordinateur rejoint l’espace chiffré créé sur un autre appareil. Bottega ne peut pas récupérer le mot de passe.",
    "unlockedDescription": "Cet ordinateur est déjà déverrouillé. Terminez pour lancer la synchronisation."
  },
  "syncBadge": {
    "synced": "À jour",
    "syncing": "Synchronisation",
    "paused": "En pause",
    "offline": "En attente de connexion",
    "attention": "Attention requise",
    "locked": "Verrouillé",
    "checking": "Vérification",
    "closing": "Déconnexion",
    "unavailable": "Indisponible"
  },
  "syncRow": {
    "synced": "Toutes les modifications locales sont dans votre compte cloud, chiffrées de bout en bout avec votre mot de passe de synchronisation.",
    "locked": "Saisissez votre mot de passe de synchronisation pour reprendre la synchronisation sur cet ordinateur."
  },
  "syncPhase": {
    "preparing": "Préparation des chats",
    "projects": "Envoi des Projects",
    "apps": "Envoi des Apps",
    "chats": "Envoi des chats",
    "bases": "Envoi des Bases",
    "files": "Envoi des fichiers",
    "homes": "Envoi de Chat Home"
  },
  "appPackages": {
    "title": "Paquets d’Apps",
    "description": "Les données Base de ces Apps sont synchronisées. Leurs paquets nécessitent votre attention avant que l’App puisse être restaurée sur un autre ordinateur.",
    "open": "Ouvrir l’App"
  },
  "platform": {
    "macos": "macOS",
    "windows": "Windows",
    "linux": "Linux",
    "browser": "Navigateur"
  },
  "apps": {
    "title": "Apps",
    "capabilities": "Interface de l’App · Mémoire · Outils",
    "description": "Consultez et modifiez les données synchronisées. Les interfaces propres aux Apps fonctionnent sur votre ordinateur.",
    "empty": "Aucune App synchronisée sur cette page.",
    "version": "Version",
    "packageReady": "Sources disponibles",
    "packagePending": "En attente du transfert de cette version depuis l’ordinateur d’origine.",
    "partial": "Certaines données restent sur l’ordinateur d’origine.",
    "baseOnly": "Les enregistrements Base font partie de la synchronisation.",
    "structure": "La structure est gérée par les mises à jour. Vous pouvez modifier les enregistrements et les vues ici.",
    "unavailable": "Cette App a été supprimée ou est inaccessible.",
    "back": "Retour aux Apps",
    "backToApp": "Retour à l’App"
  },
  "catalog": {
    "titleColumn": "Titre",
    "tableView": "Tableau",
    "noProjects": "Aucun Project sur cette page.",
    "projects": "Projets",
    "bases": "Bases",
    "noBases": "Aucune Base synchronisée sur cette page.",


    "openBase": "Ouvrir la Base",
    "loading": "Chargement de l’espace de travail…",
    "readLimit": "Cette Base dépasse la capacité de lecture du navigateur. La dernière vue complète est conservée ; la modification est suspendue.",
    "historyUnavailable": "L’historique des enregistrements cloud n’est pas encore disponible.",
    "original": "Valeur d’origine",
    "source": "Appareil source",
    "readUpdating": "Cette Base est en cours de modification. En attente des données complètes…",
    "readError": "Les enregistrements n’ont pas pu être chargés. Votre brouillon est conservé."
  },
  "recovery": {
    "retrying": "Certains contenus n’ont pas pu être chargés. Nouvelle tentative dans {{seconds}} s…",
    "stalled": "Toujours impossible de joindre Bottega Cloud.",
    "retryNow": "Réessayer maintenant",
    "reload": "Recharger la page",
    "unavailable": "Cet élément n’est pas disponible."
  },
  "base": {
    "verification": "Vérification Base",
    "verificationDescription": "Cette page vérifie les transactions de synchronisation. L’espace Base complet est en cours de développement.",
    "empty": "Aucun enregistrement.",
    "draft": "Brouillon",
    "saved": "Enregistré",
    "partial": "Certaines modifications nécessitent votre attention",
    "outcomeUnknown": "Vérification du résultat…",
    "updating": "Actualisation des données confirmées…",
    "offline": "En attente de connexion",
    "conflicts": "Conflits",
    "noConflicts": "Aucun conflit non résolu.",
    "current": "Valeur actuelle",
    "candidate": "Votre proposition",
    "reviewCurrent": "Comparer les valeurs actuelles",
    "reviewChanged": "Les valeurs ont encore changé. Vérifiez la comparaison avant d’appliquer votre proposition.",
    "apply": "Appliquer la proposition",
    "discard": "Abandonner la proposition",
    "more": "Charger plus",

    "unavailable": "Cette Base est inaccessible ou supprimée.",
    "notInitialized": "La Base de vérification n’a pas encore été initialisée."
  },
  "workspace": "Espace de travail",
  "navigation": "Navigation principale",
  "notFound": "Page introuvable",
  "cloudDevLogin": "Se connecter à Bottega Cloud Dev",
  "cloudLogin": "Se connecter à Bottega",
  "verificationCodeNote": "Le code identifie la demande ; ce n’est pas un identifiant de connexion.",
  "deletingDescription": "L’accès au cloud est suspendu pendant la suppression de votre compte.",
  "verifyingDescription": "Vérification de votre connexion.",
  "revokedDescription": "Déconnectez-vous puis reconnectez-vous pour continuer.",
  "restrictedCloudDescription": "L’accès au cloud est restreint pour ce compte.",
  "title": "Compte",
  "syncUnavailable": "La synchronisation est temporairement indisponible. Vous pouvez continuer à travailler en local.",
  "syncSettings": "Paramètres de synchronisation",
  "google": "Continuer avec Google",
  "signOut": "Se déconnecter",
  "cancel": "Annuler",
  "retry": "Réessayer",
  "retrying": "Nouvelle tentative…",
  "save": "Enregistrer",
  "saving": "Enregistrement…",
  "rename": "Renommer",
  "deviceName": "Nom de l’appareil",
  "revoke": "Révoquer",
  "revoking": "Révocation…",
  "revokeTitle": "Révoquer cette session ?",
  "revokeDescription": "Cet appareil n’aura plus accès à votre compte cloud. Le contenu déjà téléchargé restera sur l’appareil.",
  "localDescription": "Utilisez Bottega gratuitement en local. La connexion ne transfère aucun contenu avant votre confirmation de la première synchronisation.",
  "sync": "Synchronisation",
  "syncNotConnected": "La synchronisation n’est pas encore activée.",


  "computers": {
    "label": "Ordinateurs",
    "offlineSince": "Hors ligne · {{when}}",
    "none": "Connectez-vous à Bottega sur un ordinateur et sa barre latérale apparaîtra ici.",
    "thisComputer": "Cet ordinateur",
    "name": "Nom de l'ordinateur",
    "nameTaken": "Un autre ordinateur porte déjà ce nom.",
    "notFound": "Cet ordinateur n'est pas connecté au compte.",
    "nameInvalid": "Saisissez un nom.",
    "suffixHint": "Un autre ordinateur portait déjà ce nom. Renommez celui-ci ici."
  },
  "devices": "Appareils",
  "lastSeen": "Vu {{when}}",
  "webSession": "Session Web",
  "appVersion": "Bottega {{version}}",
  "noDevices": "Aucune session sur cette page.",
  "current": "Cet appareil",
  "online": "En ligne",
  "offline": "Hors ligne",
  "revoked": "Révoquée",
  "nextPage": "Sessions suivantes",
  "firstPage": "Première page",
  "refresh": "Actualiser",
  "showPastSessions": "Afficher les sessions passées",
  "loadFailed": "Impossible de charger les sessions. Réessayez.",
  "actionFailed": "La modification n’a pas été enregistrée. Vérifiez votre connexion et réessayez.",
  "secureStorageDescription": "macOS peut demander l’accès au trousseau pour protéger votre connexion sur cet ordinateur.",
  "secureStorageRestart": "Redémarrez Bottega, puis reconnectez-vous.",
  "retrySecureSave": "Réessayer la sauvegarde sécurisée",
  "discardSavedLogin": "Supprimer la connexion enregistrée…",
  "discardSavedLoginTitle": "Supprimer la connexion enregistrée sur cet appareil ?",
  "discardSavedLoginDescription": "Cette action supprime la connexion enregistrée sur cet appareil. Vous devrez vous reconnecter. Le contenu local est conservé. Les sessions cloud peuvent rester valides jusqu’à leur expiration ou révocation, et les appareils peuvent rester répertoriés. Si la connexion est bloquée, révoquez l’ancienne session de cet appareil dans votre compte web.",
  "discardSavedLoginConfirm": "Supprimer la connexion",
  "discardSavedLoginFailed": "La suppression de la connexion enregistrée n’a pas pu être confirmée. Réessayez avant de démarrer une nouvelle connexion.",
  "discardSavedLoginExpired": "Cette confirmation a expiré ou la connexion enregistrée a changé. Vérifiez à nouveau les détails avant de confirmer.",
  "retryCredentialStorage": "Réessayer l’accès au stockage sécurisé",
  "openCloudAccount": "Ouvrir le compte web",
  "cancelUnconfirmed": "L’annulation n’est pas confirmée. Bottega réessaiera une fois connecté. Gardez Bottega ouvert pour le moment.",
  "abandonLogin": "Abandonner cette connexion et recommencer",
  "abandonLoginNote": "La demande en attente peut rester valide sur le serveur jusqu’à son expiration ou jusqu’à ce que vous la révoquiez dans votre compte web.",
  "openBrowser": "Rouvrir le navigateur",
  "loginLinkLabel": "Lien de connexion",
  "loginLinkDescription": "Le navigateur ne s’ouvre pas ? Copiez ce lien et collez-le dans votre navigateur.",
  "copyLoginLink": "Copier le lien de connexion",
  "loginLinkCopied": "Lien copié",
  "loginLinkCopyFailed": "Impossible de copier le lien. Sélectionnez-le et copiez-le manuellement.",
  "verificationCode": "Code de vérification",
  "expires": "Cette demande expire après cinq minutes.",
  "loginTitle": "Bienvenue dans Bottega",
  "loginDescription": "Connectez-vous pour accéder à votre espace synchronisé.",
  "account": "Compte",
  "back": "Retour à l’espace de travail",
  "moreActions": "Plus d’actions",
  "close": "Fermer",
  "download": "Télécharger Bottega",
  "footer": {
    "copyright": "Bottega © 2026. Tous droits réservés.",
    "language": "Langue",
    "languageError": "Impossible de changer de langue. Veuillez réessayer.",
    "navigation": "Navigation du pied de page",
    "changelog": "Nouveautés",
    "docs": "Documentation",
    "github": "GitHub",
    "issues": "Issues",
    "download": "Télécharger"
  },
  "allow": "J’ai vérifié l’application. Autoriser la connexion",
  "reject": "Je n’ai pas demandé cette connexion",
  "openDesktop": "Ouvrir Bottega",
  "approvedTitle": "Demande approuvée",
  "approvedPollingOnly": "Revenez dans la fenêtre de développement Bottega pour terminer la connexion.",
  "loginVersionUnsupported": "Ce service cloud ne prend pas en charge cette version de connexion. Mettez le service à jour et réessayez.",
  "approved": "Revenez dans Bottega pour terminer la connexion.",
  "rejected": "Cette demande a été annulée",
  "expired": "Cette demande a expiré",
  "invalidRequest": "Cette demande n’est pas disponible",
  "startAgain": "Recommencez dans Bottega.",
  "approvalDescription": "N’autorisez cette demande que si vous l’avez lancée dans Bottega sur cet ordinateur. Vérifiez que le code de vérification correspond à la fenêtre de l’application.",
  "approvalFailed": "Impossible de mettre à jour la demande. Réessayez.",
  "loading": {
    "slow": "Ouverture de votre espace de travail en cours. Une connexion lente peut prendre un moment."
  },
  "status": {
    "deleted": "Votre compte cloud a été supprimé",
    "account-switch-required": "Confirmez le changement de compte pour continuer",
    "local-only": "Local uniquement",
    "signed-out": "Déconnecté",
    "signing-in": "Connexion…",
    "signing-out": "Déconnexion en cours…",
    "connecting": "Connexion en cours…",
    "ready": "Connecté",
    "temporarily-offline": "Temporairement hors ligne",
    "revoked": "Cette session a été révoquée",
    "suspended": "Votre compte est restreint",
    "deleting": "Votre compte est en cours de suppression",
    "environment-mismatch": "L’environnement cloud ne correspond pas à cette application",
    "client-outdated": "Mettez Bottega à jour pour continuer",
    "error": "Action requise"
  },
  "error": {
    "installation-already-active": "Cet appareil possède encore une session active. Révoquez son ancienne session dans votre compte web pour que Bottega termine cette connexion.",
    "session-already-bound": "Ce navigateur est déjà connecté avec un autre enregistrement d’appareil. Déconnectez-vous puis reconnectez-vous pour continuer.",
    "device-name-unavailable": "Trop de sessions de navigateur sont enregistrées pour ce compte. Supprimez d’anciennes sessions web sur votre page de compte, puis reconnectez-vous.",
    "credentials-environment-mismatch": "Les données de connexion appartiennent à un autre environnement cloud. Utilisez l’environnement correspondant ou supprimez-les avant de vous reconnecter.",
    "credentials-unreadable": "Impossible de déverrouiller les données de connexion. Le fichier est conservé. Rétablissez le stockage sécurisé et réessayez, ou supprimez la connexion enregistrée.",
    "secure-save-failed": "Impossible de sauvegarder votre connexion en toute sécurité. Réessayez la sauvegarde ou annulez la connexion.",
    "browser-open-failed": "Impossible d’ouvrir le navigateur. Copiez le lien de connexion ci-dessous ou réessayez de l’ouvrir.",
    "encryption-unavailable": "Le stockage sécurisé est indisponible. Vérifiez le trousseau du système et redémarrez Bottega avant de réessayer. Vous pouvez continuer à utiliser Bottega localement.",
    "credentials-invalid": "Le format de la connexion enregistrée est invalide. Continuez avec Google pour réinitialiser ce fichier. Le contenu local sera conservé.",
    "connection-failed": "Votre connexion est indisponible. Bottega conserve vos informations de connexion pendant la reconnexion.",
    "login-expired": "Cette demande de connexion a expiré. Recommencez.",
    "login-rejected": "Cette demande a été annulée. Recommencez si vous en êtes à l’origine.",
    "rate-limited": "Trop de tentatives de connexion pour le moment. Attendez une minute puis réessayez.",
    "sign-out-required": "Terminez la déconnexion de la session précédente avant de lancer une nouvelle connexion.",
    "server-outdated": "Le service cloud doit être mis à jour pour fonctionner avec cette version de Bottega. Réessayez après sa mise à jour.",
    "request-failed": "La demande n’a pas pu aboutir. Réessayez.",
    "environment-mismatch": "Cette version ne peut pas se connecter à cet environnement cloud.",
    "client-outdated": "Installez une version plus récente de Bottega pour vous connecter."
  },
  "pending": {
    "preparing": "Préparation de la connexion…",
    "opening": "Ouverture du navigateur…",
    "securing": "Sauvegarde sécurisée de votre connexion…",
    "waiting": "En attente de votre approbation dans le navigateur…",
    "exchanging": "Finalisation de la connexion…",
    "confirming": "Confirmation de la connexion sécurisée…",
    "registering": "Enregistrement de cet ordinateur…",
    "cancelling": "Annulation de la demande…",
    "connection-failed": "En attente de votre connexion…"
  }
} satisfies CloudCopy;
