/**
 * [INPUT]: Depends on the shared cloud account and approval copy structure.
 * [OUTPUT]: Provides localized account, Sync settings navigation, sync, installation/removal/deletion consent, retained-file and credential recovery, browser-first sign-in, manual-link fallback, approval, footer language copy and the Web gate's slow-open loading sentence.
 * [POS]: Shared UI copy consumed by desktop and Cloud Web without platform dependencies.
 */
import type { CloudCopy } from "./en";
export const cloudCopy = {
  "appDeletion": {
    "expired": "削除リクエストの保存前に確認の有効期限が切れました。現在の App を確認してから、もう一度確定してください。",
    "sourceDeleted": "元の App は削除されました。この会話は引き続き閲覧できます。",
    "action": "すべての端末から削除",
    "title": "{{name}} をすべての端末から削除しますか？",
    "details": "クラウドアカウントと同期済みのすべての端末からこの App を削除します。保存済みの会話は読み取り専用で残ります。この操作は取り消せません。",
    "dataChoice": "App のデータ",
    "keepData": "Base データを残す",
    "keepDetails": "Base を独立した編集可能なデータとして残します。",
    "deleteData": "Base データも削除する",
    "deleteDetails": "Base のレコード、画像、関連するクラウドファイルを完全に削除します。",
    "localFiles": "未公開のソースとその他のローカルファイルは元のコンピュータに残ります。",
    "offline": "接続して同期を再開してから、確認または送信してください。",
    "reviewing": "現在の App を確認中…",
    "unknown": "結果を確認できません。再試行すると元のリクエストを確認します。データの選択は変わりません。",
    "conflicted": "確認後に App が変更されました。現在のバージョンを確認してから、もう一度選択してください。",
    "blocked": "このリクエストでは App を削除できませんでした。現在の状態を確認してから、もう一度選択してください。",
    "failed": "App を確認できませんでした。接続後に再試行してください。",
    "confirmed": "削除が確認されました。同期済みの端末は再接続時に処理を完了します。",
    "close": "閉じる",
    "review": "現在の App を確認",
    "retry": "元のリクエストを確認",
    "deleting": "削除中…",
    "confirm": "すべての端末から削除",
    "pending": "削除結果の確認が必要",
    "keep": "App を残す",
    "retainedBase": "残した Base を開く"
  },
  "appRemoval": {
    "manage": "クラウド App を管理",
    "title": "このコンピュータから {{name}} を削除しますか？",
    "details": "クラウドの App と Base は引き続き利用できます。会話は実行権限なしで保持されます。未公開ソース、ローカルファイルと設定はこのコンピューターに残り、設定への Agent の読み取り許可は解除されます。",
    "confirm": "インストールを削除",
    "remove": "このコンピュータから削除",
    "removing": "インストールを削除中…",
    "failed": "削除を完了できませんでした。同じリクエストを再試行するか、App 一覧から再開してください。",
    "pending": "ローカル削除に対応が必要です",
    "resume": "削除を再開",
    "retained": "保持したファイルを開く"
  },
  "appInstall": {
    "title": "クラウドの Apps",
    "installTitle": "{{name}} をインストール",
    "updateTitle": "{{name}} を更新",
    "consent": "このバージョンを確認し、このコンピューターでのアクセスを許可してください。設定と権限はこのコンピューターに保存されます。",
    "preparing": "このバージョンをダウンロードして確認中…",
    "failed": "処理を完了できませんでした。再読み込みで状態を確認してください。開始済みのインストールは一覧から再開できます。",
    "refresh": "再読み込み",
    "source": "クラウドアカウント",
    "configuration": "このコンピューターの設定",
    "agent": "メンテナンス Agent",
    "noAgent": "先に対応する Agent を設定してください。",
    "confirmInstall": "許可してインストール",
    "confirmUpdate": "許可して更新",
    "installing": "インストール中…",
    "loading": "クラウドの Apps を読み込み中…",
    "online": "インストールや更新にはオンライン同期を再開してください。ダウンロード済みの Base データは引き続き利用できます。",
    "version": "バージョン {{version}}",
    "notInstalled": "このコンピューターには未インストール",
    "installed": "このコンピューターにインストール済み",
    "updateAvailable": "更新があります",
    "interrupted": "インストールの確認が必要",
    "deleted": "削除済み",
    "resume": "インストールを再開",
    "install": "インストール",
    "update": "更新",
    "basePending": "インストール前に Base データ全体の取得を待っています。"
  },
  "syncReview": {
    "switchAccount": "アカウントの切り替えを確認",
    "switchTitle": "このコンピューターのアカウントを切り替える",
    "switchBody": "クラウドデータは元のアカウントに残ります。切り替え後、このアカウントで同期を再度有効にしてください。",
    "disable": "無効にする",
    "cloudData": "クラウドデータ",
    "cloudDataDescription": "このコンピューターの接続を解除し、ここに保存されたクラウドのコピーを削除します。ログアウトではどちらも行われません。",
    "disableTitle": "このコンピューターの同期を無効にしますか？",
    "disableBody": "このコンピューターにクラウドのミラーとしてのみ存在するコピーは削除されます。ここで作成または引き継いだ内容はファイルと共に残ります。再度同期を有効にするには同期パスワードが必要です。",
    "disableRemove": "Chat ミラー {{mirrors}} 件、Base ミラー {{mirroredBases}} 件、Project ミラー {{mirroredProjects}} 件、App ミラー {{mirroredApps}} 件を削除します。",
    "disableKeep": "Chat {{retainedChats}} 件、Home フォルダー {{retainedHomes}} 件、Base {{retainedBases}} 件、Project {{retainedProjects}} 件、App {{retainedApps}} 件を保持します。",
    "disableConfirm": "同期を無効にする",
    "pendingDiscard": "待機中の変更 {{count}} 件はローカルに保持し、このアカウントとの同期を解除します。",
    "progress": "{{total}} 件中 {{completed}} 件",
    "pending": "{{count}} 件の変更が待機中",
    "conflicts": "{{count}} 件の競合に対応が必要"
  },
  "syncStatus": {
    "partial": "Base データは同期済みです。一部の App パッケージに対応が必要です",
    "not-connected": "このコンピューターはまだ同期していません。",
    "scanning": "スキャン中…",
    "initializing": "初回同期を準備中…",
    "syncing": "同期中…",
    "synced": "最新の状態です",
    "paused": "同期を一時停止中",
    "offline": "ネットワーク接続を待機中",
    "error": "同期に対応が必要です",
    "closing": "アカウントの接続を解除中…"
  },
  "syncError": {
    "scan-failed": "ローカルコンテンツを確認できませんでした。インポート完了後に再試行してください。",
    "review-expired": "確認の有効期限が切れました。再スキャンしてください。",
    "upload-failed": "一部の内容は未同期です。ローカルコピーは保持されています。再試行してください。",
    "cleanup-failed": "このアカウントの切断を完了できませんでした。ローカルの内容は保持されています。再試行してください。",
    "library-owned-elsewhere": "この Bottega フォルダーは {{host}} のものです。現在のバージョンでは別のコンピューターで開けません。新しいフォルダーを作るか、そのコンピューターで使ってください。"
  },
  "syncAppBlocked": {
    "migration-blocked": "このバージョンには未対応のデータ移行が必要です。クラウドの旧バージョンを保持しています。",
    "version-conflict": "別の App バージョンが公開されました。バージョンを確認してから再試行してください。",
    "not-published": "公開済みバージョンなし",
    "package-too-large": "50 MB の上限を超えています",
    "source-unavailable": "公開済みソースを検証できません",
    "generation-changed": "確認中にバージョンが変更されました",
    "association-unavailable": "App データの関連付けの復元が必要"
  },
  "setup": {
    "signIn": "ログイン",
    "enable": "ログインを完了",
    "signInTitle": "ログインしてこのコンピューターを同期",
    "browserApproval": "ログインはブラウザで承認します。",
    "signedInAs": "{{email}} でログイン中です。",
    "checkCode": "ブラウザに表示された確認コードと一致することを確かめてから許可してください。",
    "enterPassword": "同期パスワードを入力",
    "enterPasswordDescription": "このコンピューターは、別のデバイスで作成した暗号化ワークスペースに参加します。Bottega はパスワードを復元できません。",
    "unlockedDescription": "このコンピューターはすでにロック解除されています。完了すると同期が始まります。"
  },
  "syncBadge": {
    "synced": "最新",
    "syncing": "同期中",
    "paused": "一時停止中",
    "offline": "接続待ち",
    "attention": "要対応",
    "locked": "ロック中",
    "checking": "確認中",
    "closing": "切断中",
    "unavailable": "利用不可"
  },
  "syncRow": {
    "synced": "ローカルの変更はすべてクラウドアカウントにあり、同期パスワードでエンドツーエンド暗号化されています。",
    "locked": "同期パスワードを入力して、このコンピューターの同期を再開してください。"
  },
  "syncPhase": {
    "preparing": "Chat を準備中",
    "projects": "Project をアップロード中",
    "apps": "App をアップロード中",
    "chats": "Chat をアップロード中",
    "bases": "Base をアップロード中",
    "files": "ファイルをアップロード中",
    "homes": "Chat Home をアップロード中"
  },
  "appPackages": {
    "title": "App パッケージ",
    "description": "これらの App の Base データは同期済みです。別のコンピューターで App を復元するには、パッケージへの対応が必要です。",
    "open": "App を開く"
  },
  "platform": {
    "macos": "macOS",
    "windows": "Windows",
    "linux": "Linux",
    "browser": "ブラウザ"
  },
  "apps": {
    "title": "Apps",
    "capabilities": "App GUI · メモリ · ツール",
    "description": "同期した App のレコードを表示・編集できます。専用の画面はコンピューターで実行されます。",
    "empty": "このページには同期した App がありません。",
    "version": "バージョン",
    "packageReady": "ソースパッケージ準備完了",
    "packagePending": "元のコンピューターからのアップロードを待っています。",
    "partial": "一部のデータは元のコンピューターにのみあります。",
    "baseOnly": "Base のレコードは同期対象です。",
    "structure": "App の構造はバージョン更新で管理されます。ここではレコードとビュー設定を編集できます。",
    "unavailable": "この App は削除されたか、利用できません。",
    "back": "Apps に戻る",
    "backToApp": "App に戻る"
  },
  "catalog": {
    "titleColumn": "タイトル",
    "tableView": "テーブル",
    "noProjects": "このページには Project がありません。",
    "projects": "プロジェクト",
    "bases": "Base",
    "noBases": "このページに同期済みの Base はありません。",


    "openBase": "Base を開く",
    "loading": "ワークスペースを読み込み中…",
    "readLimit": "この Base はブラウザーの読み込み上限を超えています。最後の完全な表示を保持し、編集を一時停止しています。",
    "historyUnavailable": "クラウドのレコード変更履歴はまだ利用できません。",
    "original": "元の値",
    "source": "変更元のデバイス",
    "readUpdating": "Base の更新中です。完全なデータを待っています…",
    "readError": "レコードを読み込めませんでした。下書きは保持されています。"
  },
  "recovery": {
    "retrying": "一部のコンテンツを読み込めませんでした。{{seconds}} 秒後に再試行します…",
    "stalled": "Bottega Cloud にまだ接続できません。",
    "retryNow": "今すぐ再試行",
    "reload": "ページを再読み込み",
    "unavailable": "この項目は利用できません。"
  },
  "base": {
    "verification": "Base 同期検証",
    "verificationDescription": "同期トランザクションの検証ページです。完全な Base ワークスペースは開発中です。",
    "empty": "レコードがありません。",
    "draft": "未保存",
    "saved": "保存済み",
    "partial": "一部の変更を確認してください",
    "outcomeUnknown": "保存結果を確認中…",
    "updating": "確定データを更新中…",
    "offline": "接続の回復を待っています",
    "conflicts": "競合",
    "noConflicts": "未解決の競合はありません。",
    "current": "現在の値",
    "candidate": "候補の値",
    "reviewCurrent": "最新の値を確認",
    "reviewChanged": "値が再び変更されました。比較内容を確認してから候補を適用してください。",
    "apply": "候補を適用",
    "discard": "候補を破棄",
    "more": "さらに表示",

    "unavailable": "この Base は利用できないか、削除されました。",
    "notInitialized": "検証用 Base はまだ初期化されていません。"
  },
  "workspace": "ワークスペース",
  "navigation": "メインナビゲーション",
  "notFound": "ページが見つかりません",
  "cloudDevLogin": "Bottega Cloud Dev にログイン",
  "cloudLogin": "Bottega にログイン",
  "verificationCodeNote": "確認コードは要求を識別するもので、ログイン認証情報ではありません。",
  "deletingDescription": "アカウントの削除中はクラウドへのアクセスが停止されます。",
  "verifyingDescription": "ログインを確認しています。",
  "revokedDescription": "ログアウトしてから再度ログインしてください。",
  "restrictedCloudDescription": "このアカウントのクラウドへのアクセスは制限されています。",
  "title": "アカウント",
  "syncUnavailable": "同期は一時的に利用できません。ローカル機能は引き続き使用できます。",
  "syncSettings": "同期設定",
  "google": "Google で続ける",
  "signOut": "ログアウト",
  "cancel": "キャンセル",
  "retry": "再試行",
  "retrying": "再試行中…",
  "save": "保存",
  "saving": "保存中…",
  "rename": "名前を変更",
  "deviceName": "デバイス名",
  "revoke": "取り消す",
  "revoking": "取り消し中…",
  "revokeTitle": "このセッションを取り消しますか？",
  "revokeDescription": "このデバイスからクラウドアカウントにアクセスできなくなります。ダウンロード済みの内容はデバイスに残ります。",
  "localDescription": "ローカル機能は無料で利用できます。ログイン後、初回同期を確認するまで内容はアップロードされません。",
  "sync": "同期",
  "syncNotConnected": "同期はまだ有効になっていません。",


  "computers": {
    "label": "パソコン",
    "offlineSince": "オフライン · {{when}}",
    "none": "パソコンで Bottega にログインすると、そのサイドバーがここに表示されます。",
    "thisComputer": "このパソコン",
    "name": "パソコンの名前",
    "nameTaken": "同じ名前のパソコンがすでにあります。",
    "notFound": "このパソコンはこのアカウントにログインしていません。",
    "nameInvalid": "名前を入力してください。",
    "suffixHint": "同じ名前のパソコンがすでにありました。ここで名前を変更できます。"
  },
  "devices": "デバイス",
  "lastSeen": "最終確認: {{when}}",
  "webSession": "Web セッション",
  "appVersion": "Bottega {{version}}",
  "noDevices": "このページにセッションはありません。",
  "current": "このデバイス",
  "online": "オンライン",
  "offline": "オフライン",
  "revoked": "取り消し済み",
  "nextPage": "次のページ",
  "firstPage": "最初のページ",
  "refresh": "更新",
  "showPastSessions": "過去のセッションを表示",
  "loadFailed": "セッションを読み込めませんでした。再試行してください。",
  "actionFailed": "変更を保存できませんでした。接続を確認して再試行してください。",
  "secureStorageDescription": "macOS が、このコンピュータのログイン情報を保護するためにキーチェーンへのアクセスを求める場合があります。",
  "secureStorageRestart": "Bottega を再起動してから、もう一度ログインしてください。",
  "retrySecureSave": "安全な保存を再試行",
  "discardSavedLogin": "保存済みログイン情報を破棄…",
  "discardSavedLoginTitle": "このデバイスに保存されたログイン情報を破棄しますか？",
  "discardSavedLoginDescription": "このデバイスのログイン情報を削除するため、再度ログインが必要です。ローカルのコンテンツは保持されます。クラウドのセッションは期限切れまたは取り消しまで有効な場合があり、デバイスの記録も残る場合があります。ログインできない場合は、ウェブのアカウント画面でこのデバイスの古いセッションを取り消してください。",
  "discardSavedLoginConfirm": "ログイン情報を破棄",
  "discardSavedLoginFailed": "ログイン情報の削除を確認できませんでした。新しいログインを開始する前に再試行してください。",
  "discardSavedLoginExpired": "確認の有効期限が切れたか、保存済みのログイン情報が変更されました。内容をもう一度確認してから確定してください。",
  "retryCredentialStorage": "安全なストレージへのアクセスを再試行",
  "openCloudAccount": "ウェブのアカウントを開く",
  "cancelUnconfirmed": "キャンセルはまだ確認されていません。接続が回復すると再試行します。Bottega を起動したままにしてください。",
  "abandonLogin": "このサインインを中止してやり直す",
  "abandonLoginNote": "保留中の要求は、期限切れになるか Web アカウントで取り消すまでサーバー上で有効なままになる場合があります。",
  "openBrowser": "ブラウザを再度開く",
  "loginLinkLabel": "ログインリンク",
  "loginLinkDescription": "ブラウザが開かない場合は、このリンクをコピーしてブラウザに貼り付けてください。",
  "copyLoginLink": "ログインリンクをコピー",
  "loginLinkCopied": "コピーしました",
  "loginLinkCopyFailed": "リンクをコピーできませんでした。リンクを選択して手動でコピーしてください。",
  "verificationCode": "確認コード",
  "expires": "この要求は 5 分後に期限切れになります。",
  "loginTitle": "Bottega へようこそ",
  "loginDescription": "ログインして同期済みのワークスペースを開きます。",
  "account": "アカウント",
  "back": "ワークスペースに戻る",
  "moreActions": "その他の操作",
  "close": "閉じる",
  "download": "Bottega をダウンロード",
  "footer": {
    "copyright": "Bottega © 2026. 無断転載を禁じます。",
    "language": "言語",
    "languageError": "言語を変更できませんでした。もう一度お試しください。",
    "navigation": "フッターナビゲーション",
    "changelog": "更新履歴",
    "docs": "ドキュメント",
    "github": "GitHub",
    "issues": "Issues",
    "download": "ダウンロード"
  },
  "allow": "デスクトップで確認しました。ログインを許可",
  "reject": "この要求に心当たりがありません",
  "openDesktop": "Bottega を開く",
  "approvedTitle": "要求を承認しました",
  "approvedPollingOnly": "Bottega の開発ウィンドウに戻ってログインを完了してください。",
  "loginVersionUnsupported": "クラウドサービスがこのログイン方式に対応していません。サービスを更新して再試行してください。",
  "approved": "Bottega に戻ってログインを完了してください。",
  "rejected": "この要求はキャンセルされました",
  "expired": "ログイン要求の期限が切れました",
  "invalidRequest": "このログイン要求は利用できません",
  "startAgain": "Bottega でもう一度開始してください。",
  "approvalDescription": "このコンピューターの Bottega で開始した要求のみ許可してください。確認コードがデスクトップのウィンドウと一致することを確かめてください。",
  "approvalFailed": "要求を更新できませんでした。再試行してください。",
  "loading": {
    "slow": "ワークスペースを開いています。通信が遅い場合は少し時間がかかります。"
  },
  "status": {
    "deleted": "クラウドアカウントは削除されました",
    "account-switch-required": "アカウントの切り替えを確認して続行してください",
    "local-only": "ローカルのみ",
    "signed-out": "未ログイン",
    "signing-in": "ログイン中…",
    "signing-out": "ログアウトを完了中…",
    "connecting": "接続中…",
    "ready": "ログイン済み",
    "temporarily-offline": "一時的にオフライン",
    "revoked": "このセッションは取り消されました",
    "suspended": "アカウントが制限されています",
    "deleting": "アカウントを削除中です",
    "environment-mismatch": "クラウド環境がこのアプリと一致しません",
    "client-outdated": "Bottega を更新してください",
    "error": "対応が必要です"
  },
  "error": {
    "installation-already-active": "このデバイスの古いセッションがまだ有効です。ウェブのアカウント画面で取り消すと、今回のログインを完了できます。",
    "session-already-bound": "このブラウザは別のデバイス記録でサインイン済みです。サインアウトしてからもう一度サインインしてください。",
    "device-name-unavailable": "このアカウントに登録されたブラウザセッションが多すぎます。アカウントページで古いウェブセッションを削除してから、もう一度サインインしてください。",
    "credentials-environment-mismatch": "保存されたログイン情報は別のクラウド環境のものです。対応する環境を使うか、情報を破棄して再度ログインしてください。",
    "credentials-unreadable": "保存されたログイン情報を解除できませんでした。ファイルは保持されています。安全なストレージを復旧して再試行するか、ログイン情報を破棄してください。",
    "secure-save-failed": "ログイン情報を安全に保存できませんでした。保存を再試行するか、ログインをキャンセルしてください。",
    "browser-open-failed": "ブラウザを開けませんでした。下のログインリンクをコピーするか、もう一度ブラウザを開いてください。",
    "encryption-unavailable": "安全なストレージを利用できません。システムのキーチェーンを確認し、Bottega を再起動してから再試行してください。ローカル機能は引き続き利用できます。",
    "credentials-invalid": "保存されたログイン情報の形式が無効です。Google で続行すると、このログインファイルをリセットします。ローカルのコンテンツは保持されます。",
    "connection-failed": "一時的に接続できません。Bottega はログイン情報を保持して再接続します。",
    "login-expired": "ログイン要求の期限が切れました。もう一度開始してください。",
    "login-rejected": "ログイン要求はキャンセルされました。ご自身の要求であればもう一度開始してください。",
    "rate-limited": "現在ログインの試行が多すぎます。1 分ほど待ってから再試行してください。",
    "sign-out-required": "新しいログインを開始する前に、前のセッションのサインアウトを完了してください。",
    "server-outdated": "このバージョンの Bottega に接続するには、クラウドサービスの更新が必要です。サービスの更新後に再試行してください。",
    "request-failed": "要求を完了できませんでした。再試行してください。",
    "environment-mismatch": "このビルドは現在のクラウド環境に接続できません。",
    "client-outdated": "新しいバージョンの Bottega をインストールしてください。"
  },
  "pending": {
    "preparing": "ログインを準備中…",
    "opening": "ブラウザを開いています…",
    "securing": "ログイン情報を安全に保存中…",
    "waiting": "ブラウザでの承認を待っています…",
    "exchanging": "ログインを完了中…",
    "confirming": "安全なログインを確認中…",
    "registering": "このコンピュータを登録中…",
    "cancelling": "要求をキャンセル中…",
    "connection-failed": "接続の回復を待っています…"
  }
} satisfies CloudCopy;
