/**
 * [INPUT]: Depends on the shared cloud account and approval copy structure.
 * [OUTPUT]: Provides localized account, Sync settings navigation, sync, installation/removal/deletion consent, retained-file and credential recovery, browser-first sign-in, manual-link fallback, approval, footer language copy and the Web gate's slow-open loading sentence.
 * [POS]: Shared UI copy consumed by desktop and Cloud Web without platform dependencies.
 */
import type { CloudCopy } from "./en";
export const cloudCopy = {
  "appDeletion": {
    "expired": "本次确认已过期，尚未保存删除请求。请查看当前 App 后重新确认。",
    "sourceDeleted": "来源 App 已删除，此对话已保留，可继续阅读。",
    "action": "从所有设备删除",
    "title": "从所有设备删除 {{name}}？",
    "details": "这会从云端账号及所有已同步设备移除此 App。已保存的对话将保留为只读。此操作无法撤销。",
    "dataChoice": "App 数据",
    "keepData": "保留 Base 数据",
    "keepDetails": "将 Base 保留为独立、可编辑的数据源。",
    "deleteData": "同时删除 Base 数据",
    "deleteDetails": "永久删除 Base 记录、图片及相关云端文件。",
    "localFiles": "未发布的源码和其他本机文件会留在原电脑上。",
    "offline": "请连接网络并恢复同步，再查看或提交此请求。",
    "reviewing": "正在检查当前 App…",
    "unknown": "尚未确认结果。重试会查询原请求，数据保留选项不会改变。",
    "conflicted": "此 App 在你查看后发生了变化。请查看当前版本，再重新决定。",
    "blocked": "此请求未能删除 App。请查看当前状态，再重新决定。",
    "failed": "无法查看此 App。请联网后重试。",
    "confirmed": "删除已确认。已同步设备将在重新连接后完成处理。",
    "close": "关闭",
    "review": "查看当前 App",
    "retry": "查询原请求",
    "deleting": "正在删除…",
    "confirm": "从所有设备删除",
    "pending": "删除结果待确认",
    "keep": "保留 App",
    "retainedBase": "打开保留的 Base"
  },
  "appRemoval": {
    "manage": "管理云端 App",
    "title": "从此电脑移除 {{name}}？",
    "details": "云端 App 和 Base 继续保留。会话内容会保留，不再具有执行权限。未发布源码、本机文件及配置保留在此电脑；配置的 Agent 读取授权会清除。",
    "confirm": "移除安装",
    "remove": "从此电脑移除",
    "removing": "正在移除安装…",
    "failed": "移除尚未完成。请重试此请求，或返回 App 列表继续。",
    "pending": "本机移除需要处理",
    "resume": "继续移除",
    "retained": "打开保留文件"
  },
  "appInstall": {
    "title": "云端 Apps",
    "installTitle": "安装 {{name}}",
    "updateTitle": "更新 {{name}}",
    "consent": "请检查此版本并确认在这台电脑上的访问权限。配置和权限仅保存在本机。",
    "preparing": "正在下载并检查此版本…",
    "failed": "请求未能完成。请刷新查看当前状态；已开始的安装可从列表继续。",
    "refresh": "刷新",
    "source": "你的云端账号",
    "configuration": "本机配置",
    "agent": "维护 Agent",
    "noAgent": "请先配置一个兼容的 Agent。",
    "confirmInstall": "确认权限并安装",
    "confirmUpdate": "确认权限并更新",
    "installing": "正在安装…",
    "loading": "正在加载云端 Apps…",
    "online": "恢复在线同步后可安装或更新，已下载的 Base 数据仍可使用。",
    "version": "版本 {{version}}",
    "notInstalled": "本机未安装",
    "installed": "已在本机安装",
    "updateAvailable": "有可用更新",
    "interrupted": "安装需要处理",
    "deleted": "已删除",
    "resume": "继续安装",
    "install": "安装",
    "update": "更新",
    "basePending": "正在等待完整的 Base 数据，完成后即可安装。"
  },
  "syncReview": {
    "switchAccount": "确认切换账号",
    "switchTitle": "切换这台电脑的账号",
    "switchBody": "云端数据仍属于原账号。切换后，需为当前账号重新开启同步。",
    "disable": "停用",
    "cloudData": "云端数据",
    "cloudDataDescription": "断开这台电脑并清除它保存的云端副本。退出登录不做其中任何一件。",
    "disableTitle": "停用这台电脑的同步？",
    "disableBody": "这台电脑上仅作为云端镜像的副本将被清除；本机创建或接管的内容及其文件会保留。再次开启同步需要输入同步密码。",
    "disableRemove": "清除 {{mirrors}} 个 Chat 镜像、{{mirroredBases}} 个 Base 镜像、{{mirroredProjects}} 个 Project 镜像和 {{mirroredApps}} 个 App 镜像。",
    "disableKeep": "保留 {{retainedChats}} 个 Chat、{{retainedHomes}} 个 Home 文件夹、{{retainedBases}} 个 Base、{{retainedProjects}} 个 Project 和 {{retainedApps}} 个 App。",
    "disableConfirm": "停用同步",
    "pendingDiscard": "{{count}} 项待同步修改会保留在本机，并解除与此账号的同步关联。",
    "progress": "已完成 {{completed}} / {{total}} 项",
    "pending": "{{count}} 项修改等待同步",
    "conflicts": "{{count}} 项冲突待处理"
  },
  "syncStatus": {
    "partial": "Base 数据已同步，部分 App 版本包需要处理",
    "not-connected": "这台电脑尚未开始同步。",
    "scanning": "正在扫描本机内容…",
    "initializing": "正在准备首次同步…",
    "syncing": "正在同步…",
    "synced": "已是最新",
    "paused": "同步已暂停",
    "offline": "等待网络连接",
    "error": "同步需要处理",
    "closing": "正在解除账号关联…"
  },
  "syncError": {
    "scan-failed": "无法完成本机内容扫描。请在当前导入结束后重试。",
    "review-expired": "本次扫描已过期，请重新扫描后确认。",
    "upload-failed": "部分内容尚未同步。本机副本已保留，请重试继续。",
    "cleanup-failed": "断开此账号未能完成。本机内容已保留，请重试以继续。",
    "library-owned-elsewhere": "这个 Bottega 文件夹属于电脑 {{host}}，当前版本不支持在另一台电脑上打开；新建一个文件夹，或在那台电脑上使用。"
  },
  "syncAppBlocked": {
    "migration-blocked": "此版本需要尚不支持的数据迁移，已保留云端旧版本。",
    "version-conflict": "云端已有其他版本，请核对版本后重试。",
    "not-published": "尚无已发布版本",
    "package-too-large": "版本包超过 50 MB 上限",
    "source-unavailable": "无法验证已发布源码",
    "generation-changed": "扫描期间已发布版本发生变化",
    "association-unavailable": "App 数据关联需要恢复"
  },
  "setup": {
    "signIn": "登录",
    "enable": "完成登录",
    "signInTitle": "登录以同步这台电脑",
    "browserApproval": "你将在浏览器中确认登录。",
    "signedInAs": "当前登录账号：{{email}}",
    "checkCode": "允许登录前，请确认它与浏览器中显示的验证码一致。",
    "enterPassword": "输入同步密码",
    "enterPasswordDescription": "这台电脑将加入你在其他设备上创建的加密空间。Bottega 无法找回该密码。",
    "unlockedDescription": "这台电脑已解锁。完成后开始同步。"
  },
  "syncBadge": {
    "synced": "已是最新",
    "syncing": "同步中",
    "paused": "已暂停",
    "offline": "等待网络连接",
    "attention": "需要处理",
    "locked": "已锁定",
    "checking": "检查中",
    "closing": "正在断开",
    "unavailable": "暂不可用"
  },
  "syncRow": {
    "synced": "本机的所有修改已进入你的云端账号，并使用同步密码进行端到端加密。",
    "locked": "输入同步密码以恢复这台电脑的同步。"
  },
  "syncPhase": {
    "preparing": "正在准备 Chat",
    "projects": "正在上传 Project",
    "apps": "正在上传 App",
    "chats": "正在上传 Chat",
    "bases": "正在上传 Base",
    "files": "正在上传文件",
    "homes": "正在上传 Chat Home"
  },
  "appPackages": {
    "title": "App 版本包",
    "description": "这些 App 的 Base 数据已同步；需要处理其版本包后，才能在其他电脑恢复该 App。",
    "open": "打开 App"
  },
  "platform": {
    "macos": "macOS",
    "windows": "Windows",
    "linux": "Linux",
    "browser": "浏览器"
  },
  "apps": {
    "title": "Apps",
    "capabilities": "App 界面 · 记忆 · 工具",
    "description": "查看和编辑已同步的 App 记录。App 专用界面在电脑上运行。",
    "empty": "此页没有已同步的 App。",
    "version": "版本",
    "packageReady": "源码包已就绪",
    "packagePending": "等待源电脑上传此版本。",
    "partial": "部分数据仅在原电脑。",
    "baseOnly": "Base 记录已纳入同步。",
    "structure": "App 结构由版本更新维护。此处可编辑记录和视图设置。",
    "unavailable": "此 App 已删除或无法访问。",
    "back": "返回 Apps",
    "backToApp": "返回 App"
  },
  "catalog": {
    "titleColumn": "标题",
    "tableView": "表格",
    "noProjects": "这一页没有 Project。",
    "projects": "Projects",
    "bases": "Bases",
    "noBases": "此页暂无已同步的 Base。",


    "openBase": "打开 Base",
    "loading": "正在加载工作区…",
    "readLimit": "此 Base 超出浏览器读取容量。已保留上次完整视图，编辑暂时停用。",
    "historyUnavailable": "云端暂不提供记录修改历史。",
    "original": "原值",
    "source": "来源设备",
    "readUpdating": "此 Base 正在变化，等待完整更新…",
    "readError": "无法加载记录，已保留当前草稿。"
  },
  "recovery": {
    "retrying": "部分内容未能加载，{{seconds}} 秒后重试…",
    "stalled": "仍然无法连接 Bottega Cloud。",
    "retryNow": "立即重试",
    "reload": "刷新页面",
    "unavailable": "此内容当前不可用。"
  },
  "base": {
    "verification": "Base 同步验证",
    "verificationDescription": "此页面用于验证同步事务，完整 Base 工作区仍在开发中。",
    "empty": "暂无记录。",
    "draft": "未保存",
    "saved": "已保存",
    "partial": "部分修改需要处理",
    "outcomeUnknown": "正在核对保存结果…",
    "updating": "正在更新云端数据…",
    "offline": "等待恢复连接后保存",
    "conflicts": "冲突",
    "noConflicts": "没有待处理冲突。",
    "current": "当前值",
    "candidate": "候选值",
    "reviewCurrent": "查看最新值",
    "reviewChanged": "值已再次变化。请重新核对比较结果，再应用候选值。",
    "apply": "应用候选值",
    "discard": "放弃候选值",
    "more": "加载更多",

    "unavailable": "此 Base 无权访问或已被删除。",
    "notInitialized": "尚未初始化同步验证 Base。"
  },
  "workspace": "工作区",
  "navigation": "主导航",
  "notFound": "页面不存在",
  "cloudDevLogin": "登录 Bottega Cloud Dev",
  "cloudLogin": "登录 Bottega",
  "verificationCodeNote": "核对码用于辨认此请求，不是登录凭据。",
  "deletingDescription": "账号删除期间，云端访问已暂停。",
  "verifyingDescription": "正在验证你的登录。",
  "revokedDescription": "退出登录后重新登录即可继续。",
  "restrictedCloudDescription": "此账号的云端访问已受限。",
  "title": "账号",
  "syncUnavailable": "同步暂不可用，你可以继续使用本地功能。",
  "syncSettings": "同步设置",
  "google": "使用 Google 继续",
  "signOut": "登出",
  "cancel": "取消",
  "retry": "重试",
  "retrying": "正在重试…",
  "save": "保存",
  "saving": "正在保存…",
  "rename": "改名",
  "deviceName": "设备名称",
  "revoke": "撤销",
  "revoking": "正在撤销…",
  "revokeTitle": "撤销此会话？",
  "revokeDescription": "此设备将无法访问你的云端账号。已下载的内容仍保留在设备上。",
  "localDescription": "你可以免费使用本地功能。登录后，只有明确确认首次同步，才会上传内容。",
  "sync": "同步",
  "syncNotConnected": "尚未启用同步。",


  "computers": {
    "label": "电脑",
    "offlineSince": "离线 · {{when}}",
    "none": "在一台电脑上登录 Bottega 后，这里会出现它的侧栏。",
    "thisComputer": "本机",
    "name": "电脑名称",
    "nameTaken": "已有同名电脑",
    "notFound": "这台电脑尚未登录该账号。",
    "nameInvalid": "请输入名称。",
    "suffixHint": "已有同名电脑，可在此重命名"
  },
  "devices": "设备",
  "lastSeen": "上次在线：{{when}}",
  "webSession": "Web 会话",
  "appVersion": "Bottega {{version}}",
  "noDevices": "此页没有会话。",
  "current": "当前设备",
  "online": "在线",
  "offline": "离线",
  "revoked": "已撤销",
  "nextPage": "下一页",
  "firstPage": "首页",
  "refresh": "刷新",
  "showPastSessions": "显示历史会话",
  "loadFailed": "无法加载会话，请重试。",
  "actionFailed": "更改未能保存。请检查网络后重试。",
  "secureStorageDescription": "macOS 可能请求钥匙串授权，用于保护这台电脑上的登录信息。",
  "secureStorageRestart": "重启 Bottega 后重新登录。",
  "retrySecureSave": "重试安全保存",
  "discardSavedLogin": "放弃已保存的登录信息…",
  "discardSavedLoginTitle": "放弃这台设备上保存的登录信息？",
  "discardSavedLoginDescription": "这会删除本机保存的登录信息，你需要重新登录。本地内容会保留。此操作无法保证云端会话立即失效；会话可能持续至过期或另行撤销，设备记录可能仍会保留。若重新登录受阻，可在网页账户撤销这台设备的旧会话。",
  "discardSavedLoginConfirm": "放弃登录信息",
  "discardSavedLoginFailed": "无法确认登录信息已被移除。请重试；新登录暂未开放。",
  "discardSavedLoginExpired": "确认已过期或保存的登录信息已变化。请重新核对说明后再确认。",
  "retryCredentialStorage": "重试访问安全存储",
  "openCloudAccount": "打开网页账户",
  "cancelUnconfirmed": "取消尚未确认。连接恢复后将继续尝试，请暂时保持 Bottega 运行。",
  "abandonLogin": "放弃本次登录并重新开始",
  "abandonLoginNote": "服务器上的待处理请求可能仍然有效，直到它过期或你在网页账户中撤销它。",
  "openBrowser": "重新打开浏览器",
  "loginLinkLabel": "登录链接",
  "loginLinkDescription": "浏览器没有打开？复制此链接，粘贴到浏览器中继续登录。",
  "copyLoginLink": "复制登录链接",
  "loginLinkCopied": "链接已复制",
  "loginLinkCopyFailed": "未能复制链接。请选中链接后手动复制。",
  "verificationCode": "验证码",
  "expires": "此请求在五分钟后过期。",
  "loginTitle": "欢迎使用 Bottega",
  "loginDescription": "登录以访问已同步的工作区。",
  "account": "账号",
  "back": "返回工作区",
  "moreActions": "更多操作",
  "close": "关闭",
  "download": "下载 Bottega",
  "footer": {
    "copyright": "Bottega © 2026. 保留所有权利。",
    "language": "语言",
    "languageError": "无法切换语言，请重试。",
    "navigation": "页脚导航",
    "changelog": "更新日志",
    "docs": "文档",
    "github": "GitHub",
    "issues": "问题",
    "download": "下载"
  },
  "allow": "已核对桌面端，允许登录",
  "reject": "不是我发起的请求",
  "openDesktop": "打开 Bottega",
  "approvedTitle": "已批准请求",
  "approvedPollingOnly": "请返回 Bottega 开发窗口完成登录。",
  "loginVersionUnsupported": "云服务不支持此登录版本，请更新服务后重试。",
  "approved": "请返回 Bottega 完成登录。",
  "rejected": "此请求已取消",
  "expired": "此登录请求已过期",
  "invalidRequest": "此登录请求不可用",
  "startAgain": "请在 Bottega 中重新发起。",
  "approvalDescription": "仅允许你在此电脑的 Bottega 中发起的请求。请确认验证码与桌面窗口一致。",
  "approvalFailed": "无法更新此请求，请重试。",
  "loading": {
    "slow": "仍在打开你的工作区。网络较慢时可能需要一会儿。"
  },
  "status": {
    "deleted": "云端账号已删除",
    "account-switch-required": "请确认切换账号后继续",
    "local-only": "仅本地",
    "signed-out": "未登录",
    "signing-in": "正在登录…",
    "signing-out": "正在完成登出…",
    "connecting": "正在连接…",
    "ready": "已登录",
    "temporarily-offline": "暂时离线",
    "revoked": "此会话已撤销",
    "suspended": "账号已受限",
    "deleting": "账号删除处理中",
    "environment-mismatch": "云端环境与此应用不匹配",
    "client-outdated": "请更新 Bottega 后继续",
    "error": "需要处理"
  },
  "error": {
    "installation-already-active": "这台设备的旧会话仍有效。请在网页账户中撤销旧设备会话，Bottega 将继续完成本次登录。",
    "session-already-bound": "此浏览器已绑定到另一台设备记录。请退出后重新登录以继续。",
    "device-name-unavailable": "此账户注册的浏览器会话过多。请在账户页移除旧的网页会话后重新登录。",
    "credentials-environment-mismatch": "已保存的登录信息属于其他云环境。请使用对应环境，或放弃这些登录信息后重新登录。",
    "credentials-unreadable": "无法解锁已保存的登录信息，原文件已保留。你可以恢复安全存储后重试，或放弃这些登录信息。",
    "secure-save-failed": "无法安全保存登录信息。请重试安全保存，或取消本次登录。",
    "browser-open-failed": "无法打开浏览器。请复制下方登录链接，或重新打开浏览器。",
    "encryption-unavailable": "安全存储不可用。请检查系统钥匙串并重启 Bottega 后重试。你可以继续使用本地功能。",
    "credentials-invalid": "已保存的登录格式无效。再次使用 Google 登录将重置此登录文件，本机内容会保留。",
    "connection-failed": "网络暂时不可用。Bottega 会保留登录信息并尝试重新连接。",
    "login-expired": "此登录请求已过期，请重新发起。",
    "login-rejected": "此登录请求已取消。如果由你发起，请重新登录。",
    "rate-limited": "当前登录尝试过于频繁，请等待一分钟后重试。",
    "sign-out-required": "请先完成上一个会话的退出，再开始新的登录。",
    "server-outdated": "云服务需要更新才能连接当前版本的 Bottega，请在服务更新后重试。",
    "request-failed": "无法完成请求，请重试。",
    "environment-mismatch": "此构建无法连接当前云端环境。",
    "client-outdated": "请安装新版 Bottega 后连接。"
  },
  "pending": {
    "preparing": "正在准备登录…",
    "opening": "正在打开浏览器…",
    "securing": "正在安全保存登录信息…",
    "waiting": "等待你在浏览器中批准…",
    "exchanging": "正在完成登录…",
    "confirming": "正在确认安全登录…",
    "registering": "正在注册此电脑…",
    "cancelling": "正在取消请求…",
    "connection-failed": "等待网络恢复…"
  }
} satisfies CloudCopy;
