/**
 * [INPUT]: Depends on the selected interface locale.
 * [OUTPUT]: Provides five-language permanent deletion, conflict and uncertain-result copy.
 * [POS]: Shared Chat deletion product language, independent from platform transport.
 */
const en = { pending: "Deletion is saved on this computer and will be checked when synchronization resumes.", action: "Delete permanently", title: "Delete this conversation?", detail: "The synced conversation, files and its Base will be permanently removed. Other devices will receive the deletion. Retained local copies may remain. This cannot be undone.",
  cancel: "Cancel", deleting: "Deleting…", deleted: "This conversation has been deleted.", failed: "Deletion is not confirmed. Retry to check the original request; the conversation stays here until confirmed.",
  retry: "Check deletion", conflict: "This conversation changed on another device. Nothing was deleted by this request. Review the latest conversation before deleting again.",
  review: "Review deletion again", keep: "Keep conversation", offline: "Reconnect to delete this conversation.", unnamed: "Untitled conversation" };
type Copy = { [K in keyof typeof en]: string };
const copies: Record<string, Copy> = {
  en,
  zh: { pending: "删除请求已保存在这台电脑，恢复同步后会核对结果。", action: "永久删除", title: "删除这段对话？", detail: "云端对话、文件及所属 Base 将被永久删除，其他设备会收到删除通知。已保留的本机副本可能仍然存在。此操作无法撤销。", cancel: "取消", deleting: "正在删除…", deleted: "这段对话已删除。", failed: "删除结果尚未确认。重试会核对原请求，确认前仍保留当前对话。", retry: "核对删除结果", conflict: "这段对话已在其他设备修改，本次请求未删除任何内容。请查看最新对话后重新确认删除。", review: "重新确认删除", keep: "保留对话", offline: "请联网后删除对话。", unnamed: "未命名对话" },
  ja: { pending: "削除リクエストはこのパソコンに保存されています。同期再開後に確認します。", action: "完全に削除", title: "この会話を削除しますか？", detail: "同期済みの会話、ファイル、所属する Base は完全に削除され、他の端末にも通知されます。保持されたローカルコピーは残る場合があります。この操作は取り消せません。", cancel: "キャンセル", deleting: "削除中…", deleted: "この会話は削除されました。", failed: "削除結果を確認できません。再試行で元のリクエストを確認します。確認まで会話は保持されます。", retry: "削除結果を確認", conflict: "別の端末で会話が変更されました。このリクエストでは削除していません。最新の会話を確認してから再度削除してください。", review: "削除を再確認", keep: "会話を保持", offline: "再接続して会話を削除してください。", unnamed: "無題の会話" },
  fr: { pending: "La demande est enregistrée sur cet ordinateur. Elle sera vérifiée à la reprise de la synchronisation.", action: "Supprimer définitivement", title: "Supprimer cette conversation ?", detail: "La conversation synchronisée, ses fichiers et sa Base seront supprimés définitivement. Les autres appareils recevront la suppression. Des copies locales conservées peuvent subsister. Cette action est irréversible.", cancel: "Annuler", deleting: "Suppression…", deleted: "Cette conversation a été supprimée.", failed: "La suppression n’est pas confirmée. Réessayez pour vérifier la demande initiale. La conversation reste visible jusqu’à confirmation.", retry: "Vérifier la suppression", conflict: "Cette conversation a changé sur un autre appareil. Cette demande n’a rien supprimé. Consultez la dernière version avant de confirmer à nouveau.", review: "Revoir la suppression", keep: "Conserver la conversation", offline: "Reconnectez-vous pour supprimer cette conversation.", unnamed: "Conversation sans titre" },
  es: { pending: "La solicitud está guardada en este ordenador. Se comprobará al reanudar la sincronización.", action: "Eliminar permanentemente", title: "¿Eliminar esta conversación?", detail: "La conversación sincronizada, sus archivos y su Base se eliminarán permanentemente. Los demás dispositivos recibirán la eliminación. Las copias locales conservadas pueden permanecer. Esta acción no se puede deshacer.", cancel: "Cancelar", deleting: "Eliminando…", deleted: "Esta conversación se ha eliminado.", failed: "La eliminación no está confirmada. Reintenta para comprobar la solicitud original. La conversación permanece hasta la confirmación.", retry: "Comprobar eliminación", conflict: "Esta conversación cambió en otro dispositivo. Esta solicitud no eliminó nada. Revisa la última versión antes de confirmar de nuevo.", review: "Revisar eliminación", keep: "Conservar conversación", offline: "Vuelve a conectarte para eliminar esta conversación.", unnamed: "Conversación sin título" },
};
export const chatDeletionCopy = (locale: string): Copy => copies[locale.toLowerCase().split("-")[0]!] ?? en;
