/**
 * [INPUT]: Depends on the Objective-C sources in resources/system-dock/native, macOS Command Line Tools, the closed output-root resolver, and the appId of the builder config that packages that output root.
 * [OUTPUT]: Provides arm64 `system-dock-bridge` and `bottega-dock-recovery` under <output>/system-dock/bin and the SMAppService LaunchAgent plist <appId>.dock-recovery.plist under <output>/system-dock/LaunchAgents.
 * [POS]: Native build step for Bottega Dock, run next to the presence helper build; generated bytes stay outside source inputs and non-darwin hosts skip it.
 */

import process from "node:process";
import { mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { resolveOutputRoot } from "../assembly/output-root.mjs";

const outputRoot = resolveOutputRoot(process.argv.slice(2));
const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const native = resolve(root, "resources/system-dock/native");
const bundleProgram = "Contents/Resources/system-dock/bin/bottega-dock-recovery";

/** Each output root is packaged by exactly one builder identity; the recovery label follows that bundle id. */
function packagedAppId() {
  const config = outputRoot === "out" ? "electron-builder.yml" : "config/electron-builder.cloud-dev.yml";
  const appId = /^appId:\s*([A-Za-z0-9.-]+)\s*$/m.exec(readFileSync(resolve(root, config), "utf8"))?.[1];
  if (!appId) throw new Error(`No appId in ${config}`);
  return appId;
}
const escape = (text) => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
/** Label passed as argv[1] so the agent needs no launchd check-in API; RunAtLoad is the login-time recovery trigger. */
function launchAgentPlist(appId, label) {
  const string = (value) => `<string>${escape(value)}</string>`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  ${string(label)}
  <key>BundleProgram</key>
  ${string(bundleProgram)}
  <key>ProgramArguments</key>
  <array>
    ${string("bottega-dock-recovery")}
    ${string(label)}
  </array>
  <key>MachServices</key>
  <dict>
    <key>${escape(label)}</key>
    <true/>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <false/>
  <key>ProcessType</key>
  ${string("Background")}
  <key>AssociatedBundleIdentifiers</key>
  <array>
    ${string(appId)}
  </array>
</dict>
</plist>
`;
}
function compile(output, sources, frameworks) {
  const args = ["clang", "-arch", "arm64", "-fobjc-arc", "-O2", "-mmacosx-version-min=15.0",
    ...frameworks.flatMap((name) => ["-framework", name]), ...sources.map((name) => resolve(native, name)), "-o", output];
  const result = spawnSync("xcrun", args, { stdio: "inherit" });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

if (process.platform === "darwin") {
  const bin = resolve(root, outputRoot, "system-dock/bin");
  const agents = resolve(root, outputRoot, "system-dock/LaunchAgents");
  mkdirSync(bin, { recursive: true });
  // A renamed identity must not leave the previous label's plist behind for the builder to package.
  rmSync(agents, { recursive: true, force: true });
  mkdirSync(agents, { recursive: true });
  compile(resolve(bin, "system-dock-bridge"), ["bridge.m", "bridge-system.m", "shared.m"],
    ["AppKit", "ApplicationServices", "CoreServices", "Foundation", "Security"]);
  compile(resolve(bin, "bottega-dock-recovery"), ["recovery-agent.m", "shared.m"], ["AppKit", "Foundation", "Security"]);
  const appId = packagedAppId();
  const label = `${appId}.dock-recovery`;
  writeFileSync(resolve(agents, `${label}.plist`), launchAgentPlist(appId, label));
}
