/**
 * [INPUT]: Canonical built-in Provider ids; The confirmed U01–U07 canvas copy and the Copy board glossary (4-ui.md §7–§8).
 * [OUTPUT]: Provides en, the reference workbench catalog, and the WorkbenchCopy shape every locale must match.
 * Names built-in recipes and Workflow plugins and explains missing workflow measurements.
 * [POS]: Source language of workbench-copy; the only catalog that loads eagerly.
 */
import { BUILTIN_PROVIDER_IDS } from "@bottega/contracts/model/provider-capabilities";
import { memoryPluginCopy } from "./memory/en";
import { dock } from "./dock/en";
export const en = {
  guiHistory: {
    title: "Versions",
    current: "Current",
    previous: "Previous",
    activate: "Use this version",
    switching: "Switching…",
    pending: "Complete the pending authorization to activate this version.",
    loadFailed: "Could not load versions.",
    empty: "No built version yet.",
    initializing: "Preparing this plugin…",
    initializationFailed: "Could not initialize this plugin. Retry to prepare it again.",
    retryInitialization: "Retry initialization",
    initializationDetails: "Error details",
    refresh: "Refresh",
    edit: "Edit source",
    installLocal: "Install from folder…",
    draftBusy: "Finish or clear the current draft before opening a plugin source Chat.",
    skillMissing: "The plugin-authoring Skill is unavailable for this Agent.",
    starterPrompt: "Use the plugin-authoring Skill to create this plugin. Describe and implement the behavior I request below.",
  },
  terms: {
    pluginsAndApps: "Plugins",
    bottegaPlugin: "Bottega plugin",
    agentNativePlugin: "Agent native plugin",
    baseApp: "Base (built-in App)",
    baseBackedApp: "Base-backed App",
    agentConfig: "Agent config",
    workflow: "Workflow",
    run: "Run",
  },
  base: {
    menuGroup: "Workflow",
    setUp: "Set up a workflow…",
    settings: "Workflow settings",
    runWorkflow: "Run workflow",
    runOnTask: "Run a workflow on this task",
    ready: "Ready",
  },
  readOnly: {
    badge: "Workflow",
    columnHint: "Only workflows change this column",
    setByWorkflow: "Set by the workflow",
    laneLocked: "{{column}} is set by the workflow, so this lane does not take cards. Change your own columns instead, or open the run to change what happens next.",
    whoCanEdit: "Who can edit",
    everyone: "Everyone",
    onlyWorkflows: "Only workflows",
    whoCanEditUnavailable: "Only columns a workflow adds can be limited.",
  },
  record: {
    section: "Workflow",
    run: "Run",
    noRuns: "No runs yet",
    acceptance: "Acceptance",
    notDecided: "Not decided",
    accepted: "Accepted",
    acceptedWithException: "Accepted with exception",
  },
  plugins: {
    title: "Plugins",
    description: "The plugins installed on this Bottega host. Turn one on or off, apply updates, or open it for settings and details.",
    searchLabel: "Search plugins",
    statusLabel: "Status",
    statusAll: "All statuses",
    statusOn: "On",
    statusOff: "Off",
    statusAttention: "Needs attention",
    sortLabel: "Sort",
    sortGroup: "By category",
    sortName: "By name",
    sortRecent: "Recently changed",
    newPlugin: "New plugin",
    groupFeature: "Bottega features",
    groupProvider: "Providers",
    groupPackage: "Extensions",
    groupNative: "Agent native plugins",
    emptyTitle: "No plugins match",
    clearFilters: "Clear search and filters",
    emptyAll: "No plugins installed.",
    official: "Official",
    badgeBuiltin: "Built-in",
    badgePackage: "Extension · v{{version}}",
    badgeNative: "Agent native",
    alwaysOn: "Always on",
    nativeManagedBy: "Managed by {{agent}}",
    projectScopedBadge: "One Project only",
    projectScopedNote: "Installed for one Project, so it can’t be turned off here yet.",
    setupDock: "Set up…",
    blocked: "Missing dependency",
    unsupported: "Not supported here",
    providerUsedBy_one: "Used by {{count}} Agent config",
    providerUsedBy_other: "Used by {{count}} Agent configs",
    providerUnused: "Not used yet",
    workflowSetUpIn_one: "Set up in {{count}} Project",
    workflowSetUpIn_other: "Set up in {{count}} Projects",
    workflowSetUpInNames: "Set up in {{projects}}",
    turnedOffOn: "Turned off {{date}}",
    neverOn: "Never turned on",
    turnOffTitle: "Turn off {{name}}?",
    turnOffBody: "{{name}} will no longer start on {{computer}}. Nothing is deleted, and you can turn it back on anytime.",
    whatChanges: "What changes",
    impactConfigs: "Agent config {{config}} can’t be chosen",
    impactWorkflows: "{{workflow}} can’t start new runs while {{name}} is off",
    impactRuns_one: "{{count}} run using {{name}} will finish its current step, then pause",
    impactRuns_other: "{{count}} runs using {{name}} will finish their current step, then pause",
    impactChats_one: "{{count}} Chat with {{name}} stays readable but can’t continue",
    impactChats_other: "{{count}} Chats with {{name}} stay readable but can’t continue",
    impactMore_one: "and {{count}} more",
    impactMore_other: "and {{count}} more",
    dependentsTitle: "These plugins will stop working",
    dependentLine: "{{plugin}}: it needs something only {{name}} provides",
    turnOff: "Turn off",
    turnOn: "Turn on",
    thisComputer: "this computer",
    switchFailed: "Couldn’t change {{name}}. Try again.",
    switchLabel: "Turn {{name}} on or off",
    reinstallRequired: "{{name}}’s installed files changed while it was off, so it can’t be turned back on yet.",
    reinstallHelp: "Tell us and we’ll help you restore it.",
    reinstallIssueTitle: "{{name}} can’t be turned back on",
    reinstallBadge: "Can’t turn back on",
    reportProblem: "Report a problem",
    busyNote: "{{name}} is busy. You can change it once it’s done.",
    turningOn: "Turning on…",
    turningOff: "Turning off…",
    chatTurnedOff: "{{provider}} is turned off in Plugins. Turn it back on to continue this Chat.",
    openPlugin: "Open {{name}}",
    back: "All plugins",
    on: "On",
    off: "Off",
    sectionSettings: "Settings",
    settingsNote: "Declared by the plugin",
    settingsProviderNote: "Existing sessions are not affected",
    appliesImmediate: "Applies now",
    appliesNextTurn: "Next turn",
    appliesSessionCreate: "New sessions",
    appliesProcessStart: "After restart",
    changed: "Changed",
    resetDefault: "Reset to default",
    confirmContinue: "Continue",
    secretSet: "Set",
    secretUnset: "Not set",
    secretReplace: "Replace",
    secretClear: "Clear",
    secretSave: "Save",
    secretCancel: "Cancel",
    decrease: "Decrease",
    increase: "Increase",
    settingsFailed: "Couldn’t save {{setting}}. Try again.",
    pendingRestart: "{{name}} will restart when it’s idle to apply your changes.",
    sectionHealth: "Health",
    checkedAt: "Checked {{time}}",
    update: "Update",
    setUp: "Set up",
    sectionUsedBy: "Used by",
    usedByConfigs: "Agent configs",
    usedByProjects: "Projects with workflows",
    usedByNobody: "Nothing uses it yet.",
    sectionDependencies: "Dependencies",
    depRequires: "Needs",
    depProvides: "Provides",
    depDependents: "Needed by",
    depNone: "None",
    depSatisfiedBy: "Met by {{plugins}}",
    depHostNote: "Settings, storage, events and background work come from Bottega and are always available.",
    blockedMissing: "Nothing provides it",
    blockedDisabled: "Everything that provides it is off",
    blockedUnsupported: "What provides it can’t run on this computer",
    blockedCycle: "It depends on itself in a loop",
    blockedBanner: "{{name}} can’t start new work. {{reason}}.",
    sectionCapabilities: "Capabilities and permissions",
    capabilitiesNone: "Nothing declared.",
    sectionIncludes: "Includes",
    sectionCanDo: "What it can do",
    sectionWorksWith: "Works with",
    sectionInUse: "In use",
    sectionInformation: "Information",
    worksAlone: "Works on its own. Nothing else depends on it.",
    aboutPlugin: "About {{name}}",
    publisherBottega: "Bottega",
    about: "About",
    aboutSource: "Source",
    aboutVersion: "Version",
    aboutKind: "Kind",
    aboutId: "Plugin ID",
    aboutManagedBy: "Managed by",
    aboutLocation: "Location",
    aboutPublisher: "Publisher",
    unsigned: "Not signed",
    versionWithApp: "Comes with Bottega {{version}}",
    kindFeature: "Feature",
    kindProvider: "Provider",
    sourceLocalLong: "Local source",
    sourceBuiltinLong: "Built into Bottega",
    sourcePackageLong: "Extension",
    sourceNativeLong: "Agent native",
    related: "Related pages",
    relatedProviders: "Providers",
    relatedAgentConfigs: "Agent configs",
    relatedUsage: "Usage",
    relatedSkills: "Skills",
    relatedMemory: "Memory",
    relatedDock: "Dock",
    nativeReadOnly: "Managed by {{agent}}. Bottega only lists it here; install, update or remove it in {{agent}}.",
    notFound: "This plugin isn’t installed anymore.",
    loadFailed: "Couldn’t load this plugin. Try again.",
    retry: "Try again",
    sidebarGroup: "Plugins",
    sidebarAll: "All plugins",
    health: {
      unknown: "Not checked yet",
      notChecked: "Not checked yet",
      ready: "Ready",
      off: "Off",
      running: "Running",
      idle: "Ready, not running",
      process: "Process",
      processRunning: "Running",
      processIdle: "Starts when needed",
      nativeEnabled: "{{agent}} reports it on",
      nativeDisabled: "{{agent}} reports it off",
      cliVersion: "CLI",
      signIn: "Sign-in",
      runningRuns: "Runs in progress",
      cli: {
        unknown: "Not checked",
        missing: "Not installed",
        error: "Couldn’t check",
        unsupported: "Needs an update",
        installed: "Installed",
      },
      auth: {
        unknown: "Unknown",
        checking: "Checking…",
        authenticated: "Signed in",
        unauthenticated: "Not signed in",
        error: "Couldn’t check",
      },
    },
    unsupportedReason: {
      appleSilicon: "Only on macOS with Apple silicon",
    },
    capability: {
      startProcess: "Starts its CLI on this computer",
      projectFiles: "Reads and writes Project folders, as each Agent config allows",
      network: "Connects to its own service",
      baseStore: "Keeps tables in each Project’s folder",
      baseTools: "Gives Agents Base tools to read, write and query records",
      workflowColumns: "Adds Stage and Acceptance columns to a Base; only workflows write Stage",
      workflowRoles: "Runs each role as its Agent config",
    },
    builtin: {
      memory: memoryPluginCopy,
      dock,
      sketch: { name: "Sketch", summary: "Draw, erase and attach an editable image.", description: "Sketch adds a drawing canvas to the composer. Draw, erase and annotate, then attach the result to your message as an editable image." },
      base: {
        name: "Base",
        summary: "Tables, boards, lists and forms in every Project. Workflows and Base-backed Apps build on it.",
        description: "Base gives every Project its own tables. Lay records out as a table, board, list or form, kept in the Project’s folder next to your files.\n\nAgents read, write and query records with Base tools. Workflows and Base-backed Apps are built on it, so it is always on.",
      },
      workflow: {
        name: "Workflow",
        summary: "Agent roles move work forward on a Base, step by step, with a review at each step.",
        description: "Workflow turns a Base into a pipeline. Each step is a role played by one of your Agent configs, and each step ends with a review before work moves on.\n\nSet it up in a Project and add cards to its first column. Open any run to see what each role did and change what happens next.",
      },
      [BUILTIN_PROVIDER_IDS.claude]: {
        name: "Claude",
        summary: "Anthropic’s Claude Code, running as an Agent in Bottega.",
        description: "Run Anthropic’s Claude Code as an Agent in Bottega. It works in your Project folders with the access each Agent config allows.\n\nIt needs the Claude Code CLI and a signed-in Anthropic account on this computer. Extras like the 1M context window and Claude in Chrome are in its settings.",
        publisher: "Anthropic",
        settings: {
          memory: {
            label: "Memory",
            description: "Let Claude Code read and write its own auto memory in Bottega’s Chats. Workflow roles never use it.",
          },
          nativeSubagents: {
            label: "Allow native subagents",
            description: "Let Claude Code start its own subagents with its Task tool.",
          },
          workflowTool: {
            label: "Allow Workflow tool",
            description: "Let Claude Code use its own Workflow tool.",
          },
          context1m: {
            label: "Use 1M context",
            description: "Let Claude Code use a context window of one million tokens.",
          },
          claudeInChrome: {
            label: "Claude in Chrome",
            description: "Start Claude Code with the Claude in Chrome browser tools. Needs the Chrome extension on this computer, signed in to claude.ai.",
          },
        },
      },
      [BUILTIN_PROVIDER_IDS.codex]: {
        name: "Codex",
        summary: "OpenAI’s Codex CLI, running as an Agent in Bottega.",
        description: "Run OpenAI’s Codex CLI as an Agent in Bottega. It reads and edits your Project folders within the limits of each Agent config.\n\nIt needs the Codex CLI and a signed-in OpenAI account on this computer. Its own memories and multi-agent feature can be turned off in its settings.",
        publisher: "OpenAI",
        settings: {
          memory: {
            label: "Memory",
            description: "Let Codex use its own memories in Bottega’s Chats. Workflow roles never use them.",
          },
          nativeSubagents: {
            label: "Allow native subagents",
            description: "Let Codex use its own multi-agent feature.",
          },
        },
      },
      [BUILTIN_PROVIDER_IDS.kimi]: {
        name: "Kimi",
        summary: "Moonshot’s Kimi CLI, running as an Agent in Bottega.",
        description: "Run Moonshot’s Kimi CLI as an Agent in Bottega. It needs the Kimi CLI and a signed-in Moonshot account on this computer.",
        publisher: "Moonshot AI",
      },
      [BUILTIN_PROVIDER_IDS.opencode]: {
        name: "OpenCode",
        summary: "Open-source OpenCode, which can use models from many services.",
        description: "Run the open-source OpenCode CLI as an Agent in Bottega. It can use models from many services.",
        publisher: "OpenCode",
      },
    },
  },
  agentConfigs: {
    loading: "Loading Agent configs…",
    loadFailed: "Couldn’t load Agent configs. Try again.",
    refreshFailed: "Couldn’t refresh Agent configs. The last loaded list is still shown.",
    unavailable: "Agent configs are unavailable in this window. Try again or reopen Settings.",
    reasoningEffort: "Reasoning effort",
    agentDefault: "Agent default",
    modelsFailed: "Couldn’t load models. Your selections are kept.",
    defaultsFailed: "Couldn’t load your saved defaults. Choose a model or retry.",
    optionUnavailable: "This saved choice is unavailable here. It will be kept unless you choose another option.",
    chooseModelForEffort: "Choose an available model to see its reasoning options.",
    baseResource: "Base",
    chatResource: "Chat",
    mcpResource: "MCP",
    selectedCount: "{{count}} / {{limit}} selected",
    resourcesLoading: "Loading local resources…",
    resourcesFailed: "Some resources could not be loaded. Your selections are kept.",
    resourcesEmpty: "No local resources available.",
    resourceUnavailable: "Unavailable here",
    baseRead: "Read only",
    baseReadWrite: "Read and write",
    linkedChats: "Linked Chats only",
    resourcesHint: "Only selected resources are available in new runs. Missing resources on another computer block the run until fixed.",
    resourcesReadOnly: "Planning, review and read-only configurations can only read the Base and cannot use MCP servers.",
    baseCapped: "Requested: read and write. Effective: read only. The saved request is preserved.",
    removeReadOnlyMcp: "Remove the selected MCP servers to save a read-only configuration.",
    retryResources: "Reload resources",
    title: "Agent configs",
    description: "Reusable Provider, model, instructions and tools.",
    allProjects: "All Projects",
    someProjects: "Some Projects",
    someProjectsDescription: "Shown only in the Projects listed under each config.",
    newConfig: "New config",
    edit: "Edit",
    readOnly: "Read-only",
    newTitle: "New Agent config",
    editTitle: "Edit Agent config",
    prefilled: "{{role}} is pre-filled: role, permissions and tools. Everything stays editable.",
    startFrom: "Start from",
    blank: "Blank",
    planner: "Planner",
    developer: "Developer",
    reviewer: "Reviewer",
    name: "Name",
    availableIn: "Available in",
    searchProjects: "Search Projects",
    provider: "Provider",
    chooseProvider: "Choose a Provider",
    model: "Model",
    providerDefault: "Provider default",
    instructions: "Instructions",
    instructionsHint: "Sent to the Agent",
    purpose: "Purpose",
    purposeHint: "Shown to people choosing a config",
    permissions: "Permissions",
    skills: "Skills",
    toolsAndData: "Tools and data",
    toolsBaseReadWriteLinked: "Base read and write · linked chats only",
    toolsBaseReadLinked: "Base read · linked chats only",
    none: "None",
    create: "Create",
    missingRequired: "Add a name and choose a Provider",
    appliesToNewRuns: "Changes apply to runs that start after you save.",
    appliesNextTurn: "Applies next turn",
    restartsAgent: "Restarts the Agent",
    appliesOnNew: "Applies to new chats",
    notForRole: "Not for this role",
    notAdmitted: "Not admitted as a {{role}} yet",
    partialFailure: "Some settings could not be applied, so this config is not ready for its role.",
    presetPlanner: "Read the task and its acceptance criteria, then write a step-by-step plan. Do not change code.",
    presetDeveloper: "Follow the accepted plan. Keep changes inside the task. Run the Project checks before reporting back.",
    presetReviewer: "Check the result against the plan and the acceptance criteria. Report what is missing. Do not change code.",
    emptyTitle: "No Agent configs yet",
    emptyBody: "Create one to choose it for a workflow step.",
    syncing: "Syncing",
    conflicted: "Needs review",
    notSynced: "Not synced",
    syncIssueBudget: "This account has reached its limit of 100 Agent configs, so this one hasn’t synced yet. Delete a config you no longer use and it will sync automatically.",
    saveFailed: "Couldn’t save this config. Your changes are still here.",
    allProjectsHint: "Offered in every Project",
    noProjects: "No Projects yet",
    needsAttention: "Needs attention",
    guaranteeReadOnly: "Read-only workspace",
    guaranteeNoNetwork: "No network",
    reasonProviderCannot: "{{provider}} can’t guarantee this",
    reasonHostCannot: "This computer can’t enforce this",
    reasonHostUnavailable: "Can’t check: the computer that runs it isn’t available",
    reasonNotMeasured: "Not verified yet",
    applyPartial: "{{settings}} didn’t take effect on this computer, so workflows can’t use this config yet.",
    applyPartialGeneric: "Some settings didn’t take effect on this computer, so workflows can’t use this config yet.",
    workspace: "Workspace",
    workspaceWrite: "Can change files",
    workspaceReadOnly: "Read-only",
    network: "Network",
    networkOn: "On",
    networkOff: "Off",
    notReadOnly: "Its workspace isn’t set to read-only",
    providerTurnedOff: "{{provider}} is turned off",
  },
  setup: {
    enableTitle: "Turn on workflow",
    enableDescription: "Plan, develop and review on this computer.",
    enableAndRun: "Turn on and run this row",
    noReadyProvider: "No Provider is ready for this workflow.",
    openSettings: "Open settings",
    openBase: "Open Base to manage columns",
    openProject: "Open Project settings",
    projectUnavailable: "Choose a workspace folder in Project settings first.",
    enableFailed: "Couldn’t turn on the workflow. Check again to refresh its requirements.",
    checkAgain: "Check again",
    refusalSkillUnavailable: "A selected Skill in {{config}} is missing or disabled on this computer.",
    refusalMcpUnavailable: "A selected MCP server in {{config}} is unavailable on this computer.",
    refusalMcpReadOnly: "{{config}} selects MCP servers, which planning and review cannot use. Remove that selection or choose another config.",
    planDevelopReview: "Plan · Develop · Review",
    newTitle: "Set up a workflow",
    editTitle: "Workflow settings",
    stepOf: "Step {{current}} of {{total}}",
    tabWorkflow: "Workflow",
    tabWho: "Who does what",
    tabBase: "Your Base",
    tabCheck: "Check",
    chooseTitle: "Choose a workflow",
    whoTitle: "Who does each step",
    whoHint: "Click a name to change it.",
    whoGreyedHint: "Each list shows who can do that step; the others are greyed out with the reason.",
    you: "You",
    addStep: "Add a step",
    stepPlan: "Plan",
    stepPlanDescription: "Writes a plan for the task",
    stepConfirm: "Confirm",
    stepConfirmDescription: "You read the plan and accept it",
    stepDevelop: "Develop",
    stepDevelopDescription: "Changes the code",
    stepReview: "Review",
    stepReviewDescription: "Checks the result without changing it",
    stageDone: "Done",
    stepDecide: "Decide",
    stepDecideDescription: "You accept, end or rework",
    youConfirm: "You confirm",
    youDecide: "You decide",
    baseTitle: "What changes in your Base",
    baseIntro_one: "The workflow adds 1 column. Nothing you have is changed.",
    baseIntro_other: "The workflow adds {{count}} columns. Nothing you have is changed.",
    baseIntroEditing: "Your Base already has the workflow’s columns. Nothing here changes.",
    baseNow: "Now",
    baseAfter: "After turning on",
    baseNewColumns_one: "Your Base gets 1 new column",
    baseNewColumns_other: "Your Base gets {{count}} new columns",
    stageColumn: "Stage",
    stageDescription: "Shows where each task is. The workflow updates it; you can’t edit it.",
    acceptanceColumn: "Acceptance criteria",
    boardView: "Board · by Stage",
    acceptanceDescription: "You write what “done” means for each task.",
    baseOthersUnchanged: "Your other columns stay as they are.",
    baseFixedColumns: "The workflow decides these two columns; they can’t be changed here.",
    baseFull_one: "This Base already has {{existing}} of its {{limit}} columns. Remove 1 column in the Base to turn on the workflow.",
    baseFull_other: "This Base already has {{existing}} of its {{limit}} columns. Remove {{count}} columns in the Base to turn on the workflow.",
    baseBoardAdded: "Adds the view “{{view}}” and opens it. Your other views stay as they are.",
    baseBoardNoRoom: "This Base already has {{limit}} views, so no “{{view}}” view is added. The workflow still turns on.",
    baseChanged: "The Base’s columns changed while this window was open. This shows them as they are now.",
    checkTitle: "Check and turn on",
    checkedOn: "Checked on {{computer}}.",
    providerReady: "{{provider}} is ready on {{computer}}",
    checking: "Checking on this computer…",
    roleReady: "{{step}}: {{provider}} is ready on {{computer}}",
    roleProblem: "{{step}}: {{reason}}",
    refusalDeleted: "This config was deleted.",
    refusalNotEnabled: "{{config}} was made on another device and hasn’t been saved on {{computer}} yet. Open it in Agent configs and save it once.",
    refusalMismatch: "{{config}} switched to a different Provider and needs confirming. Open it in Agent configs and save it once.",
    refusalSelection: "{{config}} sets its own Memory, which workflow steps can’t use yet. Choose another config.",
    refusalMemoryWrite: "{{config}} requests Memory writes. Workflow steps can only read Memory.",
    refusalScope: "{{config}} uses Skills or Tools settings that workflow steps don’t support. Open the config and save it again.",
    refusalPartial: "{{config}}’s {{settings}} didn’t take effect on {{computer}}. Open the config to fix it.",
    refusalPartialGeneric: "Some of {{config}}’s settings didn’t take effect on {{computer}}. Open the config to check them.",
    refusalReadOnly: "Asks for a read-only workspace, so it can’t change the code.",
    refusalNoNetwork: "Asks for no network, which can’t be guaranteed on {{computer}} yet.",
    baseHasRoom_one: "The Base has room for 1 more column",
    baseHasRoom_other: "The Base has room for {{count}} more columns",
    baseGets: "Base gets",
    needsComputer: "Needs {{computer}} online",
    turnOn: "Turn on",
    continue: "Continue",
    back: "Back",
  },
  projectWorkflows: {
    tab: "Workflows",
    description: "Workflows you can run from a task in this Project’s Base.",
    addWorkflow: "Add workflow",
    on: "On",
    off: "Off",
    runsOn: "runs on {{computer}}",
    configsTitle: "Agent configs for this Project",
    configsHint: "Personal configs are in Settings › Agent configs.",
    availableIn: "Available in {{projects}}",
    needsBase: "Add a workflow once this Project has a Base. Workflows run on the tasks in it.",
    workflowChats_one: "{{count}} workflow Chat",
    workflowChats_other: "{{count}} workflow Chats",
    workflowRuns_one: "{{count}} run",
    workflowRuns_other: "{{count}} runs",
    alsoArchived: "Also archived with it: {{chats}} from {{runs}}.",
    alsoArchivedNoRuns: "Also archived with it: {{chats}}.",
    alsoDeleted: "This Project’s {{chats}} will be deleted with it.",
    archiveStepRunning: "A workflow step is running, so this can’t be archived yet. The run pauses when the step ends. Try again then.",
    runsStillStopping: "A workflow run of this Project is still stopping, and a process may still be running. Force stop it from the run, then try again.",
    runtimeNotReady: "Workflows are still starting on this computer. Try again in a moment.",
  },
  run: {
    blockedVersionTooOld: "{{provider}} on {{computer}} needs an update before it can run this workflow.",
    blockedExtractorVersionTooOld: "{{step}} did not return a valid result. Update Claude on {{computer}} to organize it.",
    label: "Run #{{number}}",
    onComputer: "on {{computer}}",
    queued: "Queued",
    running: "Running",
    needsYou: "Needs you",
    paused: "Paused",
    blocked: "Blocked",
    cancelling: "Cancelling…",
    succeeded: "Succeeded",
    failed: "Failed",
    cancelled: "Cancelled",
    stopped: "Stopped",
    stoppedForced: "Stopped (forced)",
    pausedWaited: "Paused · Waited 24 h",
    pausedArchived: "Paused · Project archived",
    cancellingTitle: "Cancelling",
    cancellingBody: "No new steps will start. Bottega is stopping {{provider}} on {{computer}}; this can take a few seconds. It is not stopped until this says so.",
    stuckTitle: "Still stopping after 30 seconds",
    stuckBody: "{{provider}} on {{computer}} has not exited. You can force it to stop. Code it already changed stays in the workspace; check it before the next run.",
    forceStop: "Force stop",
    forceStopUnconfirmedTitle: "A process may still be running",
    forceStopUnconfirmedBody: "Bottega stopped the step on {{computer}} but couldn’t confirm every process ended. Force stop again, then check the workspace before the next run.",
    waitingFor: "Waiting for {{computer}}",
    reminder: "The plan has waited 23 hours. Decide within 1 hour, or the run pauses.",
    waitingStarted: "A plan is ready for you to review.",
    reminderResult: "The result has waited 23 hours. Decide within 1 hour, or the run pauses.",
    waitingStartedResult: "A result is ready for your decision.",
    pauseConfirmationTimeout: "Paused: this confirmation waited more than 24 hours. Continue to be asked again.",
    pausedNotice: "Paused after waiting 24 hours. Nothing ran. Open it to continue.",
    resume: "Continue",
    resultUnknown: "Result unknown",
    resultUnknownBody: "{{computer}} accepted this at {{time}}, but the result did not come back. It will not be sent again on its own.",
    checkResult: "Check result",
    acceptPlan: "Accept plan",
    accept: "Accept",
    acceptWithException: "Accept with an exception",
    exceptionReason: "Why are you accepting it anyway?",
    exceptionReasonRequired: "Write a reason to accept with an exception.",
    end: "End",
    rework: "Rework",
    reworkFromDevelop: "Keep the accepted plan and start from Develop",
    replan: "Plan again",
    reconfirm: "The acceptance criteria changed. Confirm the plan again before the run continues.",
    alreadyHandled: "Already handled on {{device}}",
    viewResult: "View result",
    viewLog: "View log",
    tryAgain: "Try again",
    details: "Run details",
    startRun: "Start run",
    pause: "Pause",
    cancelRun: "Cancel run",
    cancelConfirmTitle: "Cancel this run?",
    cancelConfirmBody: "The step in progress stops first; code it already changed stays in the workspace. This run won’t go on; you can start again later.",
    keepRunning: "Keep running",
    forceConfirmTitle: "Force stop?",
    forceConfirmBody: "This ends every process of this step on {{computer}} at once. What it already changed isn’t undone; check the workspace before the next run.",
    keepWaiting: "Keep waiting",
    openChat: "Open Chat",
    artifact: "Result",
    evidence: "Evidence",
    stepPending: "Not started",
    stepRunning: "Running",
    stepWaiting: "Waiting for you",
    stepSucceeded: "Done",
    stepFailed: "Failed",
    stepBlocked: "Blocked",
    stepCarried: "From the accepted plan",
    stepNotRun: "Not run",
    pauseUser: "You paused this run.",
    pauseProjectArchived: "Paused because the Project was archived. Restore the Project, then continue.",
    pauseProjectRestored: "This run was paused when the Project was archived. Continue when you’re ready.",
    pausingAfterStep: "This run pauses when the current step ends.",
    pausingArchived: "The Project was archived. This run pauses when the current step ends.",
    projectArchived: "This Project is archived, so its runs can’t be started or continued. Restore the Project, then continue the run yourself.",
    pauseBindingSuspended: "Paused: the workflow’s setup changed. Fix it, then continue or cancel.",
    pausePluginDisabled: "Paused: {{provider}} is turned off in Plugins. Turn it back on, then continue or cancel.",
    waitingWorkspace: "Waiting for workspace",
    waitingWorkspaceBody: "Waiting for “{{task}}” to finish writing this workspace. One record develops in a workspace at a time; this starts on its own when it’s free.",
    waitingWorkspaceStuck: "The run for “{{task}}” may still have a process running; this starts after you resolve it there.",
    viewHoldingRun: "View that run",
    pausePluginWorkflow: "Paused: Workflows are turned off in Plugins. Turn them on to continue, or cancel now.",
    pausePluginWorkflowOn: "Paused: Workflows are turned off in Plugins on {{computer}}. Turn them back on there to continue, or cancel now.",
    workflowOffAction: "Workflows are turned off in Plugins. Turn them on to continue.",
    workflowBlockedAction: "Workflows can’t start: no Provider is turned on in Plugins. Turn one on to continue.",
    staleProposal: "The task or acceptance criteria changed while this was waiting, so you’re asked again with what the record says now.",
    stoppedForcedHint: "Stopped by force. Check the workspace before the next run.",
    stoppedForcedAtStartupHint: "Stopped by force, confirmed after the restart. Check the workspace before the next run.",
    stoppingFor: "stopping for {{seconds}} s",
    confirmPlanTitle: "Confirm the plan",
    confirmResultTitle: "Decide on the result",
    reworkTitle: "Rework",
    reworkStart: "Start rework",
    reworkReasonAcceptance: "The acceptance criteria changed",
    reworkReasonTask: "The task changed",
    reworkKeepPlanReconfirm: "Keep the plan and confirm it again",
    reworkKeepPlan: "Keep the plan",
    reworkKeepPlanMaybeReconfirm: "If the task or acceptance criteria changed, you’ll be asked to confirm the plan again first.",
    noResultYet: "No result yet",
    startWorkflowOff: "Workflows are turned off in Plugins. Turn them on to start a run.",
    startWorkflowBlocked: "Workflows can’t start a run: no Provider is turned on in Plugins. Turn one on first.",
    startFailed: "Couldn’t start the run. Try again.",
    agentWaiting: "{{step}} is waiting for your answer in its Chat",
    agentWaitingBody: "It asked for a permission or a question. Nothing moves until you answer there.",
    blockedSignedOut: "{{provider}} isn’t signed in on {{computer}}.",
    blockedAuthUnknown: "Couldn’t confirm that {{provider}} is signed in on {{computer}}.",
    blockedAuthChecking: "Still checking whether {{provider}} is signed in on {{computer}}.",
    blockedAuthError: "The sign-in check for {{provider}} on {{computer}} failed.",
    blockedAuthTimeout: "{{provider}} didn’t answer the sign-in check on {{computer}} in time.",
    blockedNotInstalled: "{{provider}} isn’t installed on {{computer}}.",
    blockedMeasurementsUnavailable: "{{provider}} does not yet have the measurement evidence required for workflows.",
    blockedPluginDisabled: "{{provider}} is turned off in Plugins.",
    blockedNotMeasured: "{{provider}} hasn’t been checked on {{computer}} yet, so it can’t do {{step}}.",
    blockedProviderCannot: "{{provider}} can’t do {{step}}: it can’t keep this step’s guarantees.",
    blockedConfigUnavailable: "The config chosen for {{step}} is no longer available.",
    blockedGuaranteeReadOnly: "The config chosen for {{step}} asks for a read-only workspace, so it can’t change the code.",
    blockedGuaranteeNetwork: "The config chosen for {{step}} asks for no network, which can’t be guaranteed on {{computer}} yet.",
    blockedInstanceChanged: "The workflow’s Base was replaced. Set up the workflow again.",
    blockedTaskMissing: "The Base’s task column is gone. Bring it back, then continue.",
    blockedStageMissing: "The Stage column is gone. Bring it back, then continue.",
    blockedAcceptanceMissing: "The Acceptance criteria column is gone. Bring it back, then continue.",
    blockedNoValidReport: "{{step}} didn’t return a valid result.",
    blockedExtractorOff: "{{step}} didn’t return a valid result, and Claude, which organizes results, is turned off in Plugins.",
    blockedExtractorNotInstalled: "{{step}} didn’t return a valid result, and Claude, which organizes results, isn’t installed on {{computer}}.",
    blockedExtractorSignedOut: "{{step}} didn’t return a valid result, and Claude, which organizes results, isn’t signed in on {{computer}}.",
    blockedExtractorAuthUnknown: "{{step}} didn’t return a valid result, and it couldn’t be confirmed that Claude, which organizes results, is signed in on {{computer}}.",
    blockedExtractorAuthChecking: "{{step}} didn’t return a valid result, and Claude’s sign-in, which organizes results, is still being checked on {{computer}}.",
    blockedExtractorAuthError: "{{step}} didn’t return a valid result, and the sign-in check for Claude, which organizes results, on {{computer}} failed.",
    blockedExtractorAuthTimeout: "{{step}} didn’t return a valid result, and Claude, which organizes results, didn’t answer the sign-in check on {{computer}} in time.",
    blockedExtractorNotMeasured: "{{step}} didn’t return a valid result, and Claude hasn’t passed the check for organizing results on {{computer}}.",
    blockedExtractorFailed: "{{step}} didn’t return a valid result, and two tries to organize it from the Chat didn’t work.",
    blockedCheckProvider: "Check {{provider}} again",
    reportDerived: "Organized from the reply",
    reportShortened: "Shortened",
    reportShortenedPlan: "Only part of the plan is shown here.",
    reportShortenedReview: "Only part of the review is shown here.",
    openWholePlan: "Open the whole plan",
    openWholeReview: "Open the whole review",
    reportDerivedHint: "The Agent didn’t submit this step’s result in the expected format. Bottega took it word for word from the Agent’s reply, keeping only references that appear there.",
    blockedDispatchFailed: "{{step}} couldn’t be sent to {{provider}}.",
    blockedAttemptsExhausted: "This step has been tried as many times as allowed. Cancel this run and start again.",
    blockedOther: "{{step}} couldn’t finish.",
    blockedBaseAction: "Updating the Base couldn’t finish.",
    blockedRecordMissing: "The record was deleted.",
    blockedBaseActionFailed: "{{action}} didn’t finish: {{failure}}.",
    baseActionRead: "Reading the record",
    baseActionSetStage: "Moving the record to its stage",
    baseActionWriteSummary: "Writing the summary",
    baseFailureUnavailable: "the Base isn’t available",
    baseFailureRefused: "the write was refused",
    baseFailureConflict: "the record changed at the same time",
    baseFailureUnknown: "the reason isn’t known",
    blockedSignIn: "Sign in to {{provider}}",
    blockedCheckSignIn: "Check sign-in",
    blockedSetUp: "Set up {{provider}}",
    blockedChooseConfig: "Choose another config",
    retryStep: "Retry this step",
    retryStillBlocked: "Checked again: still blocked.",
    actionFailed: "That didn’t go through. Try again.",
    remoteSending: "Sending to {{computer}}…",
    remoteExpired: "{{computer}} didn’t answer in time, so nothing changed. You can try again.",
    remoteCommandExpired: "This didn’t reach {{computer}} in time, so nothing was done. Try again.",
    remoteUnknown: "It’s not known whether {{computer}} did this. Check the run before trying again.",
    remoteClassMismatch: "{{computer}} didn’t run this: it’s on a different version of Bottega from this device. Update Bottega on both, then try again.",
    remoteOffline: "{{computer}} is offline. You can act on this once it’s back.",
    checkResultFailed: "Couldn’t check the result. Try again.",
    retryFailed: "Couldn’t retry this step. Try again.",
    retryNotBlocked: "This step isn’t blocked anymore.",
  },
  /** U06-c: an App's Use Chat and Edit from the Web or a phone; the text-only first Edit message; refusals by name. */
  appOps: {
    useChat: "Use Chat",
    edit: "Edit",
    editHintWeb: "Changes this App in a Chat on {{computer}}. It rebuilds when the Chat finishes.",
    editHintPhone: "Changes this App in a Chat on {{computer}}.",
    sending: "Sending to {{computer}}…",
    sendingUse: "{{computer}} opens the Use Chat for {{app}}; it appears here as soon as it answers. If it doesn’t answer in time, nothing changes and you can try again.",
    sendingEdit: "{{computer}} opens the Edit Chat for {{app}}; it appears here as soon as it answers. If it doesn’t answer in time, nothing changes and you can try again.",
    startingEdit: "Starting the Edit Chat on {{computer}}…",
    offlineReason: "{{computer}} is offline. You can act on this once it’s back.",
    offlineTitle: "{{computer}} is offline",
    offlineBody: "Use Chat and Edit run on {{computer}}. You can act on this once it’s back. Opening {{app}} and editing its records still work here.",
    offlineChip: "{{computer}} offline",
    useChatOffline: "Use Chat ({{computer}} is offline)",
    appNotFound: "{{app}} is no longer on {{computer}}.",
    appNotEditable: "{{app}} can’t be edited on {{computer}}. Only its records can change.",
    appBusy: "A reply is still running in {{app}}’s current Use Chat on {{computer}}. Open it to wait or stop it, then try again.",
    appTransitioning: "{{app}} is being updated on {{computer}}. Try again in a moment.",
    agentUnavailable: "{{computer}} has no Agent available. Set one up in Bottega on {{computer}}.",
    reservationExpired: "{{computer}} didn’t start the Edit Chat in time. Your message is kept — send it again.",
    reservationFilled: "{{app}} already had an Edit Chat on {{computer}}. Your message is here as a draft.",
    firstMessageText: "The first message is text only. Attachments work from the second.",
    unknown: "It’s not known whether {{computer}} opened it. Trying again is safe; it won’t open a second Chat.",
    startupPending: "Bottega is still finishing its startup checks. Try again in a moment.",
    earlierProcess: "An earlier Agent process is still finishing. Try again in a moment.",
    /* U06-d: the build status on the App page (building, waiting for the extension decision, failed) and its two commands. */
    buildingStatus: "Building on {{computer}}…",
    buildingTitleWeb: "Building the new version on {{computer}}…",
    buildingBodyWeb: "The last edit finished. {{app}} keeps opening the current version until the new one is ready; then it opens the new one and says so.",
    buildingTitlePhone: "Building the new version…",
    buildingBodyPhone: "On {{computer}}. The current version keeps opening until the new one is ready.",
    buildFailedStatus: "Build failed",
    buildFailedTitle: "Couldn’t build the new version",
    buildFailedBodyWeb: "The last edit didn’t build on {{computer}}. {{app}} still opens the previous version. To fix the code, ask the maintenance Agent in {{app}} on your computer.",
    buildFailedBodyPhone: "The last edit didn’t build on {{computer}}. {{app}} still opens the previous version.",
    buildFailedInterrupted: "The update was interrupted before it finished. Try again.",
    buildRetry: "Try again",
    buildRepair: "Repair on your computer",
    confirmStatus: "Waiting for your computer",
    confirmTitle: "Waiting for your computer to confirm",
    confirmBody: "This edit adds an extension to {{app}}. Approve it on {{computer}} to build the new version. Until then the current version keeps working.",
    confirmCancel: "Cancel request",
    confirmCancelledRemotely: "Cancelled from another device.",
    confirmTimedOut: "No one approved it on {{computer}} in 30 minutes, so the new version was built without the extension. To add it, ask again and approve it on {{computer}}.",
    confirmAlreadyResolved: "Already answered on {{computer}}.",
  },
  phone: {
    needsYou: "Needs you",
    needsYouCount_one: "{{count}} needs you",
    needsYouCount_other: "{{count}} need you",
    sheetNote: "Only items waiting for a decision. Tapping one opens it; nothing is confirmed until you choose.",
    empty: "Nothing is waiting for you.",
    pushLanding: "Opening this does not confirm anything.",
    moreNeedsYou: "{{count}} more will show here as you handle these.",
    alreadyHandled: "This has already been handled.",
    signInOnComputer: "Sign in to {{provider}} on {{computer}} to use it here.",
    theComputer: "the Project’s computer",
    workflowSuspended: "This workflow can’t start runs until its setup is fixed on {{computer}}.",
  },
};

type Shape<T> = { readonly [K in keyof T]: T[K] extends string ? string : Shape<T[K]> };
export type WorkbenchCopy = Shape<typeof en>;
