/**
 * [INPUT]: Depends on ./en for the WorkbenchCopy shape.
 * [OUTPUT]: Provides es, the Spanish workbench catalog.
 * Names built-in recipes and Workflow plugins and explains missing workflow measurements.
 * [POS]: Lazy workbench-copy locale; the interface says only Workflow and Ejecución; lanes are carriles, columns columnas.
 */
import { dock } from "./dock/es";
import type { WorkbenchCopy } from "./en";
import { memoryPluginCopy } from "./memory/es";

export const es: WorkbenchCopy = {
  guiHistory: {
    title: "Versiones",
    current: "Actual",
    previous: "Anterior",
    activate: "Usar esta versión",
    switching: "Cambiando…",
    pending: "Completa la autorización pendiente para activar esta versión.",
    loadFailed: "No se pudieron cargar las versiones.",
    empty: "Todavía no hay una versión compilada.",
    refresh: "Actualizar",
    edit: "Editar código",
    installLocal: "Instalar desde una carpeta…",
    draftBusy: "Termina o vacía el borrador actual antes de abrir el Chat del plugin.",
    skillMissing: "El Skill plugin-authoring no está disponible para este Agent.",
    starterPrompt: "Usa el Skill plugin-authoring para crear este plugin según los requisitos que describiré.",
  },
  terms: {
    pluginsAndApps: "Plugins",
    bottegaPlugin: "Plugin de Bottega",
    agentNativePlugin: "Plugin nativo del Agent",
    baseApp: "Base (App integrada)",
    baseBackedApp: "App basada en Base",
    agentConfig: "Configuración de Agent",
    workflow: "Workflow",
    run: "Ejecución",
  },
  base: {
    menuGroup: "Workflow",
    setUp: "Configurar un Workflow…",
    settings: "Ajustes del Workflow",
    runWorkflow: "Ejecutar Workflow",
    runOnTask: "Ejecutar un Workflow en esta tarea",
    ready: "Listo",
  },
  readOnly: {
    badge: "Workflow",
    columnHint: "Solo los Workflows cambian esta columna",
    setByWorkflow: "Lo define el Workflow",
    laneLocked: "{{column}} lo define el Workflow, así que este carril no acepta tarjetas. Cambia tus propias columnas o abre la ejecución para cambiar lo que sigue.",
    whoCanEdit: "Quién puede editar",
    everyone: "Todos",
    onlyWorkflows: "Solo Workflows",
    whoCanEditUnavailable: "Solo se pueden limitar las columnas que añade un Workflow.",
  },
  record: {
    section: "Workflow",
    run: "Ejecución",
    noRuns: "Todavía no hay ejecuciones",
    acceptance: "Aceptación",
    notDecided: "Sin decidir",
    accepted: "Aceptado",
    acceptedWithException: "Aceptado con una excepción",
  },
  plugins: {
    title: "Plugins",
    description: "Los plugins instalados en este host de Bottega. Activa o desactiva uno, aplica actualizaciones, o ábrelo para ver los ajustes y los detalles.",
    searchLabel: "Buscar plugins",
    statusLabel: "Estado",
    statusAll: "Todos los estados",
    statusOn: "Activados",
    statusOff: "Desactivados",
    statusAttention: "Requieren atención",
    sortLabel: "Orden",
    sortGroup: "Por categoría",
    sortName: "Por nombre",
    sortRecent: "Cambiados recientemente",
    newPlugin: "Nuevo plugin",
    groupFeature: "Funciones de Bottega",
    groupProvider: "Proveedores",
    groupPackage: "Extensiones",
    groupNative: "Plugins nativos de Agent",
    emptyTitle: "Ningún plugin coincide",
    clearFilters: "Borrar búsqueda y filtros",
    emptyAll: "No hay plugins instalados.",
    official: "Oficial",
    badgeBuiltin: "Integrado",
    badgePackage: "Extensión · v{{version}}",
    badgeNative: "Nativo de Agent",
    alwaysOn: "Siempre activado",
    nativeManagedBy: "Lo gestiona {{agent}}",
    projectScopedBadge: "Solo un Project",
    projectScopedNote: "Está instalado para un solo Project, así que aún no se puede desactivar aquí.",
    setupMemory: "Activar…",
    setupDock: "Configurar…",
    blocked: "Falta una dependencia",
    unsupported: "No compatible aquí",
    providerUsedBy_one: "Lo usa {{count}} configuración de Agent",
    providerUsedBy_other: "Lo usan {{count}} configuraciones de Agent",
    providerUnused: "Aún sin uso",
    workflowSetUpIn_one: "Configurado en {{count}} Project",
    workflowSetUpIn_other: "Configurado en {{count}} Projects",
    workflowSetUpInNames: "Configurado en {{projects}}",
    turnedOffOn: "Desactivado el {{date}}",
    neverOn: "Nunca activado",
    turnOffTitle: "¿Desactivar {{name}}?",
    turnOffBody: "{{name}} ya no se iniciará en {{computer}}. No se elimina nada y puedes volver a activarlo cuando quieras.",
    whatChanges: "Qué cambia",
    impactConfigs: "La configuración de Agent {{config}} ya no se puede elegir",
    impactWorkflows: "{{workflow}} no puede iniciar nuevas ejecuciones mientras {{name}} esté desactivado",
    impactRuns_one: "{{count}} ejecución que usa {{name}} terminará su paso actual y luego se pausará",
    impactRuns_other: "{{count}} ejecuciones que usan {{name}} terminarán su paso actual y luego se pausarán",
    impactChats_one: "{{count}} chat con {{name}} se puede leer, pero no continuar",
    impactChats_other: "{{count}} chats con {{name}} se pueden leer, pero no continuar",
    impactMore_one: "y {{count}} más",
    impactMore_other: "y {{count}} más",
    dependentsTitle: "Estos plugins dejarán de funcionar",
    dependentLine: "{{plugin}}: necesita algo que solo proporciona {{name}}",
    turnOff: "Desactivar",
    turnOn: "Activar",
    thisComputer: "este ordenador",
    switchFailed: "No se pudo cambiar {{name}}. Inténtalo de nuevo.",
    switchLabel: "Activar o desactivar {{name}}",
    reinstallRequired: "Los archivos instalados de {{name}} cambiaron mientras estaba desactivado, así que aún no se puede volver a activar.",
    reinstallHelp: "Avísanos y te ayudaremos a restaurarlo.",
    reinstallIssueTitle: "{{name}} no se puede volver a activar",
    reinstallBadge: "No se puede reactivar",
    reportProblem: "Informar de un problema",
    busyNote: "{{name}} está ocupado. Podrás cambiarlo cuando termine.",
    turningOn: "Activando…",
    turningOff: "Desactivando…",
    chatTurnedOff: "{{provider}} está desactivado en Plugins. Vuelve a activarlo para continuar este chat.",
    openPlugin: "Abrir el plugin {{name}}",
    back: "Todos los plugins",
    on: "Activado",
    off: "Desactivado",
    sectionSettings: "Ajustes",
    settingsNote: "Declarados por el plugin",
    settingsProviderNote: "Las sesiones abiertas no cambian",
    appliesImmediate: "Al instante",
    appliesNextTurn: "En el siguiente turno",
    appliesSessionCreate: "En sesiones nuevas",
    appliesProcessStart: "Tras reiniciar",
    changed: "Cambiado",
    resetDefault: "Restablecer",
    confirmContinue: "Continuar",
    secretSet: "Definido",
    secretUnset: "Sin definir",
    secretReplace: "Reemplazar",
    secretClear: "Borrar",
    secretSave: "Guardar",
    secretCancel: "Cancelar",
    decrease: "Reducir",
    increase: "Aumentar",
    settingsFailed: "No se pudo guardar «{{setting}}». Inténtalo de nuevo.",
    pendingRestart: "{{name}} se reiniciará cuando esté inactivo para aplicar los cambios.",
    sectionHealth: "Estado",
    checkedAt: "Comprobado {{time}}",
    update: "Actualizar",
    setUp: "Configurar",
    sectionUsedBy: "Lo usan",
    usedByConfigs: "Configuraciones de Agent",
    usedByProjects: "Projects con Workflows",
    usedByNobody: "Nada lo usa todavía.",
    sectionDependencies: "Dependencias",
    depRequires: "Necesita",
    depProvides: "Proporciona",
    depDependents: "Lo necesitan",
    depNone: "Ninguna",
    depSatisfiedBy: "Lo proporciona {{plugins}}",
    depHostNote: "Los ajustes, el almacenamiento, los eventos y las tareas en segundo plano los proporciona Bottega y siempre están disponibles.",
    blockedMissing: "Nada lo proporciona",
    blockedDisabled: "Todo lo que lo proporciona está desactivado",
    blockedUnsupported: "Lo que lo proporciona no funciona en este ordenador",
    blockedCycle: "Depende de sí mismo en un bucle",
    blockedBanner: "{{name}} no puede iniciar trabajo nuevo. {{reason}}.",
    sectionCapabilities: "Capacidades y permisos",
    capabilitiesNone: "Nada declarado.",
    sectionIncludes: "Incluye",
    sectionCanDo: "Qué puede hacer",
    sectionWorksWith: "Dependencias",
    sectionInUse: "En uso",
    sectionInformation: "Información",
    worksAlone: "Funciona por sí solo. Ningún otro plugin depende de él.",
    aboutPlugin: "Acerca de {{name}}",
    publisherBottega: "Bottega",
    about: "Información",
    aboutSource: "Origen",
    aboutVersion: "Versión",
    aboutKind: "Tipo",
    aboutId: "ID del plugin",
    aboutManagedBy: "Lo gestiona",
    aboutLocation: "Ubicación",
    aboutPublisher: "Editor",
    unsigned: "Sin firmar",
    versionWithApp: "Incluido con Bottega {{version}}",
    kindFeature: "Función",
    kindProvider: "Proveedor",
    sourceLocalLong: "Código local",
    sourceBuiltinLong: "Integrado en Bottega",
    sourcePackageLong: "Extensión",
    sourceNativeLong: "Nativo de Agent",
    related: "Páginas relacionadas",
    relatedProviders: "Proveedores",
    relatedAgentConfigs: "Configuraciones de Agent",
    relatedUsage: "Uso",
    relatedSkills: "Skills",
    relatedMemory: "Memoria",
    relatedDock: "Dock",
    nativeReadOnly: "Lo gestiona {{agent}}. Bottega solo lo muestra; instálalo, actualízalo o quítalo en {{agent}}.",
    notFound: "Este plugin ya no está instalado.",
    loadFailed: "No se pudo cargar este plugin. Inténtalo de nuevo.",
    retry: "Reintentar",
    sidebarGroup: "Plugins",
    sidebarAll: "Todos los plugins",
    health: {
      unknown: "Aún sin comprobar",
      notChecked: "Aún sin comprobar",
      ready: "Listo",
      off: "Desactivado",
      running: "En ejecución",
      idle: "Listo, sin ejecutarse",
      process: "Proceso",
      processRunning: "En ejecución",
      processIdle: "Se inicia cuando hace falta",
      nativeEnabled: "{{agent}} indica que está activado",
      nativeDisabled: "{{agent}} indica que está desactivado",
      cliVersion: "CLI",
      signIn: "Inicio de sesión",
      runningRuns: "Ejecuciones en curso",
      cli: {
        unknown: "Sin comprobar",
        missing: "No instalada",
        error: "No se pudo comprobar",
        unsupported: "Necesita actualizarse",
        installed: "Instalada",
      },
      auth: {
        unknown: "Desconocido",
        checking: "Comprobando…",
        authenticated: "Sesión iniciada",
        unauthenticated: "Sin sesión",
        error: "No se pudo comprobar",
      },
    },
    unsupportedReason: {
      appleSilicon: "Solo en macOS con chip de Apple",
    },
    capability: {
      startProcess: "Inicia su CLI en este ordenador",
      projectFiles: "Lee y escribe en las carpetas de los Projects, según cada configuración de Agent",
      network: "Se conecta a su propio servicio",
      baseStore: "Guarda tablas en la carpeta de cada Project",
      baseTools: "Da a los Agents herramientas de Base para leer, escribir y consultar registros",
      workflowColumns: "Añade las columnas Etapa y Criterios de aceptación a una Base; solo los Workflows escriben la Etapa",
      workflowRoles: "Ejecuta cada rol con su configuración de Agent",
    },
    builtin: {
      memory: memoryPluginCopy,
      dock,
      sketch: { name: "Boceto", summary: "Dibuja, borra y adjunta una imagen editable.", description: "Boceto añade un lienzo de dibujo al compositor. Dibuja, borra y anota, y luego adjunta el resultado a tu mensaje como imagen editable." },
      base: {
        name: "Base",
        summary: "Tablas, tableros, listas y formularios en cada Project. Los Workflows y las Apps basadas en Base se apoyan en ella.",
        description: "Base da a cada Project sus propias tablas. Muestra los registros como tabla, tablero, lista o formulario, guardados en la carpeta del Project junto a tus archivos.\n\nLos Agents leen, escriben y consultan registros con las herramientas de Base. Los Workflows y las Apps basadas en Base se apoyan en ella, por eso siempre está activada.",
      },
      workflow: {
        name: "Workflow",
        summary: "Los roles de Agent hacen avanzar el trabajo en una Base, paso a paso, con una revisión en cada paso.",
        description: "Workflow convierte una Base en una cadena de trabajo. Cada paso es un rol que interpreta una de tus configuraciones de Agent, y cada paso termina con una revisión antes de seguir.\n\nConfigúralo en un Project y añade tarjetas a su primera columna. Abre cualquier ejecución para ver qué hizo cada rol y decidir qué pasa después.",
      },
      claude: {
        name: "Claude",
        summary: "Claude Code de Anthropic, funcionando como Agent en Bottega.",
        description: "Ejecuta Claude Code de Anthropic como Agent en Bottega. Trabaja en tus carpetas de Project con el acceso que permite cada configuración de Agent.\n\nNecesita la CLI de Claude Code y una cuenta de Anthropic con la sesión iniciada en este ordenador. Extras como el contexto de un millón de tokens y Claude in Chrome están en sus ajustes.",
        publisher: "Anthropic",
        settings: {
          memory: {
            label: "Memoria",
            description: "Permite que Claude Code lea y escriba su propia memoria automática en los chats de Bottega. Los roles de Workflow nunca la usan.",
          },
          nativeSubagents: {
            label: "Permitir subagentes nativos",
            description: "Permite que Claude Code inicie sus propios subagentes con su herramienta Task.",
          },
          workflowTool: {
            label: "Permitir la herramienta Workflow",
            description: "Permite que Claude Code use su propia herramienta Workflow.",
          },
          context1m: {
            label: "Usar contexto de 1M",
            description: "Permite que Claude Code use una ventana de contexto de un millón de tokens.",
          },
          claudeInChrome: {
            label: "Claude in Chrome",
            description: "Inicia Claude Code con las herramientas de navegador de Claude in Chrome. Necesita la extensión de Chrome en este ordenador, con sesión iniciada en claude.ai.",
          },
        },
      },
      codex: {
        name: "Codex",
        summary: "La CLI de Codex de OpenAI, funcionando como Agent en Bottega.",
        description: "Ejecuta la CLI de Codex de OpenAI como Agent en Bottega. Lee y edita tus carpetas de Project dentro de los límites de cada configuración de Agent.\n\nNecesita la CLI de Codex y una cuenta de OpenAI con la sesión iniciada en este ordenador. Sus propias memorias y su función multiagente se pueden desactivar en sus ajustes.",
        publisher: "OpenAI",
        settings: {
          memory: {
            label: "Memoria",
            description: "Permite que Codex use sus propias memorias en los chats de Bottega. Los roles de Workflow nunca las usan.",
          },
          nativeSubagents: {
            label: "Permitir subagentes nativos",
            description: "Permite que Codex use su propia función multiagente.",
          },
        },
      },
      kimi: {
        name: "Kimi",
        summary: "La CLI de Kimi de Moonshot, funcionando como Agent en Bottega.",
        description: "Ejecuta la CLI de Kimi de Moonshot como Agent en Bottega. Necesita la CLI de Kimi y una cuenta de Moonshot con la sesión iniciada en este ordenador.",
        publisher: "Moonshot AI",
      },
      opencode: {
        name: "OpenCode",
        summary: "OpenCode, de código abierto, que puede usar modelos de muchos servicios.",
        description: "Ejecuta la CLI de código abierto OpenCode como Agent en Bottega. Puede usar modelos de muchos servicios.",
        publisher: "OpenCode",
      },
    },
  },
  agentConfigs: {
    loading: "Cargando configuraciones de Agent…",
    loadFailed: "No se pudieron cargar las configuraciones de Agent. Inténtalo de nuevo.",
    refreshFailed: "No se pudieron actualizar las configuraciones de Agent. Se muestra la última lista cargada.",
    unavailable: "Las configuraciones de Agent no están disponibles en esta ventana. Reinténtalo o vuelve a abrir los ajustes.",
    reasoningEffort: "Esfuerzo de razonamiento",
    agentDefault: "Predeterminado del Agent",
    modelsFailed: "No se pudieron cargar los modelos. Se conservan tus selecciones.",
    defaultsFailed: "No se pudieron cargar los valores predeterminados guardados. Elige un modelo o reinténtalo.",
    optionUnavailable: "Esta opción guardada no está disponible aquí. Se conservará hasta que elijas otra opción.",
    chooseModelForEffort: "Elige un modelo disponible para ver sus opciones de razonamiento.",
    baseResource: "Base",
    chatResource: "Chat",
    mcpResource: "MCP",
    selectedCount: "{{count}} / {{limit}} seleccionados",
    resourcesLoading: "Cargando recursos locales…",
    resourcesFailed: "No se pudieron cargar algunos recursos. Se conservan tus selecciones.",
    resourcesEmpty: "No hay recursos locales disponibles.",
    resourceUnavailable: "No disponible aquí",
    baseRead: "Solo lectura",
    baseReadWrite: "Lectura y escritura",
    linkedChats: "Solo Chats relacionados",
    resourcesHint: "Las nuevas ejecuciones solo usan los recursos seleccionados. Los recursos ausentes en otro equipo bloquean la ejecución hasta corregirlos.",
    resourcesReadOnly: "La planificación, la revisión y las configuraciones de solo lectura solo pueden leer la Base y no pueden usar servidores MCP.",
    baseCapped: "Solicitado: lectura y escritura. Efectivo: solo lectura. Se conserva la solicitud guardada.",
    removeReadOnlyMcp: "Quita los servidores MCP seleccionados para guardar una configuración de solo lectura.",
    retryResources: "Recargar recursos",
    title: "Configuraciones de Agent",
    description: "Proveedor, modelo, instrucciones y herramientas reutilizables.",
    allProjects: "Todos los Projects",
    someProjects: "Algunos Projects",
    someProjectsDescription: "Solo aparece en los Projects indicados debajo de cada configuración.",
    newConfig: "Nueva configuración",
    edit: "Editar",
    readOnly: "Solo lectura",
    newTitle: "Nueva configuración de Agent",
    editTitle: "Editar configuración de Agent",
    prefilled: "Rellenada para el rol de {{role}}: rol, permisos y herramientas. Todo se puede editar.",
    startFrom: "Empezar desde",
    blank: "En blanco",
    planner: "Planificación",
    developer: "Desarrollo",
    reviewer: "Revisión",
    name: "Nombre",
    availableIn: "Disponible en",
    searchProjects: "Buscar Projects",
    provider: "Proveedor",
    chooseProvider: "Elige un proveedor",
    model: "Modelo",
    providerDefault: "Predeterminado del proveedor",
    instructions: "Instrucciones",
    instructionsHint: "Se envían al Agent",
    purpose: "Propósito",
    purposeHint: "Lo ven quienes eligen una configuración",
    permissions: "Permisos",
    skills: "Skills",
    toolsAndData: "Herramientas y datos",
    toolsBaseReadWriteLinked: "Base en lectura y escritura · solo chats relacionados",
    toolsBaseReadLinked: "Base en lectura · solo chats relacionados",
    none: "Ninguno",
    create: "Crear",
    missingRequired: "Añade un nombre y elige un proveedor",
    appliesToNewRuns: "Los cambios se aplican a las ejecuciones que empiecen después de guardar.",
    appliesNextTurn: "Se aplica en el siguiente turno",
    restartsAgent: "Reinicia el Agent",
    appliesOnNew: "Se aplica a los chats nuevos",
    notForRole: "No apto para este rol",
    notAdmitted: "Aún no validado para el rol de {{role}}",
    partialFailure: "Algunos ajustes no se pudieron aplicar, así que esta configuración no está lista para su rol.",
    presetPlanner: "Lee la tarea y sus criterios de aceptación y escribe un plan paso a paso. No cambies el código.",
    presetDeveloper: "Sigue el plan aceptado. Limita los cambios a la tarea. Ejecuta las comprobaciones del Project antes de informar.",
    presetReviewer: "Comprueba el resultado frente al plan y los criterios de aceptación. Indica lo que falta. No cambies el código.",
    emptyTitle: "Aún no hay configuraciones de Agent",
    emptyBody: "Crea una para elegirla en un paso de un Workflow.",
    syncing: "Sincronizando",
    conflicted: "Requiere revisión",
    notSynced: "Sin sincronizar",
    syncIssueBudget: "Esta cuenta llegó a su límite de 100 configuraciones de Agent, así que esta aún no se ha sincronizado. Elimina una configuración que ya no uses y se sincronizará automáticamente.",
    saveFailed: "No se pudo guardar esta configuración. Tus cambios siguen aquí.",
    allProjectsHint: "Disponible en todos los Projects",
    noProjects: "Aún no hay Projects",
    needsAttention: "Requiere atención",
    guaranteeReadOnly: "Espacio de trabajo de solo lectura",
    guaranteeNoNetwork: "Sin red",
    reasonProviderCannot: "{{provider}} no puede garantizarlo",
    reasonHostCannot: "Este ordenador no puede imponerlo",
    reasonHostUnavailable: "No se puede comprobar: el ordenador que lo ejecuta no está disponible",
    reasonNotMeasured: "Aún sin verificar",
    applyPartial: "{{settings}} no se aplicaron en este ordenador, así que un Workflow todavía no puede usar esta configuración.",
    applyPartialGeneric: "Algunos ajustes no se aplicaron en este ordenador, así que un Workflow todavía no puede usar esta configuración.",
    workspace: "Espacio de trabajo",
    workspaceWrite: "Puede cambiar archivos",
    workspaceReadOnly: "Solo lectura",
    network: "Red",
    networkOn: "Activada",
    networkOff: "Desactivada",
    notReadOnly: "Su espacio de trabajo no es de solo lectura",
    providerTurnedOff: "{{provider}} está desactivado",
  },
  setup: {
    enableTitle: "Activar flujo",
    enableDescription: "Planificar, desarrollar y revisar en este equipo.",
    enableAndRun: "Activar y ejecutar esta fila",
    noReadyProvider: "No hay un proveedor listo para este flujo.",
    openSettings: "Abrir ajustes",
    openBase: "Abrir Base para gestionar columnas",
    openProject: "Abrir ajustes del proyecto",
    projectUnavailable: "Primero elige una carpeta de trabajo en los ajustes del proyecto.",
    enableFailed: "No se pudo activar el flujo. Vuelve a comprobar sus requisitos.",
    checkAgain: "Volver a comprobar",
    refusalSkillUnavailable: "Un Skill seleccionado en {{config}} no está disponible o está desactivado en este equipo.",
    refusalMcpUnavailable: "Un servidor MCP seleccionado en {{config}} no está disponible en este equipo.",
    refusalMcpReadOnly: "{{config}} selecciona servidores MCP que los pasos de planificación y revisión no pueden usar. Quita la selección o elige otra configuración.",
    planDevelopReview: "Planificar · Desarrollar · Revisar",
    newTitle: "Configurar un Workflow",
    editTitle: "Ajustes del Workflow",
    stepOf: "Paso {{current}} de {{total}}",
    tabWorkflow: "Workflow",
    tabWho: "Quién hace qué",
    tabBase: "Tu Base",
    tabCheck: "Comprobación",
    chooseTitle: "Elige un Workflow",
    whoTitle: "Quién hace cada paso",
    whoHint: "Haz clic en un nombre para cambiarlo.",
    whoGreyedHint: "Cada lista muestra quién puede hacer ese paso; los demás aparecen atenuados con el motivo.",
    you: "Tú",
    addStep: "Añadir un paso",
    stepPlan: "Planificar",
    stepPlanDescription: "Escribe un plan para la tarea",
    stepConfirm: "Confirmar",
    stepConfirmDescription: "Lees el plan y lo aceptas",
    stepDevelop: "Desarrollar",
    stepDevelopDescription: "Cambia el código",
    stepReview: "Revisar",
    stepReviewDescription: "Comprueba el resultado sin cambiarlo",
    stageDone: "Hecho",
    stepDecide: "Decidir",
    stepDecideDescription: "Aceptas, terminas o rehaces",
    youConfirm: "Tú confirmas",
    youDecide: "Tú decides",
    baseTitle: "Qué cambia en tu Base",
    baseIntro_one: "El Workflow añade 1 columna. No se cambia nada de lo que ya tienes.",
    baseIntro_other: "El Workflow añade {{count}} columnas. No se cambia nada de lo que ya tienes.",
    baseIntroEditing: "Tu Base ya tiene las columnas del Workflow. Aquí no cambia nada.",
    baseNow: "Ahora",
    baseAfter: "Después de activarlo",
    baseNewColumns_one: "Tu Base recibe 1 columna nueva",
    baseNewColumns_other: "Tu Base recibe {{count}} columnas nuevas",
    stageColumn: "Fase",
    stageDescription: "Muestra en qué punto está cada tarea. El Workflow la actualiza; tú no puedes editarla.",
    acceptanceColumn: "Criterios de aceptación",
    boardView: "Tablero · por fase",
    acceptanceDescription: "Tú escribes qué significa «terminado» para cada tarea.",
    baseOthersUnchanged: "Tus otras columnas quedan como están.",
    baseFixedColumns: "El Workflow decide estas dos columnas; no se pueden cambiar aquí.",
    baseFull_one: "Esta Base ya tiene {{existing}} de sus {{limit}} columnas. Elimina 1 columna en la Base para activar el Workflow.",
    baseFull_other: "Esta Base ya tiene {{existing}} de sus {{limit}} columnas. Elimina {{count}} columnas en la Base para activar el Workflow.",
    baseBoardAdded: "Añade la vista “{{view}}” y la abre. Tus otras vistas quedan como están.",
    baseBoardNoRoom: "Esta Base ya tiene {{limit}} vistas, así que no se añade la vista “{{view}}”. El Workflow se activa igualmente.",
    baseChanged: "Las columnas de la Base cambiaron mientras esta ventana estaba abierta. Esto las muestra como están ahora.",
    checkTitle: "Comprobar y activar",
    checkedOn: "Comprobado en {{computer}}.",
    providerReady: "{{provider}} está listo en {{computer}}",
    checking: "Comprobando en este ordenador…",
    roleReady: "{{step}}: {{provider}} está listo en {{computer}}",
    roleProblem: "{{step}}: {{reason}}",
    refusalDeleted: "Esta configuración se eliminó.",
    refusalNotEnabled: "{{config}} se creó en otro dispositivo y todavía no se ha guardado en {{computer}}. Ábrela en las configuraciones de Agent y guárdala una vez.",
    refusalMismatch: "{{config}} cambió a otro Provider y hay que confirmarla. Ábrela en las configuraciones de Agent y guárdala una vez.",
    refusalSelection: "{{config}} define su propia Memory, que los pasos de un Workflow aún no pueden usar. Elige otra configuración.",
    refusalMemoryWrite: "{{config}} solicita escribir en Memory. Los pasos de un Workflow solo pueden leerla.",
    refusalScope: "Los pasos de un Workflow no admiten los ajustes de Skills o Tools de {{config}}. Abre la configuración y vuelve a guardarla.",
    refusalPartial: "{{settings}} de {{config}} no se aplicaron en {{computer}}. Abre la configuración para corregirlo.",
    refusalPartialGeneric: "Parte de los ajustes de {{config}} no se aplicaron en {{computer}}. Abre la configuración para revisarlos.",
    refusalReadOnly: "Pide un espacio de trabajo de solo lectura, así que no puede cambiar el código.",
    refusalNoNetwork: "Pide no usar la red, algo que aún no se puede garantizar en {{computer}}.",
    baseHasRoom_one: "La Base tiene espacio para 1 columna más",
    baseHasRoom_other: "La Base tiene espacio para {{count}} columnas más",
    baseGets: "La Base recibe",
    needsComputer: "{{computer}} debe estar en línea",
    turnOn: "Activar",
    continue: "Continuar",
    back: "Atrás",
  },
  projectWorkflows: {
    tab: "Workflows",
    description: "Workflows que puedes ejecutar desde una tarea de la Base de este Project.",
    addWorkflow: "Añadir Workflow",
    on: "Activado",
    off: "Desactivado",
    runsOn: "se ejecuta en {{computer}}",
    configsTitle: "Configuraciones de Agent de este Project",
    configsHint: "Las configuraciones personales están en Ajustes › Configuraciones de Agent.",
    availableIn: "Disponible en {{projects}}",
    needsBase: "Añade un Workflow cuando este Project tenga una Base. Los Workflows se ejecutan en sus tareas.",
    workflowChats_one: "{{count}} Chat de Workflow",
    workflowChats_other: "{{count}} Chats de Workflow",
    workflowRuns_one: "{{count}} ejecución",
    workflowRuns_other: "{{count}} ejecuciones",
    alsoArchived: "También se archivan con él: {{chats}} de {{runs}}.",
    alsoArchivedNoRuns: "También se archivan con él: {{chats}}.",
    alsoDeleted: "Los {{chats}} de este Project se eliminarán con él.",
    archiveStepRunning: "Hay un paso del Workflow en curso, así que aún no se puede archivar. La ejecución se pausará cuando termine el paso. Vuelve a intentarlo entonces.",
    runsStillStopping: "Una ejecución de Workflow de este Project aún se está deteniendo y puede que siga habiendo un proceso en marcha. Fuérzala a detenerse desde la ejecución y vuelve a intentarlo.",
    runtimeNotReady: "Los Workflows aún se están iniciando en este ordenador. Vuelve a intentarlo en un momento.",
  },
  run: {
    blockedVersionTooOld: "Actualiza {{provider}} en {{computer}} antes de ejecutar este Workflow.",
    blockedExtractorVersionTooOld: "{{step}} no devolvió un resultado válido. Actualiza Claude en {{computer}} para organizarlo.",
    label: "Ejecución n.º {{number}}",
    onComputer: "en {{computer}}",
    queued: "En cola",
    running: "En curso",
    needsYou: "Pendiente de ti",
    paused: "En pausa",
    blocked: "Bloqueada",
    cancelling: "Cancelando…",
    succeeded: "Completada",
    failed: "Fallida",
    cancelled: "Cancelada",
    stopped: "Detenida",
    stoppedForced: "Detención forzada",
    pausedWaited: "En pausa · 24 h de espera",
    pausedArchived: "En pausa · Project archivado",
    cancellingTitle: "Cancelando",
    cancellingBody: "No empezarán pasos nuevos. Bottega está deteniendo {{provider}} en {{computer}}; puede tardar unos segundos. No estará detenida hasta que aquí lo indique.",
    stuckTitle: "Aún no se ha detenido tras 30 segundos",
    stuckBody: "{{provider}} en {{computer}} no ha terminado. Puedes forzar la detención. El código que ya cambió se queda en el espacio de trabajo; revísalo antes de la próxima ejecución.",
    forceStop: "Forzar detención",
    forceStopUnconfirmedTitle: "Puede que un proceso siga en ejecución",
    forceStopUnconfirmedBody: "Bottega detuvo el paso en {{computer}}, pero no pudo confirmar que todos los procesos terminaran. Fuerza la detención de nuevo y revisa el espacio de trabajo antes de la próxima ejecución.",
    waitingFor: "Esperando a {{computer}}",
    reminder: "El plan lleva 23 horas esperando. Decide en la próxima hora o la ejecución se pausará.",
    waitingStarted: "Hay un plan listo para que lo revises.",
    reminderResult: "El resultado lleva 23 horas esperando. Decide en la próxima hora o la ejecución se pausará.",
    waitingStartedResult: "Hay un resultado listo para que decidas.",
    pauseConfirmationTimeout: "En pausa: esta confirmación esperó más de 24 horas. Continúa para que se te vuelva a pedir.",
    pausedNotice: "En pausa tras esperar 24 horas. No se ejecutó nada. Ábrela para continuar.",
    resume: "Continuar",
    resultUnknown: "Resultado desconocido",
    resultUnknownBody: "{{computer}} la aceptó a las {{time}}, pero el resultado no llegó. No se volverá a enviar por sí sola.",
    checkResult: "Comprobar resultado",
    acceptPlan: "Aceptar el plan",
    accept: "Aceptar",
    acceptWithException: "Aceptar con una excepción",
    exceptionReason: "¿Por qué lo aceptas de todos modos?",
    exceptionReasonRequired: "Escribe un motivo para aceptar con una excepción.",
    end: "Terminar",
    rework: "Rehacer",
    reworkFromDevelop: "Mantener el plan aceptado y volver a empezar desde Desarrollar",
    replan: "Planificar de nuevo",
    reconfirm: "Los criterios de aceptación cambiaron. Confirma el plan de nuevo antes de que siga la ejecución.",
    alreadyHandled: "Ya gestionado en {{device}}",
    viewResult: "Ver resultado",
    viewLog: "Ver registro",
    tryAgain: "Reintentar",
    details: "Detalles de la ejecución",
    startRun: "Iniciar ejecución",
    pause: "Pausar",
    cancelRun: "Cancelar ejecución",
    cancelConfirmTitle: "¿Cancelar esta ejecución?",
    cancelConfirmBody: "El paso en curso se detiene primero; el código que ya cambió se queda en el espacio de trabajo. Esta ejecución no seguirá; podrás empezar otra más tarde.",
    keepRunning: "Seguir ejecutando",
    forceConfirmTitle: "¿Forzar la detención?",
    forceConfirmBody: "Esto termina de inmediato todos los procesos de este paso en {{computer}}. Lo que ya cambió no se deshace; revisa el espacio de trabajo antes de la próxima ejecución.",
    keepWaiting: "Seguir esperando",
    openChat: "Abrir chat",
    artifact: "Resultado",
    evidence: "Pruebas",
    stepPending: "Sin empezar",
    stepRunning: "En curso",
    stepWaiting: "Pendiente de ti",
    stepSucceeded: "Hecho",
    stepFailed: "Fallido",
    stepBlocked: "Bloqueado",
    stepCarried: "Del plan aceptado",
    stepNotRun: "No ejecutado",
    pauseUser: "Pausaste esta ejecución.",
    pauseProjectArchived: "En pausa porque el Project se archivó. Restaura el Project y luego continúa.",
    pauseProjectRestored: "Esta ejecución se pausó al archivar el Project. Continúa cuando estés listo.",
    pausingAfterStep: "Esta ejecución se pausará cuando termine el paso actual.",
    pausingArchived: "El Project se archivó. Esta ejecución se pausará cuando termine el paso actual.",
    projectArchived: "Este Project está archivado, así que sus ejecuciones no pueden iniciarse ni continuar. Restaura el Project y luego continúa la ejecución tú mismo.",
    pauseBindingSuspended: "En pausa: la configuración del Workflow cambió. Corrígela y luego continúa o cancela.",
    pausePluginDisabled: "En pausa: {{provider}} está desactivado en Plugins. Vuelve a activarlo y luego continúa o cancela.",
    waitingWorkspace: "Esperando el espacio de trabajo",
    waitingWorkspaceBody: "Esperando a que «{{task}}» termine de escribir en este espacio de trabajo. En un espacio de trabajo se desarrolla un registro a la vez; este empezará solo cuando quede libre.",
    waitingWorkspaceStuck: "La ejecución de «{{task}}» puede tener aún un proceso en marcha; esta empezará cuando lo resuelvas allí.",
    viewHoldingRun: "Ver esa ejecución",
    pausePluginWorkflow: "En pausa: los Workflows están desactivados en Plugins. Actívalos para continuar o cancela ahora.",
    pausePluginWorkflowOn: "En pausa: los Workflows están desactivados en Plugins en {{computer}}. Vuelve a activarlos allí para continuar o cancela ahora.",
    workflowOffAction: "Los Workflows están desactivados en Plugins. Actívalos para continuar.",
    workflowBlockedAction: "Los Workflows no pueden continuar: no hay ningún proveedor activado en Plugins. Activa uno para continuar.",
    staleProposal: "La tarea o los criterios de aceptación cambiaron mientras esto esperaba, así que se te vuelve a pedir según lo que dice ahora el registro.",
    stoppedForcedHint: "Detenida a la fuerza. Revisa el espacio de trabajo antes de la próxima ejecución.",
    stoppedForcedAtStartupHint: "Detenida a la fuerza, confirmado tras el reinicio. Revisa el espacio de trabajo antes de la próxima ejecución.",
    stoppingFor: "deteniéndose desde hace {{seconds}} s",
    confirmPlanTitle: "Confirmar el plan",
    confirmResultTitle: "Decidir el resultado",
    reworkTitle: "Rehacer",
    reworkStart: "Rehacer ahora",
    reworkReasonAcceptance: "Los criterios de aceptación cambiaron",
    reworkReasonTask: "La tarea cambió",
    reworkKeepPlanReconfirm: "Mantener el plan y confirmarlo de nuevo",
    reworkKeepPlan: "Mantener el plan",
    reworkKeepPlanMaybeReconfirm: "Si la tarea o los criterios de aceptación cambiaron, primero se te pedirá confirmar el plan de nuevo.",
    noResultYet: "Aún no hay resultado",
    startWorkflowOff: "Los Workflows están desactivados en Plugins. Actívalos para iniciar una ejecución.",
    startWorkflowBlocked: "Los Workflows no pueden iniciar una ejecución: no hay ningún proveedor activado en Plugins. Activa uno primero.",
    startFailed: "No se pudo iniciar la ejecución. Inténtalo de nuevo.",
    agentWaiting: "{{step}} espera tu respuesta en su Chat",
    agentWaitingBody: "Pidió un permiso o hizo una pregunta. Nada avanza hasta que respondas allí.",
    blockedSignedOut: "{{provider}} no ha iniciado sesión en {{computer}}.",
    blockedAuthUnknown: "No se pudo confirmar que {{provider}} haya iniciado sesión en {{computer}}.",
    blockedAuthChecking: "Todavía se está comprobando si {{provider}} ha iniciado sesión en {{computer}}.",
    blockedAuthError: "Falló la comprobación del inicio de sesión de {{provider}} en {{computer}}.",
    blockedAuthTimeout: "{{provider}} no respondió a tiempo a la comprobación de inicio de sesión en {{computer}}.",
    blockedNotInstalled: "{{provider}} no está instalado en {{computer}}.",
    blockedMeasurementsUnavailable: "{{provider}} aún no tiene las mediciones necesarias para los flujos de trabajo.",
    blockedPluginDisabled: "{{provider}} está desactivado en Plugins.",
    blockedNotMeasured: "{{provider}} aún no se ha comprobado en {{computer}}, así que no puede hacer {{step}}.",
    blockedProviderCannot: "{{provider}} no puede hacer {{step}}: no cumple las garantías que pide este paso.",
    blockedConfigUnavailable: "La configuración elegida para {{step}} ya no está disponible.",
    blockedGuaranteeReadOnly: "La configuración elegida para {{step}} pide un espacio de trabajo de solo lectura, así que no puede cambiar el código.",
    blockedGuaranteeNetwork: "La configuración elegida para {{step}} pide no usar la red, algo que aún no se puede garantizar en {{computer}}.",
    blockedInstanceChanged: "Se reemplazó la Base del Workflow. Vuelve a configurar el Workflow.",
    blockedTaskMissing: "La columna de tareas de la Base ya no existe. Recupérala y continúa.",
    blockedStageMissing: "La columna Fase ya no existe. Recupérala y continúa.",
    blockedAcceptanceMissing: "La columna de criterios de aceptación ya no existe. Recupérala y continúa.",
    blockedNoValidReport: "{{step}} no devolvió un resultado válido.",
    blockedExtractorOff: "{{step}} no devolvió un resultado válido, y Claude, que organiza los resultados, está desactivado en Plugins.",
    blockedExtractorNotInstalled: "{{step}} no devolvió un resultado válido, y Claude, que organiza los resultados, no está instalado en {{computer}}.",
    blockedExtractorSignedOut: "{{step}} no devolvió un resultado válido, y Claude, que organiza los resultados, no ha iniciado sesión en {{computer}}.",
    blockedExtractorAuthUnknown: "{{step}} no devolvió un resultado válido, y no se pudo confirmar que Claude, que organiza los resultados, haya iniciado sesión en {{computer}}.",
    blockedExtractorAuthChecking: "{{step}} no devolvió un resultado válido, y todavía se está comprobando si Claude, que organiza los resultados, ha iniciado sesión en {{computer}}.",
    blockedExtractorAuthError: "{{step}} no devolvió un resultado válido, y falló la comprobación del inicio de sesión de Claude, que organiza los resultados, en {{computer}}.",
    blockedExtractorAuthTimeout: "{{step}} no devolvió un resultado válido, y Claude, que organiza los resultados, no respondió a tiempo a la comprobación de inicio de sesión en {{computer}}.",
    blockedExtractorNotMeasured: "{{step}} no devolvió un resultado válido, y Claude aún no ha superado la comprobación para organizar resultados en {{computer}}.",
    blockedExtractorFailed: "{{step}} no devolvió un resultado válido, y dos intentos de organizarlo desde el Chat no funcionaron.",
    blockedCheckProvider: "Comprobar {{provider}} de nuevo",
    reportDerived: "Organizado a partir de la respuesta",
    reportShortened: "Acortado",
    reportShortenedPlan: "Aquí solo se muestra una parte del plan.",
    reportShortenedReview: "Aquí solo se muestra una parte de la revisión.",
    openWholePlan: "Abrir el plan completo",
    openWholeReview: "Abrir la revisión completa",
    reportDerivedHint: "El Agent no envió el resultado de este paso en el formato esperado. Bottega lo tomó palabra por palabra de la respuesta del Agent y solo conservó las referencias que aparecen en ella.",
    blockedDispatchFailed: "{{step}} no se pudo enviar a {{provider}}.",
    blockedAttemptsExhausted: "Este paso alcanzó el número máximo de intentos. Cancela esta ejecución y vuelve a empezar.",
    blockedOther: "{{step}} no pudo terminar.",
    blockedBaseAction: "No se pudo terminar de actualizar la Base.",
    blockedRecordMissing: "Se eliminó el registro.",
    blockedBaseActionFailed: "{{action}} no pudo terminar: {{failure}}.",
    baseActionRead: "La lectura del registro",
    baseActionSetStage: "El cambio de fase del registro",
    baseActionWriteSummary: "La escritura del resumen",
    baseFailureUnavailable: "la Base no está disponible",
    baseFailureRefused: "se rechazó la escritura",
    baseFailureConflict: "el registro cambió al mismo tiempo",
    baseFailureUnknown: "se desconoce el motivo",
    blockedSignIn: "Iniciar sesión en {{provider}}",
    blockedCheckSignIn: "Comprobar inicio de sesión",
    blockedSetUp: "Configurar {{provider}}",
    blockedChooseConfig: "Elegir otra configuración",
    retryStep: "Reintentar este paso",
    retryStillBlocked: "Comprobado de nuevo: sigue bloqueado.",
    actionFailed: "No se pudo completar. Inténtalo de nuevo.",
    remoteSending: "Enviando a {{computer}}…",
    remoteExpired: "{{computer}} no respondió a tiempo, así que no cambió nada. Puedes volver a intentarlo.",
    remoteCommandExpired: "Esto no llegó a tiempo a {{computer}}, así que no se hizo nada. Vuelve a intentarlo.",
    remoteUnknown: "No se sabe si {{computer}} lo hizo. Revisa la ejecución antes de volver a intentarlo.",
    remoteClassMismatch: "{{computer}} no lo ejecutó: tiene una versión de Bottega distinta de la de este dispositivo. Actualiza Bottega en ambos y vuelve a intentarlo.",
    remoteOffline: "{{computer}} está sin conexión. Podrás actuar aquí cuando vuelva.",
    checkResultFailed: "No se pudo comprobar el resultado. Inténtalo de nuevo.",
    retryFailed: "No se pudo reintentar este paso. Inténtalo de nuevo.",
    retryNotBlocked: "Este paso ya no está bloqueado.",
  },
  appOps: {
    useChat: "Chat de uso",
    edit: "Editar",
    editHintWeb: "Cambia esta App en un Chat en {{computer}}. Se reconstruye cuando termina el Chat.",
    editHintPhone: "Cambia esta App en un Chat en {{computer}}.",
    sending: "Enviando a {{computer}}…",
    sendingUse: "{{computer}} abre el Chat de uso de {{app}}; aparecerá aquí en cuanto responda. Si no responde a tiempo, no cambia nada y puedes volver a intentarlo.",
    sendingEdit: "{{computer}} abre el Chat de edición de {{app}}; aparecerá aquí en cuanto responda. Si no responde a tiempo, no cambia nada y puedes volver a intentarlo.",
    startingEdit: "Iniciando el Chat de edición en {{computer}}…",
    offlineReason: "{{computer}} está sin conexión. Podrás hacerlo cuando vuelva.",
    offlineTitle: "{{computer}} está sin conexión",
    offlineBody: "El Chat de uso y la edición se ejecutan en {{computer}}. Podrás usarlos cuando vuelva. Aquí puedes seguir abriendo {{app}} y editando sus registros.",
    offlineChip: "{{computer}} sin conexión",
    useChatOffline: "Chat de uso ({{computer}} está sin conexión)",
    appNotFound: "{{app}} ya no está en {{computer}}.",
    appNotEditable: "{{app}} no se puede editar en {{computer}}. Solo pueden cambiar sus registros.",
    appBusy: "Todavía hay una respuesta en curso en el Chat de uso actual de {{app}} en {{computer}}. Ábrelo para esperar o detenerla y vuelve a intentarlo.",
    appTransitioning: "{{app}} se está actualizando en {{computer}}. Vuelve a intentarlo en un momento.",
    agentUnavailable: "{{computer}} no tiene ningún Agent disponible. Configura uno en Bottega en {{computer}}.",
    reservationExpired: "{{computer}} no inició el Chat de edición a tiempo. Tu mensaje se conserva: vuelve a enviarlo.",
    reservationFilled: "{{app}} ya tenía un Chat de edición en {{computer}}. Tu mensaje está aquí como borrador.",
    firstMessageText: "El primer mensaje solo admite texto. Los adjuntos funcionan a partir del segundo.",
    unknown: "No se sabe si {{computer}} lo abrió. Puedes volver a intentarlo sin riesgo: no abrirá un segundo Chat.",
    startupPending: "Bottega aún está terminando sus comprobaciones de inicio. Vuelve a intentarlo en un momento.",
    earlierProcess: "Un proceso anterior del Agent aún está terminando. Vuelve a intentarlo en un momento.",
    /* U06-d: the build status on the App page (building, waiting for the extension decision, failed) and its two commands. */
    buildingStatus: "Creando en {{computer}}…",
    buildingTitleWeb: "Creando la nueva versión en {{computer}}…",
    buildingBodyWeb: "La última edición terminó. {{app}} sigue abriendo la versión actual hasta que la nueva esté lista; entonces abre la nueva y te lo indica.",
    buildingTitlePhone: "Creando la nueva versión…",
    buildingBodyPhone: "En {{computer}}. La versión actual sigue abriéndose hasta que la nueva esté lista.",
    buildFailedStatus: "La creación falló",
    buildFailedTitle: "No se pudo crear la nueva versión",
    buildFailedBodyWeb: "La última edición no se pudo crear en {{computer}}. {{app}} sigue abriendo la versión anterior. Para corregir el código, pide al Agent de mantenimiento de {{app}} en tu ordenador que lo diagnostique y lo repare.",
    buildFailedBodyPhone: "La última edición no se pudo crear en {{computer}}. {{app}} sigue abriendo la versión anterior.",
    buildFailedInterrupted: "La actualización se interrumpió antes de terminar. Vuelve a intentarlo.",
    buildRetry: "Reintentar",
    buildRepair: "Reparar en tu ordenador",
    confirmStatus: "Esperando a tu ordenador",
    confirmTitle: "Esperando la confirmación de tu ordenador",
    confirmBody: "Esta edición añade una extensión a {{app}}. Apruébala en {{computer}} para crear la nueva versión. Hasta entonces, la versión actual sigue funcionando.",
    confirmCancel: "Cancelar solicitud",
    confirmCancelledRemotely: "Se canceló desde otro dispositivo.",
    confirmTimedOut: "Nadie lo aprobó en {{computer}} en 30 minutos, así que la nueva versión se creó sin la extensión. Para añadirla, vuelve a pedirlo y apruébalo en {{computer}}.",
    confirmAlreadyResolved: "Ya se respondió en {{computer}}.",
  },
  phone: {
    needsYou: "Pendiente de ti",
    needsYouCount_one: "{{count}} pendiente de ti",
    needsYouCount_other: "{{count}} pendientes de ti",
    sheetNote: "Solo lo que espera una decisión. Al tocar un elemento se abre; no se confirma nada hasta que elijas.",
    empty: "No hay nada esperándote.",
    pushLanding: "Abrir esto no confirma nada.",
    moreNeedsYou: "Aparecerán {{count}} más aquí a medida que atiendas estos.",
    alreadyHandled: "Esto ya se atendió.",
    signInOnComputer: "Inicia sesión en {{provider}} en {{computer}} para usarlo aquí.",
    theComputer: "el ordenador del Project",
    workflowSuspended: "Este Workflow no puede iniciar ejecuciones hasta que se arregle su configuración en {{computer}}.",
  },
};
