/**
 * [INPUT]: Canonical built-in Provider ids; Depends on ./en for the WorkbenchCopy shape.
 * [OUTPUT]: Provides fr, the French workbench catalog.
 * Names built-in recipes and Workflow plugins and explains missing workflow measurements.
 * [POS]: Lazy workbench-copy locale; the interface says only Workflow and Exécution; lanes are couloirs, columns colonnes.
 */
import { BUILTIN_PROVIDER_IDS } from "@bottega/contracts/model/provider-capabilities";
import { dock } from "./dock/fr";
import type { WorkbenchCopy } from "./en";
import { memoryPluginCopy } from "./memory/fr";

export const fr: WorkbenchCopy = {
  guiHistory: {
    title: "Versions",
    current: "Actuelle",
    previous: "Précédente",
    activate: "Utiliser cette version",
    switching: "Changement…",
    pending: "Terminez l’autorisation en attente pour activer cette version.",
    loadFailed: "Impossible de charger les versions.",
    empty: "Aucune version compilée pour le moment.",
    initializing: "Préparation de ce plugin…",
    initializationFailed: "Impossible d’initialiser ce plugin. Réessayez pour le préparer à nouveau.",
    retryInitialization: "Réessayer l’initialisation",
    initializationDetails: "Détails de l’erreur",
    refresh: "Actualiser",
    edit: "Modifier le code",
    installLocal: "Installer depuis un dossier…",
    draftBusy: "Terminez ou effacez le brouillon actuel avant d’ouvrir le Chat du plugin.",
    skillMissing: "Le Skill plugin-authoring est indisponible pour cet Agent.",
    starterPrompt: "Utilisez le Skill plugin-authoring pour créer ce plugin selon les besoins que je vais décrire.",
  },
  terms: {
    pluginsAndApps: "Plugins",
    bottegaPlugin: "Plugin Bottega",
    agentNativePlugin: "Plugin natif d’Agent",
    baseApp: "Base (App intégrée)",
    baseBackedApp: "App basée sur Base",
    agentConfig: "Configuration d’Agent",
    workflow: "Workflow",
    run: "Exécution",
  },
  base: {
    menuGroup: "Workflow",
    setUp: "Configurer un Workflow…",
    settings: "Réglages du Workflow",
    runWorkflow: "Lancer le Workflow",
    runOnTask: "Lancer un Workflow sur cette tâche",
    ready: "Prêt",
  },
  readOnly: {
    badge: "Workflow",
    columnHint: "Seuls les Workflows modifient cette colonne",
    setByWorkflow: "Défini par le Workflow",
    laneLocked: "{{column}} est défini par le Workflow : ce couloir n’accepte pas de cartes. Modifiez plutôt vos propres colonnes, ou ouvrez l’exécution pour changer la suite.",
    whoCanEdit: "Qui peut modifier",
    everyone: "Tout le monde",
    onlyWorkflows: "Workflows uniquement",
    whoCanEditUnavailable: "Seules les colonnes ajoutées par un Workflow peuvent être limitées.",
  },
  record: {
    section: "Workflow",
    run: "Exécution",
    noRuns: "Aucune exécution pour l’instant",
    acceptance: "Acceptation",
    notDecided: "Non décidé",
    accepted: "Accepté",
    acceptedWithException: "Accepté avec une exception",
  },
  plugins: {
    title: "Plugins",
    description: "Les plugins installés sur cet hôte Bottega. Activez-en un ou désactivez-le, appliquez les mises à jour, ou ouvrez-le pour ses réglages et ses détails.",
    searchLabel: "Rechercher des plugins",
    statusLabel: "État",
    statusAll: "Tous les états",
    statusOn: "Activés",
    statusOff: "Désactivés",
    statusAttention: "À vérifier",
    sortLabel: "Tri",
    sortGroup: "Par catégorie",
    sortName: "Par nom",
    sortRecent: "Modifiés récemment",
    newPlugin: "Nouveau plugin",
    groupFeature: "Fonctionnalités Bottega",
    groupProvider: "Fournisseurs",
    groupPackage: "Extensions",
    groupNative: "Plugins natifs des Agents",
    emptyTitle: "Aucun plugin ne correspond",
    clearFilters: "Effacer la recherche et les filtres",
    emptyAll: "Aucun plugin installé.",
    official: "Officiel",
    badgeBuiltin: "Intégré",
    badgePackage: "Extension · v{{version}}",
    badgeNative: "Natif d’Agent",
    alwaysOn: "Toujours activé",
    nativeManagedBy: "Géré par {{agent}}",
    projectScopedBadge: "Un seul Project",
    projectScopedNote: "Installé pour un seul Project, il ne peut pas encore être désactivé ici.",
    setupDock: "Configurer…",
    blocked: "Dépendance manquante",
    unsupported: "Non pris en charge ici",
    providerUsedBy_one: "Utilisé par {{count}} configuration d’Agent",
    providerUsedBy_other: "Utilisé par {{count}} configurations d’Agent",
    providerUnused: "Pas encore utilisé",
    workflowSetUpIn_one: "Configuré dans {{count}} Project",
    workflowSetUpIn_other: "Configuré dans {{count}} Projects",
    workflowSetUpInNames: "Configuré dans {{projects}}",
    turnedOffOn: "Désactivé le {{date}}",
    neverOn: "Jamais activé",
    turnOffTitle: "Désactiver {{name}} ?",
    turnOffBody: "{{name}} ne démarrera plus sur {{computer}}. Rien n’est supprimé ; vous pouvez le réactiver à tout moment.",
    whatChanges: "Ce qui change",
    impactConfigs: "La configuration d’Agent {{config}} ne peut plus être choisie",
    impactWorkflows: "{{workflow}} ne peut pas lancer de nouvelles exécutions tant que {{name}} est désactivé",
    impactRuns_one: "{{count}} exécution qui utilise {{name}} termine son étape en cours, puis se met en pause",
    impactRuns_other: "{{count}} exécutions qui utilisent {{name}} terminent leur étape en cours, puis se mettent en pause",
    impactChats_one: "{{count}} chat avec {{name}} reste lisible, mais ne peut plus continuer",
    impactChats_other: "{{count}} chats avec {{name}} restent lisibles, mais ne peuvent plus continuer",
    impactMore_one: "et {{count}} autre",
    impactMore_other: "et {{count}} autres",
    dependentsTitle: "Ces plugins cesseront de fonctionner",
    dependentLine: "{{plugin}} : il a besoin de ce que seul {{name}} fournit",
    turnOff: "Désactiver",
    turnOn: "Activer",
    thisComputer: "cet ordinateur",
    switchFailed: "Impossible de modifier {{name}}. Réessayez.",
    switchLabel: "Activer ou désactiver {{name}}",
    reinstallRequired: "Les fichiers installés de {{name}} ont changé pendant qu’il était désactivé. Il ne peut pas être réactivé pour l’instant.",
    reinstallHelp: "Dites-le-nous et nous vous aiderons à le restaurer.",
    reinstallIssueTitle: "{{name}} ne peut pas être réactivé",
    reinstallBadge: "Réactivation impossible",
    reportProblem: "Signaler un problème",
    busyNote: "{{name}} est occupé. Vous pourrez le modifier une fois l’opération terminée.",
    turningOn: "Activation…",
    turningOff: "Désactivation…",
    chatTurnedOff: "{{provider}} est désactivé dans Plugins. Réactivez-le pour continuer ce chat.",
    openPlugin: "Ouvrir le plugin {{name}}",
    back: "Tous les plugins",
    on: "Activé",
    off: "Désactivé",
    sectionSettings: "Réglages",
    settingsNote: "Déclarés par le plugin",
    settingsProviderNote: "Les sessions en cours ne changent pas",
    appliesImmediate: "Immédiat",
    appliesNextTurn: "Au prochain tour",
    appliesSessionCreate: "Nouvelles sessions",
    appliesProcessStart: "Après redémarrage",
    changed: "Modifié",
    resetDefault: "Rétablir la valeur par défaut",
    confirmContinue: "Continuer",
    secretSet: "Défini",
    secretUnset: "Non défini",
    secretReplace: "Remplacer",
    secretClear: "Effacer",
    secretSave: "Enregistrer",
    secretCancel: "Annuler",
    decrease: "Diminuer",
    increase: "Augmenter",
    settingsFailed: "Impossible d’enregistrer « {{setting}} ». Réessayez.",
    pendingRestart: "{{name}} redémarrera quand il sera inactif pour appliquer vos changements.",
    sectionHealth: "État",
    checkedAt: "Vérifié {{time}}",
    update: "Mettre à jour",
    setUp: "Configurer",
    sectionUsedBy: "Utilisé par",
    usedByConfigs: "Configurations d’Agent",
    usedByProjects: "Projects avec des Workflows",
    usedByNobody: "Rien ne l’utilise encore.",
    sectionDependencies: "Dépendances",
    depRequires: "Requiert",
    depProvides: "Fournit",
    depDependents: "Requis par",
    depNone: "Aucune",
    depSatisfiedBy: "Fourni par {{plugins}}",
    depHostNote: "Les réglages, le stockage, les événements et les tâches de fond viennent de Bottega et sont toujours disponibles.",
    blockedMissing: "Rien ne le fournit",
    blockedDisabled: "Tout ce qui le fournit est désactivé",
    blockedUnsupported: "Ce qui le fournit ne fonctionne pas sur cet ordinateur",
    blockedCycle: "Il dépend de lui-même en boucle",
    blockedBanner: "{{name}} ne peut pas démarrer de nouveau travail. {{reason}}.",
    sectionCapabilities: "Capacités et autorisations",
    capabilitiesNone: "Rien de déclaré.",
    sectionIncludes: "Contient",
    sectionCanDo: "Ce qu’il peut faire",
    sectionWorksWith: "Dépendances",
    sectionInUse: "Utilisation",
    sectionInformation: "Informations",
    worksAlone: "Fonctionne seul. Aucun autre plugin n’en dépend.",
    aboutPlugin: "À propos de {{name}}",
    publisherBottega: "Bottega",
    about: "À propos",
    aboutSource: "Source",
    aboutVersion: "Version",
    aboutKind: "Type",
    aboutId: "ID du plugin",
    aboutManagedBy: "Géré par",
    aboutLocation: "Emplacement",
    aboutPublisher: "Éditeur",
    unsigned: "Non signé",
    versionWithApp: "Fourni avec Bottega {{version}}",
    kindFeature: "Fonctionnalité",
    kindProvider: "Fournisseur",
    sourceLocalLong: "Source locale",
    sourceBuiltinLong: "Intégré à Bottega",
    sourcePackageLong: "Extension",
    sourceNativeLong: "Natif d’Agent",
    related: "Pages liées",
    relatedProviders: "Fournisseurs",
    relatedAgentConfigs: "Configurations d’Agent",
    relatedUsage: "Utilisation",
    relatedSkills: "Skills",
    relatedMemory: "Mémoire",
    relatedDock: "Dock",
    nativeReadOnly: "Géré par {{agent}}. Bottega se contente de l’afficher ; installez-le, mettez-le à jour ou supprimez-le dans {{agent}}.",
    notFound: "Ce plugin n’est plus installé.",
    loadFailed: "Impossible de charger ce plugin. Réessayez.",
    retry: "Réessayer",
    sidebarGroup: "Plugins",
    sidebarAll: "Tous les plugins",
    health: {
      unknown: "Pas encore vérifié",
      notChecked: "Pas encore vérifié",
      ready: "Prêt",
      off: "Désactivé",
      running: "En cours d’exécution",
      idle: "Prêt, à l’arrêt",
      process: "Processus",
      processRunning: "En cours d’exécution",
      processIdle: "Démarre à la demande",
      nativeEnabled: "{{agent}} le signale activé",
      nativeDisabled: "{{agent}} le signale désactivé",
      cliVersion: "CLI",
      signIn: "Connexion",
      runningRuns: "Exécutions en cours",
      cli: {
        unknown: "Non vérifiée",
        missing: "Non installée",
        error: "Vérification impossible",
        unsupported: "Mise à jour requise",
        installed: "Installée",
      },
      auth: {
        unknown: "Inconnue",
        checking: "Vérification…",
        authenticated: "Connecté",
        unauthenticated: "Non connecté",
        error: "Vérification impossible",
      },
    },
    unsupportedReason: {
      appleSilicon: "Uniquement sur macOS avec puce Apple",
    },
    capability: {
      startProcess: "Lance sa CLI sur cet ordinateur",
      projectFiles: "Lit et écrit dans les dossiers des Projects, selon chaque configuration d’Agent",
      network: "Se connecte à son propre service",
      baseStore: "Conserve des tableaux dans le dossier de chaque Project",
      baseTools: "Donne aux Agents des outils Base pour lire, écrire et interroger les enregistrements",
      workflowColumns: "Ajoute les colonnes Étape et Critères d’acceptation à une Base ; seuls les Workflows écrivent l’Étape",
      workflowRoles: "Exécute chaque rôle avec sa configuration d’Agent",
    },
    builtin: {
      memory: memoryPluginCopy,
      dock,
      sketch: { name: "Croquis", summary: "Dessinez, effacez et joignez une image modifiable.", description: "Croquis ajoute une zone de dessin au compositeur. Dessinez, effacez, annotez, puis joignez le résultat à votre message comme image modifiable." },
      base: {
        name: "Base",
        summary: "Tableaux, Kanban, listes et formulaires dans chaque Project. Les Workflows et les Apps basées sur Base s’appuient dessus.",
        description: "Base donne à chaque Project ses propres tables. Affichez les enregistrements en tableau, Kanban, liste ou formulaire, rangés dans le dossier du Project à côté de vos fichiers.\n\nLes Agents lisent, écrivent et interrogent les enregistrements avec les outils Base. Les Workflows et les Apps basées sur Base reposent dessus, il reste donc toujours activé.",
      },
      workflow: {
        name: "Workflow",
        summary: "Des rôles d’Agent font avancer le travail sur une Base, étape par étape, avec une revue à chaque étape.",
        description: "Workflow transforme une Base en chaîne de production. Chaque étape est un rôle tenu par une de vos configurations d’Agent, et chaque étape se termine par une revue avant de passer à la suivante.\n\nConfigurez-le dans un Project et ajoutez des cartes dans sa première colonne. Ouvrez une exécution pour voir ce que chaque rôle a fait et décider de la suite.",
      },
      [BUILTIN_PROVIDER_IDS.claude]: {
        name: "Claude",
        summary: "Claude Code d’Anthropic, exécuté comme Agent dans Bottega.",
        description: "Exécutez Claude Code d’Anthropic comme Agent dans Bottega. Il travaille dans vos dossiers de Project avec l’accès autorisé par chaque configuration d’Agent.\n\nIl nécessite la CLI Claude Code et un compte Anthropic connecté sur cet ordinateur. Les options comme le contexte d’un million de jetons et Claude in Chrome se trouvent dans ses réglages.",
        publisher: "Anthropic",
        settings: {
          memory: {
            label: "Mémoire",
            description: "Laisser Claude Code lire et écrire sa propre mémoire automatique dans les chats Bottega. Les rôles de Workflow ne l’utilisent jamais.",
          },
          nativeSubagents: {
            label: "Autoriser les sous-agents natifs",
            description: "Laisser Claude Code lancer ses propres sous-agents avec son outil Task.",
          },
          workflowTool: {
            label: "Autoriser l’outil Workflow",
            description: "Laisser Claude Code utiliser son propre outil Workflow.",
          },
          context1m: {
            label: "Utiliser le contexte 1M",
            description: "Laisser Claude Code utiliser une fenêtre de contexte d’un million de jetons.",
          },
          claudeInChrome: {
            label: "Claude in Chrome",
            description: "Démarrer Claude Code avec les outils de navigateur Claude in Chrome. Nécessite l’extension Chrome sur cet ordinateur, connectée à claude.ai.",
          },
        },
      },
      [BUILTIN_PROVIDER_IDS.codex]: {
        name: "Codex",
        summary: "La CLI Codex d’OpenAI, exécutée comme Agent dans Bottega.",
        description: "Exécutez la CLI Codex d’OpenAI comme Agent dans Bottega. Elle lit et modifie vos dossiers de Project dans les limites de chaque configuration d’Agent.\n\nElle nécessite la CLI Codex et un compte OpenAI connecté sur cet ordinateur. Ses propres mémoires et sa fonction multi-agent peuvent être désactivées dans ses réglages.",
        publisher: "OpenAI",
        settings: {
          memory: {
            label: "Mémoire",
            description: "Laisser Codex utiliser ses propres mémoires dans les chats Bottega. Les rôles de Workflow ne les utilisent jamais.",
          },
          nativeSubagents: {
            label: "Autoriser les sous-agents natifs",
            description: "Laisser Codex utiliser sa propre fonction multi-agents.",
          },
        },
      },
      [BUILTIN_PROVIDER_IDS.kimi]: {
        name: "Kimi",
        summary: "La CLI Kimi de Moonshot, exécutée comme Agent dans Bottega.",
        description: "Exécutez la CLI Kimi de Moonshot comme Agent dans Bottega. Elle nécessite la CLI Kimi et un compte Moonshot connecté sur cet ordinateur.",
        publisher: "Moonshot AI",
      },
      [BUILTIN_PROVIDER_IDS.opencode]: {
        name: "OpenCode",
        summary: "OpenCode, open source, qui peut utiliser les modèles de nombreux services.",
        description: "Exécutez la CLI open source OpenCode comme Agent dans Bottega. Elle peut utiliser des modèles de nombreux services.",
        publisher: "OpenCode",
      },
    },
  },
  agentConfigs: {
    loading: "Chargement des configurations Agent…",
    loadFailed: "Impossible de charger les configurations Agent. Réessayez.",
    refreshFailed: "Impossible d’actualiser les configurations Agent. La dernière liste chargée reste affichée.",
    unavailable: "Les configurations Agent sont indisponibles dans cette fenêtre. Réessayez ou rouvrez les réglages.",
    reasoningEffort: "Effort de raisonnement",
    agentDefault: "Par défaut de l’Agent",
    modelsFailed: "Impossible de charger les modèles. Vos choix sont conservés.",
    defaultsFailed: "Impossible de charger vos valeurs par défaut. Choisissez un modèle ou réessayez.",
    optionUnavailable: "Ce choix enregistré est indisponible ici. Il sera conservé tant que vous ne choisissez pas une autre option.",
    chooseModelForEffort: "Choisissez un modèle disponible pour voir ses options de raisonnement.",
    baseResource: "Base",
    chatResource: "Chat",
    mcpResource: "MCP",
    selectedCount: "{{count}} / {{limit}} sélectionnés",
    resourcesLoading: "Chargement des ressources locales…",
    resourcesFailed: "Certaines ressources n’ont pas pu être chargées. Vos sélections sont conservées.",
    resourcesEmpty: "Aucune ressource locale disponible.",
    resourceUnavailable: "Indisponible ici",
    baseRead: "Lecture seule",
    baseReadWrite: "Lecture et écriture",
    linkedChats: "Chats liés uniquement",
    resourcesHint: "Les nouvelles exécutions utilisent uniquement les ressources sélectionnées. Une ressource absente sur un autre ordinateur bloque l’exécution jusqu’à sa correction.",
    resourcesReadOnly: "La planification, la revue et les configurations en lecture seule peuvent uniquement lire la Base et ne peuvent pas utiliser de serveurs MCP.",
    baseCapped: "Demandé : lecture et écriture. Effectif : lecture seule. La demande enregistrée est conservée.",
    removeReadOnlyMcp: "Retirez les serveurs MCP sélectionnés pour enregistrer une configuration en lecture seule.",
    retryResources: "Recharger les ressources",
    title: "Configurations d’Agent",
    description: "Fournisseur, modèle, instructions et outils réutilisables.",
    allProjects: "Tous les Projects",
    someProjects: "Certains Projects",
    someProjectsDescription: "Affichée uniquement dans les Projects listés sous chaque configuration.",
    newConfig: "Nouvelle configuration",
    edit: "Modifier",
    readOnly: "Lecture seule",
    newTitle: "Nouvelle configuration d’Agent",
    editTitle: "Modifier la configuration d’Agent",
    prefilled: "Préremplie pour le rôle {{role}} : rôle, autorisations et outils. Tout reste modifiable.",
    startFrom: "Partir de",
    blank: "Vide",
    planner: "Planification",
    developer: "Développement",
    reviewer: "Relecture",
    name: "Nom",
    availableIn: "Disponible dans",
    searchProjects: "Rechercher des Projects",
    provider: "Fournisseur",
    chooseProvider: "Choisir un fournisseur",
    model: "Modèle",
    providerDefault: "Par défaut (fournisseur)",
    instructions: "Instructions",
    instructionsHint: "Envoyées à l’Agent",
    purpose: "Objectif",
    purposeHint: "Affiché aux personnes qui choisissent une configuration",
    permissions: "Autorisations",
    skills: "Skills",
    toolsAndData: "Outils et données",
    toolsBaseReadWriteLinked: "Base en lecture et écriture · chats liés uniquement",
    toolsBaseReadLinked: "Base en lecture · chats liés uniquement",
    none: "Aucun",
    create: "Créer",
    missingRequired: "Ajoutez un nom et choisissez un fournisseur",
    appliesToNewRuns: "Les modifications s’appliquent aux exécutions lancées après l’enregistrement.",
    appliesNextTurn: "S’applique au prochain tour",
    restartsAgent: "Redémarre l’Agent",
    appliesOnNew: "S’applique aux nouveaux chats",
    notForRole: "Non adapté à ce rôle",
    notAdmitted: "Pas encore validé pour le rôle {{role}}",
    partialFailure: "Certains réglages n’ont pas pu être appliqués : cette configuration n’est pas prête pour son rôle.",
    presetPlanner: "Lisez la tâche et ses critères d’acceptation, puis rédigez un plan étape par étape. Ne modifiez pas le code.",
    presetDeveloper: "Suivez le plan accepté. Limitez les modifications à la tâche. Lancez les vérifications du Project avant de rendre compte.",
    presetReviewer: "Vérifiez le résultat par rapport au plan et aux critères d’acceptation. Signalez ce qui manque. Ne modifiez pas le code.",
    emptyTitle: "Aucune configuration d’Agent pour l’instant",
    emptyBody: "Créez-en une pour la choisir dans une étape d’un Workflow.",
    syncing: "Synchronisation",
    conflicted: "À vérifier",
    notSynced: "Non synchronisé",
    syncIssueBudget: "Ce compte a atteint sa limite de 100 configurations d’Agent, celle-ci n’est donc pas encore synchronisée. Supprimez une configuration que vous n’utilisez plus et elle se synchronisera automatiquement.",
    saveFailed: "Impossible d’enregistrer cette configuration. Vos modifications sont conservées.",
    allProjectsHint: "Proposée dans tous les Projects",
    noProjects: "Aucun Project pour l’instant",
    needsAttention: "À traiter",
    guaranteeReadOnly: "Espace de travail en lecture seule",
    guaranteeNoNetwork: "Sans réseau",
    reasonProviderCannot: "{{provider}} ne peut pas le garantir",
    reasonHostCannot: "Cet ordinateur ne peut pas l’imposer",
    reasonHostUnavailable: "Vérification impossible : l’ordinateur qui l’exécute n’est pas disponible",
    reasonNotMeasured: "Pas encore vérifié",
    applyPartial: "{{settings}} n’ont pas pris effet sur cet ordinateur ; un Workflow ne peut donc pas encore utiliser cette configuration.",
    applyPartialGeneric: "Certains réglages n’ont pas pris effet sur cet ordinateur ; un Workflow ne peut donc pas encore utiliser cette configuration.",
    workspace: "Espace de travail",
    workspaceWrite: "Peut modifier les fichiers",
    workspaceReadOnly: "Lecture seule",
    network: "Réseau",
    networkOn: "Activé",
    networkOff: "Désactivé",
    notReadOnly: "Son espace de travail n’est pas en lecture seule",
    providerTurnedOff: "{{provider}} est désactivé",
  },
  setup: {
    enableTitle: "Activer le workflow",
    enableDescription: "Planifier, développer et vérifier sur cet ordinateur.",
    enableAndRun: "Activer et lancer cette ligne",
    noReadyProvider: "Aucun fournisseur n’est prêt pour ce workflow.",
    openSettings: "Ouvrir les paramètres",
    openBase: "Ouvrir la Base pour gérer les colonnes",
    openProject: "Ouvrir les paramètres du projet",
    projectUnavailable: "Choisissez d’abord un dossier de travail dans les paramètres du projet.",
    enableFailed: "Impossible d’activer le workflow. Vérifiez à nouveau ses conditions.",
    checkAgain: "Vérifier à nouveau",
    refusalSkillUnavailable: "Un Skill sélectionné dans {{config}} est absent ou désactivé sur cet ordinateur.",
    refusalMcpUnavailable: "Un serveur MCP sélectionné dans {{config}} est indisponible sur cet ordinateur.",
    refusalMcpReadOnly: "{{config}} sélectionne des serveurs MCP inutilisables pour la planification et la revue. Retirez cette sélection ou choisissez une autre configuration.",
    planDevelopReview: "Planifier · Développer · Réviser",
    newTitle: "Configurer un Workflow",
    editTitle: "Réglages du Workflow",
    stepOf: "Étape {{current}} sur {{total}}",
    tabWorkflow: "Workflow",
    tabWho: "Qui fait quoi",
    tabBase: "Votre Base",
    tabCheck: "Vérification",
    chooseTitle: "Choisir un Workflow",
    whoTitle: "Qui fait chaque étape",
    whoHint: "Cliquez sur un nom pour le changer.",
    whoGreyedHint: "Chaque liste montre qui peut faire cette étape ; les autres sont grisés avec la raison.",
    you: "Vous",
    addStep: "Ajouter une étape",
    stepPlan: "Planifier",
    stepPlanDescription: "Rédige un plan pour la tâche",
    stepConfirm: "Confirmer",
    stepConfirmDescription: "Vous lisez le plan et l’acceptez",
    stepDevelop: "Développer",
    stepDevelopDescription: "Modifie le code",
    stepReview: "Relire",
    stepReviewDescription: "Vérifie le résultat sans le modifier",
    stageDone: "Terminé",
    stepDecide: "Décider",
    stepDecideDescription: "Vous acceptez, arrêtez ou faites refaire",
    youConfirm: "Vous confirmez",
    youDecide: "Vous décidez",
    baseTitle: "Ce qui change dans votre Base",
    baseIntro_one: "Le Workflow ajoute 1 colonne. Vos données existantes ne sont pas modifiées.",
    baseIntro_other: "Le Workflow ajoute {{count}} colonnes. Vos données existantes ne sont pas modifiées.",
    baseIntroEditing: "Votre Base a déjà les colonnes du Workflow. Rien ne change ici.",
    baseNow: "Maintenant",
    baseAfter: "Après activation",
    baseNewColumns_one: "Votre Base reçoit 1 nouvelle colonne",
    baseNewColumns_other: "Votre Base reçoit {{count}} nouvelles colonnes",
    stageColumn: "Phase",
    stageDescription: "Indique où en est chaque tâche. Le Workflow la met à jour ; vous ne pouvez pas la modifier.",
    acceptanceColumn: "Critères d’acceptation",
    boardView: "Tableau · par phase",
    acceptanceDescription: "Vous écrivez ce que « terminé » veut dire pour chaque tâche.",
    baseOthersUnchanged: "Vos autres colonnes restent telles quelles.",
    baseFixedColumns: "Le Workflow détermine ces deux colonnes ; elles ne peuvent pas être modifiées ici.",
    baseFull_one: "Cette Base a déjà {{existing}} colonnes sur {{limit}}. Supprimez 1 colonne dans la Base pour activer le Workflow.",
    baseFull_other: "Cette Base a déjà {{existing}} colonnes sur {{limit}}. Supprimez {{count}} colonnes dans la Base pour activer le Workflow.",
    baseBoardAdded: "Ajoute la vue « {{view}} » et l’ouvre. Vos autres vues restent telles quelles.",
    baseBoardNoRoom: "Cette Base a déjà {{limit}} vues, donc la vue « {{view}} » n’est pas ajoutée. Le Workflow s’active quand même.",
    baseChanged: "Les colonnes de la Base ont changé pendant que cette fenêtre était ouverte. Elles s’affichent ici telles qu’elles sont maintenant.",
    checkTitle: "Vérifier et activer",
    checkedOn: "Vérifié sur {{computer}}.",
    providerReady: "{{provider}} est prêt sur {{computer}}",
    checking: "Vérification sur cet ordinateur…",
    roleReady: "{{step}} : {{provider}} est prêt sur {{computer}}",
    roleProblem: "{{step}} : {{reason}}",
    refusalDeleted: "Cette configuration a été supprimée.",
    refusalNotEnabled: "{{config}} a été créée sur un autre appareil et n’a pas encore été enregistrée sur {{computer}}. Ouvrez-la dans les configurations d’Agent et enregistrez-la une fois.",
    refusalMismatch: "{{config}} est passée à un autre Provider et doit être confirmée. Ouvrez-la dans les configurations d’Agent et enregistrez-la une fois.",
    refusalSelection: "{{config}} définit sa propre Memory, que les étapes d’un Workflow ne peuvent pas encore utiliser. Choisissez une autre configuration.",
    refusalMemoryWrite: "{{config}} demande à écrire dans Memory. Les étapes d’un Workflow peuvent uniquement la lire.",
    refusalScope: "Les étapes d’un Workflow ne prennent pas en charge les réglages Skills ou Tools de {{config}}. Ouvrez la configuration et enregistrez-la à nouveau.",
    refusalPartial: "{{settings}} de {{config}} n’ont pas pris effet sur {{computer}}. Ouvrez la configuration pour corriger.",
    refusalPartialGeneric: "Certains réglages de {{config}} n’ont pas pris effet sur {{computer}}. Ouvrez la configuration pour les vérifier.",
    refusalReadOnly: "Demande un espace de travail en lecture seule, ne peut donc pas modifier le code.",
    refusalNoNetwork: "Demande l’absence de réseau, ce qui ne peut pas encore être garanti sur {{computer}}.",
    baseHasRoom_one: "La Base a de la place pour 1 colonne de plus",
    baseHasRoom_other: "La Base a de la place pour {{count}} colonnes de plus",
    baseGets: "La Base reçoit",
    needsComputer: "{{computer}} doit être en ligne",
    turnOn: "Activer",
    continue: "Continuer",
    back: "Retour",
  },
  projectWorkflows: {
    tab: "Workflows",
    description: "Les Workflows que vous pouvez lancer depuis une tâche de la Base de ce Project.",
    addWorkflow: "Ajouter un Workflow",
    on: "Activé",
    off: "Désactivé",
    runsOn: "s’exécute sur {{computer}}",
    configsTitle: "Configurations d’Agent de ce Project",
    configsHint: "Les configurations personnelles sont dans Réglages › Configurations d’Agent.",
    availableIn: "Disponible dans {{projects}}",
    needsBase: "Ajoutez un Workflow quand ce Project aura une Base. Les Workflows s’exécutent sur ses tâches.",
    workflowChats_one: "{{count}} Chat de Workflow",
    workflowChats_other: "{{count}} Chats de Workflow",
    workflowRuns_one: "{{count}} exécution",
    workflowRuns_other: "{{count}} exécutions",
    alsoArchived: "Aussi archivés avec lui : {{chats}}, issus de {{runs}}.",
    alsoArchivedNoRuns: "Aussi archivés avec lui : {{chats}}.",
    alsoDeleted: "Les {{chats}} de ce Project seront supprimés avec lui.",
    archiveStepRunning: "Une étape du Workflow est en cours, l’archivage n’est donc pas encore possible. L’exécution se met en pause à la fin de l’étape. Réessayez à ce moment-là.",
    runsStillStopping: "Une exécution de Workflow de ce Project est encore en cours d’arrêt, et un processus tourne peut-être encore. Forcez son arrêt depuis l’exécution, puis réessayez.",
    runtimeNotReady: "Les Workflows démarrent encore sur cet ordinateur. Réessayez dans un instant.",
  },
  run: {
    blockedVersionTooOld: "Mettez à jour {{provider}} sur {{computer}} avant d’exécuter ce Workflow.",
    blockedExtractorVersionTooOld: "L’étape {{step}} n’a pas rendu de résultat valide. Mettez à jour Claude sur {{computer}} pour l’organiser.",
    label: "Exécution n° {{number}}",
    onComputer: "sur {{computer}}",
    queued: "En file d’attente",
    running: "En cours",
    needsYou: "Action requise",
    paused: "En pause",
    blocked: "Bloquée",
    cancelling: "Annulation…",
    succeeded: "Réussie",
    failed: "Échec",
    cancelled: "Annulée",
    stopped: "Arrêtée",
    stoppedForced: "Arrêt forcé",
    pausedWaited: "En pause · 24 h d’attente",
    pausedArchived: "En pause · Project archivé",
    cancellingTitle: "Annulation en cours",
    cancellingBody: "Aucune nouvelle étape ne démarrera. Bottega arrête {{provider}} sur {{computer}} ; cela peut prendre quelques secondes. L’arrêt n’est effectif que lorsqu’il est indiqué ici.",
    stuckTitle: "Toujours pas arrêté après 30 secondes",
    stuckBody: "{{provider}} sur {{computer}} ne s’est pas arrêté. Vous pouvez forcer l’arrêt. Le code déjà modifié reste dans l’espace de travail ; vérifiez-le avant la prochaine exécution.",
    forceStop: "Forcer l’arrêt",
    forceStopUnconfirmedTitle: "Un processus tourne peut-être encore",
    forceStopUnconfirmedBody: "Bottega a arrêté l’étape sur {{computer}}, sans pouvoir confirmer que tous les processus sont terminés. Forcez l’arrêt à nouveau, puis vérifiez l’espace de travail avant la prochaine exécution.",
    waitingFor: "En attente de {{computer}}",
    reminder: "Le plan attend depuis 23 heures. Décidez dans l’heure, sinon l’exécution se met en pause.",
    waitingStarted: "Un plan attend votre relecture.",
    reminderResult: "Le résultat attend depuis 23 heures. Décidez dans l’heure, sinon l’exécution se met en pause.",
    waitingStartedResult: "Un résultat attend votre décision.",
    pauseConfirmationTimeout: "En pause : cette confirmation attend depuis plus de 24 heures. Continuez pour qu’elle vous soit redemandée.",
    pausedNotice: "Mise en pause après 24 heures d’attente. Rien n’a été exécuté. Ouvrez-la pour continuer.",
    resume: "Continuer",
    resultUnknown: "Résultat inconnu",
    resultUnknownBody: "{{computer}} l’a acceptée à {{time}}, mais le résultat n’est pas revenu. Elle ne sera pas renvoyée automatiquement.",
    checkResult: "Vérifier le résultat",
    acceptPlan: "Accepter le plan",
    accept: "Accepter",
    acceptWithException: "Accepter avec une exception",
    exceptionReason: "Pourquoi l’acceptez-vous malgré tout ?",
    exceptionReasonRequired: "Indiquez une raison pour accepter avec une exception.",
    end: "Arrêter",
    rework: "Refaire",
    reworkFromDevelop: "Garder le plan accepté et repartir de l’étape Développer",
    replan: "Planifier à nouveau",
    reconfirm: "Les critères d’acceptation ont changé. Confirmez à nouveau le plan avant que l’exécution continue.",
    alreadyHandled: "Déjà traité sur {{device}}",
    viewResult: "Voir le résultat",
    viewLog: "Voir le journal",
    tryAgain: "Réessayer",
    details: "Détails de l’exécution",
    startRun: "Lancer l’exécution",
    pause: "Mettre en pause",
    cancelRun: "Annuler l’exécution",
    cancelConfirmTitle: "Annuler cette exécution ?",
    cancelConfirmBody: "L’étape en cours s’arrête d’abord ; le code qu’elle a déjà modifié reste dans l’espace de travail. Cette exécution ne reprendra pas ; vous pourrez en relancer une plus tard.",
    keepRunning: "Continuer l’exécution",
    forceConfirmTitle: "Forcer l’arrêt ?",
    forceConfirmBody: "Tous les processus de cette étape sur {{computer}} s’arrêtent immédiatement. Ce qu’elle a déjà modifié n’est pas annulé ; vérifiez l’espace de travail avant la prochaine exécution.",
    keepWaiting: "Continuer d’attendre",
    openChat: "Ouvrir le chat",
    artifact: "Résultat",
    evidence: "Preuves",
    stepPending: "Pas commencé",
    stepRunning: "En cours",
    stepWaiting: "Action requise",
    stepSucceeded: "Terminé",
    stepFailed: "Échec",
    stepBlocked: "Bloqué",
    stepCarried: "Repris du plan accepté",
    stepNotRun: "Non exécuté",
    pauseUser: "Vous avez mis cette exécution en pause.",
    pauseProjectArchived: "En pause, car le Project a été archivé. Restaurez le Project, puis reprenez.",
    pauseProjectRestored: "Cette exécution a été mise en pause lors de l’archivage du Project. Continuez quand vous êtes prêt.",
    pausingAfterStep: "Cette exécution se met en pause à la fin de l’étape en cours.",
    pausingArchived: "Le Project a été archivé. Cette exécution se met en pause à la fin de l’étape en cours.",
    projectArchived: "Ce Project est archivé, ses exécutions ne peuvent donc ni démarrer ni reprendre. Restaurez le Project, puis reprenez l’exécution vous-même.",
    pauseBindingSuspended: "En pause : la configuration du Workflow a changé. Corrigez-la, puis continuez ou annulez.",
    pausePluginDisabled: "En pause : {{provider}} est désactivé dans Plugins. Réactivez-le, puis continuez ou annulez.",
    waitingWorkspace: "En attente de l’espace de travail",
    waitingWorkspaceBody: "En attente que « {{task}} » ait fini d’écrire dans cet espace de travail. Un seul enregistrement est développé à la fois dans un espace de travail ; celui-ci démarrera tout seul quand il sera libre.",
    waitingWorkspaceStuck: "L’exécution de « {{task}} » a peut-être encore un processus en cours ; celle-ci démarrera une fois le problème réglé là-bas.",
    viewHoldingRun: "Voir cette exécution",
    pausePluginWorkflow: "En pause : les Workflows sont désactivés dans Plugins. Activez-les pour continuer, ou annulez maintenant.",
    pausePluginWorkflowOn: "En pause : les Workflows sont désactivés dans Plugins sur {{computer}}. Réactivez-les là-bas pour continuer, ou annulez maintenant.",
    workflowOffAction: "Les Workflows sont désactivés dans Plugins. Activez-les pour continuer.",
    workflowBlockedAction: "Les Workflows ne peuvent pas continuer : aucun fournisseur n’est activé dans Plugins. Activez-en un pour continuer.",
    staleProposal: "La tâche ou les critères d’acceptation ont changé pendant l’attente. La confirmation vous est donc redemandée d’après ce que dit l’enregistrement maintenant.",
    stoppedForcedHint: "Arrêt forcé. Vérifiez l’espace de travail avant la prochaine exécution.",
    stoppedForcedAtStartupHint: "Arrêt forcé, confirmé après le redémarrage. Vérifiez l’espace de travail avant la prochaine exécution.",
    stoppingFor: "arrêt en cours depuis {{seconds}} s",
    confirmPlanTitle: "Confirmer le plan",
    confirmResultTitle: "Décider du résultat",
    reworkTitle: "Refaire",
    reworkStart: "Refaire maintenant",
    reworkReasonAcceptance: "Les critères d’acceptation ont changé",
    reworkReasonTask: "La tâche a changé",
    reworkKeepPlanReconfirm: "Garder le plan et le confirmer à nouveau",
    reworkKeepPlan: "Garder le plan",
    reworkKeepPlanMaybeReconfirm: "Si la tâche ou les critères d’acceptation ont changé, on vous demandera d’abord de confirmer à nouveau le plan.",
    noResultYet: "Pas encore de résultat",
    startWorkflowOff: "Les Workflows sont désactivés dans Plugins. Activez-les pour lancer une exécution.",
    startWorkflowBlocked: "Les Workflows ne peuvent pas démarrer : aucun fournisseur n’est activé dans Plugins. Activez-en un d’abord.",
    startFailed: "Impossible de lancer l’exécution. Réessayez.",
    agentWaiting: "{{step}} attend votre réponse dans son Chat",
    agentWaitingBody: "Il demande une autorisation ou pose une question. Rien n’avance tant que vous n’y répondez pas.",
    blockedSignedOut: "{{provider}} n’est pas connecté sur {{computer}}.",
    blockedAuthUnknown: "Impossible de confirmer que {{provider}} est connecté sur {{computer}}.",
    blockedAuthChecking: "Vérification en cours de la connexion de {{provider}} sur {{computer}}.",
    blockedAuthError: "La vérification de la connexion de {{provider}} sur {{computer}} a échoué.",
    blockedAuthTimeout: "{{provider}} n’a pas répondu à temps à la vérification de connexion sur {{computer}}.",
    blockedNotInstalled: "{{provider}} n’est pas installé sur {{computer}}.",
    blockedMeasurementsUnavailable: "{{provider}} ne dispose pas encore des résultats de mesure requis pour les flux de travail.",
    blockedPluginDisabled: "{{provider}} est désactivé dans Plugins.",
    blockedNotMeasured: "{{provider}} n’a pas encore été vérifié sur {{computer}}, il ne peut donc pas faire l’étape {{step}}.",
    blockedProviderCannot: "{{provider}} ne peut pas faire l’étape {{step}} : il ne tient pas les garanties qu’elle demande.",
    blockedConfigUnavailable: "La configuration choisie pour {{step}} n’est plus disponible.",
    blockedGuaranteeReadOnly: "La configuration choisie pour {{step}} demande un espace de travail en lecture seule, elle ne peut donc pas modifier le code.",
    blockedGuaranteeNetwork: "La configuration choisie pour {{step}} demande l’absence de réseau, ce qui ne peut pas encore être garanti sur {{computer}}.",
    blockedInstanceChanged: "La Base du Workflow a été remplacée. Configurez à nouveau le Workflow.",
    blockedTaskMissing: "La colonne des tâches de la Base a disparu. Rétablissez-la, puis continuez.",
    blockedStageMissing: "La colonne Phase a disparu. Rétablissez-la, puis continuez.",
    blockedAcceptanceMissing: "La colonne des critères d’acceptation a disparu. Rétablissez-la, puis continuez.",
    blockedNoValidReport: "L’étape {{step}} n’a pas rendu de résultat valide.",
    blockedExtractorOff: "L’étape {{step}} n’a pas rendu de résultat valide, et Claude, qui organise les résultats, est désactivé dans Plugins.",
    blockedExtractorNotInstalled: "L’étape {{step}} n’a pas rendu de résultat valide, et Claude, qui organise les résultats, n’est pas installé sur {{computer}}.",
    blockedExtractorSignedOut: "L’étape {{step}} n’a pas rendu de résultat valide, et Claude, qui organise les résultats, n’est pas connecté sur {{computer}}.",
    blockedExtractorAuthUnknown: "L’étape {{step}} n’a pas rendu de résultat valide, et il est impossible de confirmer que Claude, qui organise les résultats, est connecté sur {{computer}}.",
    blockedExtractorAuthChecking: "L’étape {{step}} n’a pas rendu de résultat valide, et la connexion de Claude, qui organise les résultats, est encore en cours de vérification sur {{computer}}.",
    blockedExtractorAuthError: "L’étape {{step}} n’a pas rendu de résultat valide, et la vérification de la connexion de Claude, qui organise les résultats, a échoué sur {{computer}}.",
    blockedExtractorAuthTimeout: "L’étape {{step}} n’a pas rendu de résultat valide, et Claude, qui organise les résultats, n’a pas répondu à temps à la vérification de connexion sur {{computer}}.",
    blockedExtractorNotMeasured: "L’étape {{step}} n’a pas rendu de résultat valide, et Claude n’a pas encore réussi la vérification pour organiser les résultats sur {{computer}}.",
    blockedExtractorFailed: "L’étape {{step}} n’a pas rendu de résultat valide, et deux essais pour l’organiser depuis le Chat ont échoué.",
    blockedCheckProvider: "Vérifier {{provider}} à nouveau",
    reportDerived: "Organisé à partir de la réponse",
    reportShortened: "Raccourci",
    reportShortenedPlan: "Seule une partie du plan est affichée ici.",
    reportShortenedReview: "Seule une partie de la relecture est affichée ici.",
    openWholePlan: "Ouvrir le plan complet",
    openWholeReview: "Ouvrir la relecture complète",
    reportDerivedHint: "L’Agent n’a pas soumis le résultat de cette étape au format attendu. Bottega l’a repris mot pour mot de la réponse de l’Agent, en ne gardant que les références qui y figurent.",
    blockedDispatchFailed: "L’étape {{step}} n’a pas pu être envoyée à {{provider}}.",
    blockedAttemptsExhausted: "Cette étape a atteint le nombre maximal de tentatives. Annulez cette exécution et recommencez.",
    blockedOther: "L’étape {{step}} n’a pas pu se terminer.",
    blockedBaseAction: "La mise à jour de la Base n’a pas pu se terminer.",
    blockedRecordMissing: "L’enregistrement a été supprimé.",
    blockedBaseActionFailed: "{{action}} n’a pas pu se terminer : {{failure}}.",
    baseActionRead: "La lecture de l’enregistrement",
    baseActionSetStage: "Le passage de l’enregistrement à sa phase",
    baseActionWriteSummary: "L’écriture du résumé",
    baseFailureUnavailable: "la Base n’est pas disponible",
    baseFailureRefused: "l’écriture a été refusée",
    baseFailureConflict: "l’enregistrement a changé en même temps",
    baseFailureUnknown: "la raison est inconnue",
    blockedSignIn: "Se connecter à {{provider}}",
    blockedCheckSignIn: "Vérifier la connexion",
    blockedSetUp: "Configurer {{provider}}",
    blockedChooseConfig: "Choisir une autre configuration",
    retryStep: "Réessayer cette étape",
    retryStillBlocked: "Vérifié à nouveau : toujours bloqué.",
    actionFailed: "L’action n’a pas abouti. Réessayez.",
    remoteSending: "Envoi à {{computer}}…",
    remoteExpired: "{{computer}} n’a pas répondu à temps, rien n’a donc changé. Vous pouvez réessayer.",
    remoteCommandExpired: "Cette action n’a pas atteint {{computer}} à temps, rien n’a donc été fait. Réessayez.",
    remoteUnknown: "On ne sait pas si {{computer}} l’a fait. Vérifiez l’exécution avant de réessayer.",
    remoteClassMismatch: "{{computer}} ne l’a pas exécuté : sa version de Bottega est différente de celle de cet appareil. Mettez Bottega à jour sur les deux, puis réessayez.",
    remoteOffline: "{{computer}} est hors ligne. Vous pourrez agir ici dès son retour.",
    checkResultFailed: "Impossible de vérifier le résultat. Réessayez.",
    retryFailed: "Impossible de réessayer cette étape. Réessayez.",
    retryNotBlocked: "Cette étape n’est plus bloquée.",
  },
  appOps: {
    useChat: "Chat d’utilisation",
    edit: "Modifier",
    editHintWeb: "Modifie cette App dans un Chat sur {{computer}}. Elle est reconstruite à la fin du Chat.",
    editHintPhone: "Modifie cette App dans un Chat sur {{computer}}.",
    sending: "Envoi à {{computer}}…",
    sendingUse: "{{computer}} ouvre le Chat d’utilisation de {{app}} ; il s’affiche ici dès qu’il répond. S’il ne répond pas à temps, rien ne change et vous pouvez réessayer.",
    sendingEdit: "{{computer}} ouvre le Chat de modification de {{app}} ; il s’affiche ici dès qu’il répond. S’il ne répond pas à temps, rien ne change et vous pouvez réessayer.",
    startingEdit: "Ouverture du Chat de modification sur {{computer}}…",
    offlineReason: "{{computer}} est hors ligne. Vous pourrez le faire dès son retour.",
    offlineTitle: "{{computer}} est hors ligne",
    offlineBody: "Le Chat d’utilisation et la modification s’exécutent sur {{computer}}. Vous pourrez les utiliser dès son retour. Ouvrir {{app}} et modifier ses enregistrements fonctionnent toujours ici.",
    offlineChip: "{{computer}} hors ligne",
    useChatOffline: "Chat d’utilisation ({{computer}} est hors ligne)",
    appNotFound: "{{app}} n’est plus sur {{computer}}.",
    appNotEditable: "{{app}} ne peut pas être modifiée sur {{computer}}. Seuls ses enregistrements peuvent changer.",
    appBusy: "Une réponse est encore en cours dans le Chat d’utilisation actuel de {{app}} sur {{computer}}. Ouvrez-le pour attendre ou l’arrêter, puis réessayez.",
    appTransitioning: "{{app}} est en cours de mise à jour sur {{computer}}. Réessayez dans un instant.",
    agentUnavailable: "Aucun Agent n’est disponible sur {{computer}}. Configurez-en un dans Bottega sur {{computer}}.",
    reservationExpired: "{{computer}} n’a pas ouvert le Chat de modification à temps. Votre message est conservé : renvoyez-le.",
    reservationFilled: "{{app}} avait déjà un Chat de modification sur {{computer}}. Votre message est ici en brouillon.",
    firstMessageText: "Le premier message ne contient que du texte. Les pièces jointes fonctionnent à partir du deuxième.",
    unknown: "On ne sait pas si {{computer}} l’a ouvert. Vous pouvez réessayer sans risque : aucun second Chat ne s’ouvrira.",
    startupPending: "Bottega termine encore ses vérifications de démarrage. Réessayez dans un instant.",
    earlierProcess: "Un processus précédent de l’Agent est en train de se terminer. Réessayez dans un instant.",
    /* U06-d: the build status on the App page (building, waiting for the extension decision, failed) and its two commands. */
    buildingStatus: "Création sur {{computer}}…",
    buildingTitleWeb: "Création de la nouvelle version sur {{computer}}…",
    buildingBodyWeb: "La dernière modification est terminée. {{app}} continue d’ouvrir la version actuelle jusqu’à ce que la nouvelle soit prête, puis ouvre la nouvelle et vous le signale.",
    buildingTitlePhone: "Création de la nouvelle version…",
    buildingBodyPhone: "Sur {{computer}}. La version actuelle continue de s’ouvrir jusqu’à ce que la nouvelle soit prête.",
    buildFailedStatus: "Échec de la création",
    buildFailedTitle: "Impossible de créer la nouvelle version",
    buildFailedBodyWeb: "La dernière modification n’a pas pu être créée sur {{computer}}. {{app}} ouvre toujours la version précédente. Pour corriger le code, demandez à l’Agent de maintenance de {{app}} sur votre ordinateur de diagnostiquer et réparer.",
    buildFailedBodyPhone: "La dernière modification n’a pas pu être créée sur {{computer}}. {{app}} ouvre toujours la version précédente.",
    buildFailedInterrupted: "La mise à jour a été interrompue avant la fin. Réessayez.",
    buildRetry: "Réessayer",
    buildRepair: "Réparer sur votre ordinateur",
    confirmStatus: "En attente de votre ordinateur",
    confirmTitle: "En attente de la confirmation de votre ordinateur",
    confirmBody: "Cette modification ajoute une extension à {{app}}. Approuvez-la sur {{computer}} pour créer la nouvelle version. D’ici là, la version actuelle continue de fonctionner.",
    confirmCancel: "Annuler la demande",
    confirmCancelledRemotely: "Annulé depuis un autre appareil.",
    confirmTimedOut: "Personne ne l’a approuvée sur {{computer}} en 30 minutes ; la nouvelle version a donc été créée sans l’extension. Pour l’ajouter, refaites la demande et approuvez-la sur {{computer}}.",
    confirmAlreadyResolved: "Déjà traité sur {{computer}}.",
  },
  phone: {
    needsYou: "Action requise",
    needsYouCount_one: "{{count}} action requise",
    needsYouCount_other: "{{count}} actions requises",
    sheetNote: "Seulement ce qui attend une décision. Toucher un élément l’ouvre ; rien n’est confirmé avant votre choix.",
    empty: "Rien ne vous attend.",
    pushLanding: "Ouvrir ceci ne confirme rien.",
    moreNeedsYou: "{{count}} autres s’afficheront ici à mesure que vous traitez celles-ci.",
    alreadyHandled: "Ceci a déjà été traité.",
    signInOnComputer: "Connectez-vous à {{provider}} sur {{computer}} pour l’utiliser ici.",
    theComputer: "l’ordinateur du Project",
    workflowSuspended: "Ce Workflow ne peut pas lancer d’exécution tant que sa configuration n’est pas réparée sur {{computer}}.",
  },
};
