/**
 * [INPUT]: Depends on ./en for the WorkbenchCopy shape.
 * [OUTPUT]: Provides ja, the Japanese workbench catalog.
 * Names built-in recipes and Workflow plugins and explains missing workflow measurements.
 * [POS]: Lazy workbench-copy locale; the interface says only ワークフロー and 実行.
 */
import { dock } from "./dock/ja";
import type { WorkbenchCopy } from "./en";
import { memoryPluginCopy } from "./memory/ja";

export const ja: WorkbenchCopy = {
  guiHistory: {
    title: "バージョン",
    current: "現在",
    previous: "前のバージョン",
    activate: "このバージョンを使う",
    switching: "切り替え中…",
    pending: "このバージョンを有効にするには、保留中の承認を完了してください。",
    loadFailed: "バージョンを読み込めませんでした。",
    empty: "ビルド済みのバージョンはまだありません。",
    initializing: "プラグインを準備しています…",
    initializationFailed: "プラグインを初期化できませんでした。もう一度お試しください。",
    retryInitialization: "初期化を再試行",
    initializationDetails: "エラーの詳細",
    refresh: "更新",
    edit: "ソースを編集",
    installLocal: "フォルダーからインストール…",
    draftBusy: "プラグインのソース Chat を開く前に、現在の下書きを完了または消去してください。",
    skillMissing: "この Agent では plugin-authoring Skill を利用できません。",
    starterPrompt: "plugin-authoring Skill を使い、これから説明する機能をプラグインに実装してください。",
  },
  terms: {
    pluginsAndApps: "プラグイン",
    bottegaPlugin: "Bottega プラグイン",
    agentNativePlugin: "Agent ネイティブプラグイン",
    baseApp: "Base（組み込み App）",
    baseBackedApp: "Base を使う App",
    agentConfig: "Agent 設定",
    workflow: "ワークフロー",
    run: "実行",
  },
  base: {
    menuGroup: "ワークフロー",
    setUp: "ワークフローを設定…",
    settings: "ワークフローの設定",
    runWorkflow: "ワークフローを実行",
    runOnTask: "このタスクでワークフローを実行",
    ready: "準備完了",
  },
  readOnly: {
    badge: "ワークフロー",
    columnHint: "この列はワークフローだけが変更できます",
    setByWorkflow: "ワークフローが設定します",
    laneLocked: "{{column}} はワークフローが設定するため、このレーンにはカードを移動できません。自分の列を変更するか、実行を開いてこの後の進め方を変更してください。",
    whoCanEdit: "編集権限",
    everyone: "全員",
    onlyWorkflows: "ワークフローのみ",
    whoCanEditUnavailable: "編集を制限できるのは、ワークフローが追加した列だけです。",
  },
  record: {
    section: "ワークフロー",
    run: "実行",
    noRuns: "まだ実行はありません",
    acceptance: "受け入れ判定",
    notDecided: "未判定",
    accepted: "受け入れ済み",
    acceptedWithException: "例外付きで受け入れ済み",
  },
  plugins: {
    title: "プラグイン",
    description: "この Bottega ホストにインストールされているプラグインです。オンまたはオフにし、更新を適用するか、開いて設定と詳細を確認できます。",
    searchLabel: "プラグインを検索",
    statusLabel: "状態",
    statusAll: "すべての状態",
    statusOn: "オン",
    statusOff: "オフ",
    statusAttention: "対応が必要",
    sortLabel: "並べ替え",
    sortGroup: "カテゴリ順",
    sortName: "名前順",
    sortRecent: "最近の変更順",
    newPlugin: "新しいプラグイン",
    groupFeature: "Bottega の機能",
    groupProvider: "Provider",
    groupPackage: "拡張機能",
    groupNative: "Agent ネイティブのプラグイン",
    emptyTitle: "一致するプラグインはありません",
    clearFilters: "検索と絞り込みをクリア",
    emptyAll: "プラグインはまだインストールされていません。",
    official: "公式",
    badgeBuiltin: "内蔵",
    badgePackage: "拡張機能 · v{{version}}",
    badgeNative: "Agent ネイティブ",
    alwaysOn: "常にオン",
    nativeManagedBy: "{{agent}} が管理",
    projectScopedBadge: "1 つの Project のみ",
    projectScopedNote: "1 つの Project 用にインストールされているため、ここではまだオフにできません。",
    setupDock: "設定…",
    blocked: "依存関係が不足",
    unsupported: "このコンピューターでは非対応",
    providerUsedBy_one: "{{count}} 個の Agent 設定で使用中",
    providerUsedBy_other: "{{count}} 個の Agent 設定で使用中",
    providerUnused: "まだ使われていません",
    workflowSetUpIn_one: "{{count}} 個の Project で使用中",
    workflowSetUpIn_other: "{{count}} 個の Project で使用中",
    workflowSetUpInNames: "{{projects}} で使用中",
    turnedOffOn: "{{date}}にオフ",
    neverOn: "一度もオンにしていません",
    turnOffTitle: "{{name}} をオフにしますか？",
    turnOffBody: "{{name}} は{{computer}}で起動しなくなります。何も削除されず、いつでもオンに戻せます。",
    whatChanges: "変わること",
    impactConfigs: "Agent 設定 {{config}} は選べなくなります",
    impactWorkflows: "{{name}} がオフの間、{{workflow}} は新しい実行を始められません",
    impactRuns_one: "{{name}} を使う {{count}} 件の実行は、今のステップを終えてから一時停止します",
    impactRuns_other: "{{name}} を使う {{count}} 件の実行は、今のステップを終えてから一時停止します",
    impactChats_one: "{{name}} との {{count}} 件の Chat は読めますが、続けられません",
    impactChats_other: "{{name}} との {{count}} 件の Chat は読めますが、続けられません",
    impactMore_one: "ほか {{count}} 件",
    impactMore_other: "ほか {{count}} 件",
    dependentsTitle: "次のプラグインが使えなくなります",
    dependentLine: "{{plugin}}：必要な機能を {{name}} だけが提供しています",
    turnOff: "オフにする",
    turnOn: "オンにする",
    thisComputer: "このコンピューター",
    switchFailed: "{{name}} を変更できませんでした。もう一度お試しください。",
    switchLabel: "{{name}} のオンとオフを切り替え",
    reinstallRequired: "{{name}} のインストールファイルがオフの間に変わったため、まだオンに戻せません。",
    reinstallHelp: "お知らせいただければ、復元をお手伝いします。",
    reinstallIssueTitle: "{{name}} をオンに戻せません",
    reinstallBadge: "オンに戻せません",
    reportProblem: "問題を報告",
    busyNote: "{{name}} は処理中です。終わると操作できます。",
    turningOn: "オンにしています…",
    turningOff: "オフにしています…",
    chatTurnedOff: "{{provider}} はプラグインでオフになっています。オンに戻すとこの Chat を続けられます。",
    openPlugin: "{{name}} プラグインを開く",
    back: "すべてのプラグイン",
    on: "オン",
    off: "オフ",
    sectionSettings: "設定",
    settingsNote: "プラグインが宣言した設定",
    settingsProviderNote: "既存のセッションには影響しません",
    appliesImmediate: "すぐに反映",
    appliesNextTurn: "次のターンから",
    appliesSessionCreate: "新しいセッションから",
    appliesProcessStart: "再起動後に反映",
    changed: "変更済み",
    resetDefault: "既定に戻す",
    confirmContinue: "続ける",
    secretSet: "設定済み",
    secretUnset: "未設定",
    secretReplace: "置き換え",
    secretClear: "消去",
    secretSave: "保存",
    secretCancel: "キャンセル",
    decrease: "減らす",
    increase: "増やす",
    settingsFailed: "「{{setting}}」を保存できませんでした。もう一度お試しください。",
    pendingRestart: "{{name}} は空いたときに再起動し、変更を反映します。",
    sectionHealth: "状態",
    checkedAt: "{{time}}に確認",
    update: "更新",
    setUp: "設定",
    sectionUsedBy: "使用元",
    usedByConfigs: "Agent 設定",
    usedByProjects: "ワークフローを使う Project",
    usedByNobody: "まだ使われていません。",
    sectionDependencies: "依存関係",
    depRequires: "必要",
    depProvides: "提供",
    depDependents: "依存元",
    depNone: "なし",
    depSatisfiedBy: "{{plugins}} が満たしています",
    depHostNote: "設定、ストレージ、イベント、バックグラウンド処理は Bottega が提供し、常に使えます。",
    blockedMissing: "提供するものがありません",
    blockedDisabled: "提供するものがすべてオフです",
    blockedUnsupported: "提供するものがこのコンピューターで動きません",
    blockedCycle: "依存関係が循環しています",
    blockedBanner: "{{name}} は今、新しい作業を始められません。{{reason}}。",
    sectionCapabilities: "機能と権限",
    capabilitiesNone: "宣言はありません。",
    sectionIncludes: "含まれるもの",
    sectionCanDo: "できること",
    sectionWorksWith: "依存関係",
    sectionInUse: "使用状況",
    sectionInformation: "情報",
    worksAlone: "単独で動作し、依存しているプラグインもありません。",
    aboutPlugin: "{{name}} について",
    publisherBottega: "Bottega",
    about: "情報",
    aboutSource: "提供元",
    aboutVersion: "バージョン",
    aboutKind: "種類",
    aboutId: "プラグイン ID",
    aboutManagedBy: "管理する Agent",
    aboutLocation: "場所",
    aboutPublisher: "公開元",
    unsigned: "署名なし",
    versionWithApp: "Bottega {{version}} に同梱",
    kindFeature: "機能",
    kindProvider: "Provider",
    sourceLocalLong: "ローカルソース",
    sourceBuiltinLong: "Bottega に内蔵",
    sourcePackageLong: "拡張機能",
    sourceNativeLong: "Agent ネイティブ",
    related: "関連ページ",
    relatedProviders: "Providers",
    relatedAgentConfigs: "Agent 設定",
    relatedUsage: "使用量",
    relatedSkills: "Skills",
    relatedMemory: "メモリ",
    relatedDock: "Dock",
    nativeReadOnly: "{{agent}} が管理しています。Bottega は表示のみです。インストール、更新、削除は {{agent}} で行ってください。",
    notFound: "このプラグインはもうありません。",
    loadFailed: "このプラグインを読み込めませんでした。もう一度お試しください。",
    retry: "再試行",
    sidebarGroup: "プラグイン",
    sidebarAll: "すべてのプラグイン",
    health: {
      unknown: "まだ確認していません",
      notChecked: "まだ確認していません",
      ready: "正常",
      off: "オフ",
      running: "実行中",
      idle: "正常（未実行）",
      process: "プロセス",
      processRunning: "実行中",
      processIdle: "必要なときに起動",
      nativeEnabled: "{{agent}} の報告：オン",
      nativeDisabled: "{{agent}} の報告：オフ",
      cliVersion: "CLI",
      signIn: "サインイン",
      runningRuns: "進行中の実行",
      cli: {
        unknown: "未確認",
        missing: "未インストール",
        error: "確認できません",
        unsupported: "更新が必要",
        installed: "インストール済み",
      },
      auth: {
        unknown: "不明",
        checking: "確認中…",
        authenticated: "サインイン済み",
        unauthenticated: "未サインイン",
        error: "確認できません",
      },
    },
    unsupportedReason: {
      appleSilicon: "Apple シリコン搭載の macOS のみ",
    },
    capability: {
      startProcess: "このコンピューターで CLI を起動します",
      projectFiles: "Agent 設定の権限に従って Project フォルダを読み書きします",
      network: "自分のサービスに接続します",
      baseStore: "各 Project のフォルダに表を保存します",
      baseTools: "Agent にレコードの読み書き・検索ができる Base ツールを渡します",
      workflowColumns: "Base にステージと受け入れ基準の列を追加します（ステージはワークフローだけが書き込みます）",
      workflowRoles: "各ロールをその Agent 設定で実行します",
    },
    builtin: {
      memory: memoryPluginCopy,
      dock,
      sketch: { name: "スケッチ", summary: "描画、消去、再編集できる画像の添付。", description: "スケッチは入力欄に描画キャンバスを追加します。描く、消す、書き込むことができ、結果を再編集できる画像としてメッセージに添付します。" },
      base: {
        name: "Base",
        summary: "すべての Project にある表、ボード、リスト、フォーム。ワークフローと Base 型 App の土台です。",
        description: "Base はすべての Project に専用の表を用意します。レコードは表、ボード、リスト、フォームで表示でき、Project のフォルダにファイルと一緒に保存されます。\n\nAgent は Base ツールでレコードを読み書き、検索できます。ワークフローと Base 型 App の土台なので、常にオンです。",
      },
      workflow: {
        name: "ワークフロー",
        summary: "Agent のロールが Base 上で作業を一歩ずつ進め、各ステップで確認できます。",
        description: "ワークフローは Base をパイプラインに変えます。各ステップは Agent 設定が担うロールで、ステップごとに確認してから次へ進みます。\n\nProject で設定し、最初の列にカードを追加すると始まります。実行を開くと各ロールの作業を確認し、次の進め方を変えられます。",
      },
      claude: {
        name: "Claude",
        summary: "Anthropic の Claude Code を Bottega の Agent として実行します。",
        description: "Anthropic の Claude Code を Bottega の Agent として実行します。各 Agent 設定が許す範囲で Project のフォルダを扱います。\n\nこのコンピューターに Claude Code CLI と Anthropic アカウントへのサインインが必要です。100 万トークンのコンテキストや Claude in Chrome などは設定で有効にできます。",
        publisher: "Anthropic",
        settings: {
          memory: {
            label: "メモリ",
            description: "Bottega の Chat で Claude Code が自身の自動メモリを読み書きできるようにします。ワークフローのロールは使いません。",
          },
          nativeSubagents: {
            label: "ネイティブのサブエージェントを許可",
            description: "Claude Code が Task ツールで自身のサブエージェントを起動できるようにします。",
          },
          workflowTool: {
            label: "Workflow ツールを許可",
            description: "Claude Code が自身の Workflow ツールを使えるようにします。",
          },
          context1m: {
            label: "1M コンテキストを使う",
            description: "Claude Code が 100 万トークンのコンテキストウィンドウを使えるようにします。",
          },
          claudeInChrome: {
            label: "Claude in Chrome",
            description: "Claude in Chrome のブラウザツール付きで Claude Code を起動します。このコンピューターに Chrome 拡張機能があり、claude.ai にサインインしている必要があります。",
          },
        },
      },
      codex: {
        name: "Codex",
        summary: "OpenAI の Codex CLI を Bottega の Agent として実行します。",
        description: "OpenAI の Codex CLI を Bottega の Agent として実行します。各 Agent 設定の範囲内で Project のフォルダを読み書きします。\n\nこのコンピューターに Codex CLI と OpenAI アカウントへのサインインが必要です。Codex 独自のメモリとマルチエージェント機能は設定でオフにできます。",
        publisher: "OpenAI",
        settings: {
          memory: {
            label: "メモリ",
            description: "Bottega の Chat で Codex が自身のメモリを使えるようにします。ワークフローのロールは使いません。",
          },
          nativeSubagents: {
            label: "ネイティブのサブエージェントを許可",
            description: "Codex が自身のマルチエージェント機能を使えるようにします。",
          },
        },
      },
      kimi: {
        name: "Kimi",
        summary: "Moonshot の Kimi CLI を Bottega の Agent として実行します。",
        description: "Moonshot の Kimi CLI を Bottega の Agent として実行します。このコンピューターに Kimi CLI と Moonshot アカウントへのサインインが必要です。",
        publisher: "Moonshot AI",
      },
      opencode: {
        name: "OpenCode",
        summary: "多くのサービスのモデルを使えるオープンソースの OpenCode です。",
        description: "オープンソースの OpenCode CLI を Bottega の Agent として実行します。さまざまなサービスのモデルを使えます。",
        publisher: "OpenCode",
      },
    },
  },
  agentConfigs: {
    loading: "Agent 設定を読み込み中…",
    loadFailed: "Agent 設定を読み込めませんでした。再試行してください。",
    refreshFailed: "Agent 設定を更新できませんでした。前回読み込んだ一覧を表示しています。",
    unavailable: "このウィンドウでは Agent 設定を利用できません。再試行するか、設定を開き直してください。",
    reasoningEffort: "推論の強度",
    agentDefault: "Agent のデフォルト",
    modelsFailed: "モデルを読み込めませんでした。選択内容は保持されています。",
    defaultsFailed: "保存済みのデフォルト値を読み込めませんでした。モデルを選択するか再試行してください。",
    optionUnavailable: "保存済みの選択肢はここでは利用できません。別の選択肢を選ぶまで元の値を保持します。",
    chooseModelForEffort: "利用可能なモデルを選択すると、推論の選択肢が表示されます。",
    baseResource: "Base",
    chatResource: "Chat",
    mcpResource: "MCP",
    selectedCount: "{{count}} / {{limit}} 件を選択",
    resourcesLoading: "ローカルリソースを読み込み中…",
    resourcesFailed: "一部のリソースを読み込めませんでした。選択は保持されます。",
    resourcesEmpty: "利用できるローカルリソースがありません。",
    resourceUnavailable: "この端末では利用不可",
    baseRead: "読み取り専用",
    baseReadWrite: "読み書き",
    linkedChats: "関連する Chat のみ",
    resourcesHint: "新しい実行では選択したリソースのみを使用します。別のコンピューターにリソースがない場合は修正まで実行を停止します。",
    resourcesReadOnly: "計画・レビュー・読み取り専用の設定では Base の読み取りのみ可能で、MCP サーバーは利用できません。",
    baseCapped: "要求：読み書き。適用：読み取り専用。保存された要求は保持されます。",
    removeReadOnlyMcp: "読み取り専用の設定を保存するには、選択した MCP サーバーを解除してください。",
    retryResources: "リソースを再読み込み",
    title: "Agent 設定",
    description: "再利用できるプロバイダー、モデル、指示、ツール。",
    allProjects: "すべての Project",
    someProjects: "一部の Project",
    someProjectsDescription: "各設定の下に記載された Project にだけ表示されます。",
    newConfig: "新しい設定",
    edit: "編集",
    readOnly: "読み取り専用",
    newTitle: "新しい Agent 設定",
    editTitle: "Agent 設定を編集",
    prefilled: "{{role}} 用に役割、権限、ツールを入力済みです。すべて変更できます。",
    startFrom: "初期内容",
    blank: "白紙",
    planner: "計画",
    developer: "開発",
    reviewer: "レビュー",
    name: "名前",
    availableIn: "利用範囲",
    searchProjects: "Project を検索",
    provider: "プロバイダー",
    chooseProvider: "プロバイダーを選択",
    model: "モデル",
    providerDefault: "プロバイダーのデフォルト",
    instructions: "指示",
    instructionsHint: "Agent に送信されます",
    purpose: "用途",
    purposeHint: "設定を選ぶ人に表示されます",
    permissions: "権限",
    skills: "Skills",
    toolsAndData: "ツールとデータ",
    toolsBaseReadWriteLinked: "Base の読み書き · 関連する Chat のみ",
    toolsBaseReadLinked: "Base の読み取り · 関連する Chat のみ",
    none: "なし",
    create: "作成",
    missingRequired: "名前を入力し、プロバイダーを選んでください",
    appliesToNewRuns: "変更は保存後に開始する実行にだけ適用されます。",
    appliesNextTurn: "次のターンから適用",
    restartsAgent: "Agent を再起動します",
    appliesOnNew: "新しいチャットから適用",
    notForRole: "この役割には使えません",
    notAdmitted: "まだ {{role}} 担当として使えません",
    partialFailure: "一部の設定を適用できなかったため、この設定はまだ役割を担えません。",
    presetPlanner: "タスクと受け入れ基準を読み、手順ごとの計画を書いてください。コードは変更しないでください。",
    presetDeveloper: "受け入れた計画に従い、変更はタスクの範囲内にとどめてください。報告の前に Project のチェックを実行してください。",
    presetReviewer: "計画と受け入れ基準に照らして結果を確認し、足りない点を報告してください。コードは変更しないでください。",
    emptyTitle: "Agent 設定はまだありません",
    emptyBody: "作成すると、ワークフローのステップで選べるようになります。",
    syncing: "同期中",
    conflicted: "確認が必要",
    notSynced: "未同期",
    syncIssueBudget: "このアカウントの Agent 設定は上限（100 件）に達しているため、これはまだ同期されていません。使わなくなった設定を 1 件削除すると、自動で同期されます。",
    saveFailed: "この設定を保存できませんでした。変更内容はそのまま残っています。",
    allProjectsHint: "すべての Project で選べます",
    noProjects: "Project はまだありません",
    needsAttention: "対応が必要",
    guaranteeReadOnly: "読み取り専用のワークスペース",
    guaranteeNoNetwork: "ネットワークなし",
    reasonProviderCannot: "{{provider}} ではこれを保証できません",
    reasonHostCannot: "このコンピューターでは強制できません",
    reasonHostUnavailable: "確認できません：実行するコンピューターを利用できません",
    reasonNotMeasured: "まだ検証されていません",
    applyPartial: "{{settings}}はこのコンピューターで有効になっていないため、ワークフローではまだこの設定を使えません。",
    applyPartialGeneric: "一部の設定がこのコンピューターで有効になっていないため、ワークフローではまだこの設定を使えません。",
    workspace: "ワークスペース",
    workspaceWrite: "ファイルを変更できる",
    workspaceReadOnly: "読み取り専用",
    network: "ネットワーク",
    networkOn: "オン",
    networkOff: "オフ",
    notReadOnly: "ワークスペースが読み取り専用に設定されていません",
    providerTurnedOff: "{{provider}} はオフです",
  },
  setup: {
    enableTitle: "ワークフローを有効にする",
    enableDescription: "このコンピューターで計画・開発・レビューを実行します。",
    enableAndRun: "有効にしてこの行を実行",
    noReadyProvider: "このワークフローを実行できるプロバイダーがありません。",
    openSettings: "設定を開く",
    openBase: "Base を開いて列を整理",
    openProject: "プロジェクト設定を開く",
    projectUnavailable: "先にプロジェクト設定で作業フォルダを選択してください。",
    enableFailed: "ワークフローを有効にできませんでした。条件を再確認してください。",
    checkAgain: "再確認",
    refusalSkillUnavailable: "{{config}} で選択した Skill がこのコンピューターにないか、無効です。",
    refusalMcpUnavailable: "{{config}} で選択した MCP サーバーはこのコンピューターで利用できません。",
    refusalMcpReadOnly: "{{config}} は MCP サーバーを選択しています。計画とレビューでは使えないため、選択を解除するか別の設定を選んでください。",
    planDevelopReview: "計画 · 開発 · レビュー",
    newTitle: "ワークフローを設定",
    editTitle: "ワークフローの設定",
    stepOf: "ステップ {{current}} / {{total}}",
    tabWorkflow: "ワークフロー",
    tabWho: "担当",
    tabBase: "Base",
    tabCheck: "最終確認",
    chooseTitle: "ワークフローを選択",
    whoTitle: "各ステップの担当",
    whoHint: "名前をクリックすると変更できます。",
    whoGreyedHint: "各リストにはそのステップを担当できるものだけが表示され、それ以外は理由付きでグレー表示されます。",
    you: "あなた",
    addStep: "ステップを追加",
    stepPlan: "計画",
    stepPlanDescription: "タスクの計画を書きます",
    stepConfirm: "確認",
    stepConfirmDescription: "あなたが計画を読んで受け入れます",
    stepDevelop: "開発",
    stepDevelopDescription: "コードを変更します",
    stepReview: "レビュー",
    stepReviewDescription: "変更せずに結果を確認します",
    stageDone: "完了",
    stepDecide: "判断",
    stepDecideDescription: "受け入れ、終了、やり直しを選びます",
    youConfirm: "あなたが確認",
    youDecide: "あなたが判断",
    baseTitle: "Base で変わること",
    baseIntro_one: "ワークフローは列を 1 つ追加します。既存の内容は変更されません。",
    baseIntro_other: "ワークフローは列を {{count}} つ追加します。既存の内容は変更されません。",
    baseIntroEditing: "この Base にはワークフローの列がすでにあります。ここで変わるものはありません。",
    baseNow: "現在",
    baseAfter: "オンにした後",
    baseNewColumns_one: "Base に 1 つの列が加わります",
    baseNewColumns_other: "Base に {{count}} つの列が加わります",
    stageColumn: "ステージ",
    stageDescription: "各タスクの進み具合を示します。ワークフローが更新するため、手動では編集できません。",
    acceptanceColumn: "受け入れ基準",
    boardView: "カンバン · ステージ別",
    acceptanceDescription: "各タスクで何をもって「完了」とするかを、あなたが書きます。",
    baseOthersUnchanged: "ほかの列はそのままです。",
    baseFixedColumns: "この 2 つの列はワークフローが決めるため、ここでは変更できません。",
    baseFull_one: "この Base には上限 {{limit}} 列のうち {{existing}} 列がすでにあります。ワークフローをオンにするには、Base で 1 列を削除してください。",
    baseFull_other: "この Base には上限 {{limit}} 列のうち {{existing}} 列がすでにあります。ワークフローをオンにするには、Base で {{count}} 列を削除してください。",
    baseBoardAdded: "ビュー「{{view}}」を追加して開きます。ほかのビューはそのままです。",
    baseBoardNoRoom: "この Base にはすでに {{limit}} 個のビューがあるため、「{{view}}」ビューは追加されません。ワークフローはそのままオンになります。",
    baseChanged: "このウィンドウを開いている間に Base の列が変わりました。現在の状態を表示しています。",
    checkTitle: "確認してオンにする",
    checkedOn: "{{computer}}で確認しました。",
    providerReady: "{{provider}} は{{computer}}で準備完了です",
    checking: "このコンピューターで確認しています…",
    roleReady: "{{step}}：{{provider}} は{{computer}}で準備ができています",
    roleProblem: "{{step}}：{{reason}}",
    refusalDeleted: "この設定は削除されました。",
    refusalNotEnabled: "{{config}} は別のデバイスで作成され、{{computer}}ではまだ保存されていません。Agent 設定で開いて、一度保存してください。",
    refusalMismatch: "{{config}} は別の Provider に切り替わったため、確認が必要です。Agent 設定で開いて、一度保存してください。",
    refusalSelection: "{{config}} は独自の Memory を設定していますが、ワークフローのステップではまだ使えません。別の設定を選んでください。",
    refusalMemoryWrite: "{{config}} は Memory への書き込みを要求しています。ワークフローのステップでは読み取りのみ可能です。",
    refusalScope: "ワークフローのステップは {{config}} の Skills または Tools の設定に対応していません。設定を開いて保存し直してください。",
    refusalPartial: "{{config}} の{{settings}}は {{computer}} で有効になりませんでした。設定を開いて修正してください。",
    refusalPartialGeneric: "{{config}} の一部の設定は {{computer}} で有効になりませんでした。設定を開いて確認してください。",
    refusalReadOnly: "読み取り専用のワークスペースを求めているため、コードを変更できません。",
    refusalNoNetwork: "ネットワークなしを求めていますが、{{computer}}ではまだ保証できません。",
    baseHasRoom_one: "Base にはあと 1 列追加できます",
    baseHasRoom_other: "Base にはあと {{count}} 列追加できます",
    baseGets: "Base に追加",
    needsComputer: "{{computer}}がオンラインである必要があります",
    turnOn: "オンにする",
    continue: "続ける",
    back: "戻る",
  },
  projectWorkflows: {
    tab: "ワークフロー",
    description: "この Project の Base のタスクから実行できるワークフロー。",
    addWorkflow: "ワークフローを追加",
    on: "オン",
    off: "オフ",
    runsOn: "{{computer}}で実行",
    configsTitle: "この Project の Agent 設定",
    configsHint: "個人用の設定は「設定 › Agent 設定」にあります。",
    availableIn: "{{projects}} で使えます",
    needsBase: "この Project に Base ができてからワークフローを追加できます。ワークフローは Base のタスクで動きます。",
    workflowChats_one: "ワークフロー Chat {{count}} 件",
    workflowChats_other: "ワークフロー Chat {{count}} 件",
    workflowRuns_one: "{{count}} 回の実行",
    workflowRuns_other: "{{count}} 回の実行",
    alsoArchived: "{{runs}}から生まれた{{chats}}も一緒にアーカイブされます。",
    alsoArchivedNoRuns: "{{chats}}も一緒にアーカイブされます。",
    alsoDeleted: "この Project の{{chats}}も一緒に削除されます。",
    archiveStepRunning: "ワークフローのステップを実行中のため、まだアーカイブできません。ステップが終わると実行は一時停止するので、そのあとでもう一度お試しください。",
    runsStillStopping: "この Project のワークフロー実行がまだ停止中で、プロセスが動いている可能性があります。実行から強制停止してから、もう一度お試しください。",
    runtimeNotReady: "このコンピューターでワークフローがまだ起動中です。少し待ってからもう一度お試しください。",
  },
  run: {
    blockedVersionTooOld: "{{computer}}の {{provider}} を更新してからワークフローを実行してください。",
    blockedExtractorVersionTooOld: "{{step}}は有効な結果を返しませんでした。結果を整理するには{{computer}}の Claude を更新してください。",
    label: "実行 #{{number}}",
    onComputer: "{{computer}}で",
    queued: "待機中",
    running: "実行中",
    needsYou: "対応が必要",
    paused: "一時停止中",
    blocked: "ブロック中",
    cancelling: "キャンセル中…",
    succeeded: "完了",
    failed: "失敗",
    cancelled: "キャンセル済み",
    stopped: "停止済み",
    stoppedForced: "停止済み（強制）",
    pausedWaited: "一時停止中 · 24 時間待機",
    pausedArchived: "一時停止中 · Project はアーカイブ済み",
    cancellingTitle: "キャンセル中",
    cancellingBody: "新しいステップは開始されません。Bottega は{{computer}}の {{provider}} を停止しています。数秒かかることがあります。ここに停止と表示されるまでは停止していません。",
    stuckTitle: "30 秒経っても停止していません",
    stuckBody: "{{computer}}の {{provider}} が終了していません。強制停止できます。すでに変更されたコードはワークスペースに残るため、次の実行の前に確認してください。",
    forceStop: "強制停止",
    forceStopUnconfirmedTitle: "まだプロセスが動いている可能性があります",
    forceStopUnconfirmedBody: "Bottega は{{computer}}でこのステップを止めましたが、すべてのプロセスが終わったことを確認できませんでした。もう一度強制停止し、次の実行の前にワークスペースを確認してください。",
    waitingFor: "{{computer}}を待っています",
    reminder: "計画が 23 時間待っています。1 時間以内に判断しないと、実行は一時停止します。",
    waitingStarted: "確認待ちの計画があります。",
    reminderResult: "結果が 23 時間待っています。1 時間以内に判断しないと、実行は一時停止します。",
    waitingStartedResult: "判断待ちの結果があります。",
    pauseConfirmationTimeout: "確認が 24 時間を超えて待たれたため、一時停止しました。続けると、もう一度確認をお願いします。",
    pausedNotice: "24 時間待ったため一時停止しました。何も実行されていません。開いて続けてください。",
    resume: "再開",
    resultUnknown: "結果不明",
    resultUnknownBody: "{{computer}}は {{time}} に受け付けましたが、結果が届いていません。自動では再送されません。",
    checkResult: "結果を確認",
    acceptPlan: "計画を受け入れる",
    accept: "受け入れる",
    acceptWithException: "例外付きで受け入れる",
    exceptionReason: "それでも受け入れる理由は？",
    exceptionReasonRequired: "例外付きで受け入れるには理由を書いてください。",
    end: "終了",
    rework: "やり直し",
    reworkFromDevelop: "受け入れた計画のまま、開発からやり直す",
    replan: "計画し直す",
    reconfirm: "受け入れ基準が変わりました。実行を続ける前に計画をもう一度確認してください。",
    alreadyHandled: "{{device}} で対応済み",
    viewResult: "結果を表示",
    viewLog: "ログを表示",
    tryAgain: "再試行",
    details: "実行の詳細",
    startRun: "実行を開始",
    pause: "一時停止",
    cancelRun: "実行をキャンセル",
    cancelConfirmTitle: "この実行をキャンセルしますか？",
    cancelConfirmBody: "進行中のステップが先に止まります。すでに変更されたコードはワークスペースに残ります。この実行はもう続きませんが、あとでもう一度始められます。",
    keepRunning: "実行を続ける",
    forceConfirmTitle: "強制停止しますか？",
    forceConfirmBody: "{{computer}}でこのステップのプロセスをすべてすぐに終了します。すでに行われた変更は元に戻りません。次の実行の前にワークスペースを確認してください。",
    keepWaiting: "待ち続ける",
    openChat: "チャットを開く",
    artifact: "結果",
    evidence: "根拠",
    stepPending: "未開始",
    stepRunning: "実行中",
    stepWaiting: "対応が必要",
    stepSucceeded: "完了",
    stepFailed: "失敗",
    stepBlocked: "ブロック中",
    stepCarried: "受け入れた計画を引き継ぎ",
    stepNotRun: "未実行",
    pauseUser: "この実行を一時停止しました。",
    pauseProjectArchived: "Project がアーカイブされたため一時停止しました。Project を復元してから続行してください。",
    pauseProjectRestored: "Project がアーカイブされたときに、この実行は一時停止しました。準備ができたら続けてください。",
    pausingAfterStep: "現在のステップが終わると、この実行は一時停止します。",
    pausingArchived: "Project がアーカイブされました。現在のステップが終わると、この実行は一時停止します。",
    projectArchived: "この Project はアーカイブ済みのため、実行を開始・続行できません。Project を復元してから、実行を手動で続行してください。",
    pauseBindingSuspended: "一時停止中：ワークフローの設定が変わりました。直してから続けるかキャンセルしてください。",
    pausePluginDisabled: "一時停止中：{{provider}} がプラグインでオフになっています。オンに戻してから続けるかキャンセルしてください。",
    waitingWorkspace: "ワークスペース待ち",
    waitingWorkspaceBody: "「{{task}}」がこのワークスペースへの書き込みを終えるのを待っています。1 つのワークスペースで開発できるのは一度に 1 件だけで、空いたら自動で始まります。",
    waitingWorkspaceStuck: "「{{task}}」の実行ではまだプロセスが動いている可能性があります。そちらで対処すると、ここが始まります。",
    viewHoldingRun: "その実行を見る",
    pausePluginWorkflow: "一時停止中：ワークフローはプラグインでオフになっています。オンにすると続けられます。今すぐキャンセルすることもできます。",
    pausePluginWorkflowOn: "一時停止中：{{computer}}のワークフローはプラグインでオフになっています。そのコンピューターで再びオンにすると続けられます。今すぐキャンセルすることもできます。",
    workflowOffAction: "ワークフローはプラグインでオフになっています。オンにすると続けられます。",
    workflowBlockedAction: "ワークフローを進められません：プラグインでオンの Provider がありません。どれかをオンにしてください。",
    staleProposal: "待っている間にタスクまたは受け入れ基準が変わったため、今のレコードの内容で改めて確認をお願いしています。",
    stoppedForcedHint: "強制停止しました。次の実行の前にワークスペースを確認してください。",
    stoppedForcedAtStartupHint: "強制停止しました（再起動後に確認）。次の実行の前にワークスペースを確認してください。",
    stoppingFor: "停止処理 {{seconds}} 秒",
    confirmPlanTitle: "計画を確認",
    confirmResultTitle: "結果を判断",
    reworkTitle: "やり直し",
    reworkStart: "やり直しを開始",
    reworkReasonAcceptance: "受け入れ基準が変わりました",
    reworkReasonTask: "タスクが変わりました",
    reworkKeepPlanReconfirm: "計画を引き継いで確認し直す",
    reworkKeepPlan: "計画を引き継ぐ",
    reworkKeepPlanMaybeReconfirm: "タスクや受け入れ基準が変わっていたら、先に計画を確認し直してもらいます。",
    noResultYet: "まだ結果はありません",
    startWorkflowOff: "ワークフローはプラグインでオフになっています。オンにすると実行を開始できます。",
    startWorkflowBlocked: "ワークフローを開始できません：プラグインでオンの Provider がありません。先にどれかをオンにしてください。",
    startFailed: "実行を開始できませんでした。もう一度お試しください。",
    agentWaiting: "{{step}} が Chat であなたの返事を待っています",
    agentWaitingBody: "権限の確認か質問が届いています。そこで答えるまで、この実行は進みません。",
    blockedSignedOut: "{{provider}} は{{computer}}でサインインしていません。",
    blockedAuthUnknown: "{{provider}} が{{computer}}でサインインしているか確認できませんでした。",
    blockedAuthChecking: "{{provider}} が{{computer}}でサインインしているか、まだ確認中です。",
    blockedAuthError: "{{computer}}での {{provider}} のサインイン確認でエラーが発生しました。",
    blockedAuthTimeout: "{{computer}}の {{provider}} がサインイン確認に時間内に応答しませんでした。",
    blockedNotInstalled: "{{computer}}に {{provider}} がインストールされていません。",
    blockedMeasurementsUnavailable: "{{provider}} にはワークフローに必要な実測結果がまだありません。",
    blockedPluginDisabled: "{{provider}} はプラグインでオフになっています。",
    blockedNotMeasured: "{{provider}} は{{computer}}でまだ確認されていないため、{{step}}を担当できません。",
    blockedProviderCannot: "{{provider}} は{{step}}を担当できません。このステップに必要な保証を満たせません。",
    blockedConfigUnavailable: "{{step}}に選んだ設定は使えなくなりました。",
    blockedGuaranteeReadOnly: "{{step}}に選んだ設定は読み取り専用のワークスペースを求めているため、コードを変更できません。",
    blockedGuaranteeNetwork: "{{step}}に選んだ設定はネットワークなしを求めていますが、{{computer}}ではまだそれを保証できません。",
    blockedInstanceChanged: "ワークフローの Base が置き換えられました。ワークフローを設定し直してください。",
    blockedTaskMissing: "Base のタスク列がなくなりました。戻してから続けてください。",
    blockedStageMissing: "ステージ列がなくなりました。戻してから続けてください。",
    blockedAcceptanceMissing: "受け入れ基準の列がなくなりました。戻してから続けてください。",
    blockedNoValidReport: "{{step}}は有効な結果を返しませんでした。",
    blockedExtractorOff: "{{step}}は有効な結果を返しませんでした。結果を整理する Claude がプラグインでオフになっています。",
    blockedExtractorNotInstalled: "{{step}}は有効な結果を返しませんでした。結果を整理する Claude が{{computer}}にインストールされていません。",
    blockedExtractorSignedOut: "{{step}}は有効な結果を返しませんでした。結果を整理する Claude が{{computer}}でサインインしていません。",
    blockedExtractorAuthUnknown: "{{step}}は有効な結果を返しませんでした。結果を整理する Claude が{{computer}}でサインインしているか確認できませんでした。",
    blockedExtractorAuthChecking: "{{step}}は有効な結果を返しませんでした。結果を整理する Claude が{{computer}}でサインインしているか、まだ確認中です。",
    blockedExtractorAuthError: "{{step}}は有効な結果を返しませんでした。{{computer}}での、結果を整理する Claude のサインイン確認でエラーが発生しました。",
    blockedExtractorAuthTimeout: "{{step}}は有効な結果を返しませんでした。{{computer}}の、結果を整理する Claude がサインイン確認に時間内に応答しませんでした。",
    blockedExtractorNotMeasured: "{{step}}は有効な結果を返しませんでした。Claude は{{computer}}で結果を整理するための確認にまだ合格していません。",
    blockedExtractorFailed: "{{step}}は有効な結果を返しませんでした。Chat から 2 回整理を試みましたが、うまくいきませんでした。",
    blockedCheckProvider: "{{provider}} をもう一度確認",
    reportDerived: "回答から整理",
    reportShortened: "一部のみ",
    reportShortenedPlan: "ここには計画の一部だけが表示されています。",
    reportShortenedReview: "ここにはレビューの一部だけが表示されています。",
    openWholePlan: "計画の全文を開く",
    openWholeReview: "レビューの全文を開く",
    reportDerivedHint: "Agent はこのステップの結果を決められた形式で提出しませんでした。Bottega が Agent の回答からそのまま整理し、参照は回答に出てきたものだけを残しています。",
    blockedDispatchFailed: "{{step}}を {{provider}} に送れませんでした。",
    blockedAttemptsExhausted: "このステップは再試行の上限に達しました。この実行をキャンセルして、もう一度始めてください。",
    blockedOther: "{{step}}を完了できませんでした。",
    blockedBaseAction: "Base の更新を完了できませんでした。",
    blockedRecordMissing: "レコードが削除されました。",
    blockedBaseActionFailed: "{{action}}を完了できませんでした：{{failure}}。",
    baseActionRead: "レコードの読み取り",
    baseActionSetStage: "レコードのステージ更新",
    baseActionWriteSummary: "要約の書き込み",
    baseFailureUnavailable: "Base を利用できません",
    baseFailureRefused: "書き込みが拒否されました",
    baseFailureConflict: "レコードが同時に変更されました",
    baseFailureUnknown: "理由は不明です",
    blockedSignIn: "{{provider}} にサインイン",
    blockedCheckSignIn: "サインインを確認",
    blockedSetUp: "{{provider}} を設定",
    blockedChooseConfig: "別の設定を選ぶ",
    retryStep: "このステップを再試行",
    retryStillBlocked: "再確認しました。まだ止まっています。",
    actionFailed: "操作できませんでした。もう一度お試しください。",
    remoteSending: "{{computer}}に送信しています…",
    remoteExpired: "{{computer}}から時間内に応答がなかったため、何も変わっていません。もう一度お試しください。",
    remoteCommandExpired: "この操作は時間内に{{computer}}へ届かなかったため、何も実行されていません。もう一度お試しください。",
    remoteUnknown: "{{computer}}がこれを実行したかどうか分かりません。やり直す前に実行を確認してください。",
    remoteClassMismatch: "{{computer}}では実行されませんでした。このデバイスとは Bottega のバージョンが異なります。両方の Bottega を最新にしてから、もう一度お試しください。",
    remoteOffline: "{{computer}}はオフラインです。オンラインに戻ると、ここで操作できます。",
    checkResultFailed: "結果を確認できませんでした。もう一度お試しください。",
    retryFailed: "このステップを再試行できませんでした。もう一度お試しください。",
    retryNotBlocked: "このステップはもう止まっていません。",
  },
  appOps: {
    useChat: "使用 Chat",
    edit: "編集",
    editHintWeb: "{{computer}}の Chat でこの App を変更します。Chat が終わると再ビルドされます。",
    editHintPhone: "{{computer}}の Chat でこの App を変更します。",
    sending: "{{computer}}に送信しています…",
    sendingUse: "{{computer}}が{{app}}の使用 Chat を開きます。応答があればすぐここに表示されます。時間内に応答がなければ何も変わらないので、もう一度お試しください。",
    sendingEdit: "{{computer}}が{{app}}の編集 Chat を開きます。応答があればすぐここに表示されます。時間内に応答がなければ何も変わらないので、もう一度お試しください。",
    startingEdit: "{{computer}}で編集 Chat を開始しています…",
    offlineReason: "{{computer}}はオフラインです。オンラインに戻ると操作できます。",
    offlineTitle: "{{computer}}はオフラインです",
    offlineBody: "使用 Chat と編集は{{computer}}で動きます。オンラインに戻ると操作できます。{{app}}を開くことと記録の編集は、ここでも引き続きできます。",
    offlineChip: "{{computer}}オフライン",
    useChatOffline: "使用 Chat（{{computer}}はオフライン）",
    appNotFound: "{{computer}}に{{app}}はもうありません。",
    appNotEditable: "{{app}}は{{computer}}では編集できません。変更できるのは記録だけです。",
    appBusy: "{{computer}}で{{app}}の現在の使用 Chat がまだ応答中です。開いて待つか停止してから、もう一度お試しください。",
    appTransitioning: "{{computer}}で{{app}}を更新中です。少し待ってからもう一度お試しください。",
    agentUnavailable: "{{computer}}に使える Agent がありません。{{computer}}の Bottega で設定してください。",
    reservationExpired: "{{computer}}が時間内に編集 Chat を開始しませんでした。メッセージは保持されています。もう一度送信してください。",
    reservationFilled: "{{app}}には{{computer}}ですでに編集 Chat があります。メッセージは下書きとしてここにあります。",
    firstMessageText: "最初のメッセージはテキストのみです。添付は 2 通目から使えます。",
    unknown: "{{computer}}が開いたかどうかわかりません。もう一度試しても安全で、Chat が重複して開くことはありません。",
    startupPending: "Bottega は起動時のチェックをまだ実行中です。しばらくしてからもう一度お試しください。",
    earlierProcess: "以前の Agent プロセスがまだ終了処理中です。しばらくしてからもう一度お試しください。",
    /* U06-d: the build status on the App page (building, waiting for the extension decision, failed) and its two commands. */
    buildingStatus: "{{computer}}でビルド中…",
    buildingTitleWeb: "{{computer}}で新しいバージョンをビルド中…",
    buildingBodyWeb: "前回の編集が終わりました。新しいバージョンの準備ができるまで、{{app}}は現在のバージョンで開きます。準備ができたら新しいバージョンで開き、お知らせします。",
    buildingTitlePhone: "新しいバージョンをビルド中…",
    buildingBodyPhone: "{{computer}}で実行中。新しいバージョンの準備ができるまで、現在のバージョンで開きます。",
    buildFailedStatus: "ビルドに失敗しました",
    buildFailedTitle: "新しいバージョンをビルドできませんでした",
    buildFailedBodyWeb: "前回の編集は{{computer}}でビルドできませんでした。{{app}}は以前のバージョンで開きます。コードを直すには、コンピューターの{{app}}でメンテナンス Agent に診断と修復を依頼してください。",
    buildFailedBodyPhone: "前回の編集は{{computer}}でビルドできませんでした。{{app}}は以前のバージョンで開きます。",
    buildFailedInterrupted: "更新が完了する前に中断されました。もう一度お試しください。",
    buildRetry: "もう一度試す",
    buildRepair: "コンピューターで修復",
    confirmStatus: "コンピューターの確認待ち",
    confirmTitle: "コンピューターでの確認を待っています",
    confirmBody: "この編集で{{app}}に拡張機能が追加されます。新しいバージョンをビルドするには、{{computer}}で承認してください。それまでは現在のバージョンがそのまま使えます。",
    confirmCancel: "リクエストを取り消す",
    confirmCancelledRemotely: "別のデバイスで取り消されました。",
    confirmTimedOut: "30 分以内に{{computer}}で承認されなかったため、新しいバージョンは拡張機能なしでビルドされました。追加するには、もう一度編集を依頼し、{{computer}}で承認してください。",
    confirmAlreadyResolved: "{{computer}}ですでに回答済みです。",
  },
  phone: {
    needsYou: "対応が必要",
    needsYouCount_one: "対応待ち {{count}} 件",
    needsYouCount_other: "対応待ち {{count}} 件",
    sheetNote: "判断を待っている項目だけを表示します。タップすると開くだけで、選ぶまでは何も確定しません。",
    empty: "対応が必要なものはありません。",
    pushLanding: "開いただけでは何も確定しません。",
    moreNeedsYou: "ほかに {{count}} 件あります。上のものを処理すると、ここに表示されます。",
    alreadyHandled: "これはすでに処理されています。",
    signInOnComputer: "ここで使うには、{{computer}}で {{provider}} にログインしてください。",
    theComputer: "Project のコンピューター",
    workflowSuspended: "{{computer}}でこのワークフローの設定を直すまで、実行を開始できません。",
  },
};
