/**
 * [INPUT]: Depends on ./en for the WorkbenchCopy shape.
 * [OUTPUT]: Provides zhCN, the Simplified Chinese workbench catalog.
 * Names built-in recipes and Workflow plugins and explains missing workflow measurements.
 * [POS]: Lazy workbench-copy locale; the interface says only 流程 and 运行.
 */
import { dock } from "./dock/zh-cn";
import type { WorkbenchCopy } from "./en";
import { memoryPluginCopy } from "./memory/zh-cn";

export const zhCN: WorkbenchCopy = {
  guiHistory: {
    title: "版本",
    current: "当前版本",
    previous: "上一版本",
    activate: "使用此版本",
    switching: "正在切换…",
    pending: "完成待处理的授权后，此版本才会启用。",
    loadFailed: "无法加载版本。",
    empty: "还没有构建成功的版本。",
    refresh: "刷新",
    edit: "编辑源码",
    installLocal: "从文件夹安装…",
    draftBusy: "请先完成或清空当前草稿，再打开插件源码 Chat。",
    skillMissing: "此 Agent 暂时无法使用 plugin-authoring Skill。",
    starterPrompt: "请使用 plugin-authoring Skill 创建这个插件，按我接下来描述的需求实现。",
  },
  terms: {
    pluginsAndApps: "插件",
    bottegaPlugin: "Bottega 插件",
    agentNativePlugin: "Agent 原生插件",
    baseApp: "Base 功能 App",
    baseBackedApp: "基于 Base 的 App",
    agentConfig: "Agent 配置",
    workflow: "流程",
    run: "运行",
  },
  base: {
    menuGroup: "流程",
    setUp: "设置流程…",
    settings: "流程设置",
    runWorkflow: "运行流程",
    runOnTask: "对这个任务运行流程",
    ready: "可以开始",
  },
  readOnly: {
    badge: "流程",
    columnHint: "只有流程能改这一列",
    setByWorkflow: "由流程填写",
    laneLocked: "{{column}} 由流程填写，这一列不接收卡片。请改你自己的列，或打开这次运行来决定下一步。",
    whoCanEdit: "谁能编辑",
    everyone: "所有人",
    onlyWorkflows: "只有流程",
    whoCanEditUnavailable: "只有流程添加的列可以限制编辑。",
  },
  record: {
    section: "流程",
    run: "运行",
    noRuns: "还没有运行",
    acceptance: "验收",
    notDecided: "未决定",
    accepted: "已接受",
    acceptedWithException: "带例外接受",
  },
  plugins: {
    title: "插件",
    description: "已安装在这台 Bottega 主机上的插件。可以开启或关闭、应用更新，或打开它查看设置和详情。",
    searchLabel: "搜索插件",
    statusLabel: "状态",
    statusAll: "全部状态",
    statusOn: "已开启",
    statusOff: "已关闭",
    statusAttention: "需要处理",
    sortLabel: "排序",
    sortGroup: "按类别",
    sortName: "按名称",
    sortRecent: "最近更改",
    newPlugin: "新建插件",
    groupFeature: "Bottega 功能",
    groupProvider: "Provider",
    groupPackage: "扩展",
    groupNative: "Agent 原生插件",
    emptyTitle: "没有符合条件的插件",
    clearFilters: "清除搜索和筛选",
    emptyAll: "还没有安装插件。",
    official: "官方",
    badgeBuiltin: "内置",
    badgePackage: "扩展 · v{{version}}",
    badgeNative: "Agent 原生",
    alwaysOn: "始终开启",
    nativeManagedBy: "由 {{agent}} 管理",
    projectScopedBadge: "仅限一个 Project",
    projectScopedNote: "这个插件只为一个 Project 安装，目前不能在这里关闭。",
    setupMemory: "开启…",
    setupDock: "设置…",
    blocked: "缺少依赖",
    unsupported: "本平台不支持",
    providerUsedBy_one: "{{count}} 个 Agent 配置在用",
    providerUsedBy_other: "{{count}} 个 Agent 配置在用",
    providerUnused: "尚未使用",
    workflowSetUpIn_one: "{{count}} 个 Project 在用",
    workflowSetUpIn_other: "{{count}} 个 Project 在用",
    workflowSetUpInNames: "已在 {{projects}} 中开启",
    turnedOffOn: "{{date}}关闭",
    neverOn: "从未开启",
    turnOffTitle: "关闭 {{name}}？",
    turnOffBody: "{{name}} 将不再在{{computer}}上启动。不会删除任何内容，随时可以重新打开。",
    whatChanges: "会有哪些变化",
    impactConfigs: "Agent 配置 {{config}} 不能再被选择",
    impactWorkflows: "{{name}} 关闭期间，{{workflow}} 不能开始新的运行",
    impactRuns_one: "{{count}} 个使用 {{name}} 的运行会做完当前步骤，然后暂停",
    impactRuns_other: "{{count}} 个使用 {{name}} 的运行会做完当前步骤，然后暂停",
    impactChats_one: "{{count}} 个与 {{name}} 的 Chat 仍可阅读，但不能再发消息",
    impactChats_other: "{{count}} 个与 {{name}} 的 Chat 仍可阅读，但不能再发消息",
    impactMore_one: "还有 {{count}} 项",
    impactMore_other: "还有 {{count}} 项",
    dependentsTitle: "这些插件会因此不可用",
    dependentLine: "{{plugin}}：它需要的能力只有 {{name}} 在提供",
    turnOff: "关闭",
    turnOn: "打开",
    thisComputer: "这台电脑",
    switchFailed: "没能更改 {{name}}，请重试。",
    switchLabel: "打开或关闭 {{name}}",
    reinstallRequired: "{{name}} 的安装文件在关闭期间有变化，暂时不能重新打开。",
    reinstallHelp: "请告诉我们，我们会帮你恢复。",
    reinstallIssueTitle: "{{name}} 无法重新打开",
    reinstallBadge: "不能重新打开",
    reportProblem: "报告问题",
    busyNote: "{{name}} 正在处理，完成后就能操作。",
    turningOn: "正在打开…",
    turningOff: "正在关闭…",
    chatTurnedOff: "{{provider}} 已在插件中关闭，重新打开后可以继续这个 Chat。",
    openPlugin: "打开 {{name}} 插件",
    back: "全部插件",
    on: "已开启",
    off: "已关闭",
    sectionSettings: "设置",
    settingsNote: "由插件清单声明",
    settingsProviderNote: "已有的会话不受影响",
    appliesImmediate: "立即生效",
    appliesNextTurn: "下一回合生效",
    appliesSessionCreate: "新会话生效",
    appliesProcessStart: "重启插件后生效",
    changed: "已更改",
    resetDefault: "恢复默认",
    confirmContinue: "继续",
    secretSet: "已设置",
    secretUnset: "未设置",
    secretReplace: "替换",
    secretClear: "清除",
    secretSave: "保存",
    secretCancel: "取消",
    decrease: "减少",
    increase: "增加",
    settingsFailed: "没能保存「{{setting}}」，请重试。",
    pendingRestart: "{{name}} 会在空闲时重启，以应用这些设置。",
    sectionHealth: "运行状态",
    checkedAt: "{{time}}检查",
    update: "更新",
    setUp: "设置",
    sectionUsedBy: "被谁使用",
    usedByConfigs: "Agent 配置",
    usedByProjects: "开启了流程的 Project",
    usedByNobody: "还没有被使用。",
    sectionDependencies: "依赖与被依赖",
    depRequires: "需要",
    depProvides: "提供",
    depDependents: "被依赖",
    depNone: "无",
    depSatisfiedBy: "由 {{plugins}} 满足",
    depHostNote: "设置、存储、事件与后台任务由 Bottega 提供，始终可用。",
    blockedMissing: "没有插件提供它",
    blockedDisabled: "提供它的插件都已关闭",
    blockedUnsupported: "提供它的插件不能在这台电脑上运行",
    blockedCycle: "它和别的插件互相依赖成环",
    blockedBanner: "{{name}} 现在不能开始新的工作。{{reason}}。",
    sectionCapabilities: "能力与权限",
    capabilitiesNone: "没有声明。",
    sectionIncludes: "包含",
    sectionCanDo: "能做什么",
    sectionWorksWith: "依赖关系",
    sectionInUse: "使用情况",
    sectionInformation: "信息",
    worksAlone: "可独立运行，也没有其他插件依赖它。",
    aboutPlugin: "关于 {{name}}",
    publisherBottega: "Bottega",
    about: "关于",
    aboutSource: "来源",
    aboutVersion: "版本",
    aboutKind: "类型",
    aboutId: "插件 ID",
    aboutManagedBy: "管理它的 Agent",
    aboutLocation: "位置",
    aboutPublisher: "发布者",
    unsigned: "未签名",
    versionWithApp: "随应用 {{version}}",
    kindFeature: "功能",
    kindProvider: "Provider",
    sourceLocalLong: "本地源码",
    sourceBuiltinLong: "Bottega 内置",
    sourcePackageLong: "扩展",
    sourceNativeLong: "Agent 原生",
    related: "相关页面",
    relatedProviders: "Providers",
    relatedAgentConfigs: "Agent 配置",
    relatedUsage: "用量",
    relatedSkills: "Skills",
    relatedMemory: "记忆",
    relatedDock: "Dock",
    nativeReadOnly: "这个插件由 {{agent}} 管理，Bottega 只做展示。要安装、更新或移除它，请在 {{agent}} 里操作。",
    notFound: "这个插件已经不在了。",
    loadFailed: "没能读取这个插件，请重试。",
    retry: "重试",
    sidebarGroup: "插件",
    sidebarAll: "全部插件",
    health: {
      unknown: "还没有检查",
      notChecked: "还没有检查",
      ready: "运行正常",
      off: "已关闭",
      running: "运行中",
      idle: "正常，未在运行",
      process: "进程",
      processRunning: "运行中",
      processIdle: "需要时启动",
      nativeEnabled: "{{agent}} 报告：已启用",
      nativeDisabled: "{{agent}} 报告：已停用",
      cliVersion: "CLI",
      signIn: "登录",
      runningRuns: "进行中的运行",
      cli: {
        unknown: "未检查",
        missing: "没有安装",
        error: "检查失败",
        unsupported: "需要更新",
        installed: "已安装",
      },
      auth: {
        unknown: "未知",
        checking: "正在检查…",
        authenticated: "已登录",
        unauthenticated: "未登录",
        error: "检查失败",
      },
    },
    unsupportedReason: {
      appleSilicon: "仅支持 macOS（Apple 芯片）",
    },
    capability: {
      startProcess: "在这台电脑上启动它的 CLI",
      projectFiles: "按 Agent 配置的权限读写 Project 文件夹",
      network: "联网访问它自己的服务",
      baseStore: "在每个 Project 的文件夹里保存表格",
      baseTools: "为 Agent 提供 Base 工具：读、写、查询记录",
      workflowColumns: "在 Base 里添加「阶段」「验收标准」两列，只有流程能写「阶段」",
      workflowRoles: "以各角色的 Agent 配置运行角色回合",
    },
    builtin: {
      memory: memoryPluginCopy,
      dock,
      sketch: { name: "草图", summary: "绘制、擦除并附上可继续编辑的图片。", description: "草图在输入框里加入一块画布。绘制、擦除、标注，然后把结果作为可继续编辑的图片附到消息里。" },
      base: {
        name: "Base",
        summary: "每个 Project 都有的表格、看板、列表和表单。流程与 Base 型 App 都建立在它之上。",
        description: "Base 让每个 Project 都有自己的表格。记录可以按表格、看板、列表或表单查看，保存在 Project 文件夹里，和你的文件放在一起。\n\nAgent 可以用 Base 工具读写和查询记录。流程与 Base 型 App 都建立在它之上，所以它始终开启。",
      },
      workflow: {
        name: "流程",
        summary: "让 Agent 角色按流程在 Base 上接力推进工作，每一步都可以审阅。",
        description: "流程把 Base 变成一条流水线。每一步由一个 Agent 配置扮演的角色完成，每一步结束都要审阅，通过后才进入下一步。\n\n在 Project 里设置流程，把卡片放进第一列即可开始。随时打开一次运行，查看每个角色做了什么，并决定接下来怎么走。",
      },
      claude: {
        name: "Claude",
        summary: "Anthropic 的 Claude Code，作为 Agent 在 Bottega 里运行。",
        description: "把 Anthropic 的 Claude Code 作为 Agent 在 Bottega 里运行。它在你的 Project 文件夹里工作，权限由各个 Agent 配置决定。\n\n需要在这台电脑上安装 Claude Code CLI 并登录 Anthropic 账号。100 万上下文、Claude in Chrome 等额外能力在它的设置里开启。",
        publisher: "Anthropic",
        settings: {
          memory: {
            label: "记忆",
            description: "让 Claude Code 在 Bottega 的对话里读写它自带的自动记忆。流程角色的回合始终不用。",
          },
          nativeSubagents: {
            label: "允许原生 subagent",
            description: "允许 Claude Code 用它自带的 Task 工具派生子 Agent。",
          },
          workflowTool: {
            label: "允许 Workflow 工具",
            description: "允许 Claude Code 使用它自带的 Workflow 工具。",
          },
          context1m: {
            label: "使用 1M 上下文",
            description: "允许 Claude Code 使用 100 万 token 的上下文窗口。",
          },
          claudeInChrome: {
            label: "Claude in Chrome",
            description: "启动 Claude Code 时带上 Claude in Chrome 浏览器工具。需要这台电脑装了 Chrome 扩展，并登录 claude.ai。",
          },
        },
      },
      codex: {
        name: "Codex",
        summary: "OpenAI 的 Codex CLI，作为 Agent 在 Bottega 里运行。",
        description: "把 OpenAI 的 Codex CLI 作为 Agent 在 Bottega 里运行。它在各个 Agent 配置允许的范围内读写你的 Project 文件夹。\n\n需要在这台电脑上安装 Codex CLI 并登录 OpenAI 账号。它自带的记忆和多 Agent 功能可以在设置里关闭。",
        publisher: "OpenAI",
        settings: {
          memory: {
            label: "记忆",
            description: "让 Codex 在 Bottega 的对话里使用它自带的记忆。流程角色的回合始终不用。",
          },
          nativeSubagents: {
            label: "允许原生 subagent",
            description: "允许 Codex 使用它自带的多 Agent 功能。",
          },
        },
      },
      kimi: {
        name: "Kimi",
        summary: "月之暗面的 Kimi CLI，作为 Agent 在 Bottega 里运行。",
        description: "把 Moonshot 的 Kimi CLI 作为 Agent 在 Bottega 里运行。需要在这台电脑上安装 Kimi CLI 并登录 Moonshot 账号。",
        publisher: "Moonshot AI",
      },
      opencode: {
        name: "OpenCode",
        summary: "开源的 OpenCode，可以接入多家模型服务。",
        description: "把开源的 OpenCode CLI 作为 Agent 在 Bottega 里运行。它可以使用多家服务的模型。",
        publisher: "OpenCode",
      },
    },
  },
  agentConfigs: {
    loading: "正在加载 Agent 配置…",
    loadFailed: "无法加载 Agent 配置，请重试。",
    refreshFailed: "无法刷新 Agent 配置，仍显示上次加载的列表。",
    unavailable: "当前窗口无法读取 Agent 配置，请重试或重新打开设置。",
    reasoningEffort: "推理强度",
    agentDefault: "Agent 默认",
    modelsFailed: "无法加载模型，已保留你的选择。",
    defaultsFailed: "无法读取已保存的默认值，请选择模型或重试。",
    optionUnavailable: "此处无法使用已保存的选项。选择其他选项前会保留原值。",
    chooseModelForEffort: "选择可用模型后可查看其推理强度选项。",
    baseResource: "Base",
    chatResource: "Chat",
    mcpResource: "MCP",
    selectedCount: "已选 {{count}} / {{limit}} 项",
    resourcesLoading: "正在读取本机资源…",
    resourcesFailed: "部分资源未能读取。已保留你的选择。",
    resourcesEmpty: "本机没有可选资源。",
    resourceUnavailable: "本机不可用",
    baseRead: "只读",
    baseReadWrite: "读写",
    linkedChats: "仅关联的 Chat",
    resourcesHint: "新运行只使用所选资源。另一台电脑缺少资源时，会提示修正后再运行。",
    resourcesReadOnly: "规划、评审和只读配置只能读取 Base，不能使用 MCP server。",
    baseCapped: "请求范围：读写。实际范围：只读。保存时保留原请求。",
    removeReadOnlyMcp: "请取消所选 MCP server，再保存只读配置。",
    retryResources: "重新读取资源",
    title: "Agent 配置",
    description: "可复用的 Provider、模型、指令和工具。",
    allProjects: "所有 Project",
    someProjects: "部分 Project",
    someProjectsDescription: "只出现在每个配置下列出的 Project 中。",
    newConfig: "新建配置",
    edit: "编辑",
    readOnly: "只读",
    newTitle: "新建 Agent 配置",
    editTitle: "编辑 Agent 配置",
    prefilled: "已按{{role}}预先填好角色、权限和工具，都可以修改。",
    startFrom: "起点",
    blank: "空白",
    planner: "规划",
    developer: "开发",
    reviewer: "评审",
    name: "名称",
    availableIn: "可用于",
    searchProjects: "搜索 Project",
    provider: "Provider",
    chooseProvider: "选择 Provider",
    model: "模型",
    providerDefault: "Provider 默认",
    instructions: "指令",
    instructionsHint: "会发给 Agent",
    purpose: "用途",
    purposeHint: "给选择配置的人看",
    permissions: "权限",
    skills: "Skills",
    toolsAndData: "工具与数据",
    toolsBaseReadWriteLinked: "Base 读写 · 仅关联的 Chat",
    toolsBaseReadLinked: "Base 只读 · 仅关联的 Chat",
    none: "无",
    create: "创建",
    missingRequired: "请填写名称并选择 Provider",
    appliesToNewRuns: "保存后，只影响之后开始的运行。",
    appliesNextTurn: "下一轮生效",
    restartsAgent: "会重启 Agent",
    appliesOnNew: "新建 Chat 时生效",
    notForRole: "不适合这个角色",
    notAdmitted: "还不能担任{{role}}",
    partialFailure: "部分设置没有生效，这个配置暂时不能担任它的角色。",
    presetPlanner: "阅读任务和验收标准，然后写出分步计划。不要修改代码。",
    presetDeveloper: "按已接受的计划做，改动只限于这个任务。汇报前先运行 Project 的检查。",
    presetReviewer: "对照计划和验收标准检查结果，写明缺了什么。不要修改代码。",
    emptyTitle: "还没有 Agent 配置",
    emptyBody: "新建一个，就能在流程的步骤里选用。",
    syncing: "同步中",
    conflicted: "需要处理",
    notSynced: "未同步",
    syncIssueBudget: "这个账号的 Agent 配置已达上限（100 个），这一个还没同步。删掉一个不再用的配置后，它会自动同步。",
    saveFailed: "没能保存这个配置，你的修改还在。",
    allProjectsHint: "在所有 Project 中可选",
    noProjects: "还没有 Project",
    needsAttention: "需要处理",
    guaranteeReadOnly: "只读工作区",
    guaranteeNoNetwork: "不联网",
    reasonProviderCannot: "{{provider}} 做不到这一点",
    reasonHostCannot: "这台电脑无法强制执行",
    reasonHostUnavailable: "无法检查：运行它的电脑不可用",
    reasonNotMeasured: "尚未验证",
    applyPartial: "{{settings}}在这台电脑上没有生效，流程暂时不能用这个配置。",
    applyPartialGeneric: "部分设置在这台电脑上没有生效，流程暂时不能用这个配置。",
    workspace: "工作区",
    workspaceWrite: "可以修改文件",
    workspaceReadOnly: "只读",
    network: "网络",
    networkOn: "开",
    networkOff: "关",
    notReadOnly: "它的工作区没有设为只读",
    providerTurnedOff: "{{provider}} 已关闭",
  },
  setup: {
    enableTitle: "开启流程",
    enableDescription: "规划、开发、评审，由这台电脑执行。",
    enableAndRun: "开启并运行当前行",
    noReadyProvider: "还没有可运行此流程的 Provider。",
    openSettings: "打开设置",
    openBase: "打开 Base 整理列",
    openProject: "打开 Project 设置",
    projectUnavailable: "请先在 Project 设置中选择工作文件夹。",
    enableFailed: "流程未能开启。请重新检查当前条件。",
    checkAgain: "重新检查",
    refusalSkillUnavailable: "{{config}} 选中的 Skill 在这台电脑上缺失或已停用。",
    refusalMcpUnavailable: "{{config}} 选中的 MCP server 在这台电脑上不可用。",
    refusalMcpReadOnly: "{{config}} 选了 MCP server，规划与评审不能使用。请取消选择或换一个配置。",
    planDevelopReview: "规划 · 开发 · 审查",
    newTitle: "设置流程",
    editTitle: "流程设置",
    stepOf: "第 {{current}} 步，共 {{total}} 步",
    tabWorkflow: "流程",
    tabWho: "谁来做",
    tabBase: "你的 Base",
    tabCheck: "检查",
    chooseTitle: "选择流程",
    whoTitle: "每一步谁来做",
    whoHint: "点名字可以换人。",
    whoGreyedHint: "每个列表只列出能做这一步的配置，其余置灰并写明原因。",
    you: "你",
    addStep: "加一步",
    stepPlan: "规划",
    stepPlanDescription: "为任务写计划",
    stepConfirm: "确认",
    stepConfirmDescription: "你阅读并接受计划",
    stepDevelop: "开发",
    stepDevelopDescription: "修改代码",
    stepReview: "评审",
    stepReviewDescription: "检查结果，不做修改",
    stageDone: "完成",
    stepDecide: "决定",
    stepDecideDescription: "你接受、结束或返工",
    youConfirm: "你确认",
    youDecide: "你决定",
    baseTitle: "你的 Base 会怎样变",
    baseIntro_one: "流程会新增 1 列，你已有的内容不会改变。",
    baseIntro_other: "流程会新增 {{count}} 列，你已有的内容不会改变。",
    baseIntroEditing: "你的 Base 已经有流程的两列，这里不会有变化。",
    baseNow: "现在",
    baseAfter: "开启后",
    baseNewColumns_one: "你的 Base 会新增 1 列",
    baseNewColumns_other: "你的 Base 会新增 {{count}} 列",
    stageColumn: "阶段",
    stageDescription: "显示每个任务走到哪一步。由流程更新，你不能修改。",
    acceptanceColumn: "验收标准",
    boardView: "看板 · 按阶段",
    acceptanceDescription: "由你写下每个任务怎样才算“完成”。",
    baseOthersUnchanged: "你的其他列保持不变。",
    baseFixedColumns: "这两列由流程决定，这里不能修改。",
    baseFull_one: "这个 Base 最多 {{limit}} 列，现在已有 {{existing}} 列。在 Base 里删掉 1 列后才能开启流程。",
    baseFull_other: "这个 Base 最多 {{limit}} 列，现在已有 {{existing}} 列。在 Base 里删掉 {{count}} 列后才能开启流程。",
    baseBoardAdded: "新增视图“{{view}}”并打开它。你的其他视图保持不变。",
    baseBoardNoRoom: "这个 Base 已有 {{limit}} 个视图，所以不会新增“{{view}}”视图，流程照常开启。",
    baseChanged: "打开这个窗口后，Base 的列有了变化。这里显示的是现在的样子。",
    checkTitle: "检查并开启",
    checkedOn: "已在{{computer}}上检查。",
    providerReady: "{{provider}} 在{{computer}}上已就绪",
    checking: "正在这台电脑上检查…",
    roleReady: "{{step}}：{{provider}} 已在{{computer}}上就绪",
    roleProblem: "{{step}}：{{reason}}",
    refusalDeleted: "这个配置已被删除。",
    refusalNotEnabled: "{{config}} 是在其他设备上创建的，还没在{{computer}}上保存过。到 Agent 配置里打开它，保存一次即可。",
    refusalMismatch: "{{config}} 换了 Provider，需要重新确认。到 Agent 配置里打开它，保存一次即可。",
    refusalSelection: "{{config}} 设置了自己的 Memory，流程步骤暂时还用不了。请换一个配置。",
    refusalMemoryWrite: "{{config}} 请求写入 Memory。流程步骤只能读取 Memory。",
    refusalScope: "流程步骤不支持 {{config}} 里的 Skills 或工具设置。打开这个配置重新保存即可。",
    refusalPartial: "{{config}} 的{{settings}}在 {{computer}} 上没有生效。打开这个配置修改一下。",
    refusalPartialGeneric: "{{config}} 的部分设置在 {{computer}} 上没有生效。打开这个配置检查一下。",
    refusalReadOnly: "要求只读工作区，所以不能改代码。",
    refusalNoNetwork: "要求不联网，{{computer}}上暂时还无法保证。",
    baseHasRoom_one: "Base 还能再放 1 列",
    baseHasRoom_other: "Base 还能再放 {{count}} 列",
    baseGets: "Base 新增",
    needsComputer: "需要{{computer}}在线",
    turnOn: "开启",
    continue: "继续",
    back: "返回",
  },
  projectWorkflows: {
    tab: "流程",
    description: "可以从这个 Project 的 Base 任务上运行的流程。",
    addWorkflow: "添加流程",
    on: "开",
    off: "关",
    runsOn: "在{{computer}}上运行",
    configsTitle: "这个 Project 的 Agent 配置",
    configsHint: "个人配置在 设置 › Agent 配置。",
    availableIn: "可用于 {{projects}}",
    needsBase: "这个 Project 有了 Base 之后才能添加流程，流程在 Base 的任务上运行。",
    workflowChats_one: "{{count}} 个流程 Chat",
    workflowChats_other: "{{count}} 个流程 Chat",
    workflowRuns_one: "{{count}} 次运行",
    workflowRuns_other: "{{count}} 次运行",
    alsoArchived: "另有 {{chats}}（来自 {{runs}}）会一起归档。",
    alsoArchivedNoRuns: "另有 {{chats}} 会一起归档。",
    alsoDeleted: "这个 Project 的 {{chats}} 会一并删除。",
    archiveStepRunning: "流程正在执行一步，现在还不能归档。这一步结束后运行会暂停，到时再试。",
    runsStillStopping: "这个 Project 有一次流程运行还在停止中，可能仍有进程在运行。请在运行里强制停止，然后再试。",
    runtimeNotReady: "流程还在这台电脑上启动，请稍后再试。",
  },
  run: {
    blockedVersionTooOld: "{{computer}}上的 {{provider}} 版本过低，请更新后再运行流程。",
    blockedExtractorVersionTooOld: "{{step}}没有交出有效结果，请更新{{computer}}上的 Claude 后整理结果。",
    label: "运行 #{{number}}",
    onComputer: "在{{computer}}上",
    queued: "排队中",
    running: "运行中",
    needsYou: "等你处理",
    paused: "已暂停",
    blocked: "受阻",
    cancelling: "正在取消…",
    succeeded: "已完成",
    failed: "失败",
    cancelled: "已取消",
    stopped: "已停止",
    stoppedForced: "已停止（强制）",
    pausedWaited: "已暂停 · 等了 24 小时",
    pausedArchived: "已暂停 · Project 已归档",
    cancellingTitle: "正在取消",
    cancellingBody: "不会再开始新的步骤。Bottega 正在停止{{computer}}上的 {{provider}}，可能需要几秒。在这里显示已停止之前，它还没有停下。",
    stuckTitle: "30 秒后仍在停止",
    stuckBody: "{{computer}}上的 {{provider}} 还没有退出，你可以强制停止。它已经改过的代码会留在工作区，下次运行前请先检查。",
    forceStop: "强制停止",
    forceStopUnconfirmedTitle: "可能仍有进程在运行",
    forceStopUnconfirmedBody: "Bottega 已在{{computer}}上停止这一步，但没能确认所有进程都已结束。请再次强制停止，并在下次运行前检查工作区。",
    waitingFor: "等待{{computer}}",
    reminder: "计划已经等了 23 小时。请在 1 小时内决定，否则这次运行会暂停。",
    waitingStarted: "有一份计划等你审阅。",
    reminderResult: "结果已经等了 23 小时。请在 1 小时内决定，否则这次运行会暂停。",
    waitingStartedResult: "有一份结果等你决定。",
    pauseConfirmationTimeout: "等待确认超过 24 小时，已暂停。继续后会重新请你确认。",
    pausedNotice: "等了 24 小时后已暂停，没有执行任何步骤。打开它继续。",
    resume: "继续",
    resultUnknown: "结果未知",
    resultUnknownBody: "{{computer}}在 {{time}} 已受理，但结果没有传回来。不会自动重新发送。",
    checkResult: "核对结果",
    acceptPlan: "接受计划",
    accept: "接受",
    acceptWithException: "带例外接受",
    exceptionReason: "为什么仍然接受？",
    exceptionReasonRequired: "带例外接受需要写明理由。",
    end: "结束",
    rework: "返工",
    reworkFromDevelop: "保留已接受的计划，从开发开始",
    replan: "重新规划",
    reconfirm: "验收标准有改动。继续运行前，请重新确认计划。",
    alreadyHandled: "已在 {{device}} 上处理",
    viewResult: "查看结果",
    viewLog: "查看日志",
    tryAgain: "重试",
    details: "运行详情",
    startRun: "开始运行",
    pause: "暂停",
    cancelRun: "取消运行",
    cancelConfirmTitle: "取消这次运行？",
    cancelConfirmBody: "正在进行的步骤会先停下，已经改动的代码会留在工作区。这次运行不会再继续，之后可以重新开始。",
    keepRunning: "继续运行",
    forceConfirmTitle: "强制停止？",
    forceConfirmBody: "会直接结束{{computer}}上这一步的所有进程。它已经做的改动不会撤回，下次运行前请检查工作区。",
    keepWaiting: "继续等待",
    openChat: "打开 Chat",
    artifact: "结果",
    evidence: "证据",
    stepPending: "未开始",
    stepRunning: "运行中",
    stepWaiting: "等你处理",
    stepSucceeded: "已完成",
    stepFailed: "失败",
    stepBlocked: "受阻",
    stepCarried: "沿用已接受的计划",
    stepNotRun: "未运行",
    pauseUser: "你暂停了这次运行。",
    pauseProjectArchived: "Project 已归档，这次运行已暂停。恢复 Project 后再继续。",
    pauseProjectRestored: "Project 归档时暂停了这次运行。准备好后可以继续。",
    pausingAfterStep: "当前这一步结束后，这次运行会暂停。",
    pausingArchived: "Project 已归档。当前这一步结束后，这次运行会暂停。",
    projectArchived: "这个 Project 已归档，它的运行不能开始或继续。恢复 Project 后，再手动继续这次运行。",
    pauseBindingSuspended: "已暂停：流程的设置有变化。修好后可以继续或取消。",
    pausePluginDisabled: "已暂停：{{provider}} 已在插件中关闭。重新打开后可以继续或取消。",
    waitingWorkspace: "等待工作区",
    waitingWorkspaceBody: "正在等「{{task}}」写完这个工作区。同一个工作区一次只有一条记录在开发，轮到时会自动开始。",
    waitingWorkspaceStuck: "「{{task}}」那次运行可能还有进程没停下，去那里处理后这里才会开始。",
    viewHoldingRun: "查看那次运行",
    pausePluginWorkflow: "已暂停：流程已在「插件」中关闭。打开后可以继续，也可以现在取消。",
    pausePluginWorkflowOn: "已暂停：{{computer}}上的流程已在「插件」中关闭。在那台电脑上重新开启后可以继续，也可以现在取消。",
    workflowOffAction: "流程已在「插件」中关闭，打开后才能继续。",
    workflowBlockedAction: "流程缺少依赖：插件里没有开启的 Provider。打开任意一个后才能继续。",
    staleProposal: "任务或验收标准在等待期间改了，这一步已按现在的内容重新请你确认。",
    stoppedForcedHint: "已强制停止。下次运行前请先检查工作区。",
    stoppedForcedAtStartupHint: "已强制停止，重启后确认。下次运行前请先检查工作区。",
    stoppingFor: "已停止 {{seconds}} 秒",
    confirmPlanTitle: "确认计划",
    confirmResultTitle: "决定结果",
    reworkTitle: "返工",
    reworkStart: "开始返工",
    reworkReasonAcceptance: "验收标准已改",
    reworkReasonTask: "任务已改",
    reworkKeepPlanReconfirm: "沿用原计划并重新确认",
    reworkKeepPlan: "保留计划",
    reworkKeepPlanMaybeReconfirm: "如果任务或验收标准变了，会先请你重新确认计划。",
    noResultYet: "还没有结果",
    startWorkflowOff: "流程已在「插件」中关闭。打开后才能开始运行。",
    startWorkflowBlocked: "流程缺少依赖：插件里没有开启的 Provider。先打开任意一个，才能开始运行。",
    startFailed: "没能开始运行，请重试。",
    agentWaiting: "{{step}}在它的 Chat 里等你答复",
    agentWaitingBody: "它提出了权限请求或问题。你在那里答复之前，这次运行不会继续。",
    blockedSignedOut: "{{provider}} 没有在{{computer}}上登录。",
    blockedAuthUnknown: "无法确认 {{provider}} 已在{{computer}}上登录。",
    blockedAuthChecking: "仍在确认 {{provider}} 是否已在{{computer}}上登录。",
    blockedAuthError: "检查 {{provider}} 在{{computer}}上的登录状态时出错。",
    blockedAuthTimeout: "{{provider}} 在{{computer}}上的登录检查超时。",
    blockedNotInstalled: "{{computer}}上没有安装 {{provider}}。",
    blockedMeasurementsUnavailable: "{{provider}} 还没有流程所需的实测证据。",
    blockedPluginDisabled: "{{provider}} 已在「插件」中关闭。",
    blockedNotMeasured: "{{provider}} 还没有在{{computer}}上完成检测，所以不能做{{step}}。",
    blockedProviderCannot: "{{provider}} 不能做{{step}}：它做不到这一步要求的保证。",
    blockedConfigUnavailable: "{{step}}选用的配置已经不可用。",
    blockedGuaranteeReadOnly: "{{step}}选用的配置要求只读工作区，所以不能改代码。",
    blockedGuaranteeNetwork: "{{step}}选用的配置要求不联网，{{computer}}上暂时还无法保证这一点。",
    blockedInstanceChanged: "流程所在的 Base 被替换了。请重新设置流程。",
    blockedTaskMissing: "Base 的任务列不见了。恢复后再继续。",
    blockedStageMissing: "阶段列不见了。恢复后再继续。",
    blockedAcceptanceMissing: "验收标准列不见了。恢复后再继续。",
    blockedNoValidReport: "{{step}}没有交出有效结果。",
    blockedExtractorOff: "{{step}}没有交出有效结果，负责整理结果的 Claude 已在「插件」中关闭。",
    blockedExtractorNotInstalled: "{{step}}没有交出有效结果，负责整理结果的 Claude 没有安装在{{computer}}上。",
    blockedExtractorSignedOut: "{{step}}没有交出有效结果，负责整理结果的 Claude 没有在{{computer}}上登录。",
    blockedExtractorAuthUnknown: "{{step}}没有交出有效结果，无法确认负责整理结果的 Claude 已在{{computer}}上登录。",
    blockedExtractorAuthChecking: "{{step}}没有交出有效结果，负责整理结果的 Claude 在{{computer}}上的登录状态仍在确认。",
    blockedExtractorAuthError: "{{step}}没有交出有效结果，检查负责整理结果的 Claude 在{{computer}}上的登录状态时出错。",
    blockedExtractorAuthTimeout: "{{step}}没有交出有效结果，负责整理结果的 Claude 在{{computer}}上的登录检查超时。",
    blockedExtractorNotMeasured: "{{step}}没有交出有效结果，Claude 还没有在{{computer}}上通过整理结果的检测。",
    blockedExtractorFailed: "{{step}}没有交出有效结果，从 Chat 里整理了两次也没成功。",
    blockedCheckProvider: "重新检测 {{provider}}",
    reportDerived: "从回答整理",
    reportShortened: "已截短",
    reportShortenedPlan: "这里只显示了规划的一部分。",
    reportShortenedReview: "这里只显示了评审的一部分。",
    openWholePlan: "打开完整规划",
    openWholeReview: "打开完整评审",
    reportDerivedHint: "Agent 没有按格式提交这一步的结果。这份报告由 Bottega 从它这一轮的回答里原样整理，引用只保留回答里出现过的。",
    blockedDispatchFailed: "{{step}}没能发送给 {{provider}}。",
    blockedAttemptsExhausted: "这一步已重试到上限。请取消这次运行后重新开始。",
    blockedOther: "{{step}}没能完成。",
    blockedBaseAction: "更新 Base 没能完成。",
    blockedRecordMissing: "这条记录已被删除。",
    blockedBaseActionFailed: "{{action}}没能完成：{{failure}}。",
    baseActionRead: "读取记录",
    baseActionSetStage: "更新记录的阶段",
    baseActionWriteSummary: "写入摘要",
    baseFailureUnavailable: "Base 不可用",
    baseFailureRefused: "写入被拒绝",
    baseFailureConflict: "记录同时被改动了",
    baseFailureUnknown: "原因未知",
    blockedSignIn: "登录 {{provider}}",
    blockedCheckSignIn: "检查登录",
    blockedSetUp: "设置 {{provider}}",
    blockedChooseConfig: "换一个配置",
    retryStep: "重试这一步",
    retryStillBlocked: "已重新检查：仍然受阻。",
    actionFailed: "操作没有成功，请重试。",
    remoteSending: "正在发送到{{computer}}…",
    remoteExpired: "{{computer}}没有及时回应，什么都没有改。可以再试一次。",
    remoteCommandExpired: "这个操作没能及时送达{{computer}}，所以没有执行。请重试。",
    remoteUnknown: "不确定{{computer}}有没有执行。先看一下这次运行，再决定要不要重试。",
    remoteClassMismatch: "{{computer}}没有执行：它和这台设备的 Bottega 版本不一致。把两边都更新到最新版本后再试。",
    remoteOffline: "{{computer}}离线。它上线后才能在这里操作。",
    checkResultFailed: "没能检查结果，请重试。",
    retryFailed: "没能重试这一步，请再试一次。",
    retryNotBlocked: "这一步已经不再受阻。",
  },
  appOps: {
    useChat: "使用 Chat",
    edit: "编辑",
    editHintWeb: "在{{computer}}上的 Chat 里修改这个 App，Chat 结束后会重新构建。",
    editHintPhone: "在{{computer}}上的 Chat 里修改这个 App。",
    sending: "正在发送到{{computer}}…",
    sendingUse: "{{computer}}会打开{{app}}的使用 Chat，回应后会立即显示在这里。如果没有及时回应，不会有任何改动，可以再试一次。",
    sendingEdit: "{{computer}}会打开{{app}}的编辑 Chat，回应后会立即显示在这里。如果没有及时回应，不会有任何改动，可以再试一次。",
    startingEdit: "正在{{computer}}上开启编辑 Chat…",
    offlineReason: "{{computer}}已离线，恢复在线后即可操作。",
    offlineTitle: "{{computer}}已离线",
    offlineBody: "使用 Chat 和编辑都在{{computer}}上运行，恢复在线后即可操作。在这里仍可打开{{app}}并编辑记录。",
    offlineChip: "{{computer}}离线",
    useChatOffline: "使用 Chat（{{computer}}已离线）",
    appNotFound: "{{computer}}上已经没有{{app}}。",
    appNotEditable: "{{app}}在{{computer}}上不可编辑，只能修改它的记录。",
    appBusy: "{{app}}当前的使用 Chat 在{{computer}}上仍有回复在进行，打开它等待或停止后再试。",
    appTransitioning: "{{app}}正在{{computer}}上更新，请稍后再试。",
    agentUnavailable: "{{computer}}没有可用的 Agent，请在{{computer}}的 Bottega 里设置。",
    reservationExpired: "{{computer}}没有及时开启编辑 Chat，消息已保留，请再次发送。",
    reservationFilled: "{{app}}在{{computer}}上已有编辑 Chat，消息已作为草稿放在这里。",
    firstMessageText: "第一条消息只能发文字，从第二条起可以添加附件。",
    unknown: "不确定{{computer}}是否已打开。可以再试一次，不会重复打开 Chat。",
    startupPending: "Bottega 仍在完成启动检查，请稍后再试。",
    earlierProcess: "之前的 Agent 进程还在收尾，请稍后再试。",
    /* U06-d: the build status on the App page (building, waiting for the extension decision, failed) and its two commands. */
    buildingStatus: "正在{{computer}}上构建…",
    buildingTitleWeb: "正在{{computer}}上构建新版本…",
    buildingBodyWeb: "上一次编辑已完成。新版本就绪前，{{app}}仍打开当前版本；就绪后会打开新版本并提示。",
    buildingTitlePhone: "正在构建新版本…",
    buildingBodyPhone: "在{{computer}}上。新版本就绪前，仍打开当前版本。",
    buildFailedStatus: "构建失败",
    buildFailedTitle: "无法构建新版本",
    buildFailedBodyWeb: "上一次编辑没能在{{computer}}上构建。{{app}}仍打开上一个版本。要修复代码，请在电脑上的{{app}}里让维护 Agent 诊断修复。",
    buildFailedBodyPhone: "上一次编辑没能在{{computer}}上构建。{{app}}仍打开上一个版本。",
    buildFailedInterrupted: "更新在完成前被中断了。请重试。",
    buildRetry: "重试",
    buildRepair: "在电脑上修复",
    confirmStatus: "等待电脑确认",
    confirmTitle: "等待电脑确认",
    confirmBody: "这次编辑为{{app}}添加了扩展。请在{{computer}}上批准后再构建新版本，在此之前当前版本照常可用。",
    confirmCancel: "取消请求",
    confirmCancelledRemotely: "已在另一台设备上取消。",
    confirmTimedOut: "30 分钟内没有人在{{computer}}上批准，新版本已不带扩展构建。如需添加，请重新发起编辑并在{{computer}}上批准。",
    confirmAlreadyResolved: "已在{{computer}}上处理。",
  },
  phone: {
    needsYou: "等你处理",
    needsYouCount_one: "{{count}} 项等你处理",
    needsYouCount_other: "{{count}} 项等你处理",
    sheetNote: "这里只列等你决定的事项。点开只是打开，你做出选择之前不会确认任何事。",
    empty: "没有等你处理的事项。",
    pushLanding: "点开并不等于确认。",
    moreNeedsYou: "还有 {{count}} 项，处理完上面的会继续显示。",
    alreadyHandled: "这一项已经处理过了。",
    signInOnComputer: "请在{{computer}}上登录 {{provider}}，然后就能在这里使用。",
    theComputer: "Project 所在的电脑",
    workflowSuspended: "这个流程的设置需要先在{{computer}}上修好，才能开始运行。",
  },
};
