/**
 * [INPUT]: Depends on the active product locale.
 * [OUTPUT]: Provides packageCopy for installation, signature review and retained data decisions.
 * [POS]: Settings Plugins package copy; every supported locale has the same keys.
 */
const en = {
  install: "Install plugin…", source: "Install a plugin", review: "Review this plugin", update: "Review plugin update",
  description: "Choose a GitHub repository or a built package on this computer. Review its source and permissions before installing.",
  signature: "Publisher signature", verified: "Verified publisher", unverified: "Publisher not verified. Install only if you trust this source.",
  digest: "Package fingerprint", permissions: "Requested permissions", manage: "Installed package", retention: "Uninstall keeps this plugin’s data on this computer. You can delete it separately after its running work and references are released.",
  purge: "Delete retained data?", purgeDescription: "This permanently deletes the selected plugin’s retained data on this computer.",
  unavailable: "This request is no longer available for this account. Review it again on the requesting account.",
  localUpdate: "Choose the rebuilt package using Install plugin to review an update.",
};
type Copy = { [K in keyof typeof en]: string };
const copies: Record<string, Copy> = {
  en,
  "zh-cn": { install: "安装插件…", source: "安装插件", review: "确认插件信息", update: "确认插件更新", description: "选择 GitHub 仓库或这台电脑上已构建的插件包，检查来源和权限后安装。", signature: "发布者签名", verified: "发布者已验证", unverified: "发布者尚未验证。请仅安装你信任的来源。", digest: "插件包指纹", permissions: "申请的权限", manage: "已安装的插件包", retention: "卸载会保留这台电脑上的插件数据。运行中的工作和引用释放后，可单独删除数据。", purge: "删除保留数据？", purgeDescription: "这会永久删除所选插件在这台电脑上保留的数据。", unavailable: "当前账号无法确认这个请求。请使用发起请求的账号重新检查。", localUpdate: "使用“安装插件”选择重新构建的插件包，确认更新。" },
  ja: { install: "プラグインをインストール…", source: "プラグインのインストール", review: "プラグインを確認", update: "更新を確認", description: "GitHub リポジトリか、このコンピューターでビルド済みのパッケージを選び、提供元と権限を確認してください。", signature: "発行者の署名", verified: "確認済みの発行者", unverified: "発行者を確認できません。信頼できる提供元のみインストールしてください。", digest: "パッケージの指紋", permissions: "要求された権限", manage: "インストール済みパッケージ", retention: "アンインストール後もデータは保持されます。実行中の処理と参照の解放後、個別に削除できます。", purge: "保持データを削除しますか？", purgeDescription: "選択したプラグインの保持データをこのコンピューターから完全に削除します。", unavailable: "このアカウントでは要求を確認できません。要求元のアカウントで再確認してください。", localUpdate: "再ビルドしたパッケージを「プラグインをインストール」から選択し、更新を確認してください。" },
  es: { install: "Instalar plugin…", source: "Instalar un plugin", review: "Revisar plugin", update: "Revisar actualización", description: "Elige un repositorio de GitHub o un paquete compilado en este equipo. Revisa su origen y permisos antes de instalarlo.", signature: "Firma del editor", verified: "Editor verificado", unverified: "Editor sin verificar. Instala solo si confías en su origen.", digest: "Huella del paquete", permissions: "Permisos solicitados", manage: "Paquete instalado", retention: "Al desinstalar se conservan los datos en este equipo. Podrás eliminarlos por separado cuando terminen las tareas y se liberen las referencias.", purge: "¿Eliminar los datos conservados?", purgeDescription: "Se eliminarán permanentemente los datos del plugin seleccionado en este equipo.", unavailable: "Esta cuenta ya no puede confirmar la solicitud. Revísala desde la cuenta que la envió.", localUpdate: "Elige el paquete recompilado desde Instalar plugin para revisar la actualización." },
  fr: { install: "Installer un plugin…", source: "Installer un plugin", review: "Examiner le plugin", update: "Examiner la mise à jour", description: "Choisissez un dépôt GitHub ou un paquet compilé sur cet ordinateur. Vérifiez sa source et ses autorisations avant de l’installer.", signature: "Signature de l’éditeur", verified: "Éditeur vérifié", unverified: "Éditeur non vérifié. Installez uniquement une source de confiance.", digest: "Empreinte du paquet", permissions: "Autorisations demandées", manage: "Paquet installé", retention: "La désinstallation conserve les données sur cet ordinateur. Vous pourrez les supprimer séparément après la fin des tâches et la libération des références.", purge: "Supprimer les données conservées ?", purgeDescription: "Les données conservées du plugin sélectionné seront définitivement supprimées de cet ordinateur.", unavailable: "Ce compte ne peut plus confirmer cette demande. Examinez-la avec le compte qui l’a envoyée.", localUpdate: "Choisissez le paquet recompilé avec Installer un plugin pour examiner sa mise à jour." },
};
const requestEn = { requests: "Plugin installation requests", requestDescription: "Review requests in Settings → Plugins on the computer. Every installation requires confirmation there.", requestSource: "Requested from {{device}}", request: "Request installation", computer: "Computer", repository: "GitHub repository", waiting: "Waiting for confirmation on the computer", reviewing: "Being reviewed on the computer", installing: "Installing on the computer", installed: "Installed", declined: "Declined", expired: "Request expired", unknown: "Outcome unknown. Check the computer before trying again.", failed: "Could not read the result. Refresh to check again.", offline: "Computer offline", refresh: "Refresh", pending: "Sending request…" };
type RequestCopy = { [K in keyof typeof requestEn]: string };
const requests: Record<string, RequestCopy> = {
  en: requestEn,
  "zh-cn": { requests: "插件安装请求", requestDescription: "请到电脑的“设置 → 插件”检查请求。每次安装都需要在电脑上确认。", requestSource: "来自 {{device}} 的请求", request: "请求安装", computer: "电脑", repository: "GitHub 仓库", waiting: "等待电脑确认", reviewing: "正在电脑上检查", installing: "正在电脑上安装", installed: "已安装", declined: "已拒绝", expired: "请求已过期", unknown: "结果尚不明确，请先在电脑上检查，再决定是否重试。", failed: "暂时无法读取结果，请刷新重试。", offline: "电脑离线", refresh: "刷新", pending: "正在发送请求…" },
  ja: { requests: "プラグインのインストール要求", requestDescription: "コンピューターの「設定 → プラグイン」で要求を確認してください。すべてのインストールに、そのコンピューターでの確認が必要です。", requestSource: "{{device}} からの要求", request: "インストールを要求", computer: "コンピューター", repository: "GitHub リポジトリ", waiting: "コンピューターでの確認待ち", reviewing: "コンピューターで確認中", installing: "コンピューターにインストール中", installed: "インストール済み", declined: "拒否されました", expired: "要求の期限が切れました", unknown: "結果は不明です。再試行前にコンピューターを確認してください。", failed: "結果を取得できません。更新して再確認してください。", offline: "コンピューターはオフラインです", refresh: "更新", pending: "要求を送信中…" },
  es: { requests: "Solicitudes de instalación", requestDescription: "Revisa las solicitudes en Ajustes → Plugins del equipo. Cada instalación requiere confirmación allí.", requestSource: "Solicitud desde {{device}}", request: "Solicitar instalación", computer: "Equipo", repository: "Repositorio de GitHub", waiting: "Esperando confirmación en el equipo", reviewing: "Revisando en el equipo", installing: "Instalando en el equipo", installed: "Instalado", declined: "Rechazado", expired: "Solicitud caducada", unknown: "Resultado desconocido. Comprueba el equipo antes de reintentar.", failed: "No se pudo leer el resultado. Actualiza para comprobarlo.", offline: "Equipo desconectado", refresh: "Actualizar", pending: "Enviando solicitud…" },
  fr: { requests: "Demandes d’installation de plugins", requestDescription: "Examinez les demandes dans Réglages → Plugins sur l’ordinateur. Chaque installation doit y être confirmée.", requestSource: "Demande depuis {{device}}", request: "Demander l’installation", computer: "Ordinateur", repository: "Dépôt GitHub", waiting: "En attente de confirmation sur l’ordinateur", reviewing: "Examen sur l’ordinateur", installing: "Installation sur l’ordinateur", installed: "Installé", declined: "Refusé", expired: "Demande expirée", unknown: "Résultat inconnu. Vérifiez l’ordinateur avant de réessayer.", failed: "Impossible de lire le résultat. Actualisez pour vérifier.", offline: "Ordinateur hors ligne", refresh: "Actualiser", pending: "Envoi de la demande…" },
};
export const packageCopy = (locale: string): Copy & RequestCopy => {
  const key = copies[locale.toLowerCase()] ? locale.toLowerCase() : copies[locale.split("-")[0]] ? locale.split("-")[0] : "en";
  return { ...copies[key], ...requests[key] };
};
