/**
 * [INPUT]: No runtime dependencies
 * [OUTPUT]: Provides projectSettingsFr, the French Project Settings catalog
 * [POS]: French leaf of shared/i18n/locales/project-settings; loaded on demand by the matching top-level locale
 */
import { workspaceCopy } from "@ai-chat/ui/workspace-copy/fr";


export const projectSettingsFr = {
  entry: workspaceCopy.project.settings, open: "Ouvrir les paramètres du Project", title: workspaceCopy.project.settingsTitle, tabs: { general: "Général", personalization: "Personnalisation", skills: "Skills", extensions: "Extensions", tools: "Outils" },
  general: { sectionBasics: workspaceCopy.project.basics, name: workspaceCopy.project.identity, renameAction: "Renommer", appearanceAria: workspaceCopy.project.appearanceLabel, memory: "Memory", memoryDisabled: "Le service Memory est désactivé", memoryPaused: "Memory est en pause", memoryUnavailable: "Service indisponible", memoryScoped: "Ce Project possède un espace Memory indépendant", memoryShared: "Memory est partagé par Chat ou profil personnel", memoryDelivering: "Distribution de la Memory importée…", memoryManage: "Gérer Memory", history: "Import History", historyHint: "Importer l’historique Agent externe compatible.", appsSection: "Apps", appsDescription: "Les Apps ajoutées ici sont utilisables dans les conversations de ce Project. Pin les place seulement dans la Sidebar et ne change jamais les données qu’elles voient.", appsManagedByApp: "Les autorisations de cet App Project se gèrent depuis la page App.", placements: { pinControl: "Épingler {{name}} dans la Sidebar", grantSummary: "{{grant}} · {{agent}}", unavailableBadge: "Indisponible", agentOn: "l’Agent peut agir pour vous", agentOff: "vous seul pouvez l’utiliser", noGrant: "pas encore autorisée", unavailable: "Ce build ne peut pas encore s’exécuter — réparez-le sur la page Apps avant de l’épingler", empty: "Aucune App dans ce Project pour l’instant", emptyHint: "Une fois ajoutée, elle apparaît dans les conversations de ce Project. Vous décidez des données qu’elle voit.", loading: "Chargement des Apps…", failed: "Impossible de charger les Apps.", retry: "Réessayer", pending: "Enregistrement du Pin…", pinFailed: "Impossible d’enregistrer le Pin de cette App." }, baseSection: workspaceCopy.project.baseTitle, baseEmpty: workspaceCopy.project.baseEmpty, baseCreate: workspaceCopy.project.baseCreate, baseOpen: workspaceCopy.project.baseOpen, baseSummary: workspaceCopy.project.baseSummary, baseLoading: "Chargement de la Project Base", danger: workspaceCopy.project.danger, archiveHint: workspaceCopy.project.archiveHint, detachHint: "Retirer l’enregistrement local sans supprimer le dossier externe.", appLifecycleHint: "Cet App Project suit le cycle de son App. Supprimez l’App depuis la page Apps." },
  instructions: { section: "Instructions du Project", description: "Modifier les fichiers lus par les Agents dans ce Project.", pointerHint: "Ce fichier pointe vers AGENTS.md et ne nécessite généralement pas d’édition.", noWorkspace: "Choisissez d’abord un dossier depuis le menu du Project.", bridgeMissing: "La personnalisation du Project est indisponible.", appReadOnly: "Les instructions d’un App Project sont en lecture seule car la génération App les possède.", appEditGuide: "Ouvrez la page App et poursuivez dans une conversation App Edit.", workspaceChanged: "Le dossier du Project a changé. Le brouillon est conservé.", loading: "Chargement des instructions", saveFailed: "Échec de l’enregistrement", outsideWorkspace: "Ce fichier pointe hors du dossier du Project.", appManaged: "Les instructions sont gérées par la génération App." },
  skills: { section: "Project Skills appelables", scopeNote: "Les Project Skills suivent ce dossier ; gérez la bibliothèque globale dans Paramètres › Skills.", runtimeNote: "Cette liste contient les Skills appelables via `$` dans le produit ; les terminaux Agent peuvent différer.", inheritedGroup: "Skills globaux hérités ({{count}})", empty: "Aucun Project Skill appelable", emptyHint: "Placez un Skill dans {{dir}}/.agents/skills/<nom>/SKILL.md puis actualisez.",   noWorkspace: "Aucun dossier Project sélectionné", noWorkspaceHint: "Choisissez un dossier pour ajouter des Project Skills. Les Skills globaux et d’extension restent visibles ci-dessous.", loadFailed: "Impossible de charger les Project Skills.", badge: { repo: "Project", user: "Utilisateur", system: "Système", admin: "Admin", extension: "Extension" } },
  extensions: { scopeNote: "Installez une Extension dans ce Project : ses Skills ne seront disponibles que dans les conversations de ce Project, sans affecter les autres." },
  tools: { scopeNote: "Les changements ici affectent uniquement « {{name}} » ; les éléments inchangés héritent des valeurs globales.", bridgeMissing: "Les réglages d’outils du Project sont indisponibles dans cet environnement." }
};
